### ISSUE TITLE
モンスターナンバー0の "プレイヤー" が出現

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#10]
クローン地獄内、ジャートとの交戦中に "プレイヤー" が出現したという報告があった。
追加の情報は以下。

・攻撃することはできなかった。
・その他モンスターを全滅させてクエストクリアにならなかった。
・セーブ&リスタートにより消滅
・消滅後、モンスターを呪い装備から召喚して倒すことによってクエストクリアになった。 (=完全に消滅？)

発生直後のセーブデータからは"プレイヤー"の痕跡は発見できなかった。
発生直前のセーブデータ、再現手順の確立が待たれる。

**Comment by dis-** [comment]
発生は2/7の昼頃、バージョンはα4r。

**Comment by argrath** [comment]
再現不能でクローズしてよさそう?
