### ISSUE TITLE
店売りについて、まだ不便な欠品が目立つという意見

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1009]
daradarach氏より、以下の件があるのでもう一度提起。
店をあまり便利にしすぎるのはまずい、時間経過ペナルティを将来調整するための兼ね合いなど色々あると思うので、Issue化した。

魔法の地図の巻物を買うために三日くらい寝て過ごすことはぼちぼちありますが運が悪いだけなのか…ってところです。

利用頻度の高い杖のうち、鑑定の杖と周辺感知の杖は常時販売で非常にありがたいんですが、
アイテム感知の杖と邪悪存在感知の杖もかなり使う割に在庫欠品が多く、序盤から1週間ほど寝て過ごすことがあるので、
この2種も常時販売だとめちゃくちゃ嬉しいです。

_Originally posted by @daradarach in https://github.com/hengband/hengband/discussions/221#discussioncomment-669709_

**Comment by Hourier** [comment]
これ、Discussionの方がいいような気がします
いかがでしょうか？

**Comment by sikabane-works** [comment]
よくよく考えてみれば元で議論しなおせばこのIssueは無用ですか。ではさっさと閉じてもとで話しましょう。
