### ISSUE TITLE
v3.0.0 Alpha22～23 モンスター追加/調整

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1020]
調整メイン
多少追加もする

**Comment by RL-Nadir** [comment]
もしかしたら意図的に残したのかもしれませんが、集団生成版の見習戦士の打撃が「殴って攻撃する」のままでした。

**Comment by Hourier** [comment]
修正ミスです
Alpha22で反映させます、お手数おかけします

**Comment by sikabane-works** [comment]
本日もうリリースしたいのでalpha23に回させてもらいます。

**Comment by daradarach** [comment]
セイレーンにPREVENT_SUDDEN_MAGICがないので、荒野(not広域)で水辺に出た瞬間にテレポートバックされ、そのまま蹂躙されて死ぬ可能性があります。意図した即死トラップ「水辺に近づく奴が悪い」なら問題ありません。
![image](https://user-images.githubusercontent.com/78687408/117656298-26141c00-b1d3-11eb-8bdb-e69de1030d55.png)

**Comment by sikabane-works** [comment]
鼠小僧がDROP_GREAT持っているにも関わらずドロップ数が0のため何もも落とさなくなっています。

**Comment by RL-Nadir** [comment]
『火蜂』にPREVENT_SUDDEN_MAGICがありません。（FORCE_SLEEPを眠った状態で生成と思って抜いたのが原因です）
細かい調整を詰めるより前に、これだけは先につけたほうが良いように思います。

**Comment by Hourier** [comment]
#933 及び上記で頂いたリクエストは、像の件を除き全て実装しました
像は微妙なところなので保留中です
(他にも像と呼べるモンスターはいるため。g以外にもu ガーゴイル 等)
