### ISSUE TITLE
【バグ】 地形のシンボル変更がマップ表示に反映されない

### ISSUE THREAD

**Issue by RL-Nadir** [hengband/hengband#1037]
## 環境

- OS: windows版
- バージョン: 3.0.0Alpha21

## バグの詳細

%)コマンドで設定した、「地形の色／文字を変更する」の変更内容が、実際のマップ表示に反映されない。
（alpha 20までに設定していた内容が反映されていないことに気づき、改めてエディタで変更しようとしたが効果がなかった）

## 再現手順

添付のセーブファイル、ユーザー設定ファイルを読み込む。
alpha20で浅い水地形を = と表示するようにしているが、デフォルトの ~ として表示される。
[save&prf.zip](https://github.com/hengband/hengband/files/6424965/save.prf.zip)

## 期待される正常な動作

%)コマンドで設定した、「地形の色／文字を変更する」の変更内容が、実際のマップ表示に反映される。

## スクリーンショット

alpha20における表示
![image](https://user-images.githubusercontent.com/79453028/117094388-a6371d80-ad9e-11eb-80a5-efe1cbc3e6aa.png)

同じセーブデータ、ユーザー設定ファイルをalpha21で読み込んだ時
![image](https://user-images.githubusercontent.com/79453028/117094757-9966f980-ad9f-11eb-870e-35c387a0e8b3.png)

## 補足事項

補足事項があれば記載

**Comment by shimitei** [comment]
#936 5de68366efd64ef6a7cc53ce55af6ad48bfbcdc1 のタイル切り替えの修正コミットで、表示シンボルが常に初期化されるようになっていました。
切り替え処理を見直します。
