### ISSUE TITLE
【バグ】 マクロ編集コマンド'@'を押した後\eでゲームに戻ろうとするとゲームが落ちる

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1070]
## 環境

- OS: WIndows
- バージョン: 3.0.0Alpha21

## バグの詳細

バグの内容を明確かつ簡潔に説明

添付の自動拾いファイル、

[picktype.txt](https://github.com/hengband/hengband/files/6447613/picktype.txt)

を使用すると、ゲーム内でマクロ編集画面を開いたあとゲームに戻ろうとするとゲームが落ちる。
## 再現手順

バグを発生させる手順が分かっていれば記載

まっさらな状態の変愚蛮怒のlib\userに添付のpicktype.prfを置く。（拡張子がtxtになっているのでprfに戻してから）
新規ゲームを開始する。
@コマンドからマクロ編集画面を開く。
escでゲームに戻ろうとすると落ちる。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

落ちない。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by iyukyo** [comment]
マクロのキーを指定していなかった。お手数をおかけしてすみません。クローズします。

**Comment by iyukyo** [comment]
自動拾いにマクロを記載する場合に、キーを指定せずにマクロ動作だけ記載した場合に落ちるということで、書式が間違ってはいるのだが落ちること自体は事実なのでreopenする。

**Comment by shimitei** [comment]
確認しました。

マクロ表示のバッファ(1024バイト)にマクロをサイズ確認なしでコピーするためスタックが盛大に\*破壊\*されます。
https://github.com/hengband/hengband/blob/6e973f3d3a84f04c6878830d5dfd727510fcc198/src/cmd-io/cmd-macro.cpp#L168

長い行が記述されていると、自動拾いエディタ他でも1行最大1024バイトでエッジケースの処理があまくバッファオーバーフローします。
https://github.com/hengband/hengband/blob/6e973f3d3a84f04c6878830d5dfd727510fcc198/src/autopick/autopick-reader-writer.cpp#L74
angband_fgets関数は第2引数のサイズを超えて終端NULLを書き込む。
