### ISSUE TITLE
【バグ】 ユーザー設定ファイルのロードについて

### ISSUE THREAD

**Issue by radinms** [hengband/hengband#1078]
## 環境

- OS: Windows 10
- バージョン: 例: 3.0.0Alpha20

## バグの詳細
@コマンドから入れる（１）のユーザー設定ファイルのロードで、
一部のファイルがロードできない

## 再現手順
1. ＠コマンド→（１）ユーザー設定ファイルのロードで、picktype.prfを入力する（なぜそんなものを。。。とは突っ込まないでください）
2. 添付のＳＳのエラーが発生します。ユーザーフォルダではなくprefフォルダ内のpicktype.prfファイルを読み込み、謎の賞金首エラーです。

## 期待される正常な動作
賞金首エラーが起きないこと

本来期待される正常な動作を記載

## スクリーンショット

![image](https://user-images.githubusercontent.com/26111256/117827765-3c41db00-b2ac-11eb-910a-7a8755f833d9.png)

## 補足事項

補足事項があれば記載

**Comment by shimitei** [comment]
@コマンドのマクロの設定で、(2)でファイルに保存するとlib\user\に出力されます。
なので(1)で読み込む場合もlib\user\からロードするのが間違いないにもかかわらず、lib\pref\を優先する処理がダメですね。
ユーザー指定のファイルがlib\pref\にあるわけがない。

(1)でロードするファイルはlib\user\から読み込むように修正したいと思います。
