### ISSUE TITLE
【バグ】 セーブデータを引数に指定してコマンドウインドウからHengband.exeを実行すると効果音が鳴らない

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1082]
## 環境

- OS: Windows 8.1
- バージョン: 3.0.0Alpha22

## バグの詳細

バグの内容を明確かつ簡潔に説明

コマンドウインドウからHengband.exeを実行する際に、セーブデータを引数に指定すると起動と同時にセーブデータを開いてくれるのだが、そうすると効果音が鳴らない。
ダブルクリックでHengband.exeを実行すると鳴る。
コマンドウインドウで実行する場合でも引数を指定せず単にHengband.exeとすると鳴る。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. ○○ する
2. ✕✕ する
3. バグが発生

1. Hengband.exeのあるディレクトリでコマンドウインドウを開く
2. Hengband.exe (そのディレクトリのパス)\lib\save\(セーブファイル)と入力して変愚を起動する。
3. オプションの効果音にチェックが入っているのを確認する。
4. ゲームを開始し、効果音が鳴らないのを確認する。
5. 変愚を終了し、コマンドウインドウに単にHengband.exeと入力して変愚を実行し、先程と同じセーブファイルを開く。
6. ゲームを進めると効果音が鳴る。
7. 変愚を終了し、Hengband.exeをダブルクリックして変愚を起動し、先程のセーブファイルを開いてゲームを進めて効果音が鳴るのを確認する。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

コマンドウインドウでセーブファイルを引数に指定して変愚を実行した場合でも効果音が鳴る。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by shimitei** [comment]
コマンドライン引数でセーブファイルを指定した場合、効果音の初期化前にゲームが開始されていました。
このため効果音が鳴らなくなっています。
処理順の見直しで修正します。
