### ISSUE TITLE
【バグ】 キャラクタ情報のファイル出力で装備の記号が表示されない場合がある

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#1090]
## 環境

- OS: Mac X11
- バージョン: 3.0.0Alpha22 developブランチ

## バグの詳細

キャラクタ情報のファイル出力で装備の記号 / }=="*[(]]] 等が表示されないことがある

## 再現手順

1. 適当なキャラクターで始める（ 再現しない場合もあり条件は不明 ）
2. 適当な武器、防具を購入して装備する
3. C コマンドから f コマンドでファイル出力する

## 期待される正常な動作

記号が表示される

## 補足事項

最近の例
Alpha22　がまんづよい　マインドフレア　元素使い
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=83542
Alpha21　セクシーギャル　アンドロイド　戦士
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=83541
Alpha21　ちからじまん　クラッコン　レンジャー
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=83540
Alpha20　ちからじまん　コボルド　修行僧
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=83539
Alpha20　すばしっこい　ドラコニアン　盗賊
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=83520

Alpha12でも発生を確認しました

Mac X11 以外でも発生していると思われます

**Comment by tanguband** [comment]
新しくセーブデータを作り直したところ発生しませんでした
古いセーブデータを引き継いで使っている場合に起きる現象かもしれません
現在のバージョンで問題がないようでしたらクローズしてください
よろしくお願いいたします

**Comment by tanguband** [comment]
windows版 Alpha20 新規作成データで発生を確認しました

**Comment by shimitei** [comment]
確実に発生するセーブファイルがあればください。
ZIPファイルにするとコメント入力欄の下のところにドロップして添付できます。

**Comment by tanguband** [comment]
よろしくお願いいたします
[501.element.zip](https://github.com/hengband/hengband/files/6481741/501.element.zip)

**Comment by shimitei** [comment]
equippy_charsオプション（ステータスに文字で装備を表示する）が「いいえ」の場合に表示（出力）しないのは仕様ですね。
タイル表示の場合も同様に装備のシンボルはファイルには出力されないように処理されています。

例に上がっている中で一部の装備記号のみ出力されているのはおかしいように見えます。

**Comment by tanguband** [comment]
オプションを設定して忘れていました、失礼しました
一部装備の表記がないファイルはぐりっどばぐの参加者の中にいらっしゃるので
後ほど提供していただけるか確認してみます

**Comment by tanguband** [comment]
有志の方よりセーブデータを提供していただきました
タイル表示で装備表示されないようです
こちらではwindows環境がなく確認できませんでした
よろしくお願いいたします
[Multilockon.zip](https://github.com/hengband/hengband/files/6487582/Multilockon.zip)

**Comment by shimitei** [comment]
タイル表示の場合も、ファイル出力には装備の記号は出ないように処理されています。

画面表示もファイル出力も同じ処理を流用していて、タイル表示の場合はファイルには出力しようがないためかスペースに置き換えられています。
タイル表示の場合に装備の記号に置き換えるのは処理が大変そうなことと、
タイル表示のユーザーには装備の記号は馴染みがないと思われるため
現在の動作になっていると考えられます。

**Comment by tanguband** [comment]
ありがとうございます
原因として考えられそうなところとしてはオプションで非表示、タイルによる非表示でしょうか？
それ以外で非表示がないようでしたら問題ないと思われますのでクローズしていただいて大丈夫です
よろしくお願いいたします

**Comment by shimitei** [comment]
ダンプをよく見ると、タイル表示でも表示が文字になっているアイテムだけが出ていますね。
根本的な原因は、新アイテムにタイル表示の割り当てがされていないためでした。
#387 のduplicateとしてクローズします。
