### ISSUE TITLE
【バグ】 凡庸化のメッセージ

### ISSUE THREAD

**Issue by gold-onion** [hengband/hengband#1099]
## 環境

- OS:Winsows10
- バージョン: 3.0.0Alpha22

## バグの詳細

助詞がおかしいのか凡庸化のメッセージに違和感がある

## 再現手順

1. 凡庸の巻物を読む
2. アイテム選択で 「どれを使いますか？」と表示される

## 期待される正常な動作

「どれに使いますか？」とか「どのアイテムに使いますか？」とかを表示する

**Comment by shimitei** [comment]
他の選択させるメッセージは「どの○○を○○しますか？」となっているため、凡庸化のメッセージを「どのアイテムを凡庸化しますか？」に変更します。
