### ISSUE TITLE
【バグ】 マクロ設定でマクロを確認しても正しく表示されない

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#1100]
## 環境

- OS: Mac X11
- バージョン: 3.0.0Alpha22 developブランチ

## バグの詳細

マクロ設定でマクロを確認しても正しく表示されない

## 再現手順

1. 適当なキャラクターで始める
2. @ コマンドでマクロ画面に入る
3. ファンクションキーF1にマクロを設定する
4. ファンクションキーF2にマクロを設定する
5. (3) のマクロの確認で F1 を選択
6. マクロを確認しました。の表示が出るが表示されるのは F2 のマクロのまま

## 期待される正常な動作

F1 のマクロ内容が表示される

## 補足事項

マクロを更に追加すると表示は最後に設定したマクロ内容のままになります

Alpha22 の master では正常に表示されています
[501.0516.zip](https://github.com/hengband/hengband/files/6488380/501.0516.zip)

**Comment by shimitei** [comment]
Alpha22とdevelop最新でなぜか挙動が違いますが、現在の方がソースコードの通りに動作していると思います。
また、#1073 以降でも長いマクロが登録されていると(4)マクロの作成、(8)キー配置を選択するとスタックが壊れる問題が残っています。

試してみると再現しませんでした。
F1に「*t」、F2に「R99」を登録し、(3)の確認でF1を押すと「マクロを確認しました。」のメッセージとF1の登録内容が表示される。
![f1macro](https://user-images.githubusercontent.com/3318603/118381907-d26a5e00-b62a-11eb-85a7-fe441684c9b7.png)

何かキーを押すと下には最後に登録した内容が表示される。
![after](https://user-images.githubusercontent.com/3318603/118381948-1198af00-b62b-11eb-8096-9179ba4e162b.png)

**Comment by tanguband** [comment]
検証ありがとうございます
こちらの環境の可能性もありそうなので再度調査をしてご報告します

**Comment by tanguband** [comment]
オプション設定の ( 1 ) キー入力オプションで
キー待ちしないで連続でメッセージを表示する を はい にすると
表示が飛ばされて最後に登録した内容が表示されるようです
現状ですとこのオプションを使用するとマクロの内容の確認が難しい状態になっているので
可能でしたら以前と同じ挙動にしていただけると有り難いです

**Comment by tanguband** [comment]
キー待ちしないで連続でメッセージを表示する　について
有志の方のオプション利用割合を調べたところ
はい　が　7名　いいえ　が　2名でした

**Comment by shimitei** [comment]
メッセージ表示を読み飛ばすオプション有効時の問題と認識しました。
メッセージ送り待ちに依存しない処理にすることで対応したいと思います。
