### ISSUE TITLE
【バグ】 登録済みマクロを参照した直後にマクロ作成した時に、参照したマクロ文字列が表示されない

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#1109]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha23

## バグの詳細

登録済みマクロを参照した直後にマクロ作成した時に、参照したマクロ文字列が表示されない

## 再現手順

@3で適当なマクロ登録済みキーのマクロを確認
4で適当なキーにマクロを設定しようとする

## 期待される正常な動作

@3で参照したマクロが表示されて編集できる

**Comment by shimitei** [comment]
長いマクロが登録されている場合に問題があったため、#1102 でマクロの作成時にバッファを空にする対応を行いました。
副作用として従来行えていたマクロのコピー、再編集ができなくなっています。

従来の動作を安全な範囲で行えるように対応を検討します。
