### ISSUE TITLE
新地形の詳細化

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#111]
OSDNより移行。[41368](https://osdn.net/projects/hengband/ticket/41368)

フォーラム 変愚蛮怒3.0.0Alpha開発フォーラム ![#86893] からの引用

[forum: 86893]
> 新地形の便宜上毒沼について。毒沼に漬かる機会があったのですが、装備の毒耐性と毒の二重耐性がある状態でも一歩歩くごとに状態異常の毒になりました。
>
> 毒は即治るのでダメージはないようですが、どうにも挙動が怪しかったので報告します。

以下の項目について、追記が必要
 * 浮遊なし・耐性なしで侵入した時のダメージXdY、及び効果 (以下同様)
 * 浮遊あり・耐性なし
 * 浮遊なし・耐性あり
 * 浮遊あり・耐性あり
 * 浮遊なし・二重耐性なし
 * 浮遊なし・二重耐性あり

以上は毒沼に限らず、低温帯・酸の沼・帯電帯も適用
毒以外は上記に加えて免疫の場合も要考慮

**Comment by iks3** [comment]
現状のまとめ
|地形|属性|耐性|二重|免疫|浮遊|深い場合|追加効果|
|---|---|---|---|---|---|---|---|
|溶岩|火炎|1/3|1/3|有効|1/5|浮遊なしで頻度増|なし|
|低温|冷気|1/3|1/3|有効|1/5|浮遊なしで頻度増|なし|
|帯電|電撃|1/3|1/3|有効|1/5|浮遊なしで頻度増|なし|
|酸沼|酸|1/3|1/3|有効|1/5|浮遊なしで頻度増|なし|
|毒沼|毒|102/300|102/300|無効|1/5|浮遊なしで頻度増|浮遊なしで毒状態|

毒沼の免疫が抜けているようです。

**Comment by iks3** [comment]
#428 の毒沼処理順の問題があるため、追加効果に意味がなくなっています。

**Comment by sikabane-works** [comment]
毒沼の問題はなおしたし、マニュアルと古い更新履歴にいれることで終わりにしておく。

**Comment by sikabane-works** [comment]
とりあえず日本語版だけ先追加。英語は自力で何とかするかEric氏に頼みたい。
