### ISSUE TITLE
alpha23のモンスター設定不具合

### ISSUE THREAD

**Issue by RL-Nadir** [hengband/hengband#1113]
3.0.0alpha23追加モンスターにて、不自然な実装形態のものを見つけたので報告いたします。
発案者は関係者と相談の上、適切な内容への修正をお願いします。
・闇の帝王『ヴォルデモート』が、打撃内容の設定がないにもかかわらず、NEVER_BLOWフラグが無い
・パックンフラワーが射撃フラグ有しているが、SHOOT:HURTの設定がない

**Comment by RRyukkuriRyu** [comment]
『ヴォルデモート』とパックンフラワーの発案者です。
どちらも記入漏れです、すみません。
『ヴォルデモート』はNEVER_BLOWフラグを付与、パックンフラワーは B:SHOOT:HURT:13d1 でお願いします。

**Comment by RL-Nadir** [comment]
鬼殺隊の隊士が　SHOOT:HURT　が設定されているものの、射撃フラグがないため、射撃に関する設定が依然として死んでいます。

**Comment by Hourier** [comment]
上記2点、解消させました
α24をお待ち下さい
