### ISSUE TITLE
v3.0.0 モンスター調整 α24

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1116]
掲題の通り
基本調整、多少追加するかもしれない

**Comment by RL-Nadir** [comment]
弱い方のイェンダーの魔法使いまで☆アミュレット確定ドロップはちょっと美味しすぎるので、
落とさない／落としにくい／嫌なものを落とす　のように調整するのはいかがでしょうか。
実装された以上はもはや提案者私物ではないとの認識ですので、現行または他の案が適当との判断であっても、もちろん全く差し支えありません。
ご検討よろしくお願いします。

**Comment by Hourier** [comment]
上記、楽をしようと処理をまとめただけに過ぎないので、修正を前提に調整します
一番簡単なのは「★など無指定で完全ランダムにアミュレットを落とす」ですが、いかがでしょうか

元の案である4冊目の魔導書でも良いですが、これも以下の要素が1/3ずつ混ざった結果です
- 共通化で楽をした
- 二重苦と普通のでパラメータが違うのに気付いたのが最近だった
- 4冊目といえどランダムで果たして嬉しいのかという疑問があった

**Comment by gold-onion** [comment]
偽物のイェンダーの魔除け(Cheap plastic imitation of the Amulet of Yendor)はどうでしょうか
NetHackだと分身がドロップする場合があるので

**Comment by Hourier** [comment]
それを実装しても良いのですが、本物が☆を落とすのと整合性が取れない (本物のイェンダーの魔除けを実装してもいいんですが)のと、より重要な問題としてパラメータ (耐性、pval、他)をどう設定すればいいかまるでアイディアがありません
何かあればお受けします

**Comment by RL-Nadir** [comment]
ありがとうございます。
とりあえず、美味しすぎる問題を解消するための当面の方策として、アミュレット限定の並ドロップは良い考えだと思います。
分身がパチモノの魔除けを持ってくる要素にも触れていますし。

上位魔法書ドロップ案はJITで所望の領域を引けると嬉しいかも知れませんが、☆アミュレットで大当たり／糞を引いたみたいな話の種になる感じではないので、もういいのかな、と思います。
うま味を希釈するような調整をする際の要素として、メモ書き程度に残しておくのが良いのではないでしょうか。

**Comment by Hourier** [comment]
承知しました
それではアミュレット限定でのドロップに差し替えます
調整案ありがとうございました

**Comment by Hourier** [comment]
実装しました
但しアミュレットのレアリティ的に、あまり低すぎる階層 (例：1F)だと落としません
nasty生成の話を抜きにすると、最速40FのVaultに出現の可能性がありますが、この辺りなら何かしら落とします
α24リリース後にご確認下さい

**Comment by daradarach** [comment]
イェンダーの魔法使い(偽物)の☆ドロップに関しては実装的に楽だった=現状からの実装変更が面倒ならもうしばらく現状のままで良いのではないでしょうか。
と言うのも時折Discordでメンテナの一人(dis-さん)を含め、そもそも本人の生成階層の変更や、★イェンダーの魔除けの性能に関して議論を

って書いてたら目の前で実装完了したので簡単だったんですね

**Comment by Hourier** [comment]
デスソード等、特定種別のアイテムをドロップする実装は既に充実しているので、そちらに差し替えるだけですね
★を抑制して☆ (しかも呪いつきは落とさない仕様)だけドロップさせるのが一手間かかっていたものです

**Comment by Hourier** [comment]
Discordでの議論により『プロフェッサー・オオツキ』が実装漏れを起こしていたことが分かりました
調べたところ、没となったウロボロスと同じレスにあったため、巻き添えになっていたようです
α24で実装します
