### ISSUE TITLE
【バグ】 固定クエスト内で魔法の熟練度が初心者から上がらない

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#1119]
## 環境

- OS:Windows 版
- バージョン: 3.0.0Alpha23

## バグの詳細

固定クエスト内で魔法を唱え続けてもその魔法の熟練度が初心者から上がらない

## 再現手順

1. 人間、カオス/仙術メイジを作成し証人クエに入る
2. マジックミサイルを空撃ちし続ける
3. 手持ちの松明と食料を使い切るまで空撃ちを続けても熟練度が初心者のまま

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
[save.zip](https://github.com/hengband/hengband/files/6502161/save.zip)

## 期待される正常な動作

ver2.2.1rの頃と比べて熟練度が伸びづら過ぎるかあるいは全く伸びていないのが不具合と判断。
仕様変更の意図が無ければ、ver2.2.1rの頃と同程度に熟練度が伸びているべき。

## 補足事項

上記再現手順をhengband-2.2.1r (最新安定版)で試してみたところ、松明と食料を使い切る前にマジックミサイルの熟練度が達人にまで上がりました。
バージョン問わず、固定クエスト以外の鉄獄などのダンジョン内でも同様の現象が起きるかは未確認です。

**Comment by Hourier** [comment]
そのような仕様変更は意図していないので不具合と強く想定されます
但しいつから起きていたのか全く不明なので調査に時間を使うかもしれません
しばらくお待ち下さい
