### ISSUE TITLE
マーフォークの仕様変更

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#112]
OSDNより移行。[41086](https://osdn.net/projects/hengband/ticket/41086)

 * 得意武器にトライデントを与える。
 * 騎乗時には修正がつかないなどの整理を与える。

**Comment by iks3** [comment]
水上加速ボーナスと浮遊ないときの減速ペナルティは、そもそも騎乗時には適用外でした。

**Comment by iks3** [comment]
AQUATICに騎乗中に水上での加速はとりあえずなしでいいのでは、という話になりましたので、もしあるなら次回に回します。
