### ISSUE TITLE
【バグ】 知能で魔法を使う職業で無銘の小手を装備してもMPが減らない

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#1120]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha23

## バグの詳細

知能で魔法を使う職業で無銘の小手を装備してもMPが減らない

## 再現手順

メイジで無銘の革グローブを装備

## 期待される正常な動作

MPが減る

**Comment by habu1010** [comment]
原因コミット特定
f60b24f1c913ea6f0ac347a70af690e58d696ed2

m_info.txtの読み込みで `0x05` 等の16進数で表された値を std::stoi (の引数で与える基数のデフォルト値10)で変換しているために 0 になってしまっていると思われる。
まだ調べていないが、 #1119 もこのパーサの変更が関係ありそうな気がする。
