### ISSUE TITLE
【バグ】 腕力が下がって弓が運搬中になると命中修正が上がる

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1133]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha23

## バグの詳細

バグの内容を明確かつ簡潔に説明

腕力が下がると
> こんな重い弓を装備しているのは大変だ 
と表示されるが、命中修正がむしろ腕力が下がる前より高くステータス画面に表示される。

## 再現手順

バグを発生させる手順が分かっていれば記載

添付のセーブファイルの初期状態が素の腕力18、修正込みで腕力18/10で弓が運搬中になっておらず、

> 射撃命中  :150-超越
> 射撃攻撃修正    (+60,+15)

とステータス画面に表示されている。この状態からデバッグで腕力を17、修正込みで18にすると、

> こんな重い弓を装備しているのは大変だ。

と表示されるが、ステータス画面上では、

> 射撃命中  :258-伝説的[10]
> 射撃攻撃修正    (+96,+15)

となっており、もとより命中修正が上がっている。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

[ウィザード.zip](https://github.com/hengband/hengband/files/6523316/default.zip)

## 期待される正常な動作

本来期待される正常な動作を記載

弓が運搬中のときの仕様がわからないが、射撃の性能が落ちるか、なにも起こらないと考えられる。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
## 原因

重すぎる弓に対する命中ペナルティ算出は下記の場所で行われているが、
https://github.com/hengband/hengband/blob/097166b64c03e33afba0b2eb1ba70b78df9c0fef/src/player/player-status.cpp#L2380-L2382
calc_weapon_weight_limitは次の通り武器を両手持ちにしている時にadj_str_holdを2倍するボーナスが入るので武器を両手持ちしている時に重すぎる弓を装備すると逆に命中が増えてしまうことがある。
https://github.com/hengband/hengband/blob/097166b64c03e33afba0b2eb1ba70b78df9c0fef/src/player/player-status.cpp#L3029-L3037
