### ISSUE TITLE
両手持ちボーナスを得られる条件がおそらく意図せず変わっている

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1134]
Issue #1113 に関連して calc_weapon_weight_limit を使用している関数を調べたところ、下記の has_disable_two_handed_bonus について処理が正しくないのではないかという箇所を見つけた。

https://github.com/hengband/hengband/blob/097166b64c03e33afba0b2eb1ba70b78df9c0fef/src/player/player-status-flags.cpp#L2014-L2027

calc_weapon_weight_lmiitの戻り値に 2 を掛けているが、これが calc_weapon_weight_limit の中で計算される両手持ち時に2倍するボーナスを打ち消すものであるとすれば 2 で割るのが正しいように思える。
この部分のリファクタリングを担当された方に確認いただきたく。

ちなみにバージョン 2.2.1 では同一の処理を意図する部分と思われる箇所のコードは
https://github.com/hengband/hengband/blob/5e4acf90005915536cb067b1dac85e1f7d04924a/src/xtra1.c#L5033
となっている。

**Comment by habu1010** [comment]
改めてV2.2.1の頃のコードと比べると、元のコードは両手持ちの時の重量制限は`adj_str_hold[p_ptr->stat_ind[A_STR]] * 2 ( == hold)` で、

- `hold < o_ptr->weight / 10` の時：運搬中
- `hold < o_ptr->weight / 5` の時：両手持ちボーナス（攻撃回数が増えやすい、to_hとto_dが増える）が得られない

となっている。
しかるに、現在のコードは calc_weapon_weight_limit の中で `adj_str_hold[p_ptr->stat_ind[A_STR]] * 2` 相当の計算がされており、その戻り値をさらに2倍しているので、結局のところ、V2.2.1の時と違い

- `hold * 2 < o_ptr->weight / 5` の時：両手持ちボーナスが得られない

となっている。つまり、以前に比べて両手持ちボーナスを得られる条件が大幅に緩和されてしまっている。

V2.2.1 準拠に戻すには calc_weapon_weight_limit の戻り値に *2 しているのをなくせばよいが、両手持ち前提の武器のバランス調整に問題が出そう。
具体的にはドラゴンころしで、V2.2.1準拠にすると35kgの武器は両手持ちだと戦士で5回しか振れなくなり、命中とダメージへのボーナスもなくなってしまう。どうするべきだろうか。

**Comment by habu1010** [comment]
一旦まとめ。
武器を両手持ちをする事によるメリットは以下の2つがある。

1. 運搬中になるまでの重量制限が2倍になる
2. 攻撃回数計算と命中・ダメージにボーナス

そして、V2.2.1 では 1 のメリットは無条件で得られ、 2 のメリットは片手持ちでも運搬中にならない武器ならば得られる。
現在のバージョンではどちらのメリットも無条件で得られる。

1 のみだと本来片手で振れる武器を両手持ちする意味がなくなるので 2 の仕様を追加したと考えれば、やはり V2.2.1 の仕様が自然に思える。

**Comment by dis-** [comment]
意図した変更ではなさそうなので、以前の仕様に戻すで良いと考えます。
ドラゴンころしについては一先ず25kgバージョンに戻します。
