### ISSUE TITLE
【バグ】 長いマクロを実行中にメイン画面のコントラストを反転させて模様を描くと画面が更新されなくなったりバグったりする

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1135]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha23

## バグの詳細

バグの内容を明確かつ簡潔に説明

長いマクロを連打すると、処理中は画面をドラッグして反転させた状態が残り続け、これを利用して模様を描くと画面が更新されなくなる、またはバグる。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 添付のセーブファイルとpicktype.prfを使用する。
2. ゲーム開始後、サブウィンドウ2(持ち物/装備一覧)を出して、F10を50回程度押すと、5分ほどマクロを実行した後lv40のボーナス選択画面で止まるので、その間に添付の画像のような市松模様をメイン画面に描く。
3. 10分も待つと、画面は変わらないが内部的にはlv40のボーナス選択画面になっている。
4. 例えば\edy^xと入力して器用にボーナスを振ってからゲームを終了する。
5. 再起動するとlv40になった状態からゲームが開始する。

新規変愚蛮怒フォルダにセーブファイルとpicktypeを移して行った場合は画面が更新されなかったが、普段プレイしているときは画面がバグり、左のステータス画面が2重に表示されたり自動拾い画面から戻っても自動拾い画面が中途半端に表示され続けたりした。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
[PLAYER.zip](https://github.com/hengband/hengband/files/6525793/PLAYER.zip)

## 期待される正常な動作

本来期待される正常な動作を記載

画面が正しく表示される。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付
![市松模様](https://user-images.githubusercontent.com/81608944/119214715-cc312180-bb03-11eb-82b3-0adc3331d415.png)

## 補足事項

補足事項があれば記載

**Comment by shimitei** [comment]
対処としては、画面のドラッグ選択でゲームの進行を止めるか、マクロ実行中は選択できないように制限するかですね。
ゲームの進行を停止しておくのが難しいのと、マクロ実行中は画面が変化していくことが予想されるため、マクロ実行中は選択できないように制限をかける対応が良さそうです。
