### ISSUE TITLE
【誤訳】あてどなくふらつく商人の思い出に誤訳あり

### ISSUE THREAD

**Issue by Taro0910** [hengband/hengband#1138]
## 環境

- OS: おそらく全て
- バージョン: 3.0.0Alpha22以降

## バグの詳細

バグではなく誤訳なのですが、誤訳の報告をどこで行うかわからなかったのでここで質問させていただきます。すみません。
あてどなくふらつく商人の思い出文章にある「魅力のアミュレットを買おうと町を探し回っている。」は元の文章（英語）ではlooking for more amulets of adornment to buy.となっておりますが、k_infoによるとamulets of adornmentは魅力のアミュレットではなく装飾のアミュレットのようです。

## 再現手順

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

×：魅力のアミュレットを買おうと→〇：装飾のアミュレットを買おうと

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

Discordにおいて今朝既にDeskullさんには話したのですが、「折角ですし突っ込んどいて下さい」とのことでしたのでこちらでもご報告いたします。

**Comment by Hourier** [comment]
これは現行開発者は修正せず保留としておきたいです
- 実害はない
- 新規開発者の方がいらっしゃった時のために残しておきたい
- 修正が容易、むしろGit/GitHubに慣れる方が大変

**Comment by sikabane-works** [comment]
新規開発者のテスト台にということでしょうか。まあ、緊急度が高いわけではないのは確かなのでHourier氏の意をくんでbeta修正案件にしときます。

**Comment by Hourier** [comment]
新進気鋭の開発志望者がいらっしゃったので、私の責任で直してもらいます
