### ISSUE TITLE
【要望】 思い出でロケットの使用確率を表示して欲しい

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#1153]
## 環境
- バージョン: 3.0.0Alpha24

## 詳細
思い出でロケットの使用確率が表示されない場合がある

## 補足事項
該当モンスターはバズーカ、ハヤブサ、サイバーデーモン

魔法行動がロケットのみの場合に表示されないようです

ロケットのみの敵も使用確率が表示されると助かると思います

**Comment by Hourier** [comment]
射撃だけの場合も該当するようなので確認します
なお思い出とスポイラーの多重実装も何とかしたいところ(これは別イシュー)

**Comment by Hourier** [comment]
display-lore.cpp にて、ロケットと射撃が同列に扱われていることを確認しました
同根につき修正後はどちらも表示されるようになると思います

**Comment by Hourier** [comment]
修正しました
α25で反映予定です

**Comment by sikabane-works** [comment]
Hourier氏の一度却下になったモンスター調整がすまないと終わりませんね。先に別途拾って対策した方がいいんでしょうか。

**Comment by tanguband** [comment]
特に困る問題でもないので調整のペースに合わせていただいて問題ないと思います。

**Comment by sikabane-works** [comment]
了解です。

**Comment by sikabane-works** [comment]
Hourier氏の作業が七月以降になりそうなのでもう少し先のマイルストーンに飛ばします。

**Comment by sikabane-works** [comment]
こちらで更新されたようですのでクローズします。
