### ISSUE TITLE
【バグ】 ジュラル星人状態の敵の正体が足元情報から分かる

### ISSUE THREAD

**Issue by EpisodeNanashi** [hengband/hengband#1156]
## 環境

- OS:Windows10
- バージョン: 3.0.0Alpha23と24で確認

## バグの詳細

性格チャージマンでジュラル星人状態の敵の足元情報を
サブウィンドの足元アイテム表示から見たときに元の名前が表示される

## 再現手順

サブウィンドの足元アイテム表示からジュラル星人状態の敵の足元情報を見る

## 期待される正常な動作

ジュラル星人と表示される

## スクリーンショット

![bug](https://user-images.githubusercontent.com/80182375/119671854-12c0ac00-be75-11eb-82ef-d7f3c4f76d4c.png)

**Comment by Hourier** [comment]
原因判明・修正しました
α25で反映予定です
