### ISSUE TITLE
【バグ】 HEAVY_SPELL フラグ関連の処理の不足

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1170]
## 環境

- OS: Any
- バージョン: 3.0.0Alpha24

## バグの詳細

HEAVY_SPELL（呪文難易度上昇） に関連する処理が色々不足している。逆の効果をもたらす EASY_SPELL と比較して、以下の処理が存在しない。

- アイテムの銘に'%'を刻んだ時の表示
- アイテムの価格への影響
- 'C'で表示されるステータス画面のフラグ一覧への記載
- スポイラーでアーティファクト一覧を生成した時の効果の出力

## 再現手順

なし

## 期待される正常な動作

バグの詳細で記載した、不足している処理が実装されている事

## スクリーンショット

なし

## 補足事項

アイテムのフラグを追加した時に最低限追加が必要となる処理をまとめておいたほうがいいかもしれない。

**Comment by habu1010** [comment]
コードを見ていて気づいたが、そもそも HARD_SPELL と HEAVY_SEPLL の2種のフラグがあり、どちらも魔法の難易度を上げるという効果である。
統一するべきではないだろうか？
HEAVY_SPELL のほうが後から追加されたようだが、わざわざ同じ効果のものを追加した経緯が不明。

**Comment by sikabane-works** [comment]
呪いにより付加される方と、装備品として生来持っているペナルティを増やそうとした際の食い違いだったかもしれません。いずれにせよ、統一した方がよさそうですね。

**Comment by dis-** [comment]
#3832 にて解決したのでcloseします
