### ISSUE TITLE
alpha24にてモンスター入りモンスターボールを所持時にマップ画面の移動が重くなる件

### ISSUE THREAD

**Issue by TX105** [hengband/hengband#1180]
お疲れ様です。
当方変愚蛮怒3.00alpha24及びalpha25にて
モンスター入りのモンスターボールを所持時に
ワールドマップ上の移動処理が極端に重くなる事象に気が付きました
環境との相性およびゲームPCなどの高スぺックにて解決可能な可能性ありですが
念のため報告します
セーブデータも存在しています

**Comment by dis-** [comment]
記載の条件を全て満たす条件で検証しましたが再現しません。
セーブファイルを添付して、再現するために必要な手順を記載してください。
バグ報告テンプレートに沿って記述していただけると大変助かります。

**Comment by dis-** [comment]
#1181 と重複しているためこちらはcloseします
