### ISSUE TITLE
再度モンスターボール所持状態でワールドマップが重くなる事案を報告します

### ISSUE THREAD

**Issue by TX105** [hengband/hengband#1181]
どうももうしわけありません
## 環境
Windows 版　JPN
- バージョン: [例: 3.0.0Alpha25

## バグの詳細

3.00系になった際時折重くなる事象が発生していたが
古代万色D及びストームワイアーム入りのモンスターボールを所持してワールドマップを歩行した場合
重度の遅延が発生することに気が付く

## 再現手順

バグを発生させる手順が分かっていれば記載

セーブファイルをalpha25で起動し
モンスターボールを所持状態でマップに出る

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
[うざいライル.zip](https://github.com/hengband/hengband/files/6575608/default.zip)

補足事項があれば記載
環境との相性や高スペックのPCの使用で解決する可能性もありますが
極端に感じられたため念のため報告します

**Comment by shimitei** [comment]
ボール中モンスターのHP自然回復処理で描画フラグが立つため重くなっている。

https://github.com/hengband/hengband/blob/11e1438633deb270dc4ac8be4fd9b214ad68549e/src/hpmp/hp-mp-regenerator.cpp#L229-L231
