### ISSUE TITLE
Mac X11 ビルド版で自動拾いが機能しない

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#119]
> Mac X11 ビルド版。自動拾いが機能しません。
> 
> Esc の編集メニューが文字化け、自動破壊は機能しています。

https://osdn.net/projects/hengband/ticket/41161

よりコピー、移植元は完了する。

**Comment by taotao54321** [comment]
本件は解決済みなのではないかと思います。
OSDN 側チケットのコメントにある通り、原因はヘッダファイル内に日本語文字列リテラルが存在することでしたが、一連の修正により現在はヘッダファイル内に日本語リテラルは存在しません:

```sh
$ find src/ -name '*.h' -exec egrep --only-matching '"[^"]+"' \{\} \; | nkf --guess
ASCII (LF)
```

実際、手元の Linux X11 環境では自動拾いは問題なく機能しており、編集時の Esc メニューの表示も正常です。
万一 Mac 環境固有の問題が残っていたらすみません。

**Comment by tanguband** [comment]
現在は Max X11 でも問題なく機能しています。
報告遅れてすみません。

**Comment by Hourier** [comment]
問題は解決したようですのでクローズします
皆様対応ありがとうございました

**Comment by sikabane-works** [comment]
了解しました。Alpha6付けにします。
