### ISSUE TITLE
【バグ】 闘技場で量子的効果によって引きずり出される

### ISSUE THREAD

**Issue by Aquashrimp** [hengband/hengband#1190]
## 環境

- OS: ？
- バージョン: 3.0.0Alpha25

## バグの詳細

闘技場に点Pもどきがいるとき、量子的効果のテレポアウェイによって@が闘技場内に引きずり出され、攻撃に巻き込まれる可能性がある

## 再現手順

点Pもどきがいる試合を観戦する？

## 期待される正常な動作

闘技場では@がテレポしないようにするか、あるいは量子生物ユニークを闘技場に出さないようにするべきと思われる

## 補足事項

巻き込まれたプレイヤーのダンプ
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=83702

**Comment by sikabane-works** [comment]
ちょっと手をつけてみます。
