### ISSUE TITLE
【バグ】 デバッグコマンドでクエストに飛び込むとバグる

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#1196]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha25

## バグの詳細

デバッグの^aGQでクエストに飛び込むとメモリの海に飛び込んで、
そのまま操作しようとするとクラッシュ、セーブして終了するとセーブが破壊される

## 再現手順

バグを発生させる手順が分かっていれば記載

^aGQ2

## 期待される正常な動作

クエストに入る

## 補足事項

多分@の現在座標をそのままクエストに飛び込んでるのかなって気がしますけどソース読んだわけではないです

**Comment by sikabane-works** [comment]
![image](https://user-images.githubusercontent.com/61610939/122038212-57a28780-ce10-11eb-8a77-83f056b44b4f.png)
即クエスト突入でもなければシステム即落ちという感じでもないですが、階層おかしいですね。まず調べます。

**Comment by sikabane-works** [comment]
修正を行って指定のダンジョン生成を行い飛ぶことはできるようになったが、クエストの目的ＩＤが０のままで本来の目的がたっせいされても達成扱いにならないというバグが残る。q_info.txtから階層や目的の情報を正しく引っ張っていくのにわざわざplayer_typeやグローバルから引っ張ってきている何かがあって正しくパースで来ていないようである。
