### ISSUE TITLE
macOSビルド終了後にトップディレクトリにバイナリがコピーされない

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#120]
https://osdn.net/projects/hengband/ticket/41153 より移植

> フォーラムより、OS XのX11ターミナルにて
> ウインドウズ用のプロジェクトフォルダ名と干渉しているようです。

**Comment by tanguband** [comment]
macos が ファイル名の大文字小文字を区別しない という仕様が原因です。
ウインドウズのプロジェクトフォルダ名 "Hengband" を他の名前に変えてコンパイルすると
以前と同様にトップディレクトリに hengband バイナリがコピーされることを確認しました。

**Comment by sikabane-works** [comment]
ありがとうございます。しかし、どうするべきか代替が難しくもありますね。

**Comment by tanguband** [comment]
Mac App版には影響はないですし、Mac X11 を利用する人もほぼいないでしょうから
個人的には未対応で問題ないと思います。

**Comment by sikabane-works** [comment]
では、readmeなどに留意点など加えて完了という形にしようかなと思います。報告、アドバイスありがとうございます。

**Comment by sikabane-works** [comment]
昨日記述済なので完了。
