### ISSUE TITLE
【バグ】光速移動時の練気術師の加速表示がおかしくなる

### ISSUE THREAD

**Issue by HiddenNameZ** [hengband/hengband#1211]
## 環境

最新のα版

## バグの詳細・期待される正常な動作

勝利dumpで0+99表記になるが0の部分は素の加速の方が良いと思う

**Comment by sikabane-works** [comment]
装備による半永久加速とバフによる追加加速を分化していない上に、8bitで処理しているのが原因。いい加減なんか修正かけたい。

**Comment by sikabane-works** [comment]
PlayerSpeedクラスの計算とダンプ表示をうまくかみ合わせるのが難しいので非騎乗時光速移動時には特別に表示を加えることで不自然さを解決することにした。普通に常時加速+90以上で一時加速+10かけている時は表示が依然おかしいままになるが妥協したい。
![image](https://user-images.githubusercontent.com/61610939/126813177-4e739764-22de-447d-9772-c7293bbbd21f.png)
