### ISSUE TITLE
3.0.0.4?: English autopick preference incompatibilities: "junks" to "junk" 

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#124]
This commit (my fault), https://github.com/hengband/hengband/commit/7def7b1376f35c5fa2ccaf393aa72681ef6679ef#diff-927c5529b966f004336ea19da011b8949442e4753146eab1f314ea1b537e533e , which made it into 3.0.0.4 or 3.0.0.5 introduces backward compatibility problems for existing English autopick preference files which make use of the "junks" key.  It is also incompatible with the default pickpref.prf (which uses the "junks" key for archers).

If introducing the backwards incompatibility is acceptable for you, then this pull request, https://github.com/hengband/hengband/pull/123 , brings the default pickpref.prf and English help file for the autopick editor into agreement with the new behavior.

If introducing the backwards incompatibility is not acceptable, then reverting the effect of that commit would resolve the problem.  I can make a pull request to do that if that's what you want.

**Comment by sikabane-works** [comment]
It had been fixed by #123. I close this.
