### ISSUE TITLE
【バグ】 所持金がマイナスになる

### ISSUE THREAD

**Issue by ghn-ky** [hengband/hengband#1240]
## 環境

- OS: Windows 版
- バージョン:  3.0.0Alpha28

## バグの詳細

モリバントにて矢の強化をしていたら所持金がマイナスになりました。
以下、＠のレベル25で（+2,+4）が26本、（+5,+5）が42本から強化した時のメッセージログです。

↓ここから
＄1040で26本の クロスボウの矢 (1d5) (+3,+5) (46/shot 47/crit 39/turn/4.43% crit)
に改良しました。
＄1040で26本の クロスボウの矢 (1d5) (+4,+5) (46/shot 47/crit 39/turn/4.46% crit)
に改良しました。
ザックの中のアイテムをまとめ直した。
＄2720で68本の クロスボウの矢 (1d5) (+5,+5) (46/shot 47/crit 39/turn/4.49% crit)
に改良しました。
↑ここまで

（+5,+5）に強化する際の矢の本数が、強化が済み矢束をまとめた後の本数になっており、所持金以上の費用が発生したようです。

## 再現手順

申し訳ないですが、まだ試していないです。
セーブファイルもないです。

## 期待される正常な動作

 (+5,+5) に強化したあとで、矢束がまとまるのが本来の挙動かと思います。

## スクリーンショット

これまた申し訳ないですが、取っていません。

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
店舗での矢の強化の周辺のコードを調査したところ、種族がアンドロイドの場合に発生するのではないかと思しき箇所が見つかりました。
種族がアンドロイドだったかどうか確認したいのですが、どうだったでしょうか？

**Comment by ghn-ky** [comment]
確かにアンドロイドの＠でした。
