### ISSUE TITLE
キャラクターネーム変更時にセーブファイルを継続するオプション

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#126]
OSDNフォーラムより。
https://osdn.net/projects/hengband/forums/37402/43663/#forum-message-86986

前半省略。
ついでに。過去プレイヤーネームを変えるとセーブデータが分離して新規作成されることを報告しましたが、
やはり新しいキャラで始めるたびセーブが増えるのは煩雑です。できれば2.2.1r同様、セーブデータが継続するようにしてほしいです。

**Comment by dis-** [comment]
仕様の検討が必要です。

・指摘通り、以前の仕様にする。キャラネームとセーブファイル名は独立とする。
・指摘を却下し、現状の仕様を維持する。キャラネームとセーブファイル名は一致させる。
・オプションを付けて選択可能にする。

私は選択可能にするのが一番不満が少ないと判断しますが、他のメンバの判断はどうでしょうか。

**Comment by sikabane-works** [comment]
オプション付けますかねえ。とりあえず余裕ついたら手つけるつもりで１票。

**Comment by iks3** [comment]
キャラメイク時の改名だけなので、初期オプションに同一のセーブファイルでゲーム開始するオプションを追加。
