### ISSUE TITLE
【バグ】 鏡使いの静水のMP回復量の表示がおかしい

### ISSUE THREAD

**Issue by radinms** [hengband/hengband#1266]
## 環境

- OS: Windows10
- バージョン:  3.0.0Alpha31

## バグの詳細
鏡使いの静水のMP回復量の表示がおかしい

## 再現手順
鏡使いでプレイしてレイシャルの画面を開く
Lv30でMP回復量が　4　と表示される

## 期待される正常な動作
wikiによると

> MPが(5+レベル*レベル/100)回復する.

であるので、Lv30なら14回復と表示されなければおかしい。
実際、静水を実行すると14回復される。
表示が明鏡止水のMP回復量になってしまっているのではないかと推測。

## スクリーンショット

![unknown](https://user-images.githubusercontent.com/26111256/126061808-52f35ca2-829f-44f7-88c8-87d045f31b2a.png)

## 補足事項

補足事項があれば記載

**Comment by sikabane-works** [comment]
確認の上修正します。
