### ISSUE TITLE
【要望】視界外のモンスターの行動による効果音をオフするオプションが欲しい

### ISSUE THREAD

**Issue by 7exp** [hengband/hengband#1267]
**要望**
テキスト表示のオプション「視界外のモンスターの行動を表示しない」のように、
「視界外のモンスターの行動による効果音を鳴らさない」的な物があると嬉しいです。

**補足**
効果音の仕様を把握しておらず体感ですが、ある程度(テレパシーの感知距離ぐらい？)接近すると視界外でも効果音が鳴る感じです。
vault内が乱戦状態の場合、@が一歩動くたびに多種多様の効果音が鳴り響き煩わしいのでテキスト表示オプションのように抑制手段があればと考えた次第です。
ご一考いただけましたら幸いです。

●まだ効果音が聞こえない距離
![image](https://user-images.githubusercontent.com/79756503/126517318-40d459dc-6704-478a-b596-769300c5b8ac.png)

●効果音が聞こえだす距離
![image](https://user-images.githubusercontent.com/79756503/126517426-75c42f8a-6780-42b3-9ec9-7ba6d0c01fbb.png)

**Comment by sikabane-works** [comment]
Alpha36で完結していたようなので閉じます。
