### ISSUE TITLE
勝手版のウィンドウフラグ「足元のアイテム一覧」の輸入

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#127]
https://osdn.net/projects/hengband/forums/37402/43663/#forum-message-86988

より要望があったのでチケット化。

> 勝手版のウィンドウフラグ「足元のアイテム一覧」が非常に便利だったので本家での実装を検討していただきたいです

**Comment by taotao54321** [comment]
実装は可能だと思いますが、勝手版のコードを読んだところ一覧表示更新関数をいろいろな場所から呼び出しているようなので、その辺整理できないとコードの複雑性は増しそうです。
単にプレイヤーの足元を対象にするのでなく、look コマンド中などはカーソルのあるマスを対象とする、という仕様なので、それにうまく対応できるかどうかという感じです。

**Comment by sikabane-works** [comment]
元よりソースコードはリファクタリングで大きく乖離してしまいましたし、仕様だけ確認の上独自実装しかなさそうですね。それを踏まえて行きましょう。
