### ISSUE TITLE
【バグ】 魔法を防ぐクロークが自動拾いでレア判定されていない

### ISSUE THREAD

**Issue by HiddenNameZ** [hengband/hengband#1270]
## 環境

- バージョン: [3.0.0Alpha31]

## バグの詳細

魔法を防ぐクロークが自動拾いでありふれた装備扱いなので他の装備に巻き込まれて破壊されてしまうことがある。

## 期待される正常な動作

レアな装備扱いにする。
あと、（金銭確保のために）ミスリル鎧とアダマンタイト鎧の3種類もレア扱いにしてほしい。

**Comment by sikabane-works** [comment]
アイテム関係はHourier氏の意見も聞きたいですが、この辺は流石にありふれた扱いにすべきでないと思うので、私の判断で受理して修正します。
