### ISSUE TITLE
鍛冶師の新規耐性へのエッセンス対応について

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1273]
### 鍛冶師の新規耐性へのエッセンス対応について
呪力・水・時間逆転についてエッセンスが非対応になっていますので処理を追加できないでしょうか

_Originally posted by @gold-onion in https://github.com/hengband/hengband/discussions/321#discussioncomment-1043166_

**Comment by gold-onion** [comment]
報告が抜けてましたが善良倍打も非対応でした
強撃も多分非対応ですがこれは攻撃エッセンスですかね

**Comment by sikabane-works** [comment]
善良スレイと強撃も素直にエッセンス化したいところですね。

**Comment by sikabane-works** [comment]
これ追加するのエッセンス管理関係を先にリファクタリングした方が平和になりそうな気がする。

**Comment by habu1010** [comment]
https://github.com/hengband/hengband/discussions/321#discussioncomment-1043166
での鍛冶師のエッセンス案まとめ

### 採用する

- 耐水・耐時間逆転・耐呪力 (対応済み #1515)
- 善良スレイ/ESP (対応済み #1515)
- 切れ味 (刀剣類のみ？ただ地震のエッセンスは従来より鈍器以外にもつけられる模様)
- 魔術属性（現状ではエッセンスの入手手段が限られる）
- 免疫付与を免疫エッセンス＋対応耐性エッセンスにする

### 採用したい

- 二刀流
- アーティファクト（固定/ランダム問わず）から専用のエッセンス抽出。とりあえず使い途の1つはユニークESP/感知発動？
- 武器重量増加（強撃エッセンスを使用するなら、入手手段が少ないので鍛冶強化の別枠でよさそう）
- 反テレポート
- 発動効果 ( https://github.com/hengband/hengband/discussions/321#discussioncomment-1306692 https://github.com/hengband/hengband/discussions/321#discussioncomment-1306754 ) 鍛冶師で使えそうなのはだいたい出ていそう

### バランス考慮の必要あり

- 強力射/強速射（専用のエッセンス。ただ強力+強速の弓を簡単につくれそうだが問題ないか？）
- 強撃の小手作成

### とりあえず見送り

- 武器への強撃属性付与

**Comment by habu1010** [comment]
Issueの海に埋もれてしまっているので、対応優先度の高いものとしてPinしておきます。

**Comment by habu1010** [comment]
#1519 で鍛冶を実装していく。

**Comment by habu1010** [comment]
ひとまず、現時点で実装できそうなものは入れた。

以下は #1519 には含めず一旦保留。

- 発動効果 : 鍛冶と別枠で付与できる方向で考えたい
- 重量化/軽量化：鍛冶に限らず巻物などでもできるようにするかもしれないので、細かい仕様を詰める必要あり？
- ランダムアーティファクト生成：ユニークエッセンス大量消費でのロマン枠？
- 強撃の小手：攻撃回数-1にする調整は必須か

**Comment by habu1010** [comment]
発動付与は通常の鍛冶と枠を別にする方向にしたいと思います。
現状の地震発動(+地震攻撃)/一時元素耐性(+元素耐性)のエッセンス付与は発動単体に分けるようにします。
また、発動だけを個別に任意でつけ外しできると便利すぎるので、エッセンス消去では耐性等の通常の付与効果と発動効果の両方が消える仕様にしようかと。

**Comment by habu1010** [comment]
#1527 にて発動効果の別枠化と新しい発動効果の鍛冶を追加する。

**Comment by habu1010** [comment]
ひとまず鍛冶師のリファクタリングと新エッセンスの追加は一区切りとする。
今回見送りした案件としては以下。

- 強撃のエッセンス：強撃属性が強力なため、バランスが難しい。
- 装備の重量化/軽量化：細かい仕様などを別途検討の必要あり。

**Comment by habu1010** [comment]
もう1件

- ランダムアーティファクト生成

実装自体はすぐできそうだが鍛冶としてのランダムアーティファクト生成の存在自体がどうなのかという議論がなされる必要がありそう
