### ISSUE TITLE
【バグ】深層に飛んだ際に鉄獄のランクエが放棄されるタイミングがおかしい

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#1276]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha31

## バグの詳細

トランプタワーで高額支払うかパターンVaultで98Fに飛んだ時に道中のクエストが放棄されず、
次に鉄獄に帰還した時に初めてクエスト放棄したことになる

## 再現手順

いかさまでトランプタワーから飛ぶのが多分一番簡単？

## 期待される正常な動作

98Fに降り立った時点で道中のクエスト失敗

## 補足事項

Discordかどこか忘れたけど既に報告上がってたはず。Issueが見当たらないので作成

**Comment by sikabane-works** [comment]
Alpha35触りましたが、すくなくともトランプタワー帰還直後にすぐクエスト失敗フラグの付加を確認しました。
execute_recall()の内容を見ても特に問題ないようです、鉄獄かそれ以外かの処理にちょっと問題あるようなのでリファクタリング向けIssueに直します。
あと、パターンからのジャンプがどうなっているかは別途チェックします。

**Comment by daradarach** [comment]
この時確認したのがパターンからのジャンプで、以前Discordで見かけたのだトランプタワーだったように記憶していますが、
もしかしたらパターンからのジャンプに限定される話かもしれません

**Comment by sikabane-works** [comment]
今ちょうど、パターンの終着点からのテレポートではランクエ自動失敗処理が行われていないのを確認しました。こちらは修正します。
