### ISSUE TITLE
鍛冶師の新規エッセンス対応のためにリファクタリング

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1282]
流石に今のまま追加しようとすると色々しんどくなりそうなので整理。

整理手順の項目は追々まとめる。

**Comment by Hourier** [comment]
ざっくり案ですが、他の応用 (攻撃魔法やスレイ効果等)が幅広いので提案しておきます
コメントを中心にかなり減らしましたがそれでも20万行程度あるので、抽象的な依存関係を可能な限り高く目指すすべきと考えています
- switch-caseがある箇所をファクトリクラスに移す
- case文で処理を実行している箇所をインターフェース返却に変える
  → インターフェースメソッドを叩けば対応するエッセンスを抽出できる

**Comment by Hourier** [comment]
別件でcmd-smith.cpp/h を確認しました
本件の前段として、まずメソッド分割をするのが先決となりそうです
このチケットは別件対応との兼ね合いもあるので引き取ります

**Comment by habu1010** [comment]
こちら今回の鍛冶師のリファクタリングと関連づけてマージとともにクローズします。

**Comment by habu1010** [comment]
今後の進捗は #1488
