### ISSUE TITLE
【要望】 攻撃魔法キャンセル時の魔力消費のタイミング変更

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#1293]
## 環境

- OS: Mac X11
- バージョン: 3.0.0Alpha32

## 要望の詳細

ターゲット指定ができる攻撃魔法をターゲット前にキャンセルした場合にMPを消費しないように変更してほしい

## 再現手順

1. カオスハイメイジでスタートする
2. マジックミサイルの魔法を覚える
3. maaコマンドを入力
4. escでキャンセルする
5. マジックミサイルを打っていないのにMPは消費する

## 期待される正常な動作

攻撃魔法が打ち出されたあとにMPを消費する

## 補足事項

他のターゲット可能な攻撃魔法でも同様の動作になりますが、元素使いの場合はキャンセル時にMPが減らなかったように記憶しています
マクロを組んでいて隣のキーと押し間違えたりすることがあるのでキャンセル時にMP消費しないと助かります

**Comment by sikabane-works** [comment]
その辺何かと統一されていないのが痛いですね。領域魔法はどうなっているかとりあえずチェックします。
