### ISSUE TITLE
【バグ】デバッグのモンスター生成が仕様通りではない

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#1302]
デバッグのIDを指定してのモンスターの生成が自然生成と同じ（FRIENDLYフラグを持つモンスターは友好で召喚される）で、
`@brief モンスターを種族IDを指定して敵対的に召喚する `
の仕様通りではないと感じたのでIssue化。

ペット召喚の対義でこういう表記の可能性もあるがその場合もコメントの内容が少々わかりにくい気がするので改良が必要そう。

**Comment by Hourier** [comment]
そのコメント自体が怪しい気がします
「同一友好状態」かつ「同一の(一時)アライメント」で召喚されるのが正しい気がします
(適当なことを言ってるかもしれません)

**Comment by Slimebreath6078** [comment]
「同一」の意味がよくわからないですが、r_info.txtでされている設定と同一という意味でしょうか？

**Comment by Hourier** [comment]
FRIENDLYフラグを持ち、かつ友好的なモンスターが召喚する→友好的生成
FRIENDLYフラグを持ち、かつ＠の攻撃等で敵対的になったモンスターが召喚する→敵対的生成
を意図しました

**Comment by Slimebreath6078** [comment]
モンスターが放つ召喚魔法については #1268 で既に手を打っております。

今回のIssueは`void wiz_summon_specific_enemy(player_type *summoner_ptr, MONRACE_IDX r_idx)`（デバッグコマンド'n'で発動できます）についてです。
ここで呼び出されている召喚は召喚主IDが0で自然生成と同じであり、その仕組みがコメントと嚙み合っていないと思いましたのでこの内容のIssueになっております。

**Comment by Hourier** [comment]
承知しました
それであれば上記のコメントは無視して進めて下さい
よろしくお願いします

**Comment by Slimebreath6078** [comment]
承知いたしました。内容をコメントに合わせる方とコメントを内容に合わせる方の２択が思いついているのであとでプルリクエスト放ちます。
