### ISSUE TITLE
天使に攻撃を仕掛けた場合の徳条件の修正

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1317]
シンボルでなくANGELフラグ持ちを攻撃した場合のみとする形に変更。
https://github.com/hengband/hengband/pull/1309/commits/a7f916424ec6cd6691680f6fec0811097dbb615a

**Comment by Hourier** [comment]
(念のため確認)
記憶が確かなら、ANGELフラグを実装した目的の1つがまさにこれだったはずですが、間違いないですよね？

**Comment by sikabane-works** [comment]
問題ないです。
