### ISSUE TITLE
【バグ】 血の呪い（悪魔）で無限ステ減少が起きる

### ISSUE THREAD

**Issue by aaaa-404** [hengband/hengband#1324]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha32

## バグの詳細

whileが無限ループになってるっぽいです。

[血の呪い（悪魔）](https://github.com/hengband/hengband/blob/88a6fcbf413d85be7155323a4b05c757daa1b18a/src/spell-kind/blood-curse.cpp#L124)

`                    while (is_first_dec_stat || one_in_(2)) {
                        (void)do_dec_stat(caster_ptr, i);
                    }`

[太古の怨念](https://github.com/hengband/hengband/blob/88a6fcbf413d85be7155323a4b05c757daa1b18a/src/spell-kind/spells-random.cpp#L223)

`                while (is_first_dec_stat || one_in_(2)) {
                    is_first_dec_stat = false;
                    (void)do_dec_stat(target_ptr, i);
                }`

## 再現手順

血の呪いを使って、ステ減少を発生させ、なおかつ1/13チェックを通る。

## 期待される正常な動作

腕力が1回下がる。各ステータスについて 1/2 で連鎖で下がる。

## 補足事項

にわかなので間違っているかもしれません。すいません。
いつもメンテナンスしてくださってありがとうございます。

**Comment by sikabane-works** [comment]
いえ、こちらこそ申し訳ありません。報告ありがとうございます。
今回大規模リファクタリングを導入して、随所にエンバグが起きている可能性が多いので直ちに対処します。
