### ISSUE TITLE
【バグ】 モンスターの移動ルーチンの異常と思われる現象

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#1325]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha33

## バグの詳細

https://jbbs.shitaraba.net/bbs/read.cgi/game/9358/1625410635/291 より転載
```
最新版、敵の動きがバグってるような希ガス
敵が@を無視して全力で下に向かっていることがある
バージョンアップはしない方がよさげ
https://i.imgur.com/KIjbZww.png
```

**Comment by gold-onion** [comment]
Alpha34を動かしてみたんですが、これ直りきってないっぽいです

**Comment by sikabane-works** [comment]
再検証します。

**Comment by sikabane-works** [comment]
> Alpha34を動かしてみたんですが、これ直りきってないっぽいです

すみません、さいげんできたらそのセーブデータアップしていただけるとありがたいです。

**Comment by gold-onion** [comment]
[Europa.zip](https://github.com/hengband/hengband/files/6960766/Europa.zip)
右の対邪悪結界の巻物がある小部屋にカブラックスがいたんですが
目覚めたらこちらに寄って来ず下に走っていってしまいました
なおカブラックスはまだ生きてて下の方にいます
視界内だと寄ってきますが視界から外れるとまた下に行ってしまいます

**Comment by sikabane-works** [comment]
こちらが新バージョンに修正を加えていなかったことがそもそもの原因でした。大変申し訳ありませんでした。Alpha35で再更新します。
