### ISSUE TITLE
不要な型エイリアスの削減 Alpha36

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1366]
現在の変愚蛮怒ではintを32ビット未満で定義している処理系では正しく動作しない可能性が極めて高い (特に経験値やお金等、65536以上の値を取りうる変数群)
かつ、C++11以上のコンパイルが可能な環境でそのような処理系が存在する確率も極めて低いと想定される
よって、旧式環境での起動はmain関数で型のビット数チェックを行うことにより弾く方針とする
型自体のエイリアス (例：POSITION)は差分肥大化防止の都合上多少残すが、intやshortへ置換が可能な部分はできるだけ消す

**Comment by sikabane-works** [comment]
C++、ましてや最新の版に対応する中でtypedef定義は陳腐すぎるとは思うので、昨今の流行りに併せていくことに賛成です。それがどうあるべきかについては一度discordなりで相談いただければと思います。

**Comment by Hourier** [comment]
s32b等の置換範囲が膨大につき、先にPR出します
それベースに相談お願いします
