### ISSUE TITLE
一部ユニークを除くモンスターが時止めを使用時のメッセージを自然な形に変えて欲しい

### ISSUE THREAD

**Issue by ironside777** [hengband/hengband#1378]
## 環境

- OS: Windows
- バージョン: 3.0.0Alpha35

## バグの詳細

岩倉玲音が時止め使用時に
hek!
という不自然な文字が表示される。
discordでの話題で、意図したものではなかったということのはず。

## 期待される正常な動作

然るべきメッセージを表示する。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付
![hek](https://user-images.githubusercontent.com/79457166/130236603-abb2b643-fb21-4239-a171-ccef923f4557.png)

**Comment by Hourier** [comment]
時止め発動時は「hek!」と表示するのが仕様です (ある意味エラーメッセージのようなものですが)
以下のユニークは特殊処理でそれ以外のメッセージを表示させています
- ディオ
- リチャード・ウォン
- ディアボロ (v3.0.0で追加)

また、仕様として不自然であることはバグではないので、タイトルを変更します

**Comment by Hourier** [comment]
備忘録
- 「○○は時を止めた！」に差し替える
- 逆LOSで見えない位置から時を止められたならば「何者かによって時が止められた！」とする (時が止まったことを＠が認識できるのかは分からないがこの際無視する)
