### ISSUE TITLE
race_typeの耐性情報フラグ群 flagsrをBIT_FLAGSからFlagGroupに置き換える

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1394]
今後、新規の耐性を追加しやすくすることを目的とする
また、天使やら動物やらの種族指定フラグ等へも今後応用を広げるための土台としても利用する
(現在は最大32個までしか対応できない上にsave/loadが大変)

フラグ群だけで相当な数があるので、1つずつ考える
作業予定
- 前提として、作業終了まで現行の耐性フラグ群は放置
- race-flags3.h のHURT\_\* 群と、race-flags-resistance.h の内容を統合した、新しいenum class を作る。名前は暫定でRR (Race Resistance)とする
- 特にFIREとCOLDはHURT\_\* とIM\_\* がある。全ての属性について、予約領域としてHURT_\* (5元素、光、掘削だけで良さそう？ 予約ということで全部追加する？)、RES\_\* (5元素に対応しダメージ1/3)なんかも追加しておく
- enum class の準備ができたら、上記のmapを読み込むように修正する (注：race-readerだけでなくdungeon-readerもこれらのフラグを参照している。まともに動くかは地獄に火炎耐性のモンスターしか湧かないこと等を要確認)

後日確認事項
思い出フラグの取り扱い

**Comment by habu1010** [comment]
その用途のために EnumClassFlagGroup<enum class> を作っているので、std::map<enum class, bool> ではなくこちらを使うようにしてもらえないでしょうか。
std::map<enum class, bool> では論理演算のような事ができないので不便なところもあると思います。

**Comment by Hourier** [comment]
単にenumをリスト化のようなものだと思ってました
ability_flags 等で既に実装があるのでこれを参考に進めてみます

**Comment by Hourier** [comment]
備忘
破壊的変更になる可能性が極めて高い
セーブデータの互換性には気をつける
