### ISSUE TITLE
アプリを切り替えてもサブウィンドウが消えないオプションが欲しい

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#14]
OSDNより移行。
[41490](https://osdn.net/projects/hengband/ticket/41490)

アプリを切り替えると自動的にサブウィンドウが消えるために、
他のアプリケーションからウィンドウを対象に取れないため

**Comment by habu1010** [comment]
マージ＆クローズされた後ですが、Discordでゲームプレイオプションに入れるのはちょっとおかしいんじゃないかという話になりました。
例えばX11版では元々サブウィンドウは常に表示された状態で、このあたりは描画ドライバに依存した部分になります。
なので、ゲームオプションではなく、Windows版のメニューにトグルスイッチを追加し、それで制御するようにすべきだと思います。
