### ISSUE TITLE
【要望】地形・毒・負傷などによる被ダメージに効果音を付けてほしい

### ISSUE THREAD

**Issue by 7exp** [hengband/hengband#1401]
以下のような状況で@がダメージを受けた際に効果音を出していただきたいです。
　１：溶岩地形、酸・電・冷・毒地形、深い水などの地形移動時のダメージ
　２：毒状態、切り傷などによるダメージ

混戦で注意散漫になった時についやらかしてしまうのですが、死因ランキングでもほどほどにカウントされているので初心者救済の観点でもご一考いただければ幸いです。

**Comment by Hourier** [comment]
要望はこちらまで
https://github.com/hengband/hengband/discussions/356
https://github.com/hengband/hengband/discussions/1139

**Comment by 7exp** [comment]
重複失礼しました、すでにあったんですね。

**Comment by shimitei** [comment]
重複ではないし、新たに立てるまでもないので再オープンします。

ぼんやりしたアイデアや質問はDiscussionsが良いけれど、
明確な要望はIssueで良いんじゃないかな。
一応公式WEBには質問、要望はDiscussionへどうぞと書いてあるけれど。
