### ISSUE TITLE
Enum Class (Enumも) を内部整数型に変換する関数の導入

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1404]
## 概要

列挙型の enum class 化をすすめるにあたり、ソースコード内で配列のindexとして使用する場合などにenumと違い整数型への暗黙キャストは許可されていないため整数型への明示的なキャストが必要なので、それを行う関数 `enum2i()` を導入する。

## static_cast の代わりに使用するメリット

- 他のキャストと見分けが付くのでやっている事が明確になる
- std::underlying_type などのメタクラスを使って実装することで、キャスト先の整数型を自動的に決定できる。 `auto idx = enum2i(enum_class_val);` のように書ける。

**Comment by Hourier** [comment]
良いと思います
C++23では新しい構文が追加されるようですが、それがVSでも (まともに)使えるようになるには大体+1年と見て最速でも2024年なので、待っている理由もないと思います
