### ISSUE TITLE
オブジェクトの判定関数の不要なplayer_type引数を削除する

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1409]
object_is_\* 等のオブジェクトの判定関数は、判定に使用しないのにも関わらず item_tester_hook に関数ポインタを渡したいがためだけにplayer_typeを引数として取っているものが多々ある。
これが原因で必要もないのに player_type 構造体があらゆる箇所で引き回されて大変残念な事になっている。
まず根本原因のこれらをどうにかしたい。

**Comment by Hourier** [comment]
そもそもグローバル関数ポインタという設計自体がかなり怪しい気がします
「これひどいなぁ」と思いつつ当時はp_ptrの方が悪だったので泣く泣く引数に入れ込んだのですが、もし消去できるのであれば万々歳です
