### ISSUE TITLE
鉄獄ランクエ報酬のしょぼいのをもう少し羽振りよくする

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1413]
深層ランクエで高級品少し増えても仕方ないと思ったが、序盤でもエゴ矢とか穴掘りムカつくとの意見もDiscordで多かったので。

前者は★☆生成確定、後半は階層ごとにアイテム種やエゴを特定するか？

**Comment by Hourier** [comment]
上の話と併せて、このチケットでは4点を実施する
https://discord.com/channels/724811119545417790/802110221093699584/893779414377193554

- 呪われた装備を弾く (「状況によっては強い場合もある」はRQ報酬としてふさわしくない＆特に初心者に優しくない)
- エゴ矢弾 (価値が低い)
- 穴掘りエゴ (同上)
- 討伐対象より更に少し上のドロップテーブルを使う

RQフロアごとのバイアスはこのチケットではやらない
調整結果を見てから更に考える

**Comment by Hourier** [comment]
ついでに高級品の階層バイアスを上質よりちょっとだけ上方修正してみる
