### ISSUE TITLE
【バグ】アイテム欄に表示されるはずのアルファベットが表示されていない

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1426]
## 環境

- OS: Windows 10
- バージョン: 3.0.0Alpha36

## バグの詳細

掲題の通り

## 再現手順

1. 適当なセーブデータを作る
2. サブウィンドウに持ち物一覧を表示させる
3. 掲題のバグが発生

## 期待される正常な動作

a) hoge
b) fuga
等と表示される

## スクリーンショット

![image](https://user-images.githubusercontent.com/66951241/131209613-8c0b3c06-f82e-4008-91bf-bf2bde8c22ab.png)

## 補足事項

git bisectしたところ、下記コミットで混入した模様
https://github.com/hengband/hengband/commit/0b005e6274231ca035b249ee43a0581466bab40c

display-sub-windows.cpp ないしその周辺が怪しいように見える

**Comment by habu1010** [comment]
リファクタリング前は絞り込み対象のアイテムの記号のみ表示するという仕様だったので、それに準拠させる
