### ISSUE TITLE
【バグ】 乗馬中に向かない武器のペナルティが機能していない

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1441]
## 環境

- OS: Any
- バージョン: 3.0.0Alpha36

## バグの詳細

乗馬中に向いていない武器（ランスもしくはヘヴィ・ランスでなく、かつRIDINGフラグのついていない武器）を乗馬中に装備したときに受ける命中ペナルティが機能していない

## 再現手順

1. 適当なモンスターに乗馬する
2. ダガー等乗馬中に向かない武器を装備する
3. 「乗馬中に向かないようだ」というメッセージも出ないし、命中率も下がらない

## 期待される正常な動作

乗馬中に向いていない武器を装備した場合はペナルティを受け、その旨のメッセージが表示される

## 補足事項

以下の乗馬中に向いている武器かどうかの判定部でランスもしくはヘヴィランスではないという判定をする部分の括弧の付け方がおかしい。コードが重複しているのもやや問題あり。

https://github.com/hengband/hengband/blob/3aad4c5e300c4e55fabf01f3cee74a1fcbcf1d3f/src/player/player-status-flags.cpp#L2064-L2067

https://github.com/hengband/hengband/blob/3aad4c5e300c4e55fabf01f3cee74a1fcbcf1d3f/src/player/player-status.cpp#L2203-L2204

**Comment by Hourier** [comment]
こちらで引き取ります
(多分私のミス)

**Comment by Hourier** [comment]
取り敢えず私のミスではなかったようですが、乗りかかった船なのでこのまま進めます
