### ISSUE TITLE
【documentation】 Link to "Hengband Application for Mac OS X" from https://hengband.github.io/link.html

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#1449]
## 環境

- OS: macOS 11.5.1
- Safari 14.2.1 accessing https://hengband.github.io/link.html as of 2021/9/4

## バグの詳細

Links to the osdn site, http://hengbandforosx.osdn.io/index.html.en .  It is likely better to link to the one, https://backwardseric.github.io/hengband/ , hosted on GitHub since the one on osdn is not being updated.

**Comment by Hourier** [comment]
Thank you for your contact and I welcome that you move to GitHub practically!
I'll fix the URL, please wait a while.
It'll be reflected around the night of Sunday (JST).

**Comment by Hourier** [comment]
I reflected your request.
Please check the web page tomorrow.
https://github.com/hengband/web/pull/127
