### ISSUE TITLE
concptr をstd::string_view に置換する

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1450]
Discordの議論より
型エイリアスよりC++標準の型を使うことでモダンな設計へ進化させることを目的とする
手始めに、Alpha37で実施しかけた (が、作業量が多くなる可能性が高まったため保留した)get\_rnd\_line() 及び関連のメソッドから置換する

備考：
変愚蛮怒は既にC++17でないとコンパイル不能になっている
エラーメッセージ引数のないstatic_assert<T>() がコード中に含まれるため

**Comment by sikabane-works** [comment]
タイトル変更。

**Comment by sikabane-works** [comment]
優先度中、マイルストーンBetaとします。これも皆気づくごとにファイルやフォルダ一括で修正していく形でいきましょう。

**Comment by Hourier** [comment]
これ単体でどうにかなる分量ではない (α85時点で、ヘッダだけでまだ300箇所以上)
都度チケットを立てることとしこれはクローズする
