### ISSUE TITLE
最近追加された耐性がランダムな耐性付与で付かない

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1451]
3.0.0Alphaで 時間逆転耐性・水耐性・呪力耐性 が追加されたが、これらの耐性は固定アーティファクトやエゴアイテムで付与されるランダム上位耐性や、ランダムアーティファクトの生成で付与されることがない。
これらの耐性だけ付与されることが無いのは不自然に思えるが、一応仕様として付与されるべきかどうかの議論は必要かもしれない。
なお、王者の加護の指輪だけはなぜか時間逆転耐性と水耐性はランダム付与されるようになっている。（呪力耐性はつかない）

**Comment by Hourier** [comment]
該当の処理をリファクタリングしたり、水耐性の付与に関する議論に参加したりしましたが、チケットの件は「単にマンパワーが追いついていないだけ」です
時間が余裕があればやってもらえると万々歳ですが、様々な順番の都合 (例：クラス化/インターフェース継承を先にやりたい)で相当後回しになっています

同根の話で、鍛冶師の抽出/付与等が現在未実装です
https://github.com/hengband/hengband/issues/1282

**Comment by habu1010** [comment]
了解しました。
単に処理が抜けているだけという問題なのであれば、ひとまずランダム上位耐性付与とランダムアーティファクト生成で付くようにしてみようと思います。
