### ISSUE TITLE
enum class に先行宣言を導入する

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1452]
モンスター種族番号を始め、「何か1つ足すとリコンパイル範囲が広くなるenum」はいくつもある
更に、ヘッダ間インクルードで循環参照が起きると解消が難しい
(先日までgeometry.h が相当な悪さをしていた。enumそれ自体は循環参照の原因になりにくいが、ヘッダがヘッダを呼ぶことに躊躇いがなくなると、長期的には再発の危険性がある)
なるべくインクルードを*.cpp 側に寄せる目的もあり、表題の作業を行いたい
副次的にファイル間の依存関係を明らかにし、クラス統合の足がかりとしたい

**Comment by Hourier** [comment]
ヘッダより実装側を重くしたいので、例えばsv-*.h 辺りはこのenum class化に伴って統合してしまってもいいかもしれない
(定数の塊なので敢えて分ける意味合いが薄い)

上記を実施できた場合、別チケットにあるobject-info/ フォルダに移すなど応用が広がりそう

**Comment by sikabane-works** [comment]
ひとまず進展ないようなので、Alpha39に回させてもらいます。

**Comment by sikabane-works** [comment]
いつでもいいのでとりあえずバージョン指定は消しました。

**Comment by sikabane-works** [comment]
これまでのリファクタリング見ていると概ね目的を達している気はするが一通りチェック済ませてからにする。マイルストーンもそのため遠目に飛ばす。

**Comment by Hourier** [comment]
以下のようなプロトタイプ宣言が浸透してきたので、これはクローズして都度対応にします
```c
enum class HogeType;
```
