### ISSUE TITLE
モンスターリストの自動更新からミミック類を外す

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#147]
Discordで出た話題の備忘録

デスソード等が丸見えになっているとフレーバー的に面白くないという意見が出た
Wikiでいうところのミミック・クリーピングコイン・スペースモンスター辺りを表示させないようにする？
(最後は微妙な気もするが一応議題に挙げておきたい)

**Comment by taotao54321** [comment]
v2.2.1 にそのようなコードの残骸がありました(コメントアウトされています):
https://github.com/hengband/hengband/blob/5e4acf90005915536cb067b1dac85e1f7d04924a/src/xtra1.c#L1796-L1812

過去に何らかの議論を経て今の形になったのかと推測していましたが、詳しいところはわかりません。

**Comment by habu1010** [comment]
https://github.com/hengband/hengband/discussions/89
実はこの議題に関してDiscussionsの方に投稿してます。
Beta版ゆえにWebhookでの通知もなく、上のバッジも出ないので気づきにくいですが…

**Comment by Hourier** [comment]
あー、見当たらないと思って作ったら記憶違いではなく重複でしたか、すみません
続きは向こうでやろうかと思います
