### ISSUE TITLE
鍛冶師エッセンス付与時のエッセンス量表記を「必要数/所持数」から「所持数/必要数」に変える

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1493]
鍛冶師のコードのリファクタリングをしていて、エッセンス量の表記は「必要数/所持数」より「所持数/必要数」のほうが直感的でわかりやすいと感じた。
また、他のゲームにおいてもこの手の表記は後者であるのが普通だと思われる。
Discordで確認したところ同意が得られたので、鍛冶師のリファクタリングに合わせて表記を変更する。

**Comment by Hourier** [comment]
鍛冶師のリファクタリングはセーブデータの互換性を失うほどドラスティックな改造なので、別ブランチにて実施して頂けるととても助かります
ご連絡まで

**Comment by habu1010** [comment]
了解しました。
この件だけ単体でPR出すようにします。
