### ISSUE TITLE
職業固有データを分離する

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1520]
各職業の専用データを格納する場所として player_type::magic_num1[] 等が共有されていて可読性も拡張性も全く無いのでどうにかしたい。以下にアイデアをメモしておく。

### 職業専用データの定義

普通に構造体で定義する。呪術師のデータの例

```c++
struct spell_hex_data {
    FlagGroup<spell_hex_type, HEX_MAX> casting_spells;
    RevengeType revenge_type;
    int16_t revenge_turn;
};
```

### player_type へのもたせ方

std::variant を使う。
データはshared_ptrに入れる（player_typeヘッダでは職業専用の構造体は前方宣言で済ませたいため）

```c++
struct player_type {
    std::variant<no_class_specific_data, std::shared_ptr<spell_hex_data>, ...その他の職業専用データ> class_specific_data;
}
```

PlayerClass あたりに、職業専用データの初期化と、職業専用データへのポインタを得るメソッドを作る。職業専用データの初期化は適切なタイミングで行う（ゲーム開始時、セーブデータロード時等）

```c++
class PlayerClass {
    void init_specific_data(); // player_ptr の class や realm 等に従い、player_type::class_specific_data を設定する
    template <typename T>
    shared_ptr<T> get_specific_data(); // Tで指定した型のデータを取得（init_specific_info()でT型のデータが設定されているはず）
};

// 呪術師専用データへアクセスする例
auto specific_data = PlayerClass(player_ptr).get_specific_data<spell_hex_data>();
specific_data->revenge_type = RevengeType::PATIENCE;
```

### データのセーブ/ロード

それぞれVisitorを作成し std::visit でデータのセーブ・ロードを行う

```c++
struct SaveVisitor {
    void operator(const std::shared_ptr<spell_hex_data>& data) {
         // spell_hex_data のセーブ処理
         wr_FlagGroup(data->casting_spells, wr_byte);
         wr_byte(enum2i(data->revenge_type));
         wr_s16b(data->revenge_turn);
    }
};

std::visit(SaveVisitor{}, player_ptr->class_specific_info);
```

**Comment by Hourier** [comment]
現状、PlayerClass は単なるカプセル化のためのしょぼい入れ物にしかなっていないので、このように状態を持たせる方針での拡張は大歓迎です！
拡張の余地としては、PlayerRealm (要作成)クラスをPlayerClassに持たせておいた方が良いように思います
クラスごとの領域も (特にこの呪術と、第2領域に制限がかかるプリースト)色々あるので

**Comment by habu1010** [comment]
https://github.com/habu1010/hengband/commit/f1dc8184b718f5b505d7cc8f910c387a97cf813a

とりあえず上に書いた構造の原理試作を作ってみました。
丁度SpellHexがクラス化されていて試作対象にしやすかったので、SpellHexのリファクタリングのPRに対する変更になっています。
まだセーブ/ロードを実装していないのでセーブしてゲーム終了すると呪術の詠唱状態がすべて解除されるし、きちんと最初に固有データの初期化せずに get_specific_data() の中で必要になった時に初期化していますが、動作自体は意図通りになっているようです。

**Comment by habu1010** [comment]
#1617 をマージしましたが、注意点として過去の magic_num にセーブされていたデータを固有データへマイグレーションする必要にあたり、セーブファイルデータが 8→9 に上がります。
しかし、次のAlphaバージョンリリースまでは他の職業の magci_num から固有データへの移動の実装も同じくセーブファイルデータ 8→9 で行う予定ですので、その間developブランチ間でのセーブファイルの互換性は保証されなくなります。
developブランチでの通常プレイは避けるようにしてください。

**Comment by habu1010** [comment]
一連のコミットで、magic_num等を共用して職業固有データを扱っていた、以下の職業のデータの職業専用データへの移動を完了した。

- 鍛冶師
- 練気術師
- 青魔道士
- 魔道具術師
- 吟遊詩人
- ものまね師
- スナイパー
- 呪術ハイメイジ

データ変数の共用をなくしてソースコードを読みやすくし、さらに固有データを有する職業を追加しやすくするという目的は達せられたので、この Issue はクローズする。
