### ISSUE TITLE
敵の呪文詠唱のメッセージを表示する関数の文字列変数を改名する

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#1521]
拙勝手版から
どれもmsg1、msg2…とどういう時のメッセージか一見わからないので改名する

**Comment by Slimebreath6078** [comment]
PRとの紐づけを忘れっぱなしでした
お手数おかけして申し訳ございません

**Comment by sikabane-works** [comment]
大丈夫です。基本的にリリース前に気づき次第対応します。
