### ISSUE TITLE
整数値をenum(enum class)型に変換する関数テンプレートの追加

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1532]
整数値をenum型に変換する以下のような関数テンプレートを追加する。

```c++
template <typename EnumType, typename IntegerType>
EnumType i2enum(IntegerType i);
```

先に実装したenum(enum class)型を整数値に変換する enum2i と違い、変換先の推論ができないので static_cast と同じように型を書かなければならず必要無いかと思ったが、やはり片手落ちである気がするし、数値の型同士の変換を行う static_cast とは見分けがついたほうが読みやすいと思うのであったほうが良さそう。

**Comment by Hourier** [comment]
凄く欲しかった機能なのでありがたいです
ぜひお願いします
