### ISSUE TITLE
max_r_idx の廃止

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1536]
r\_info.size() で十分賄えるはずの値がグローバル変数で別途定義されている＆misc.txt から読み込まれている
無意味である上に後任の担当者も分かりづらいので削除したい
但しmisc.txt がr\_info.txt より先に読み込まれていたりするとバグの原因なので慎重に調査する

**Comment by Hourier** [comment]
調査したところ、info-initializer::init\_r\_info() の中でmax\_r\_idx の値を決めている
それが実質r\_info のキャパシティになっている
a\_info やe\_info 等も含めて全部直すか、当面はr\_info だけのバイパスを用意する必要がある

**Comment by Hourier** [comment]
誠に勝手ながら、関連性の高いリファクタリングを複数実施されているようですので、本件Habuさんにアサインします
急ぎではないですので後ほどご確認下さい

**Comment by habu1010** [comment]
了解しました。
まず今やっているように max\_\*\_idx を使用しなくても良い（range-based forにするなど）ところはそうして、必要なところは \*\_info.size()に置き換え、最後に max\_\*\_idx の削除（misc.txtの定義からも外す）を行いたいと思います。
