### ISSUE TITLE
【バグ】 ファルメル・ウォーモンガーの進化経験値が未設定

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1537]
## 環境

- OS: Any
- バージョン: 3.0.0Alpha37

## バグの詳細

ファルメル・ウォーモンガー（ID:1227）の進化先としてグレーター・ファルメル・ウォーモンガー（ID:1232）が設定されているが、必要経験値が未設定（0）のままである。

## 期待される正常な動作

必要経験値が0の場合どのような挙動をするのか謎だが、正しく経験値を設定すべき。

**Comment by Hourier** [comment]
ファルメル → グレーター・ファルメル へ進化する系統が5個ほどあることを確認しました
経験値が0なのがバグで、設定するのが正しい方針の修正です
Alpha38に間に合うように修正します
