### ISSUE TITLE
モンスター追加 Alpha38

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1543]
新進気鋭の開発志望者がいらっしゃったので、サンプルとして1体だけ実装する
それを見てもらって、Alpha39以降の実装を引き継いでもらおうという魂胆
また、r\_info のフォーマット、miscのお作法、git等、色々なところに慣れて頂くのも狙いの1つ

**Comment by habu1010** [comment]
折角なので、 #1537 も一緒に対応してもらったらよさそうです。
