### ISSUE TITLE
C_MAKE / C_KILL マクロを排除する

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1567]
いいかげんC言語時代の名残である C_MAKE / C_KILL マクロによる動的なメモリの確保・解放を排除する。
やりたい事はほぼ std::vector にすれば事足りると思われる。

**Comment by Hourier** [comment]
今まで私が見てきた範囲でも、ごく少数の例外を除きvectorで困る箇所がありませんでした
長さを事前に確保してきた状況からpush\_back() に変えるのが若干しんどい印象があります
実施頂けると万々歳です

**Comment by habu1010** [comment]
#1597 までのPRですべての C_MAKE / C_KILL / MAKE / KILL を排除したので、マージされ次第マクロ自体を削除する。
