### ISSUE TITLE
Twitterスコアbotのアイコンを新案に変更する。

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1579]
![image](https://user-images.githubusercontent.com/61610939/133997727-9db93d31-40a8-4939-8a85-4bcf09d3024b.png)
斑多氏がアイコン新案出してくれたので差し替えしてもらいたく。トリミング等必要ならお知らせ下さい。

**Comment by habu1010** [comment]
ひとまず差し替えておきました。
ヘッダー画像もあるなら変更します。

**Comment by Sasahito** [comment]
ヘッダー画像はこちらになります！
![変愚蛮怒ヘッダー](https://user-images.githubusercontent.com/77927139/134140931-1a2f61ea-3ce7-4991-8163-fbe0d05cb0a4.png)

**Comment by habu1010** [comment]
ヘッダー画像も設定しました。
https://twitter.com/hengscore

**Comment by sikabane-works** [comment]
変更確認しました。ご両人ありがとうございます。
