### ISSUE TITLE
マクロでターゲッティングした時と手打ちでターゲッティングした時でカーソル移動時の挙動が異なることがある

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#158]
[Chara.zip](https://github.com/hengband/hengband/files/5989389/Chara.zip)
このセーブから、`z1*bu`と手打ちした時と、
`\e\e\ez1*`というマクロのあとで`bu`と手打ちした時に、
後者だと表示画面の右上までカーソルを移動させた時のようにマップ全体が移動する

**Comment by habu1010** [comment]
#159 が原因と思われるので、一旦duplicateタグ付けてcloseしておきます。
