### ISSUE TITLE
r_info作成ツールを正式にGitHubへ載せる

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1580]
Discordにて、ほのかっか氏にHSPでr\_info.txt へ載せるモンスター情報の作成ツールを作って頂いた
公式度は本体exeよりは低いだろうが何らかの形で公開できる体制を整えたい

**Comment by sikabane-works** [comment]
Webの方でも紹介は後日行います。ひとまずAlpha41に移します。

**Comment by sikabane-works** [comment]
さらに延期。

**Comment by sikabane-works** [comment]
相変わらず延期して申し訳ない。次回のWeb更新のときに追加します。

**Comment by sikabane-works** [comment]
https://github.com/hengband/RInfoMaker
新しくリポジトリ作りました。ひとまず完了とします。

**Comment by Hourier** [comment]
対応お疲れ様でした！
