### ISSUE TITLE
Hengband.exe起動した後に一度でも他のアプリに切り替えると休憩の時間経過がゆっくりになる

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#16]
OSDNより移行。[41429](https://osdn.net/projects/hengband/ticket/41429)

hengband.exe起動直後に`R9999\r`した時と、
一度でもほかのアプリケーションにフォーカスを切り替えてから戻ってきて`R9999\r`した時で、
処理速度が大きく異なる

起動直後は通常は1秒でゲーム内時間半日以上経過するが、
一度でもアプリを切り替えていると3秒で1時間程度しか経過しない

**Comment by daradarach** [comment]
(Deskullさんのコメントを移行)
条件はご指摘の形と初めて知りましたが、実感したことはありました。すぐ治せる保証はありませんが、ひとまずマイルストーンは最新に加えます。

**Comment by daradarach** [comment]
alpha6で、アプリ切り替えしても動作が遅くならないことを確認。他の修正で一緒に直ってたっぽいのでclose

**Comment by sikabane-works** [comment]
不安材料ではありますが、どうもそのようなので了解しました。
