### ISSUE TITLE
【バグ】ウィザードコマンドのモンスターのID指定生成が手動キー入力で実行されない（ペット、敵双方）

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1614]
提題の通り、アーティファクトのCコマンドと同様に選択処理を入れなければならない。

**Comment by Hourier** [comment]
現状でも回数指定 (0 → ID → ^A → n)で生成可能ですのでバグではないです
ただ、^A → Cと同様に揃えたいのは確かですね

**Comment by sikabane-works** [comment]
タイトル変えました。Twitterで報告が来て言われてみればそっちの使い方想定されてないのもおかしいのですぐ手をつけます。
