### ISSUE TITLE
【バグ？】 エッセンス抽出した時にベースアイテムの修正値がマイナスだった場合、その数値になるまで吸ってしまう

### ISSUE THREAD

**Issue by gold-onion** [hengband/hengband#1624]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha39

## バグの詳細

鍛冶師でエッセンス抽出した時にベースアイテムの修正値がマイナスだった場合、その数値になるまで吸ってしまう

## 再現手順

1. 錆びた鎖かたびら [14,-2]をエッセンス抽出する
2. 抽出後は錆びた鎖かたびら [14,-8]となり、差分の攻撃エッセンス60が手に入る

## 期待される正常な動作

この場合ベースアイテムの修正値を0として扱って欲しい
上記の場合錆びた鎖かたびら [14,+0]となり、攻撃エッセンスは手に入らない

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by daradarach** [comment]
ベースアイテム錆びた鎖かたびらの初期値が-8なんで自然な動作に見えますけど、
エッセンス抽出の結果、初期値ではなく修正値0まで強化して欲しいって言う要望ですか？

**Comment by habu1010** [comment]
これまでの扱いとしては +6 の修正のついた錆びた鎖かたびらというアイテムだということになると思います。
修正値が +0 に戻るのは変なので、以下のどれかだと思います。

- これまでと変わらない動作
- 修正値が0以上の分しか吸収できない（錆びた鎖かたびら[14, +3] なら攻撃エッセンス30 を吸収して 錆びた鎖かたびら[14, -8] になる。錆びた鎖かたびら[14, -2] ならエッセンスは吸収できず [14, -8]になる）
- マイナスにはならない（錆びた鎖かたびら[14, +3] なら攻撃エッセンス30 を吸収して 錆びた鎖かたびら[14, 0] になる。錆びた鎖かたびら[14, -2] ならエッセンスは吸収できず [14, -2]のまま）

**Comment by gold-onion** [comment]
うーん、その中だと2番目ですかね。
1番目はプレイヤー的にちょっと気持ち悪いです。
3番目はこのままだとおそらく呪われたアイテムを吸って並品にする場合と整合性が取りにくいです。

個人的にはドラゴン鎧など並品がプラスのも含めて吸った後は+0になるようにして欲しいです。
凡庸化と共通の処理なのが原因なのですが、現状の処理はプレイヤーから見た場合は余り自然でないと思うのです。
並品の修正値はスポイラーにすら無いですし。

**Comment by habu1010** [comment]
抽出後に0にしなければならない明確な理由は無いですし、変えたところでめちゃくちゃ余る攻撃/防御のエッセンスが少し増減するだけでバランスに影響も無いので、とりあえず現状が仕様という事にしたいと思います。
錆びてるけど元々上質だったので -2 で済んでたんだよ、で説明は付くと思います。
このIssueはクローズします。
