### ISSUE TITLE
BGMファイルの管理に関する処置

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1666]
BGMと効果音のプリセットを用意する作業が進められていますが、数十キロバイトの効果音はともかく、数MBにおよぶBGM(mp3ファイル)をそのまま他と同じように管理するのは好ましくなさそうです。
ブランチをpullする時のダウンロード容量が劇的に増えてしまうし、BGMファイルを更新するたびにリポジトリのサイズがどんどん大きくなってしまいます。

このようなファイルの管理目的では、以下のGit LFSを使用するべきです。
https://docs.github.com/ja/github/managing-large-files

**Comment by habu1010** [comment]
この問題について一旦検討が必要と思いますので、解決するまでdevelopへのマージを禁止しておきます。

**Comment by habu1010** [comment]
音声素材の再配布の条件の再確認等、他にも改めて確認する必要がありそうなので、一旦以下の措置を取りたいと思います。

・**:warning: develop ブランチを音声ファイルが追加される直前のコミット e44ff69ea8d368a88bb5fc8fc0a3724da6c691cd の状態に戻して、force-push します。**

上流リポジトリのブランチを force-push するのは原則的に避けるべきですが、音声ファイルを削除するコミットをするだけではGitHub上で音声ファイルにアクセスできる状態、リポジトリのサイズの増大ともに解決されないので、例外的に実施します。
お手数ですが、各フォークリポジトリの管理者は各自のフォークリポジトリを適切に処理してください。
また、現在出されているPRで上記コミット以降のコミットからのブランチで作成されている場合は、上記コミット以前のブランチにリベースしてください。

なお、現状上記のコミット移行は、音声ファイルの追加とそれに伴う権利の表記など関連するコミットしかないため、関係無いコミットまで消えてしまうことはありません。

念の為、現在のdevelopブランチは一旦develop-bakとリネームして置いておきますが、そのうちdevelop-bakも削除して完全にアクセスできない状態にします。

音声ファイルのプリセットの件については、改めて別途検討のこととします。

**Comment by sikabane-works** [comment]
その観点での問題もあることを認識しました。措置よろしくお願いします。

**Comment by habu1010** [comment]
develop を e44ff69ea8d368a88bb5fc8fc0a3724da6c691cd に差し戻しました。
各自、GitHubのフォークとローカルリポジトリの管理をお願いします。

develop-bak については、次のAlphaバージョンリリースを目処に削除します。

**Comment by sikabane-works** [comment]
ありがとうございます。develop-bak削除次第クローズということでお願いします。

**Comment by habu1010** [comment]
develop-bak ブランチを削除しました。
なお、各自がローカルにクローンしたリポジトリには各種BGMファイルがまだBLOBとして残存している可能性があります。
ローカルのリポジトリからも完全に削除する一連のgitコマンドを記しておきます。

```sh
# リモートリポジトリのブランチ削除をローカルリポジトリに反映させる(上流リポジトリの名称が "upstream" の場合)
git remote prune upstream

# ローカルのリポジトリに音声ファイルのあるコミットに辿れるブランチがあったら削除する(各自おこなってください)

# reflog からも音声ファイルのあるコミットに辿れなくする
git reflog expire --expire-unreachable=now --all

# 辿れなくなったBLOBを削除する
git gc --prune=now
```
