### ISSUE TITLE
clang-format の微調整の提案

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1671]
#1502 で適切な箇所で改行できるようにしましたが、まだ若干気になる挙動があるので、修正を提案します。

## 二項演算子の改行位置

現状のスタイル
```c++
if (foo && bar
   && baz) {
}
```

やりたいスタイル
```c++
if (foo && bar &&
  baz) {
}
```

個人的には後者のほうが好みなのですが、どうでしょうか？

## 複数行にまたがる場合のインデント

現状のスタイル
```c++
if () {
} else if (foo && bar
    && baz) {
}
```

やりたいスタイル
```c++
if () {
} else if (foo && bar
           && baz) {
}
```

前の行とインデント揃えたいのですが、どうでしょうか？

**Comment by habu1010** [comment]
このパターンの場合は、

> どちらも賛成です 少し気になるのが2つ目で
> 
> ```
> auto hoge_hoge_hoge_hoge_hoge = mado
>                               ? homu
>                               : mami;
> ```
> 
> になりそうなことくらいですね 空白が多くなりそうです (個人的にはあまりこだわりはなく、これでもOK)

このパターンは以下のようにすることで対処できるかなという気がします。

```
auto hoge_hoge_hoge_hoge_hoge =
    mado
    ? homu
    : mami;
```

**Comment by Hourier** [comment]
それなら問題なさそうです！
