### ISSUE TITLE
生命領域の魔法「究極の耐性」/剣術家の「無双の型」を新規に追加された耐性に対応させる

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1675]
現在、生命領域の魔法「究極の耐性」と剣術家の「無双の型」は最近追加された 水耐性・時間逆転耐性・呪力耐性 の3つがつかない。
アビリティの特徴から考えると、これらの耐性もついてしかるべきかと思われる。

**Comment by Hourier** [comment]
リファクタリングで重複コードがなくなったり既存コードの見通しが良くなることで最終的に不具合に気付くというのはスパイラル開発の黄金パターンだと思います
対応よろしくお願いします
