### ISSUE TITLE
【バグ】 詐欺オプションでカーソルが動かない

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#1702]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 最新develop

## バグの詳細

詐欺オプションでカーソルが動かない

## 再現手順

develop最新でデバッグモードに入ってから=cでカーソルを上下に動かす

## 期待される正常な動作

動く

他は問題なかったので不具合かなと思ったんですがおま環だったらすみません

**Comment by Hourier** [comment]
元からこうだったかもしれませんが仕様としては不自然なので確認・修正します
なお回避策として、y/n を押すと下には行きます
(一番下まで行ったら一番上へループする)
