### ISSUE TITLE
型エイリアスQUEST_IDXの廃止

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1716]
掲題の通り
クエスト番号を意味するenum classに置き換える
具体的には40～49がランダムクエスト、等

**Comment by Hourier** [comment]
floor\_type::inside\_quest はQUEST\_IDX型である
しかしほぼ確実に「クエストにいるかいないか」の判定しかしていない
フィールド変数はquest\_number をに改名し、クエスト判定はinside\_quest() を別途定義する

**Comment by sikabane-works** [comment]
Slimebreath6078 さんがSBBandでやってくれたようですのでその成果がフィードバックされるのを待ちます。優先度中、MileStone中はBeta中で。
