### ISSUE TITLE
max_q_idx の廃止

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1722]
掲題の通り
vectorなのでもう配列の長さを別途管理する必要がない

**Comment by sikabane-works** [comment]
q_info読み取っている間にresize()かますことで対応する。

**Comment by sikabane-works** [comment]
次に回す。いい加減何とかしたいので優先度高で。

**Comment by sikabane-works** [comment]
@Slimebreath6078 がやってくれているとのことなので次回バージョンに回しつつAssign渡します。よろしくお願いします。

**Comment by Slimebreath6078** [comment]
とりあえずでAlpha56辺りまでにしておきます
