### ISSUE TITLE
乱数関連のマクロの関数化 その1

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1763]
実は #1759 でついでに randint? などの乱数関連のマクロをインライン関数にしようとしたのだが、VSで大量の型サイズ縮小警告が出るようになった。数がかなり多かったので上記PRでの関数化はやめておいたので、関数化をするかどうかを含め別Issueとして立てておく。

## 警告が出るようになる理由

以前から確認しているが、VisualStudioの現在の警告設定は型サイズ縮小に中途半端に厳しく、変数に代入される値が左辺値なら警告が出るが、右辺値であると警告が出ない。

```c++
int16_t a;
int32_t b = 0;
a = b; // 型サイズ縮小警告が発生する
a = b + 1; // 型サイズ縮小警告は発生しない
```

そして、現状 randint1(X) は randint0(X) + 1 に置換されるマクロであり右辺値であるが、これを関数化すると関数の戻り値は左辺値であるため randint1(X) を2バイト以下の型に代入している箇所全てで警告が発生してしまう。

**Comment by sikabane-works** [comment]
次回、優先度中とさせてもらいます。

**Comment by Hourier** [comment]
本件私が対応します
