### ISSUE TITLE
クエストクリア時間のように、撃破したユニーク・モンスターの撃破時点のLvとプレイ時間の表示して欲しい

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#18]
OSDNより移行。[41483](https://osdn.net/projects/hengband/ticket/41483)

撃破したユニーク・モンスターの一覧が、撃破時Lvやプレイ時間とともにDUMPに載ってたら、人のDUMPを眺める楽しみが増えるかなと言うリクエストです

**Comment by Hourier** [comment]
(コメントも移行)
race_type の拡張が必要なのでv3.2.0目処で実施することになろうかと思います
よろしくお願いします
