### ISSUE TITLE
死の大鎌の反射ダメージがマーフォークに効かない

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#180]
calc_death_scythe_reflection_magnification_mimic_none() に、case文が存在しない
倍率をいくつにするかも含めて仕様から詰める必要があるので、deskull氏に確認頂くものとする

**Comment by sikabane-works** [comment]
普通に適用の効かない種族なりに反射かますべきでしょうな。できれば自分がやります。

**Comment by Hourier** [comment]
お手数ですがよろしくお願いします
多分他にもcase漏れがあると思いますが、見つける都度にIssue作って対応していきましょう

**Comment by dis-** [comment]
default:
        return 10;

calc_death_scythe_reflection_magnification_mimic_none()内で等倍と定義されているようです。
実際にマーフォークで死の大鎌を振るえば自分に刺さることが確認できます。ご確認ください。

**Comment by Hourier** [comment]
あー、効かないってIssueのタイトルが間違ってますね
正確には、仰る通り「倍率が未定義なのでdefaultに飛ぶです」

**Comment by dis-** [comment]
SLAY_DRAGON | SLAY_ANIMAL | SLAY_HUMAN | 
SLAY_UNDEAD | SLAY_DEMON | SLAY_TROLL | SLAY_GIANT | SLAY_ORC |

考慮すべき種族スレイはこの8つですね。
龍でなく、動物でなく、人間でなく、不死でなく、悪魔でなく、トロルでなく、巨人でなく、オークでないので
等倍が妥当と考えます。

**Comment by sikabane-works** [comment]
ん、ではこの問題修正不要だったということになりますかね。とりあえず〆切の都合Alpha8に回しておきます。

**Comment by Hourier** [comment]
確認ありがとうございました
修正不要ということで本件クローズします
