### ISSUE TITLE
【バグ】 alpha42のキャラメイクでの動作不良

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#1815]
## 環境
- OS: Windows 版
- バージョン: 3.0.0Alpha42
## バグの詳細
キャラメイク中職業を選ぶ段階まで進むとｍ元素使いの右側に戦士ダムという正体不明のものが出て上下左右の操作を受け付けなくなる。
正確にはランダムの上にa)戦士が重なって表示されてしまっている。

## 再現手順
キャラメイクの職業を選ぶ段階まで進み上下左右いずれかを入力する。

## 期待される正常な動作
カーソル操作を受け付けること。
ランダムの上によくわからないものが重なって表示されないこと。

## スクリーンショット
![バグ報告用](https://user-images.githubusercontent.com/79730818/137814646-726d1939-7a57-4ee4-a2f5-34632ce568f7.png)

## 補足事項
saveファイルがある状態でのキャラメイクでも、ファイル→「新規」でも発生。
a)戦士ダムでも文字入力による操作は受け付ける。
メイジを選んでからescで戻るとb)メイジムと出たりする。

**Comment by sikabane-works** [comment]
バグこちらでも捕捉しました。本日また緊急修正したいと思います。
