### ISSUE TITLE
enum class の型名のフォーマット統一

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#1824]
C++化してまもない頃に行った enum の enum class 化のリファクタリングでは、あまり深く考えず元の enum 型のプレフィックスをそのまま型名にしたり、現在の慣習に従っていないものがいくつか存在している。
しかし、途中から enum class の型名はパスカルケースで ～Type とする慣例ができているので、上記の型名に関しても慣例に従うようにする。

以下、変更のリスト。名称についてこのほうが良いなどの提案があればいただきたい。

- RF_ABILITY → MonsterAbilityType
- MUTA → PlayerMutationType
- DF → DungeonFeatureType
- FF → FloorFeatureType
- mind_kind_type → MindKindType
- MFLAG → MonsterTemporaryFlagType
- MFLAG2 → MonsterConstantFlagType
- SM → MonsterSmartLearnType
- TRC → CurseTraitType
- TRCS →CurseSpecialTraitType
- TRG → ItemGenarationTraitType
- SmithEffect・SmithEssence・SmithCategory → Typeをつける
- MagicalBrandEffect → Typeをつける
- SamuraiStance・MonkStance → Typeをつける
- PlayerRaceLife・PlayerRaceFood → Typeをつける
- SCREEN_LOAD_OPT → ScreenLoadOptType
- spoiler_output_status → SpoilerOutputResultType
- WishResult → Typeをつける

例外

- graphic_mode / bg_mode : Windows版インターフェース処理専用なのでそのままにしておく
- PlayerCutRank / PlayerStunRank : Rank で列挙型としての意味は満たしていそうなのでTypeは付けない

**Comment by sikabane-works** [comment]
ひとまず賛成します。漏れがあってもおおむねこの方向性で修正していただいて結構です。

**Comment by dis-** [comment]
完了したのでクローズします
