### ISSUE TITLE
エゴアイテム強化の要望

### ISSUE THREAD

**Issue by Aquashrimp** [hengband/hengband#183]
兜の赤外線視力エゴや冠の急速回復エゴなど、価値が低いエゴアイテムの強化をして頂きたいです
特定の指輪/アミュ限定エゴ(テレパシーアミュ専用の感知エゴなど)も中々見つけられるものではないので、レア度にふさわしい強化をしてもらってもいいかもしれません

**Comment by sikabane-works** [comment]
弱いエゴのままにするなら拾える確率そのものを高めてそこそこの金策にできたり、強化するならそれはそれでよしという所でしょうか。念頭に入れます。
