### ISSUE TITLE
自動生成スポイラーを置いておく GitHub Pages サイトの作成

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#190]
自動生成スポイラーを置いておく GitHub Pages サイトを作成する。
[Hengband Spoiler (3.x)](http://mars.kmc.gr.jp/~dis/heng_wiki/) などからスポイラーファイルへのリンクを張ってもらえばよいかと思う。
GitHub Actions の Workflow よる自動更新を行う事を予定する。

**Comment by sikabane-works** [comment]
正式にgithubのhengbandに設置出来たら完了とさせていただきます。

**Comment by habu1010** [comment]
今回は初回ということで、手動でWorkflowを走らせました。
想定通りpublishできたようです。
https://hengband.github.io/spoiler/
今後はリリース時（masterブランチにマージされた時）に、自動的に更新されます。

**Comment by sikabane-works** [comment]
無事Alpha7のリリース時点できていたようですし、同マイルストーン扱いで完了します。お疲れさまでした。
