### ISSUE TITLE
詐欺オプションの「その他のことをのぞき見る」が一度死んだあと次のゲームでも有効になっている

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1901]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha47

## バグの詳細

バグの内容を明確かつ簡潔に説明

詐欺オプションのその他のことをのぞき見るをはいにしたあと一度Qyして新しくゲームを始めるとまだ敵に与えたダメージを確認できる状態になっている。また、通常詐欺オプションを付けた場合Qyのあとの確認の@を求められないが、この場合は求められる。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 公式から落としてきたAlpha47で新規にゲームを開始
2. 「デバッグ/詐欺オプションを許可する」をはいにする
3. 「その他のことをのぞき見る」をはいにする
4. Qyする
5. 同じセーブデータでキャラメイクしてゲームを始める
6. 敵に与えたダメージを確認できる状態になっている

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

新しく始めたゲームでは詐欺オプションがすべていいえに戻り、実際に無効になっている

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by sikabane-works** [comment]
これで対応できたはずなので、閉じておきます。
