### ISSUE TITLE
画面表示の設定でprfファイル書き出しをするとロードできないファイルが出力される

### ISSUE THREAD

**Issue by multilockon123** [hengband/hengband#1909]
## 環境

- OS: [ Windows 版]
- バージョン: [ 3.0.0Alpha40以降]

## バグの詳細

画面表示の設定からprfファイルの書き出しをするとロードできないファイルが出力される。

## 再現手順

1. 画面表示の設定でシンボル変更する。
2. ファイルの書き出しでprfファイルを出力する。
3. そのprfファイルをロードした際に何も起こらない。

## 期待される正常な動作

prfのファイル名と同一の主人公名での起動時、および画面表示の設定でユーザー設定ファイルのロードを実行すると変更されたシンボルが反映される。

**Comment by dis-** [comment]
同じ件なのでcloseします
