### ISSUE TITLE
テレポートレベル巻物で下の階へ移動してから階段を登ると巻物を読んだ場所に出ることがある

### ISSUE THREAD

**Issue by taotao54321** [hengband/hengband#192]
[OSDNフォーラム](https://osdn.net/projects/hengband/forums/37402/43663/#forum-message-87023) より:

> 荒野からダンジョンに入り適当な場所でテレポートレベルの巻物を使用し、下の階に移動する。
> その後階段をのぼってテレポートレベルを使用した階層まで戻ると、階段の上ではなくテレポートレベルの巻物を使用した場所に出現する。
> v2.x系列でも同様の処理だったかは確認していませんが、階段をのぼったのに違う場所に出るのは変なので報告します。

原因となるコードは特定できていないが、再現は確認できた。セーブデータを添付しておく(起動直後に `<` で階段を登ると平地に出る)。
自動セーブはoffになっているが、テレポートレベルの巻物を読むまではonにしていた。
[1000.dbg.zip](https://github.com/hengband/hengband/files/6004644/1000.dbg.zip)

**Comment by iks3** [comment]
階層保存の際に最後の位置を保存して、そこを復帰時の移動場所(階の結合点)にしていることが原因のようです。  
ある階(Aとする)の階段がない場所から下の階テレポート・レベルし、下の階(Bとする)から階Aに戻ると、最後にいた階段のない場所に復帰します。  
ここで階段生成の呪文で降り階段を生成して降りると、階Bに復帰できます。  
  
ですので、階層移動で保存された階に移動した場合、足元が階段ではない場合はなんらかの処理をして足元を適切な階段にする必要がありそうです。

**Comment by habu1010** [comment]
とりあえず、Discordで私とiksさんで話し合った妥当そうな解決案を記しておきます。

- テレポレベル時に、移動方向の階段(坑道除く)を探して、保存階への繋がりがないものがあればそこをそのフロアの最後の位置として保存する
- 移動方向の階段の中に保存階への繋がりが無いものがなかった場合は、移動先の階でつながりを作らない(可能であれば)。または、保存階に復帰した場合足元が階段でなければ新規階を生成する。
