### ISSUE TITLE
[要望] '(' 「ファイルに書き出した画面を表示」を押した際に、読み込むファイルが存在しなかった場合に絶対パスが表示されるのを変更してほしい

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1920]
(キーを押した際に、読み込もうとしたファイルが存在しないと、

>C:\Users\hoge\lib\user\dump.txt を開くことができませんでした。

のように開けなかったファイルが絶対パスで表示されるが、動画や配信をネットに上げた際にうっかりPCのアカウント名等見られたくない物が見えてしまう可能性がある。相対パスで表示する等、絶対パスが見えない方法に変えることはできないだろうか。

**Comment by dis-** [comment]
現状だと相対パス化もありえなくはないのですが、今後の拡張を考えると開きたいファイルが同一階層以下にあるとは限らないので難しい問題になってしまいます。
フォルダの設置箇所を配信者側で気を使っていただくしかないという結論になりそうです。
