### ISSUE TITLE
【バグ】 デバッグコマンドの領域変更で一部の数字を入れるとゲームが落ちてセーブデータが使えなくなる

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1959]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha49

## バグの詳細

バグの内容を明確かつ簡潔に説明

デバッグコマンドの領域変更で、18か40以降の数字を入れるとゲームが落ち、そのセーブデータでゲームを再開できなくなる。
18の場合も40以降の場合も、領域変更した後も移動はできるが、ステータス画面を出してからゲームに戻ると恐ろしいソフトのバグが飛びかかって来る。18の場合はその後ゲームを再開しようとしても再開してすぐに恐ろしいバグで強制終了する。40以降の場合はセーブデータをロード中に勝手に終了してゲームが始まらない。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 公式でDLしたAlpha49で普通の女性人間戦士で新規にゲームを開始。
2. デバッグコマンドで領域を変更する。0-17と言われるが18や40以降の数字を入れる。
3. ステータス画面を開いて閉じるとゲームが落ちる。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

落ちない。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by sikabane-works** [comment]
流石に単純に領域外アクセスかます設定した影響だと思いますので。他で進めている数値入力汎用化で回避します。
