### ISSUE TITLE
【バグ】重力属性の攻撃でユニークが減速する

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1960]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha48

## バグの詳細

バグの内容を明確かつ簡潔に説明

重力属性の攻撃でユニークが減速する。カオス4の重力光線と時空ワイアームの重力のブレスで確認。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. ユニークに重力属性の攻撃を当てる。
2. 当てる前後で調査する。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

昔は減速しなかったようだ。

本来期待される正常な動作を記載

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

![ユニーク遅鈍_重力](https://user-images.githubusercontent.com/81608944/148197522-80ff28b0-bef6-420b-8935-7899a3c13d05.png)

## 補足事項

補足事項があれば記載

effect_monster_gravity_slowでelseが抜けてる？

**Comment by sikabane-works** [comment]
Alpha53、優先度中で。

**Comment by Hourier** [comment]
飛竜さんが原因を発見、修正の見込みですので担当者を切り替えます
