### ISSUE TITLE
【バグ】 モンスターの射撃がRES_ALL持ちにダメージが通るようになっている

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#1962]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha48

## バグの詳細

バグの内容を明確かつ簡潔に説明
モンスターの射撃がRES_ALL持ちの敵にダメージを与えることが出来るようになっている。v2.2.1ではできなかった。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. ペットのハイエルフレンジャーにはぐれメタルを射撃させる。v2.2.1とAlpha48で結果を比較する。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

v2.2.1では完全な耐性があると言われてダメージを与えることはできない。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

v2.2.1。ダメージを与えることはできない。

![v221](https://user-images.githubusercontent.com/81608944/148224963-7e2173eb-2dc2-4841-a1be-861226cf1594.png)

Alpha48。ダメージが出ている。

![Alpha48](https://user-images.githubusercontent.com/81608944/148225018-2536fe30-e70e-4438-817f-647fcbaaed86.png)

## 補足事項

補足事項があれば記載

モンスターの射撃がRES_ALL持ちにダメージを与えることが出来てもいいかもしれないが、意図的に変更したものではないと思うので報告する。ただ射撃は必中なのでやはり問題かもしれない。

**Comment by dis-** [comment]
プレイヤー→モンスターの射撃と同様にダメージ1/100で当たるのは正常な挙動であると判断します。
ただし、現在モンスターの射撃はACによる回避が発生しない必中攻撃となっている点でプレイヤーの射撃と仕様が異なります。
こちらの仕様は別Issueにて修正する方針とします。

**Comment by sikabane-works** [comment]
次回、優先度高としておきます。

**Comment by argrath** [comment]
> プレイヤー→モンスターの射撃と同様にダメージ1/100で当たるのは正常な挙動であると判断します。 ただし、現在モンスターの射撃はACによる回避が発生しない必中攻撃となっている点でプレイヤーの射撃と仕様が異なります。 こちらの仕様は別Issueにて修正する方針とします。

この「別issue」は作成済みでしょうか?
それなら元の話は正常な挙動と言うことなのでクローズして良さそうです。

**Comment by dis-** [comment]
#1966 が作成済みであり、重複案件となるのでこのIssueはCloseします
