### ISSUE TITLE
水辺に出てくる敵の出現率が低下

### ISSUE THREAD

**Issue by gkuraki** [hengband/hengband#197]
Alpha6で確認。
水辺で騎乗用のヒドラを探していたのだが、水辺モンスターの生成率が低くなっている模様。
荒野やダンジョン入口等ほかの地形と出入りして比較すると明らかに出が悪い。

**Comment by sikabane-works** [comment]
![2 2 1r2](https://user-images.githubusercontent.com/61610939/108524416-581f8b80-7312-11eb-9ec8-742b8f1375e2.PNG)
2.2.1r2での水辺の生成例。襲撃でなくとも10体弱ほどでるのがおおよその相場。

**Comment by sikabane-works** [comment]
![3 0 0](https://user-images.githubusercontent.com/61610939/108524981-f6135600-7312-11eb-94b5-f6c7f5d4d8ad.PNG)
これが3.0.0Alpha6だと確かに2～3体、下手すると0になっているのを確認した。地形による制約などにエンバグや意図しない仕様変更がある可能性大。

**Comment by sikabane-works** [comment]
余談だが通常の平野に関しては生成数が変わっていなかった。やはり生成の地形制約に問題ができたか。以前からのIssueと絡んでいるかもしれない。

**Comment by sikabane-works** [comment]
![CheatMonster](https://user-images.githubusercontent.com/61610939/108527241-69b66280-7315-11eb-903a-fb93902b8578.PNG)
水辺の候補が丸ごと吹き飛んでいる。

**Comment by sikabane-works** [comment]
2.2.1に対して3.0.0では余計なhookが加わり、該当するモンスターがほぼ皆無になってしまうのが原因の模様。モンスター生成関数のコール関係は無茶苦茶に過ぎてリファクタリングに及んだ副作用の可能性大。引き続き自分が調査して対処する。

**Comment by iks3** [comment]
monster-race-hook.c中の、mon_hook_shallow_water()で炎オーラ持ちかどうか判定しているのですが、
`    return (r_ptr->flags2 & RF2_AURA_FIRE) != 0;`
ここの真偽判定が逆なので炎オーラ持ちが条件になっていました。
確認よろしくお願いします。

**Comment by sikabane-works** [comment]
![Debug](https://user-images.githubusercontent.com/61610939/108582106-6f8f6080-7374-11eb-88bc-fcf56f703b2f.png)

アドバイス通りで元に戻ったようです。ありがとうございます。英語のデバッグメッセージの修正しつつプルリクします。
