### ISSUE TITLE
Compilation in Cygwin failed

### ISSUE THREAD

**Issue by smbhax** [hengband/hengband#1971]
## 環境

- OS: Windows 10
- バージョン: 3.0.0Alpha49

## バグの詳細

When compiling Hengband in Cygwin, following the instructions for Unix at https://github.com/hengband/hengband/blob/develop/readme-eng.md , I get an error:

`io/uid-checker.cpp:6:10: fatal error: util.h: No such file or directory
    6 | #include "util.h"`

## 再現手順

- From Cygwin setup, you'll need the autoconf-archive and libcurl-devel packages, in addition to the packages used in compiling vanilla ASCII Angband ( http://angband.oook.cz/forum/showthread.php?t=11013 )
- In Cygwin, enter

git clone https://github.com/hengband/hengband.git

- Enter:

cd hengband
aclocal
autoconf
autoheader
automake --add-missing
autoreconf
./configure --disable-japanese
make install

- Compilation aborts with the "io/uid-checker.cpp:6:10: fatal error: util.h: No such file or directory" error noted above.

## 期待される正常な動作

The game would compile without errors.

## 補足事項

On the Angband forum, @backwardsEric commented http://angband.oook.cz/forum/showpost.php?p=156900&postcount=2 that

>That looks like a bug. I'd post an issue about it on Hengband's issue list. My guess as to why they haven't seen it when they compile for Linux is that SAFE_SETUID_POSIX somehow isn't set there while it is set on cygwin. Commenting out lines 51 to 53 of src/system/h-config.h and recompiling may work around the problem.

With that suggested workaround, the game compiles, but dies with "Fatal Error" when run in Cygwin.

**Comment by Hourier** [comment]
Thank you for the report.
We will fix this issue.

By the way, I changed the subject to the summary.
If there is any mistake, please let us know.

**Comment by Hourier** [comment]
I investigated this issue and found that util.h is not used any more.
(quit() was defined in the header once but now it moved to z-util.cpp/h)

So, would you please try to compile Hengband with uid-checker.cpp L3-9 (inclusion of util.h) removed?
This file includes z-util.cpp/h indirectly (uid-checker.cpp => angband.h => z-util.h), so there may be no problem.
If it's OK, I'll send PR to other members to merge the fix.
Thank you for your cooperation!

**Comment by smbhax** [comment]
I commented out uid-checker.cpp L3-9 (and restored the commented-out section of h-config.h that I had tried according to backwardsEric's suggestion), and the game compiled successfully.

I can't get this compiled hengband.exe to run, though. Here are the results of trying to run it in various ways from the Cygwin command line (the game and src are in a folder I made in my Cygwin home directory called "hengband"):

In [home]/hengband/src/:
- "./hengband": "Fatal Error."
- "./hengband" in a small terminal window: "Angband needs an 80x24 'curses screen"
- "./hengband" with "-?," "-f," or "-w": lists options
- "./hengband -dfile": "Try '-d<what>=<path>' not '-dfile'"
- "./hengband --output-spoilers": "Cannot access the ./lib/file/news.txt file!
The 'lib' directory is probably missing or broken.
The 'lib' directory is probably missing or broken.
See the 'README' file for more information.
Fatal Error."
- "./hengbang -[other option]": "Fatal Error"

In [home]/hengband/:
- "./hengband," etc: "Is a directory"
- ".src/hengband," etc: same errors as from [home]/hengband/src/

In [home]/hengband/ with [home]/hengband/Hengband/ renamed to [home]/hengband/zHengband/, and with or without adding "/src/" to the front of the command, ie "./src/hengband," etc:
- "/hengband": "setuid(): cannot set permissions correctly!"
- "./hengband" in a small terminal window: "Angband needs an 80x24 'curses screen"
- "./hengband -mgcu": "setuid(): cannot set permissions correctly!"
- "./hengband" with "-?," "-f," or "-w": lists options
- "./hengband -dfile": "Try '-d<what>=<path>' not '-dfile'"
- "./hengband -[other option]": "setuid(): cannot set permissions correctly!"

In [home]/, with or without [home]/hengband/Hengband/ renamed, and with either "/hengband/" or "/hengband/src/" added to the front of the command, ie "./hengband/hengband," etc or "./hengband/src/hengband," etc: same errors as from [home]/hengband/src/

Note: I do not have X11 installed.

Possibly this difficulty in running the generated hengband.exe should be entered as a separate issue, since the program does compile successfully with that modification to uid-checker.cpp.

**Comment by Hourier** [comment]
It is a good news that the compilation was successful in your environment!
Next, the new issue should be treated as another ticket as you said.
Would you please make a ticket and attach some log data?
We may take a time to resolve it because all of members don't have running Cygwin environment.

**Comment by smbhax** [comment]
I'll be happy to do that, but could you clarify what sort of log data to attach to the new issue? I don't know how to get log data out of hengband.exe.

**Comment by Hourier** [comment]
Hengband doesn't have logging feature (I regret to say :( ).
I intended to point the log of Cygwin.
(For example, lib/ exists always because it is included in the source repository, so I couldn't expect the reason of the error above yet.)

**Comment by smbhax** [comment]
There's config.log and config.status that are generated when running configure in preparation for compiling Hengband, a number of sort of log files or something in an "autom4te.cache" folder made somewhere in the configuration stages too I think, and there's the .bash_history of commands typed into the Cygwin console. That's about all that I can see but I don't know what to look for particularly. Would any of those be useful?

**Comment by Hourier** [comment]
All of them should be useful for us!
Please attach them to the new ticket and we'll investigate it later.
Thank you for making a list for investigation!
This ticket will be closed soon.

**Comment by backwardsEric** [comment]
Using debian 11 (bullseye) with its packaged version of gcc (10.2.1), I can run into problems with the safe_setuid_drop() and safe_setuid_grab() functions if I add

```
#include <unistd.h>
```

at line 50 of src/system/h-config.h (right before "#define SAFE_SETUID"; with that, the definition of _POSIX_SAVED_IDS, if it's set, will always be picked up; without it, whether or not it will be defined will depend on whether something included unistd.h before including h-config.h).

When I do so, I get the compilation problem with util.h in src/io/uid-checker.cpp.  After fixing that, the game runs through the birth process fine, but quits with the "setuid():  cannot set permissions correctly!" message from safe_setuid_grab() after accepting the character.  At that point in safe_setuid_grab(), player_ptr->player_euid and player_ptr->egid are both zero.  I suspect they were set to that during the birth process.  That wiped out the values set in main.cpp when the game started.  Also, why is player_ptr->egid used in both the call to setuid() and setgid(), shouldn't it be player_ptr->euid in the call to setuid()?  It likely doesn't matter for many Linux installations where the typical user has a user ID and group ID that are the same by may matter elsewhere.

**Comment by smbhax** [comment]
I have entered the information about the compiled hengband.exe not running in Cygwin, with @backwardsEric's information about the problem in debian, as issue #1974.
