### ISSUE TITLE
"setuid()" error attempting to run in Cygwin

### ISSUE THREAD

**Issue by smbhax** [hengband/hengband#1974]
## 環境

- OS: Cygwin in Windows 10
- バージョン: 3.0.0Alpha49 with latest code via "git clone" and "git pull"

## バグの詳細

I am attempting to compile and run the latest Hengband code with the Curses front-end in Cygwin on Windows 10.

With a workaround provided by @Hourier in issue #1971 to a compilation problem due to an include of a removed header, I am able to compile Hengband successfully in Cygwin. However, attempting to run it from the command line fails to launch the game, although in certain configurations I can get it to list its command-line options--but otherwise it fails with either "Fatal Error" or "setuid(): cannot set permissions correctly!" (See the comment in issue #1971 for the full list of messages.)

## 再現手順

1) Install and update Cygwin:
In addition to the default Cygwin packages, I also have: clang, make, libncurses++w10, libncurses-devel, automake, autoconf, m4, libtool, git, autoconf-archive, libcurl-devel

2) Get the Hengband code:
From my home/username directory, in Cygwin's command line I enter:

git clone https://github.com/hengband/hengband.git

3) Correct for a compile error:
Per Hourier in issue #1971, I comment out "uid-checker.cpp L3-9 (inclusion of util.h)"

4) Compile Hengband:
Enter:

cd hengband
aclocal
autoconf
autoheader
automake --add-missing
autoreconf
./configure --disable-japanese
make install

5) Rename home/[username]/hengband/Hengband/ to home/[username]/hengband/zHengband/ (or some other name of your choice) to avoid a "Is a directory" response blocking running hengband.exe in step 6

6) Attempt to run the compiled hengband.exe:
Enter:

./hengband

== Instead of launching the game, the console returns "./hengband: setuid(): cannot set permissions correctly!"

(Attempting to run with "-mgcu" or "-- -n4" etc returns the same message.)

## 期待される正常な動作

As described in the readme https://github.com/hengband/hengband/blob/develop/readme-eng.md , the game should launch in ASCII mode.

## 補足事項

See issue #1971 for a full list of message that may be returned from attempting to run hengband.exe from various locations, with various options.

In issue #1971, a comment by @backwardsEric supplied additional information relating to the problem:

> Using debian 11 (bullseye) with its packaged version of gcc (10.2.1), I can run into problems with the safe_setuid_drop() and safe_setuid_grab() functions if I add
> 
> ```
> #include <unistd.h>
> ```
> 
> at line 50 of src/system/h-config.h (right before "#define SAFE_SETUID"; with that, the definition of _POSIX_SAVED_IDS, if it's set, will always be picked up; without it, whether or not it will be defined will depend on whether something included unistd.h before including h-config.h).
> 
> When I do so, I get the compilation problem with util.h in src/io/uid-checker.cpp. After fixing that, the game runs through the birth process fine, but quits with the "setuid(): cannot set permissions correctly!" message from safe_setuid_grab() after accepting the character. At that point in safe_setuid_grab(), player_ptr->player_euid and player_ptr->egid are both zero. I suspect they were set to that during the birth process. That wiped out the values set in main.cpp when the game started. Also, why is player_ptr->egid used in both the call to setuid() and setgid(), shouldn't it be player_ptr->euid in the call to setuid()? It likely doesn't matter for many Linux installations where the typical user has a user ID and group ID that are the same but may matter elsewhere.

As requested by @Hourier in issue #1971, I am attaching various log files generated by the Cygwin console and compilation processes.
[logs.zip](https://github.com/hengband/hengband/files/7836463/logs.zip)

**Comment by smbhax** [comment]
Recompiled using the latest source code (and commenting out that troublesome uid-checker.cpp include), but attempting to run the .exe still results in "./hengband: setuid(): cannot set permissions correctly!"

**Comment by smbhax** [comment]
This and the uid-checker problem have been resolved by the latest code, probably "pull request #1977 from backwardsEric/uid-fixes." : )

**Comment by sikabane-works** [comment]
Thank you for reporting :)

**Comment by smbhax** [comment]
Oh this is still assigned to me, I'm not sure if that means I still have to do something. It's definitely fixed.
