### ISSUE TITLE
新装備フラグ - 魔法防御上昇

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#198]
反魔法よりはおとなしく魔法防御能力を向上させ、魔法を阻害しないフラグ。
あったら嬉しいが、なくて困るほどのものではない。
護りを与えるフレーバーに使いやすく、表現の幅を広げられそうだと感じる。

**Comment by Aquashrimp** [comment]
discussionより
★エクスカリバーに付加予定
防衛者エゴに低確率で付いて良いかも？

**Comment by iks3** [comment]
追加されたのでクローズします。
