### ISSUE TITLE
パターンvaultによるRQ飛ばし

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1986]
OSDN より移行。 [#37917](https://osdn.net/projects/hengband/ticket/37917)

> パターンvaultの階層テレポートを使用してRQ階をスルーした後に帰還してもスルーしたRQが失敗扱いにならず遂行中のままになりました。
> 直前の流れは鉄獄60Fに帰還、62RQ氷のジシスルを討伐、67Fのパターンvaultの階層テレポートで98Fへ移動、帰還、でその直後のdumpです。
> クエスト達成状況を見ると「76階いたずら者『ロキ』を倒す。」が表示されたままです。
> その後に鉄獄へ帰還すると同時に76RQ・88RQを失敗扱いになり正常な表記状態に戻りました。
> 
> 以前、ver2.2.0ですが帰還と上り階段無しONでプレイした際にも同じ現象にあいました。そちらの方は結局RQの失敗が表記されずに勝利しました。

解決方針：
> トランプの塔によるワープでは飛ばしたランクエは自動失敗になっているので、やはりそれに合わせることにする。

**Comment by Hourier** [comment]
修正済だったらしいのでクローズ

**Comment by sikabane-works** [comment]
#1276 で多分修正されたものと思われます。補足までに。
