### ISSUE TITLE
  ダメージ計算処理のバグ修正と整理

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#1989]
OSDN より移行。[#37626](https://osdn.net/projects/hengband/ticket/37626)

> hradish氏より、本タイトルに関する以下の報告を確認。
> - table.cで修行僧の打撃情報を定義するmartial_arts型ma_blowsのダメージダイスなどが日本語版と英語版で食い違っている。
> - file.cでプレイヤーのステータス表示を行うdisplay_player_various()内で修行僧/錬気術師/狂戦士の素手打撃ダメージ期待値にはcalc_expect_crit()によるクリティカル修正による見積もりが加算されていない。
> - calc_expect_crit()によるクリティカル見積もりの際、display_player_various()での呼び出しではdamに通常の100倍の値を代入している。
> - display_player_various()の武器ダメージ期待値計算の順がクリティカル→切れ味→理力と本来の理力→クリティカル→切れ味と食い違っている。 
> 
> それぞれ確認の上修正する。

**Comment by dis-** [comment]
3.0.1.6時点で調査しました。

> table.cで修行僧の打撃情報を定義するmartial_arts型ma_blowsのダメージダイスなどが日本語版と英語版で食い違っている。
正しい値になっています。

> file.cでプレイヤーのステータス表示を行うdisplay_player_various()内で修行僧/錬気術師/狂戦士の素手打撃ダメージ期待値にはcalc_expect_crit()によるクリティカル修正による見積もりが加算されていない。
正しい値になっています。

> calc_expect_crit()によるクリティカル見積もりの際、display_player_various()での呼び出しではdamに通常の100倍の値を代入している。
期待値計算のために100倍の値が代入されていますが、表示前に1/100されるため正しい挙動です。
クリティカル発生は命中率と重量により決定され、100倍の値が入力されても正しい100倍の期待値を返します。

> display_player_various()の武器ダメージ期待値計算の順がクリティカル→切れ味→理力と本来の理力→クリティカル→切れ味と食い違っている。
順序は訂正されていますが、現在理力が計算されていません。別Issueを立てて修正します。

**Comment by dis-** [comment]
修正されたのでcloseします
