### ISSUE TITLE
たまにフロア階層生成条件から外れた死体が見つかる。

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#1996]
https://osdn.net/projects/hengband/ticket/41394
にてHourier氏が報告。実際実害は少ないし、実際現在起きているか不明だが、備忘しとく。

**Comment by Hourier** [comment]
該当の処理はリファクタリングの過程でOtherItemsEnchanter::generate\_corpse() で定義した
地上のモンスターでも特に制限なく生成されるようである
本件は対処不要として解決したのでクローズする
