### ISSUE TITLE
Readme.md対応

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#2]
Github以降につきデフォルトで表示されるようになったreadme.txtをReadme.mdに変換の上加筆修正も試みる。

**Comment by backwardsEric** [comment]
If it would work with how GitHub displays the readme.txt (or Readme.md), a link at the top from the Japanese version to the English version (and similarly a link at the top of the English version to the Japanese version) could be helpful for people who can't read one of the two languages.  Unfortunately, it looks like the only way to do that now is to convert the alternate version to a resource that can be referenced with a URL and put in a link to that.  In other words, there's no syntax for saying something like repository(Readme_eng.md) and have it generate a link that'll display Readme_eng.md from the repository after running it through the Markdown processing.

**Comment by backwardsEric** [comment]
This link, https://github.community/t/how-to-localize-the-readme-file/1756 , may help with what I was trying to say in the previous comment (and perhaps what's mentioned there will work as is without referencing an external URL in the link).
