### ISSUE TITLE
カメレオン洞に通常モンスターが生成される

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#20]
OSDNより移行。[41507](https://osdn.net/projects/hengband/ticket/41507)

（Re: 変愚蛮怒3.0.0Alpha5リリースまでの要望/報告） (フォーラムメッセージ #86948 からの引用)

仕様が変わったのかと思ったが、カメレオン洞に入った時のメッセージは「カメレオンだけが棲息する洞窟へ入った。」 だった

**Comment by daradarach** [comment]
(taotaoさんのコメントを引用)
症状としては、少数のカメレオンと多数の通常モンスターが生成されています。

原因は `get_mon_num_prep()`内で確率値0のエントリを確率値1に補正する処理が加わったことのようです:

https://github.com/hengband/hengband/blob/c0e21890beeb7691069f0daff4afbd609a659f2e/src/monster/monster-util.c#L366-L367

該当箇所をコメントアウトするとカメレオンだけが生成されるようになります。

が、この補正処理が加わった経緯などはよくわかっていないので後は詳しい方にお任せします。

**Comment by taotao54321** [comment]
該当のコードは日替わり賞金首を選ぶ際に候補がなくなるのを防ぐために追加されたようです:
https://github.com/hengband/hengband/commit/c02230e80f4eafddd5a5365030bb9837820582c3

アドホックな解決としては、`get_mon_num_prep()` に賞金首選定用であることを示す bool 引数を入れるなどが考えられると思います。
ただし、賞金首選定にあたって現在地点を用いる意味は特になさそうなので、リファクタの余地はあるかと思います。

**Comment by Hourier** [comment]
現状のコードを鑑みるに、例えば竜窟などシンボルに偏りのあるダンジョンでもその偏りが弱くなる、或いはほとんど分からなくなるような感じもします
↑のbool型引数を追加する案は賛成ですが、やっていることの複雑さを考えるに一旦リファクタリングして現状のコールチェーンを確認するのが先決かもしれません
