### ISSUE TITLE
feel1に対応するBGMがmusic.cfgで指定されていないとき、townに対応するBGMが再生される

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#200]
Alpha6で確認しました。
ダンジョン探索中に階の雰囲気が悪い予感になったとき、music.cfgのfeel1にbgmが設定されていない場合、basicのtownに設定したbgmが再生されるようなのですが、これは正しい挙動でしょうか？
再生するべきbgmが見つからない場合は現在流れているbgmを再生し続ける、が正しい挙動かと思っていました。

wildにbgmを設定してfield1～3にbgmを設定していない状態で広域マップから荒野の狭いマップに入ったときは、bgmは切り替わらずwildのbgmが再生され続けます。
なので、feel1にbgmが設定されていない状態で悪い予感になったときは、同じようにそれまで流れていたbgm（dun_lowなど）が継続して再生される方が一貫性があって自然なように感じます。

**Comment by sikabane-works** [comment]
BGMが指定されていないときの代替手順を一度一通り見直したいと思います。ご指摘ありがとうございます。
