### ISSUE TITLE
【バグ】 Cygwin / Curses環境のカーソルがおかしい / Cygwin / Curses (ASCII) - Stray cursor in subwindows

### ISSUE THREAD

**Issue by smbhax** [hengband/hengband#2014]
## 環境 (environment)

- OS: Cygwin in Windows 10, Curses front end
- バージョン: 3.0.0Alpha51, English version

## バグの詳細 (bug details)

When running the game with subwindows in the Curses ASCII front end in Cygwin, the cursor can be seen flickering at various positions in the various subwindows: often above the stat bar in the main window, at the right end of the first line of text in the Monster Recall subwindow, at the right end of the topmost message in the Message subwindow, and on the character's "@" symbol in the main window, for instance (this is with the "highlight the player with the cursor (hilite_player)" option set to "no"). See circled areas in screenshots below.

This flickering cursor does not appear in current vanilla Angband.

## 再現手順 (repro steps)

1) Compile the source code in Cygwin, following the general instructions for making a Unix English ASCII versions given here: https://github.com/hengband/hengband/blob/develop/readme-eng.md

2) Start the game ("./hengband" in the Cygwin command line)

3) Set up some subwindows (=w options)

4) Move around a dungeon

== Particularly when information appears in the subwindows, such as in the Monster Recall window once a monster has been targeted, a square cursor may appear for just a single frame, or for the duration of a turn, in one of the noted positions in one of the subwindows.

## 期待される正常な動作 (expected behavior)

No stray cursors should appear. This problem has apparently been solved in vanilla Angband--the problem does not occur in Cygwin ASCII Curses builds of that game.

## スクリーンショット (screenshot)

Stray cursors circled:

![curs1](https://user-images.githubusercontent.com/91744319/150893738-f1057699-a8ae-4cc7-a7b1-16361ba59bbb.jpg)
![curs2](https://user-images.githubusercontent.com/91744319/150893837-522ca8f4-37eb-4d3a-863b-ea8ff03cc61b.jpg)
![curs3](https://user-images.githubusercontent.com/91744319/150893850-80d6ed15-d3d8-4f1e-a723-b78ae6a2f8b2.jpg)
![curs4](https://user-images.githubusercontent.com/91744319/150893864-9ececda3-d238-4181-b2de-db4dd4921487.jpg)

## 補足事項 (supplementary information)

May be seen throughout this video, particularly during dungeon exploration:

https://youtu.be/9SC7Lv5E_cM?t=4075

**Comment by sikabane-works** [comment]
All right, thank you for reports. I'm sure someone will take care of it when the time and environment is right.

**Comment by smbhax** [comment]
It looks like PR 2024 might be related to this.

**Comment by smbhax** [comment]
Fixed with latest code in develop branch.
