### ISSUE TITLE
英語版スコアサーバ無効化か英語に対応するか？/  English version - "500 Internal Server Error" HTML code across screen after send score to world score server

### ISSUE THREAD

**Issue by smbhax** [hengband/hengband#2015]
## 環境 (environment)

- OS: Cygwin in Windows 10, Curses front end
- バージョン: 3.0.0Alpha51, English version

## バグの詳細 (bug details)

While running the game in the Curses ASCII front end in Cygwin, my 9th level Merfolk Cavalry died. After being shown his character info screens, a blank screen with

`Do you send score to the world score server? [y/n]`

appeared. When I pressed the y key, the screen showed

`Sending the score...`

for a few seconds. Then, HTML code appeared in a brown font color, wrapping around the screen:

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
													<html><head>
																<title>500 Internal Server Error</title>`

and so forth. It mentioned

`Please contact the server administrator at
											webmaster@kmc.jp`
											
and

`<address>Apache/2.4.38 (Debian) Server at moon.kmc.gr.jp Port 80</address>`

and ended with

`Failed to send to the score server.`

See screenshot for the full code.

## 再現手順 (repro steps)

I have only done these steps once, but in theory:

1) Compile the source code in Cygwin, following the general instructions for making a Unix English ASCII versions given here: https://github.com/hengband/hengband/blob/develop/readme-eng.md

2) Run the game and get your character killed--I'm not sure if they have to have reached some minimum level or time played or something; my character had just reached level 9.

3) Have a working internet connection, and press "y" when asked if you want to submit your score to the world score server.

== The badly formatted error message may appear.

## 期待される正常な動作 (expected behavior)

Ideally, some sort of score report would appear, I suppose (I'm not sure exactly what the world score server is supposed to do). In any case, if there is an error message, it should be formatted so that it is easily legible and useful to the player.

## スクリーンショット (screenshot)

![500error](https://user-images.githubusercontent.com/91744319/150895617-d389e506-3db6-40c0-80db-47302c5e6890.jpg)

## 補足事項 (supplementary information)

Video:
https://youtu.be/9SC7Lv5E_cM?t=7585

**Comment by sikabane-works** [comment]
It also be accepted by bugs. Thank you for reports.

**Comment by smbhax** [comment]
Or, perhaps the --disable-japanese configure option should also just do what --disable-worldscore does, since the English version no longer has world score.

**Comment by habu1010** [comment]
> Or, perhaps the --disable-japanese configure option should also just do what --disable-worldscore does, since the English version no longer has world score.

When PR #2022 is merged, simply add --disable-japanese to disable the score server sending feature.
