### ISSUE TITLE
アリーナの対戦相手のエルフロードが友好的な状態で生成される

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#202]
Alpha6、野蛮人狂戦士いかさまのキャラクターで確認しました。
アリーナの対戦相手のエルフロードが友好的な状態で生成されます。友好的だからかしばらくターン送りしてみてもこちらを攻撃してこず、容易に撃破できます。敵との戦闘に勝利して報酬を得るというアリーナのコンセプトからするとやや不自然な挙動な気がします。

wikiのエルフロードのページのコメントを見ると以前からこの状態だったらしく、自分の手元のver2.1.4でも同様の状況が発生しました。ゲームバランスに大きな影響も無いだろうし現状のままでもこれといって問題ない気もしますが、一応報告しておきます。

**Comment by chikatei** [comment]
投稿した後で気付きましたが、友好的でも一発殴るとすぐに敵対してこちらを攻撃してくるので友好的だろうがあんまり意味ないですね……。一撃で仕留められない場合は普通に戦闘することになり苦戦する可能性もあるのでますます現状のままで問題ない気もします。

**Comment by sikabane-works** [comment]
余談ですがこれはdis-氏も前から意図してやっておられるようですね、構わずぶっ殺せって感じのようです。私もそう言うノリ個人的に好きです。

**Comment by sikabane-works** [comment]
ああ、でも直したんですな。失敬。
