### ISSUE TITLE
TERM_BLUE をもう少し見やすい色にする / Suggestion: slightly lighten the very dark TERM_BLUE color

### ISSUE THREAD

**Issue by smbhax** [hengband/hengband#2020]
Suggestion: slightly lighten the very dark TERM_BLUE color

## 環境 (environment)

- OS: Cygwin in Windows 10, Curses front end
- バージョン: 3.0.0Alpha51, English version

## バグの詳細 (details)

Items and monsters using the TERM_BLUE dark blue color defined in src/term/gameterm.cpp

`    { 0x00, 0x00, 0x00, 0xFF }, /* TERM_BLUE */`

are very hard to see against the black dungeon background. Examples include Dark Blue Potions and Bullroarer the Hobbit, both of which can be found in the Yeek caves:

![blue1](https://user-images.githubusercontent.com/91744319/151447323-ab611861-4467-4679-bc82-c4582d9b7a44.jpg)

![blue2](https://user-images.githubusercontent.com/91744319/151447369-8815f37a-81b4-48cf-b9f8-ffe247d88163.jpg)

Changing TERM_BLUE very slightly to a lighter shade, for instance

`    { 0x00, 0x00, 0x40, 0xFF }, /* TERM_BLUE */`

alleviates the problem:

![blue3](https://user-images.githubusercontent.com/91744319/151447489-c9897104-72fe-4cb8-8b1d-43da9f7f343d.jpg)

I am not sure if that might cause trouble in certain 16-color xterm consoles; it works okay in Cygwin in either xterm or xterm-256color terminal modes.

## 再現手順 (repro steps)

1) Start a new game
2) Go into the Yeek caves east of town
3) Find a dark blue item or monster

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付 (attach save files)

[197609.zip](https://github.com/hengband/hengband/files/7953948/197609.zip)

## 期待される正常な動作 (expected behavior)

Items and monsters should be easily visible.

## スクリーンショット (screenshot)

See above.

## 補足事項 (supplementary information)

The dark blue color is a problem in many old Angband variants. Current Angband has a color editor that allows the player to set the colors as they like from the options menu.

**Comment by sikabane-works** [comment]
All right. Certainly, I was worried that it would be difficult to see. I'll try it.

**Comment by sikabane-works** [comment]
優先度中、前倒しAlpha52で。

**Comment by smbhax** [comment]
Thanks for looking at it! : ) Currently I'm finding an even lighter value, such as

`    { 0x00, 0x00, 0x80, 0xFF }, /* TERM_BLUE */`

is better; of course, beyond a certain point it just comes down to personal preference.

**Comment by sikabane-works** [comment]
Sorry..., I couldn't get there in time. I'll take care of it next time.

**Comment by sikabane-works** [comment]
@smbhax Hello, I try to adjust. Please check your environment.

**Comment by sikabane-works** [comment]
Oops, I guess you've already verified it, so should I just merge it in?
