### ISSUE TITLE
【リファクタリング】if/for/while文に{} を付ける方針で統一

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#2027]
v2.2.2時代は付けない方針として順次外していたが、2003年と2021年の2回に亘って行われた議論により、付ける方針が正式に決まった
大昔から混在している残念コーディング規約であり、コード自体20万行を超えるので相当期間が想定される
本件は都度対応としたい

**Comment by sikabane-works** [comment]
前々からしばしば俎上に上がってはいましたね。全部となると途方もないので、分割していきながらやっていくとよさそうです。Betaマイルストーンで優先度低とし、皆時折ソース見直すついでに手を付けていきましょう。

**Comment by Hourier** [comment]
確認ありがとうございます
但しこのチケットはやや不正確なので改名しておきます

**Comment by Hourier** [comment]
チケットの概要部分も現状に併せて修正しました

**Comment by Hourier** [comment]
置換完了したのでクローズ

**Comment by daradarach** [comment]
Habuさんが、全ファイルにclang-format適用した後、WorkflowでPRのソースチェックするようにした
