### ISSUE TITLE
CAN_SPEAKフラグ群の新設

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2029]
#890 の前段作業

現在のCAN\_SPEAKフラグは「lib/file/mon\*.txt」のファイルを読むか読まないかの2択でしか定義できない
モンスター (特にユニーク)死亡時の特別な描写を書けないので、それが可能になるようにフラグを新設する
今あるCAN\_SPEAK フラグは発展的に解消させる
これにより、ハードコードでセリフ等を書いている箇所をなくすことを最終目的とする
また、「CAN」は自明度が高まるのでフラグ名称からは消す

- SPEAK\_ALL (今あるCAN\_SPEAK フラグを持っている連中に取り敢えずデフォルトで付けるやつ)
- SPEAK\_BATTLE (monspeak)
- SPEAK\_FEAR (monfear)
- SPEAK\_FRIEND (monfrien)
- SPEAK\_DEATH (mondeath)

**Comment by Hourier** [comment]
@Slimebreath6078 可能であればフラグ整理の時に以下2点実施頂けると助かります
そこから先は私が復帰したタイミングで実施します
* CAN\_SPEAK → SPEAK\_ALL への置換
* その他のSPEAK\_\* について、r\_info.txt に記載してもパースエラーにならない程度のダミー実装

**Comment by Slimebreath6078** [comment]
承知いたしました
そうなると SPEAK\_\* はセリフ関連フラグとしてまとめた方がいい気がするので #2190 から分けた Issue を作成しておきます

**Comment by Hourier** [comment]
ふと思いつきましたが、以下も追加頂けると助かります
SPEAK\_SPAWN (『バイケタル』と『ドッピオ』生成時の特殊セリフ。現在はsummon_special_unique() にてハードコードされているので外に出したい)
