### ISSUE TITLE
【バグ】 施設の種族割引、職業割引が正常動作していない

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#2030]
## バグの詳細

施設によってはプレイヤー種族、職業、領域で割引が発生するはずだが正常動作していない。
market/building-service.cpp 20-35の is_owner()が期待通りの値を返していない。
bldg->member_classとbldg->member_raceとbldg->member_realmにまともに値が入っていないように見える。

## 再現手順

アーチャーで開始してモリバントに行き、矢の強化を試みる。
期待されるアーチャー割引は適用されず、$40/本を請求される。

## 期待される正常な動作

旧来通り$20/本であるべき

**Comment by Hourier** [comment]
Habuさんが原因を特定しました
私のコード範囲なので直しておきます
