### ISSUE TITLE
  disturb()タイミングの調査

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2038]
OSDNより転記。[#40023](https://osdn.net/projects/hengband/ticket/40023)

> Twitterにてnono@iyukyo氏から以下のアドバイスもらったのでdisturb()を付与するタイミングについて調査する。
> > mspells4.cのspell_RF6_HEALで確定でdisturbが呼び出されて休憩が中断されると思うのですが、感知範囲外のモンスターの治癒でプレイヤーの行動が中止される必要はあまりないように感じるのですがどうでしょうか。
> > S_KINとS_HI_UNDEADでdisturbされるのも少し気になります。
> > 他の召喚ではdisturbされないので

**Comment by iyukyo** [comment]
https://github.com/hengband/hengband/pull/1926
https://github.com/hengband/hengband/pull/1927

dis-氏が対応してくれていたと思います。

**Comment by dis-** [comment]
対処済なので閉じます
