### ISSUE TITLE
fire_ball()からfire_breath()を分離する

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2046]
OSDN より移行。 [#37914](https://osdn.net/projects/hengband/ticket/37914)

> fire_ball()のrad値をマイナスに指定する、というのは流石にアレなのでどこかでまとめて直す。

現在はstd::optional<int>が使えるのでそっちに切り替えることが可能
但し設計上ボールとブレスを同じコールチェーンで通すことが正しいかは別途検討すべき

**Comment by Hourier** [comment]
差分確認しました
特に問題なさそうなのでリンクの上クローズしましょう
よろしくお願いします

**Comment by Slimebreath6078** [comment]
承知いたしました。
ではクローズいたします
