### ISSUE TITLE
Wikiにバリアント作成の手引を作る

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2063]
セーブデータの互換性がバリアント同士で自動的に無効化される仕様を作った (#1743)
しかしそもそもバリアントを作る時、バリアント名等基本的なところはどこを変えないといけないのかは指針が存在しない
これでは作るものも作れないので、「ここだけは最低限変えてね、そうするとバリアントを名乗れるよ」ができる資料を作る
本件はGitHubのWikiとして結実させる

**Comment by sikabane-works** [comment]
ひとまずBeta、優先度低に回します。気長にやってもらえれば。

**Comment by Hourier** [comment]
作成済
クローズ
https://github.com/hengband/hengband/wiki/%E3%83%90%E3%83%AA%E3%82%A2%E3%83%B3%E3%83%88%E4%BD%9C%E6%88%90%E6%8C%87%E9%87%9D
