### ISSUE TITLE
Wineで新規を選ぶと落ちる

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#2072]
https://osdn.net/projects/hengband/ticket/37853
随分と放置してしまって申し訳ないが、大きくリファクタリングした今、修正が必要かどうかも踏まえて。

> Linux上でWineを使い変愚蛮怒(Windows版)を起動し、メニューバーから［ファイル］-［新規］を選ぶと、変愚蛮怒が異常終了します。このとき画面に特段のメッセージは表示されません。 OSは Ubuntu 16.04 (x86_64)で、Wineは https://wiki.winehq.org/Ubuntu で配布されている公式配布版(wine-stable)の2.0.3を使いました。
> 
> こちらの調査では変愚蛮怒2.2.0のほか2.1.4がNGで、2.1.3は正常に動作しました（すべて公式配布版）。また、最新版ソースに以下の変更をすることで、動作可能となるようです。以下のパッチを元に修正を検討いただけましたら幸いです。
> 
> diff --git a/src/z-rand.c b/src/z-rand.c
> index 9ca8786..4ac02c6 100644
> --- a/src/z-rand.c
> +++ b/src/z-rand.c
> @@ -203,7 +203,7 @@ void Rand_state_init(void)
>  
>  	HCRYPTPROV hProvider;
>  
> -	CryptAcquireContext(&hProvider, NULL, NULL, PROV_RSA_FULL, 0);
> +	CryptAcquireContext(&hProvider, NULL, NULL, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT);
>  
>  	do {
>  		CryptGenRandom(hProvider, sizeof(Rand_state[0]) * 4, (BYTE*)Rand_state);
> 変更前はデフォルトの鍵コンテナへのアクセスを要求しており、このコンテナがない場合は hProvider に有効なハンドルを得られません。変更後は特定の鍵コンテナをオープンしないと CryptAcquireContext に指示するので、デフォルトの鍵コンテナの有無によらず hProvider に有効なハンドルを得られるようになります。
> 
> 以上よろしくお願いします。

**Comment by habu1010** [comment]
恐らく #1805 と同根で、これについては乱数の初期シードを得る方法を変更したことで修正されています。
