### ISSUE TITLE
モンスターの詠唱する魔法をenum値に対し範囲で選択している部分があり追加が大変

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#2079]
https://github.com/hengband/hengband/blob/3158c8af6ac926f24605745af3380d5db875c474/src/mspell/mspell-selector.cpp#L49-L50

https://github.com/hengband/hengband/blob/3158c8af6ac926f24605745af3380d5db875c474/src/cmd-action/cmd-mane.cpp#L92

この辺り。

**Comment by sikabane-works** [comment]
この辺ひどいすな、次バージョン優先度中としましょう。

**Comment by sikabane-works** [comment]
次回とします。どなたか着手できればお願いします。

**Comment by Slimebreath6078** [comment]
enhancementよりはrefactorに移すべき内容のためラベルを変えておきます
