### ISSUE TITLE
所持していない魔法書の呪文を唱えられてしまう

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2088]
OSDN より移行。[#37558](https://osdn.net/projects/hengband/ticket/37558)
フォーラムメッセージ [#80324](https://osdn.net/projects/hengband/ticket/37558#badid-80324) からの引用

> 安定版2.2.0-win
> OS Windows7
> 
> モンスターにアイテムを破壊されるなどで@の手番を挟まずにアイテム欄が変化した場合、所持していない魔法書の呪文を唱えられてしまうことがあります。
> 
> バグ発生までの一例
> 
> a) ? 自然の魔法書[野性の召喚]
> b) ? 自然の魔法書[自然の脅威]
> c) ? 仙術の魔法書[紋様仙術]
> 
> 1.アイテム欄が以上のような状態で'm'→'b'→’f’で自然4冊目の"f) 陽光召喚"の呪文を唱える
> 2.次の行動までにモンスターの行動などでaのアイテムが破壊されてアイテム欄が以下のようになる
> 
> a) ? 自然の魔法書[自然の脅威]
> b) ? 仙術の魔法書[紋様仙術]
> 
> 3.'n'のコマンド繰り返しをするとアイテム欄にある仙術3冊目の"f) テレポート・レベル"ではなく所持していない仙術4冊目の"f) 錬金術"が唱えられてしまう（効果もちゃんと発揮される）
> 
> 補足.唱える先の呪文（例の場合だと仙術4冊目の"f) 錬金術"）を習得していない場合は唱えられませんでした。無条件で唱えるわけではなく、あくまで持っていない魔法書の呪文を選択するバグのようです。
> 　　選択先の魔法書（例の場合だと紋様仙術）の中に習得している呪文がない場合でも発生しました。「その本には知っている呪文がない。」のメッセージは出力されませんでした。
> 　　領域ではない魔法書（トランプとか）が選択先に来た場合は（'m'での魔法書の選択の時点でトランプの魔法書が選択肢になかったため？）発生しませんでした

**Comment by habu1010** [comment]
少し調べた感じでは再現しない。
デバッガでトレースした場合でも、繰り返しコマンドは選択用のタグを刻んでいなければ前回選択したインベントリ上のインデックス番号で参照、タグを刻んでいる場合は前回選択したタグの記号を検索するようになっている。
報告2.2.0とバージョンが古すぎるため直ってる可能性がある。

**Comment by Hourier** [comment]
再現しない事象とのことなので一旦クローズします
v3.0β以降に再発したら再調査する方針とします
