### ISSUE TITLE
敵の直接攻撃を受けたときのメッセージがおかしい。

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#21]
https://osdn.net/projects/hengband/forums/37402/43663/#forum-message-86952

より、

>敵の直接攻撃が当たってもかわしたと出ます。一方で本当にかわしたときにはなにもメッセージが出ないのではないかと思います。

**Comment by taotao54321** [comment]
リファクタリングに伴うエンバグと思われます。
現状の動作は

* 敵の打撃が命中したら
  - 対邪悪結界で防いだら何も表示しない
  - さもなくば「かわした」表示
* 敵の打撃をかわしたら何も表示しない

という動作になっているようです。該当コードは以下です:

https://github.com/hengband/hengband/blob/cb4387ea96be2c5a2874df3bfe64b5fa28d7da0c/src/monster-attack/monster-attack-player.c#L393-L399

**Comment by taotao54321** [comment]
打撃命中処理の流れがやや複雑なので、一旦整理します。
v2.2.1 のコードおよび Discord での議論を踏まえると、現段階の仕様は以下のようになると考えられます:
(認識が間違っている点があればご指摘ください)

1. まず、モンスターの打撃が発動する前に居合や変わり身による阻害処理を行う(`make_attack_normal()` 内)。
2. 阻害されなかった場合、モンスターは最大4回の打撃を行う(`process_monster_blows()`)。
3. 個々の打撃を行う前に中断判定を行う(プレイヤー死亡など)。
4. 打撃の結果は命中/回避のいずれかである。
  a. 命中した場合、対邪悪結界による撃退を試みる。撃退した場合、直ちに次の打撃へ移行する。撃退しなかった場合、被弾処理、思い出処理、落馬処理、変わり身のテレポート処理を行う。
  b. 回避した場合、回避処理、思い出処理を行う。

このうち v2.2.1 からの変更点は以下の通りです:

* 4-b の回避したケースで落馬処理は行わない(元々ダメージ0なら落馬しない仕様だったので実質変更なし)
* 4-b の回避したケースで変わり身処理は行わない。これは厳密には仕様変更となるが、「〜の攻撃をかわした。変わり身失敗！攻撃を受けてしまった。」という不自然なメッセージが出るのを防ぐ措置。

**Comment by habu1010** [comment]
モンスターからプレイヤーへの攻撃の結果で行う処理・行わない処理について、マトリックスにしてまとめてみる。

|攻撃の結果|被弾処理|回避処理|思い出処理|落馬処理|変わり身のテレポート処理|
|-|-|-|-|-|-|
|命中|○|✕|○|○|○|
|命中(結界で撃退)|○|✕|○|✕|✕|
|回避|✕|○|○|✕|✕|

**Comment by taotao54321** [comment]
撃退時の思い出処理だけ意見が割れそうなところでしたが、迷ったらプレイヤーに有利な方を選ぶということで思い出処理ありにします！
