### ISSUE TITLE
【バグ】 GCU - says "Angband" instead of "Hengband" in "Angband needs an 80x24 'curses' screen" warning message

### ISSUE THREAD

**Issue by smbhax** [hengband/hengband#2116]
【バグ】 バグ報告のタイトルを編集 (title)

## 環境 (environment)

- OS: Cygwin in Windows 10, Curses front end
- バージョン: Develop branch, synced to recent commit (https://github.com/hengband/hengband/commit/3158c8af6ac926f24605745af3380d5db875c474), English version

## バグの詳細 (bug details)

When attempting to launch the ASCII version of the game from a terminal window smaller than 80x24, an error message appears that names the wrong game: "Angband needs an 80x24 'curses' screen."

## 再現手順 (repro steps)

1) Scale your terminal emulator to smaller than 80 columns and/or 24 rows

2) Attempt to launch the game (I enter "./hengband/hengband" from Cygwin's home directory, for instance)

==> An error message mis-stating the name of the game appears:

`Angband needs an 80x24 'curses' screen`

## 期待される正常な動作 (expected behavior)

This is Hengband, not Angband, so the message should read

```
Hengband needs an 80x24 'curses' screen
```

## スクリーンショット (screenshot)

![heng_curse](https://user-images.githubusercontent.com/91744319/152676970-16e3f01c-cabd-444d-9a50-c09183bd1fee.png)

## 補足事項 (supplementary information)

None

**Comment by sikabane-works** [comment]
Thanks, I set it next milestone and middle priority.

**Comment by smbhax** [comment]
Fix confirmed. : )
