### ISSUE TITLE
【バグ】剣術家のブーメランのダメージがおかしい

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#2139]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha52

## バグの詳細

バグの内容を明確かつ簡潔に説明

剣術家のブーメランが頭のおかしいダメージを叩き出す。また、投げる武器がアイテム欄のどの位置にあるかでダメージが変わる。

## 再現手順

バグを発生させる手順が分かっていれば記載

ブーメランでアイテム欄にある武器を投げる。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

少なくとも、投げる武器がアイテム欄のどこにあってもダメージは変わらない。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

fの位置にある死の大鎌を投げた場合

![f](https://user-images.githubusercontent.com/81608944/153196118-474d89b1-ce1b-4f1f-a797-37e5a5193597.png)

gの位置

![g](https://user-images.githubusercontent.com/81608944/153196161-02dc38f8-2512-46a6-8c9d-f34cf7c2f8df.png)

## 補足事項

補足事項があれば記載

**Comment by Hourier** [comment]
セーブデータの提供をお願いします

情報提供として、ObjectThrowEntity::calc_racial_power_damage() が怪しいとのこと
文脈的に"this->item" とは装備品しか指していないので、手持ちのアイテムだとおかしくなりそう
装備品を投げるのか手持ちのアイテムなのかで場合分けするのが正しいと思われる

throw-execution.cpp L487-490
```c
if (this->boomerang) {
  this->tdam *= (this->mult + this->player_ptr->num_blow[this->item - INVEN_MAIN_HAND]);
  this->tdam += this->player_ptr->to_d_m;
} else if (this->obj_flags.has(TR_THROW)) {
```

なお、少なくともv2.2.1から同じ形のコードである
見つからなかったのはたまたまか？

**Comment by iyukyo** [comment]
[PLAYER.zip](https://github.com/hengband/hengband/files/8032996/PLAYER.zip)

これでいいでしょうか。

**Comment by Hourier** [comment]
提供ありがとうございます
後ほど確認します

**Comment by Hourier** [comment]
throw-execution.cpp を見ましたが、壊れた設計のままクラス化だけ行っていびつなコードになっているのが見えてきました
修正まで時間がかかると思います
しばらくお待ち下さい
