### ISSUE TITLE
ロケール設定による警告（旧：Visual Studioでビルド時の警告

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2144]
OSDN より移行。 [#35729](https://osdn.net/projects/hengband/ticket/35729)

> システムロケールが「日本」以外の場合にwarning C4566が大量に出ます。
> Windowsのシステムロケールを「日本」に設定した場合はこの警告は出ません。
> Visual Studio 2015で確認していますが、他のバージョンでも同様の警告が出るかと思います。

> この件、この前ソースを全てBOMつきUTF-8に変えてどうなったか再確認しておきたい。
> この件まだ多分直ってない、はず。

**Comment by Hourier** [comment]
以下のページによると、「charではなくwchar\_tを使え」とあります
ソースコードの規模的に明らかに困難なのと、そもそもstd::string を使う方針でリファクタリングしているので、もうこの際抑制してもいいように思われます
https://learn.microsoft.com/ja-jp/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4566?view=msvc-170

**Comment by argrath** [comment]
[Visual studio C++のコンパイル時の警告C4566の対応方法](https://tadapon.blogspot.com/2009/09/visual-studio-cc4566.html) によると単なる警告だけでなく動作も変わってしまうようなので、警告はそのままにしてビルド要件を「日本語環境のみ」とした方が良さそうに見えます。
