### ISSUE TITLE
重力属性の効果の処理がおかしい

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#2172]
減速が効かない敵でも減速してしまう、他が効いたかどうか関係なく朦朧が効かなければ「効果がなかった。」と出て効かないことになるといった複数のバグを抱えている

他の属性もバグっているかもしれないが、それは気付き次第逐次Issueを上げていく

**Comment by Slimebreath6078** [comment]
過去に同じIssueが優先度: 中になってたようなのでそっちにラベルを変えます

**Comment by Slimebreath6078** [comment]
現状時間逆転も追加効果が効く効かないに関わらずobviousがtrueになっているが、元々の仕様が不明なためこれのIssueは一旦保留とする

**Comment by sikabane-works** [comment]
保留とのことで次に回します。
