### ISSUE TITLE
wiz_kill_enemy() が正しく機能していない

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2176]
## 環境

- OS: Windows 10 Pro
- バージョン: 3.0.0Alpha52

## バグの詳細

Effect IDをデバッガに入力させるところまでは良いですが、その入力値 (effect\_idx)が後続処理で使われていないため常に0として判定されます
そのため毎回「番号は1から%dの間で指定して下さい。」と表示されます

## 再現手順

1. デバッグモードをONにする
2. Ctrl+a → Y で指定属性のボール発射を試みる
3. ダメージは適当に1以上の値を入力
4. 属性は1～124と促されるので正常値を入力する

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
簡単に再現可能と思われるのでなし

## 期待される正常な動作

上記の4を入力後、射撃等と同様にターゲット指定が可能になる

## スクリーンショット

省略

## 補足事項

1. 暫定でeffect\_idxを参照するように弄れば動作しますが、想定仕様がイマイチ分からないので過去に担当したと思われる方々に投げます。ご確認下さい
2. 属性は数値だけでなく、何番が何属性か分かるようにmapがあると嬉しいです (別チケット案件)

**Comment by sikabane-works** [comment]
とりあえず、自分のインターフェースの汎用化の一環に入りそうな部分なので今夜あたり修正かけます。
