### ISSUE TITLE
性別のフラグをEnum class化する

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#2185]
#1951 から分離
性別は複数フラグを所持する必要性がないためEnum classにする

**Comment by Slimebreath6078** [comment]
両性は必要に応じて追加すればいいのでとりあえずそれは作らずに行こうと思います

**Comment by Hourier** [comment]
承知しました
今後追加の予定はあるにはある (時期未定)ので、拡張が容易な設計になっているととても助かります
よろしくお願いします
