### ISSUE TITLE
出現数関連のフラグをFlagsGroup化する

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#2188]
#1951 から分離
現状UNIQUE2とNAZGULのみだが、他にも同様の設定が必要になることが考えられるため拡張しやすくする

**Comment by Slimebreath6078** [comment]
UNIQUE2 は毒針耐性と分ける予定でしたが、分けるのがダメそうな場合は種族フラグに入れます
どちらの方がよいかご意見お願いいたします

**Comment by Slimebreath6078** [comment]
作業をしている最中、UNIQUE2 は毒針耐性だけでなく抹殺免疫も有していることがわかりました
毒針耐性を即死耐性に変えるか抹殺免疫として分けるかは未定

**Comment by Slimebreath6078** [comment]
UNIQUE2 は分離が必要である上、リファクタリングの範疇から外れる変更を要するため別チケットにします

**Comment by Hourier** [comment]
賛成です
UNIQUE2 フラグは、Discordでの議論を見る限り分離しないと適切な管理ができなさそうです
その仕様部分も含めて今後改めて詰めていきましょう
