### ISSUE TITLE
BOMのありなしが混在しているので定期的にBOMありへ統一する機構を作る

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2220]
VSCodeはデフォルトがBOMなしUTF-8らしく、今後外部からPRを受けた時に何度でも同じことが起き得る
VS2022はBOMなしUTF-8を正しく認識できないため、コンパイルエラーが起きる
混入前ならばCRを出すなり拒絶するなりすればいいが、既に今リポジトリに入っているものについてはBOMありへ変換するスクリプト等を入れておいた方が良さそうである

**Comment by habu1010** [comment]
事前に混入を防ぐのが一番よいだろう、という事で GitHub Actions でのビルドチェック時に BOM の有無をチェックするようにする PR #2226 を出しました。
