### ISSUE TITLE
死体を食べた時の効果を格納するフラグを削除する

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#2246]
死体を食べた時の効果は現状中身が実装されておらず、また実装される予定もないのでフラグを削除する

**Comment by Hourier** [comment]
deskull氏が馬鹿馬鹿から逆輸入したい旨の発言をどこかでしていたような記憶があります
念のため確認してから進めて下さい

**Comment by sikabane-works** [comment]
改めて消してもらってOKです。クッソ汚なそうなネタは馬鹿馬鹿でやります。

**Comment by Slimebreath6078** [comment]
死体と骨のドロップフラグもここにあるため#2258 を終えてからの作業になります
