### ISSUE TITLE
project関数内のシーカーレイ、スーパーレイを隔離する

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#2254]
#2253 から分離

これらは処理が比較的独立しており、行数も少なめで隔離しやすいためまずこれの隔離から始める。
これだけでも関数内の行数を1/4くらい削減できるため効果は大きいと思われる。

**Comment by Hourier** [comment]
チケット化されていない中期的予定で実施を考えていましたが、やってもらえると大変助かります
但し、その前にmind-mirrormaster.cpp をクラス化し、後続処理としてそこへproject() の処理をメソッドとして移植した方が幸福度が上がりそうです

**Comment by Slimebreath6078** [comment]
#2253 は既に終了しておりますので#2355 の延長線上的な Issue にします
