### ISSUE TITLE
artifact_type[] a_info の型をstd::map<FixedArtifactType, ArtifactType> に差し替え、ARTIFACT_IDX 型エイリアスを廃止する

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2276]
掲題の通り
enum をenum class に差し替えるのも含め、全部いっぺんにやらないとダメっぽい
gf\_colors と似たような手法で初期化できることも期待しつつ実施検討する

**Comment by habu1010** [comment]
この件ですが、型名だけ見ると、 FixedArtifactType と ArtfiactType の違いってなんやねんってなりそうですね。
意味合い的には、 FixedArtifactId と FixedArtifactType になるのが正しいかもしれません。（ただ他の一意のIDを表す enum class 型も ～Type になっているものが多いのですが…）

**Comment by Hourier** [comment]
ナントカtype系は慣例でそうなってるだけで大した意味がないです
ここで改めて命名規則考えるのも良さそうですね
mapのキーになるものはIdとして定義しておきます
