### ISSUE TITLE
武器の固有ボーナスの明記

### ISSUE THREAD

**Issue by Aquashrimp** [hengband/hengband#228]
マン・ゴーシュと脇差しには、二刀流で逆手に装備すると命中+10、AC+5のボーナスがありますが、ゲーム内ではそれらしい情報が全く見られません。雀の涙ほどのボーナスですが、フレーバーテキストなどに書いておいたほうが良いのではないかと思います。
また、ランス系も乗馬中はダイスが増加しますが、これもゲーム内では分かりづらいです。乗馬中かつランスを装備している間はダイスを増やした状態で表示できないでしょうか？

**Comment by sikabane-works** [comment]
* マン・ゴーシュと脇差の＊鑑定＊内容を追加
* 両武器の効果判定をk_info, e_info, a_infoのフラグに切り替える
* ランス系ボーナスの＊鑑定＊内容を追加
* 騎乗中のダイス追加状態を明治
* ランス装備の効果判定をk_info, e_info, a_infoのフラグに切り替える
以上の工程を想定。

**Comment by sikabane-works** [comment]
ランス系のブーストに関してはiks氏の指摘の問題を別途改良予定。

**Comment by dis-** [comment]
ランスも含め全て実装済なのでcloseします
