### ISSUE TITLE
clang-format により整形された状態を維持する

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#2295]
# 動機

せっかく clang-format による整形を基本とすることをプロジェクトとして決めているので、今回すべてのソースファイルに clang-format を適用したのを期に、今後は整形がくずれたコミットが混入するのを防ぎたい。

# 手段

PR に対してビルドテストのGitHub Actions Workflowを導入しているので、ここで整形のチェックも行う。チェックは今の所次の方法を想定している。

1. チェックアウトしたソースファイルに clang-format をかける
2. git diff を実行し、差分を見る。この時なんらかの差分が発生すれば、clang-format による整形が行われたという事であり、整形が維持されていないのでビルドテスト失敗扱いにする
3. エラーになった場合、git diff の内容を表示し、Workflow の結果を見ることでどこの整形に問題があるか確認できるようにする。

**Comment by Hourier** [comment]
「できたら最高」くらいに思ってましたがにわかに現実味を帯びてきた印象です
是非賛成します
