### ISSUE TITLE
海底都市クエストの、ソースコード上の廃止

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2297]
max\_q\_idx のグローバル変数を削除するに当たって議題に上がった設計変更
内部的にはまだ種々の残骸が残っており、quest (旧称 q\_info) との兼ね合いで支障がある
既に外見の仕様としては廃止されてから10年以上経っており、少なくとも今と同じ形での復旧もありえないので、関連コードを全て削除する
クエストを受領していたり旧ルルイエに＠が存在するセーブデータは、SaveDataNotSupportedException として読み込みしないものとする

**Comment by Slimebreath6078** [comment]
このIssueはmax_q_idx削除ついでで私が担当いたします

**Comment by Hourier** [comment]
よろしくお願いします
例外定義はsystem/angband-exceptions.h にありますので併せてご参考下さい
