### ISSUE TITLE
セーブ直後にキャラクターが移動できない

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#231]
ODSNのフォーラムから。

> Re: 変愚蛮怒3.0.0Alpha6以降の要望/報告 (2021-02-20 23:26 by  February20 #87068)
> Alpha 5のセーブデータをAlpha 6に移動してプレイ、 Alpha 6でセーブ、ゲームを終了し、ゲームを再開すると、 モンスターが視界内にいるとテンキーで移動が出来なくなりました。 NumLockの状態にかかわらず移動できません。カーソルキーでも移動できません。 シフト＋テンキーなら移動ができます。「*」のターゲット移動もテンキーで動きます
> 
> Alpha 6の問題かと思い、セーブデータをAlpha 5へ移動して プレイしましたが、会敵するとテンキーで移動できない症状は変わりませんでした。
>

**Comment by iks3** [comment]
調査の結果、セーブファイル自体は関係ないようだった。
デバッグ自動セーブのセーブ条件判定に不具合があり、特に起動直後においてはのセーブ関数によってキーキューがクリアされてキー待ちになっていた模様。

**Comment by sikabane-works** [comment]
マージ済ませたので閉じます。
