### ISSUE TITLE
マンキュバスの性能調整

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#2311]
39Fの敵だが、ファイア・ボールの威力(期待値261)がHP最大の古代レッド・ドラゴンの火炎ブレスに匹敵するにも関わらず、HPが高すぎ(2250は地獄の公爵すら超えている！)なので1400まで落とす
あと加速も-5にして経験値も少し上げる

**Comment by Slimebreath6078** [comment]
絶対値の-5です
今の加速も+0ですし

**Comment by Hourier** [comment]
それならOKです
調整よろしくお願いします
