### ISSUE TITLE
【バグ】 忍者が重い装備を付けると加速が+99になる

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#2322]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha53

## バグの詳細

バグの内容を明確かつ簡潔に説明

忍者が重量制限を超える重さの装備を付けると加速が+99になる。lv9ではならず、lv10とlv50で+99になるのを確認した。ゲームターンを確認したところ実際に+99になっていると思われる。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. ふつうの人間忍者で新規にゲームを開始する。
2. デバッグでアダマンタイト製プレートメイルを出して装備する。
3. lvを上げて、lv9(経験値450)、lv10(経験値500)、lv50で加速を確認する。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

装備が重いと加速ボーナスを失う。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

![無題](https://user-images.githubusercontent.com/81608944/155891325-23397094-8a48-4303-a461-881a4998a838.png)

## 補足事項

補足事項があれば記載

**Comment by Hourier** [comment]
PlayerSpeed::class_value() に誤りが見つかりました
装備制限のあるクラスは全部おかしなことになりそうです
本日中に修正します
