### ISSUE TITLE
【バグ】スレイが効くべき相手に効かず、効かないはずの相手に効く

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#2323]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha53

## バグの詳細

バグの内容を明確かつ簡潔に説明

タイトルの通り。スレイの判定が反転しているのではないか。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. a_infoを書き換えて適当な★、ここではヴァンパイア・キラーのダイスを100d1にする。
2. スレイが効くはずの相手や効かないはずの相手を殴ってダメージを確認する。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

スレイが効く相手が正しく判定される。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

殺戮修正は46。|焼X死/邪デの武器だが、邪悪なるアンデッドのデーモンである魔王の使いへの攻撃にダメージ倍率がかかっていない。善良なアンデッドのドラゴンであるダーネヴィールにはダメージが3倍になっている。

![無題](https://user-images.githubusercontent.com/81608944/155928120-8b1fb7c2-2f0b-45f1-ad5a-6054df11d876.png)

## 補足事項

補足事項があれば記載

slaying.cppの69行目に、

        if (flgs.has_not(p->slay_flag) || r_ptr->kind_flags.has(p->affect_race_flag))
            continue;

とある。武器にスレイがない、もしくは敵にフラグがある場合に処理をスキップすると読める。

**Comment by Hourier** [comment]
飛竜さんに心当たりあるようなので割り当てておきます
