### ISSUE TITLE
【バグ】 自分のキャラ表示が @ ではなく別の文字に変わってしまう

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#2331]
## 環境

- OS: Mac X11
- バージョン: 3.0.0Alpha53

## 詳細

自分のキャラ表示が @ ではなく別の文字に変わってしまう

## 再現手順

1. 新規キャラを作成する
2. 1 の店に入る
3. もし売っていれば モンスターの像を x コマンドで調べる
4. 店を出るとキャラ表示が変わることがある
5. 変わらない場合や売っていない場合は宿屋で一泊してから再度繰り返す

## 補足事項

Mac App 版では再現しないため X11 のみの現象と思われます

100% は再現しないのですが新規キャラ作成で像があった場合は再現率が高い

ナミの像の時は オレンジの p に
マリードの像の時は 緑の P に
レッド・キラービートルの像の時は 赤の K に
それぞれなりました

**Comment by Hourier** [comment]
Windows版でも極稀に見かけたことがありますが原因不明でした
頂いた条件で再現を試みてみます
