### ISSUE TITLE
【バグ】 マクロを保存しようとするとゲームが落ちる

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#2337]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha53

## バグの詳細

バグの内容を明確かつ簡潔に説明

マクロが登録された自動拾いを開いて読み込んだ後、@のゲーム内マクロ編集画面で2のマクロを保存をしようとするとゲームが落ちる。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 落としてきた変愚を解凍
2. 本issueに添付の自動拾いをuserに置く
3. 新規にゲームを開始
4. 自動拾いを読み込んでゲームに戻る
5. @→2→エンター
6. 落ちる

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

自動拾いファイル

[picktype.zip](https://github.com/hengband/hengband/files/8154182/picktype.zip)

## 期待される正常な動作

本来期待される正常な動作を記載

落ちない。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
マクロを保存する時に内容をテキストファイルに保存できる形式に変換しているが、この時に変換先バッファ長が1024で変換した長さはチェックしていないため1024バイト程度以上のマクロを保存しようとするとバッファオーバーラン。
