### ISSUE TITLE
【バグ】 画面表示の設定のシンボルエディタが機能しない場合がある

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#2363]
## 環境

- OS: Mac App版　X11版　
- バージョン: 3.0.0Alpha53 ~ 55

## 詳細

画面表示の設定のシンボルエディタが機能しない場合がある

## 再現手順

1. ' % ' コマンドで 画面表示の設定 を出す
2. (7) モンスターの色/文字を変更する （シンボルエディタ） を選ぶ
3. ユニーク　農夫『マゴット』 を選び ' v ' でシンボルを変更する
4. シンボルエディタの選択画面が表示されない

<img width="763" alt="No1" src="https://user-images.githubusercontent.com/17109188/156603228-00e6ad23-be4e-4de8-a821-acd05178a3a0.png">

## 補足事項

他の多くのキャラ（例『森トロル』）を選んだ場合は正常に表示されます
<img width="763" alt="No2" src="https://user-images.githubusercontent.com/17109188/156603345-e5d7a84c-848b-42fb-997e-db0fbeafcc54.png">

**Comment by Hourier** [comment]
Windows版でも再現しました
しかしたまにマゴットも正常に表示されて条件が不明です
取り敢えず修正のテーブルには載せます (表示されないだけでシンボル変更自体はできるんどえ、優先度低めになると思います)

**Comment by habu1010** [comment]
bisect の結果貼っときます
a7d96bfc5fedd155614552431841de025f32a981

**Comment by Hourier** [comment]
符号あり → 符号なし のキャストが悪さしているようなので後ほど修正します
