### ISSUE TITLE
enum monster_race_type と 型エイリアス MONRACE_IDX を enum class MonsterRaceId にする

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#2365]
enum monster_race_type と MONRACE_IDX は両方ごちゃまぜで使われており、さらにマップ上のモンスターリストのインデックスを指す MONSTER_IDX がある事もあいまってカオスな事になっている。実際に MONRACE_IDX であるべきところで MONSTER_IDX が使われていたりと誤用も多く見受けられる。
とりあえず前者を enum class MonsterRaceId に統一しておけば誤用を避けられ、誤って種族IDを渡すべきところにモンスターリストのインデックスを渡す事も避けられる。
リスクとしてはかなり修正範囲が大きくなる事。

**Comment by Hourier** [comment]
相当量の調整によりβリリースまでに作業完了した
クローズ
