### ISSUE TITLE
【バグ】吸血鬼が暗黒攻撃で盲目になる

### ISSUE THREAD

**Issue by hkudoh** [hengband/hengband#2368]
## 環境

- OS: Windows 10
- バージョン: 3.0.0Alpha54

## バグの詳細

- 吸血鬼（暗黒免疫所有）が暗黒攻撃を受けると盲目になります

## 再現手順

- 吸血鬼で暗黒攻撃を受ける
  - 吸血鬼魔道具術師 vs シャドウ・ハウンドで発生を確認

## 期待される正常な動作

- 暗黒免疫があるため、盲目にならない
- なお、ダメージは受けていないため、ダメージ計算には問題がないものと思います

## スクリーンショット

なし

## 補足事項

- 暗黒免疫 == 盲目も無効と記憶していますが、記憶違い（仕様通り）でしたら申し訳ありません

**Comment by Hourier** [comment]
仕様はご認識の通りです
優先度上げて確認します

**Comment by Hourier** [comment]
git bisectによってひとまず問題箇所は特定、確かに怪しそうなコミットだがどこにどんな誤りがあるかは調査中

commit 721db96904a006c586fb795b0b3fca1a01a4cdbc
Author: iks <iks3@users.noreply.github.com>
Date:   Sun Apr 18 02:02:53 2021 +0900

    [Refactor] 特殊な種族の能力/耐性の定義をplayer_raceに移動

    アイテム能力フラグにTR_VUL_ACID～TR_VUL_LITEとTR_IM_DARK追加。
    幽霊の地獄吸収ついては未対応。
    種族の食事については未対応。
    種族か切り傷を負うかどうかについては未対応。

**Comment by habu1010** [comment]
このコミットの前まで吸血鬼は内部的に暗黒耐性のフラグを持っていた（暗黒免疫は種族を見て特別処理）のですが、このコミットで暗黒免疫のフラグを作って導入すると同時に暗黒耐性のフラグが削除されています。
暗黒攻撃で盲目になるかどうかは、暗黒耐性（has_resist_dark()）しか見ておらず、免疫（has_immune_dark()）を見ていないのでこれにより盲目になるようになっています。
修正方法としては、盲目になるかどうかの判定に has_immune_dark() も加えるのが妥当そうです。

**Comment by hkudoh** [comment]
ご対応ありがとうございました =)

**Comment by hkudoh** [comment]
Alpha 57 で修正されていることを確認しました =)

**Comment by Hourier** [comment]
追加確認ありがとうございました！
