### ISSUE TITLE
【バグ】  クエスト情報表示で (危険度:0階相当)   と表示される

### ISSUE THREAD

**Issue by gold-onion** [hengband/hengband#2384]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha54（55にセーブファイルを移動しても起きる）

## バグの詳細

クエスト情報表示で (危険度:0階相当)   と表示される

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 気が付いたら出るようになってたので原因不明
2. ctrl+qでクエスト情報を表示
3.  遂行中のクエストに (危険度:0階相当)   と表示される

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
[Ceres.zip](https://github.com/hengband/hengband/files/8198777/Ceres.zip)

## 期待される正常な動作

 (危険度:0階相当) が表示されない

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付
![hengband](https://user-images.githubusercontent.com/79760235/157062959-27596f23-f731-41a6-a5e9-0aceba5cc103.png)

## 補足事項

補足事項があれば記載

**Comment by Hourier** [comment]
原因判明しました
ソースコードの設計上、「クエスト番号0番のダミークエスト」なるものが存在するのですが、何らかの理由でそれが受託状態になっておりそれが表示されたようです
「ダミークエストが受託状態になる」は恐らく過去の不具合ですが、「受託状態ならばダミークエストでも表示する」は現存する不具合なので修正します
