### ISSUE TITLE
【バグ】 50階のRQが存在しない

### ISSUE THREAD

**Issue by HiddenNameZ** [hengband/hengband#2385]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha55

## バグの詳細

鉄獄50階に入ったところ、RQ対象のユニーク名が表示されず、クエストメニューにも50階のRQが存在しなかった(それまでのRQは普通にあった)。倒したユニークが偶然ボスだったわけでもないらしい（成功表示すらないため）。また、既に51階以降への階段や坑道が生成されていた。
AF縛りで鍛冶師をやっているが多分関係ない。

## 再現手順

セーブファイルを添付した。

[Hengband-3.0.0Alpha55-jp.zip](https://github.com/hengband/hengband/files/8204140/Hengband-3.0.0Alpha55-jp.zip)

## 期待される正常な動作

50階に入ったらRQが発生する。

**Comment by Hourier** [comment]
デバッグコマンドで飛んでみましたが確かに50Fだけおかしな動きをしています
これより詳細調査します
(見た感じ、50FのRQ自体が消えてしまった模様)

**Comment by Hourier** [comment]
git bisect しました
結果、 9017d494 (good) ～ 6b487fa05 (bad) までのどこかでコケていることが分かりました
しかしここから先はコンパイルエラーがマシマシなので詳細不明です
変更範囲は飛竜さんの担当だったので、緊急案件としてチケット振ります
ご確認下さい
