### ISSUE TITLE
スプリント番号を付けたマイルストーンの廃止

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2396]
agrath氏より掲題のコメントあり
個人的にも、延々と数十個も「延期します」というマイルストーン変更記録だけが残っているチケットを見ると悲しくなるので、「NextSprint」「Beta」「v3.0正式リリース」「v3.2以降の検討事項」の4種類程度で良さそうな感じもする

以上、何かコメントあればお願いします
チケットのアサインはマイルストーン定義等の責任者であるdeskull氏にしておきます
後ほどご確認下さい

**Comment by sikabane-works** [comment]
了解。その方向で整理しましょう。

**Comment by Hourier** [comment]
確認ありがとうございます
Next sprintの扱いについては思うところもあるので、終業後にDiscordで詳細お話します

**Comment by Hourier** [comment]
概ね今いる開発メンバーに意図が伝わっているのと、プロジェクト上のGoが出たので本件クローズします
以後は以下の運用をお願いします

* すくやるチケットはNext Sprint に置いて作業する
* その他のチケットは一旦Beta以降のマイルストーンに置き、着手のタイミングでNext Sprintへ移す
