### ISSUE TITLE
ファクトリクラスが返すインスタンスをshared_ptr からunique_ptr に変える

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2407]
スマートポインタの使い方や生成コスト等考えると掲題の方が合理的なのでそちらへ寄せる

**Comment by habu1010** [comment]
賛成です。
必要ならば `std::shared_ptr<T>` は `std::unique_ptr<T>` から簡単につくれる（ `std::unique_ptr<T>&&` を受け取るコンストラクタがある）ので、ファクトリクラスは常に std::unique_ptr を返す方針でよいと思います。

**Comment by Hourier** [comment]
ご意見ありがとうございます
今あるファクトリクラスは3つ (今後2週間以内に1つ追加予定)で、全て私が作ったファクトリでした
影響範囲も把握できているので問題なく置換できる見込みです
