### ISSUE TITLE
【バグ】一部ダンジョンで出現しないはずのモンスターが出現する

### ISSUE THREAD

**Issue by seto32** [hengband/hengband#2420]
## 環境

- OS: Windows10  Pro 64bit
- バージョン: 3.0.0Alpha56

## バグの詳細
天界に非善良モンスターが出現するなど、スポイラーWikiに記載された各ダンジョンの特徴からは出現しないはずのモンスターが自然生成されています。
※こちらで確認できていない仕様変更またはスポイラーの誤情報なのかもしれませんが、念のため報告させていただきます。

〇確認できた事例
１．天界に中立・邪悪モンスターが出現する。
　　・具体例：遅鈍ハウンド（中立）・グレータータイタン（邪悪）
２．地獄に中立・善良モンスターが出現する。また、火耐性がないモンスターも出現する（これは飛行可能なモンスターのみかも）。
　　・具体例：ペガサス（中立かつ火耐性なし）ハヤブサ（善良かつ火耐性なし）
３．水没した遺跡に水地形を渡れない陸上モンスターが出現する。
　　・具体例：ドルイド僧（飛行不可かつ水泳不可）
４．火山に飛行不可かつ火耐性がなく、明らかに火山に似合わないモンスターが出現する。
　　・具体例：水トロル

参考にしたWikiの該当項目
http://mars.kmc.gr.jp/~dis/heng_wiki/?%E3%83%80%E3%83%B3%E3%82%B8%E3%83%A7%E3%83%B3

少なくとも手元に残ってたVer.2.1.5(開発版)の勝利済みセーブデータで軽く確認した範囲では天界は善良モンスター、地獄は邪悪モンスターしか出現しませんでした。

## 再現手順
1.新規セーブデータでゲームを開始する。
2.デバッグコマンド(j)で各ダンジョンに侵入する
3デバッグコマンド(d)で全感知する。
4.具体例に挙げたようなモンスターがいることを確認した。
　※天界は一発で分かりますが、他のダンジョンは何度かフロア移動しないと見つからないかもしれません。

[save.zip](https://github.com/hengband/hengband/files/8264883/save.zip)

また、サーペント撃破後に徒歩で天界や地獄に侵入しても再現します。

## 期待される正常な動作

スポイラーWikiに記載された条件に合うモンスターのみが生成される。
具体的には天界には善良モンスターのみが生成されるなど。

## スクリーンショット
地獄にハヤブサ軍団がいる図（上にいる白いqがペガサス）
![地獄](https://user-images.githubusercontent.com/101727881/158635391-c02ed71f-de3a-4156-85f0-5a0a8ecffe67.png)

## 補足事項
α55でマーフォーク忍者でサーペント撃破後に天界に入ったところ非善良モンスターだらけで違和感を感じたため、α56で上記手順で再現確認をしました。

他の出現モンスターに制約のあるダンジョンについては調査してません。
具体的にはカメレオン洞、反魔法の洞窟、反攻撃の洞窟です。

**Comment by Slimebreath6078** [comment]
ご報告ありがとうございます
バグの原因を特定したため、私が修正を担当いたします

**Comment by Hourier** [comment]
生成ルーチンが若干異常なのは修正するとして、スポイラーWikiは仕様書ではありません
必ずしも正確な記述がなされているとは限りませんのでご注意下さい

**Comment by seto32** [comment]
>スポイラーWikiは仕様書ではありません
承知しております。
こちらの意図としても厳密にスポイラー通りにして頂きたい訳ではありません。
特に火山や水没した遺跡は一見して分からない上に普段はほとんど潜りませんので以前からこの動作だったとしてもおかしくないと思っています。

本件は基本的に天界の出現モンスターが過去バージョンと違いすぎるため、意図しない不具合の可能性が高いと判断したためのご報告です。

ご対応よろしくお願いします。

**Comment by Hourier** [comment]
意図承知しました
丁寧なご連絡ありがとうございます
上記の通り修正作業は実施中ですのでしばらくお待ち下さい
よろしくお願いします
