### ISSUE TITLE
【バグ】 魔道具の使用回数がオーバーフローする

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#2454]
## 環境

- OS: [例: Windows 版、Linux X11 版 etc...]
- バージョン: 3.0.0Alpha56

## バグの詳細

バグの内容を明確かつ簡潔に説明

魔法棒の使用回数が4294967289回分という非常に大きな数字になっており、オーバーフローしたと思われる。どのタイミングでオーバーフローしたかはわからないが、直前に充填魔力吸収打撃を耐性を持った状態で受けていた。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 魔法棒を持ち、充填魔力吸収打撃を軽減する耐性を持った状態で充填魔力吸収打撃を受ける？

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

使用回数が0未満にならず、オーバーフローもしない。

本来期待される正常な動作を記載

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

![無題](https://user-images.githubusercontent.com/81608944/160223550-dd036157-c56b-4a8d-9aec-bf3a93d0e77b.png)

![無題2](https://user-images.githubusercontent.com/81608944/160223553-9749c035-f95f-4b04-8b0d-6c3087a4ce5d.png)

## 補足事項

補足事項があれば記載

**Comment by iyukyo** [comment]
再現するか試してみたところ、魔道具支配の籠手をつけているかいないかは関係がなかった。
死神ももえに殴られる場合、魔法棒の残り回数が2~4だと毎回再現した。
数字が増えるのは見た目だけで、実際に使おうとしても使えない。

**Comment by dis-** [comment]
原因を特定しました。
後に参照するときのために条件を正確にしておきます。
「TR_MAGIC_MASTERYを保持している」「充填魔力吸収攻撃を受ける」「対象となる魔法道具の現在値が2以上かつ吸収量未満である」
