### ISSUE TITLE
【バグ】 毒針にエゴが付く

### ISSUE THREAD

**Issue by ironside777** [hengband/hengband#2470]
## 環境

- OS: [Windows ]
- バージョン: [3.0.0Alpha57]

## バグの詳細

毒針には通常、エゴが付かないと思われるが、
凍結の毒針 (1d1) (+11,+11) {r冷|凍}
が出現した。

## 期待される正常な動作

並の毒針のみ生成される。

## スクリーンショット
![dokubari](https://user-images.githubusercontent.com/79457166/161377796-d093c11a-55ee-43a3-a941-e241fac58f72.png)

**Comment by Hourier** [comment]
設計ミスでした
修正します
