### ISSUE TITLE
高確率で朦朧を急蓄積させるモンスターの打撃を修正する

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#249]
以前からはクトゥルフの落とし仔やケンシロウ、最近の追加ではヘルハウンドなどXd1やXd2でSUPERHURTやAC軽減なし打撃を持ったモンスターが接近戦時プレイヤーを高確率で朦朧を蓄積させ、最悪即不明瞭までもっていくケースが多すぎると判断。

これらを解決するために、モンスターの打撃に制約を加える（さらにいうなら問題のあるような設定がある場合r_info.txtに警告を発する）か、プレイヤーの朦朧蓄積ルールそのものを改善すべきと考える。必要ならDiscussionsに移行する。

**Comment by Hourier** [comment]
r_infoの方ではなくコード側の朦朧値蓄積ルーチンを緩和する方向で解決へ導くものとする
以降の進展は#533 にて対応する
