### ISSUE TITLE
【バグ】 ブレスが壁を貫通する

### ISSUE THREAD

**Issue by PoisonCorgi** [hengband/hengband#2491]
## 環境

- OS: Windows 版
- バージョン:3.0.0Alpha57（Apha58でも確認）

## バグの詳細

プレイヤーキャラクターに隣接しない壁に向かってブレスを発動すると壁で発生したダメージ範囲が壁を無視して壁の反対側にもダメージ、アイテム、森林地形破壊等の効果を及ぼす。
元素使い及び青魔道師の魔法、ドラコニアンのレイシャルパワー、ドラゴンの火炎の魔法棒で発生を確認。
隣接した壁にブレスを発動すると貫通が発生しない。モンスターのブレスでの発生は今のところ確認していない。

## 再現手順

1.＠に隣接していない壁に向かってブレスを発動する
2. バグが発生

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
[test.zip](https://github.com/hengband/hengband/files/8487057/test.zip)

## 期待される正常な動作

ダメージ範囲が壁で遮断される

## スクリーンショット
ウィザードモード使用、直前ターンで火炎のブレスを的の方向に吐いている。

![testst](https://user-images.githubusercontent.com/103628174/163336213-bde9e2d0-76d2-444c-b3a8-98cf2c44f2c3.png)

## 補足事項

補足事項があれば記載

**Comment by Slimebreath6078** [comment]
バグの原因が判明しました
修正は私が担当いたします
