### ISSUE TITLE
【バグ】 オプションか自動拾いをいじるとターン送りが遅くなる

### ISSUE THREAD

**Issue by knpn329** [hengband/hengband#2495]
## 環境

- OS: Windows11
- バージョン:3.0.0Alpha56

## バグの詳細
オプションか自動拾いに変更を加えて保存すると、以降のターン送りが遅くなる。
ダッシュや休憩が目に見えて遅くなり、特に広域マップでの移動がひどく処理落ちする。

## 再現？手順
再現できていない。
下記の手順で基本的に発生するが、稀に起きないことがある。

1.オプションか自動拾いを変更する。
2.保存してゲーム画面に戻る。
3.さらに1.と2.を2~3回繰り返す。

参考になるかわかりませんが、Hengbandフォルダを圧縮したものを添付します。
[hengbug.zip](https://github.com/hengband/hengband/files/8546790/hengbug.zip)

## 期待される正常な動作

設定変更後も遅くならない。

## 動画
https://youtu.be/omBIbzzAg7Q

**Comment by habu1010** [comment]
#3114 と同根と思われるのでクローズ。
再現動画を見ても、戦傷兵士を殴ってモンスターの思い出がサブウィンドウに表示されてから重くなっているようなので条件を満たす。
