### ISSUE TITLE
【バグ】 虚無召来による広範囲の破壊が発生しない

### ISSUE THREAD

**Issue by PoisonCorgi** [hengband/hengband#2500]
## 環境

- OS:  Windows 版
- バージョン: 3.0.0Alpha59

## バグの詳細

カオス領域呪文の虚無召来をダンジョンの壁に隣接した状態で詠唱した場合に665/666の確率で発生する広範囲の破壊が発生せず、「地面が揺れた。」のメッセージのみが表示される。1/666の確率の壁消失の発生については確認していない。

## 再現手順

1. 壁に隣接して虚無召来を詠唱する
2. 破壊が発生しない

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

[test.zip](https://github.com/hengband/hengband/files/8569677/test.zip)

## 期待される正常な動作

広範囲の破壊が発生する

## スクリーンショット
3.0.0Alpha59
![Alpha59](https://user-images.githubusercontent.com/103628174/165461170-965da908-712f-4821-a6a5-42e342b921f8.png)

安定版2.2.1r2
![2 2 1r2](https://user-images.githubusercontent.com/103628174/165461353-470ed41f-bae4-4fd5-be48-44d55a220ea2.png)

## 補足事項

補足事項があれば記載

**Comment by sikabane-works** [comment]
現象と原因確認しました。報告ありがとうございます。
