### ISSUE TITLE
【バグ】 修正値が同一で種類も同一の装備品が未鑑定状態でもまとまる場合がある

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#2509]
## 環境

- OS: [例: Windows 版]
- バージョン: [例: 3.0.0Alpha59]

## バグの詳細

修正値が同一の並品革グローブを2つ所持していると、未鑑定の状態でもザック内でまとまる。最新安定版では発生しない現象。

## 再現手順

・Hengband-3.0.0Alpha59-jp（バグの再現）
デバッグコマンドで革グローブを2つ生成
未鑑定の2つのグローブがまとまる
鑑定し修正値が同一の並品であることを確認する

なおロングソードについて同様の手順を踏んでみたところこちらは修正値が同一でも未鑑定状態ではまとまらなかった（革グローブにはバグがあるがロングソードは問題なし）

・hengband-2.2.1r2（正常な動作の再現）
デバッグコマンドで革グローブを2つ生成
未鑑定の2つのグローブはまとまっていない
鑑定し修正値が同一の並品であることが確認された時点でまとまる

ロングソードの場合も同様で問題なし

## 期待される正常な動作

修正値が同一で種類も同一の装備品の場合、鑑定して修正値が確認されるとまとまるが、未鑑定の状態ではまとまらない。

## 補足事項

「修正値が同一で種類も同一の装備品は、鑑定して修正値が確認されるまではまとまらない」が正しい仕様だと思っているためバグ報告しますが、もし違った場合はすみません。

**Comment by sikabane-works** [comment]
ありがとうございます。本日のチェックに含めるかわかりませんが余裕あればチェックします。
