### ISSUE TITLE
【仕様確認】暗黒免疫保有時の暗闇の巻物/杖使用の影響

### ISSUE THREAD

**Issue by hkudoh** [hengband/hengband#2524]
## 環境

- OS: Windows 10
- バージョン: 3.0.0Alpha60

## バグの詳細

吸血鬼で暗闇の巻物/杖使用時に盲目になります。
この振る舞いは仕様通りでしょうか。

関連？ #2370

## 再現手順

1. 種族:吸血鬼で、暗闇の巻物、杖を使用する
1. 盲目になる

## 期待される正常な動作

暗黒免疫があるので、盲目にならなそうに思えます

## スクリーンショット

N/A

## 補足事項

なし

**Comment by sikabane-works** [comment]
DARK_WEAK属性で盲目になるのは明白にエンバグです。修正します。
報告ありがとうございます。
