### ISSUE TITLE
【バグ】両手で構えるところ右手で構えたとメッセージされる

### ISSUE THREAD

**Issue by 16003** [hengband/hengband#2535]
## 環境

- OS: [Windows 版.]
- バージョン: [例: 3.0.0Alpha61]

## バグの詳細

両手持ち武器を持っているのに「右手で構えた」と表示される。

## 再現手順

ホビット盗賊、ショート・ソードと野太刀
右手に武器（ショート・ソード）を持った状態でさらに両手持ち武器（野太刀）を装備
「二刀流で戦いますか？」ｙ
右手に武器（ショート・ソード）、左手に両手持ち武器（野太刀）を装備した状態で、右手の武器（ショート・ソード）をはずす。
「野太刀を右手で構えた。」とメッセージされる。

装備一覧ウインドウは両手と表示しています。
セーブファイルは省略します、すみません

## 期待される正常な動作

「（両手持ち武器）を両手で構えた。」とメッセージする。

## スクリーンショット

省略します

## 補足事項

過去のバグ報告は確認していないためダブっていたら無視してください。
失礼しました。

**Comment by sikabane-works** [comment]
返事遅れてすみません。ありがとうございます。ダブりがあっても再チェックの対象にはすべきと思うので、よほどの乱発でなければ大丈夫です。どうぞ気兼ねなく今後とも報告お願いします。
