### ISSUE TITLE
確認 - セーブデータの宝物庫の報酬ID保存領域

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#254]
もしかしてbyteではないか？

**Comment by iks3** [comment]
fixed-map-generator.cのparse_qtw_QR()関数で報酬のIDをq_ptr->k_idxに入れて利用しています。
この変数がKIND_OBJECT_IDX型ですが、s16bのようですので、とりあえずbyteではないようです。

**Comment by dis-** [comment]
確認おつかれさまです。問題なさそうなので閉じます。
