### ISSUE TITLE
アリーナから出てくると乗っていないペットが消える

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#2547]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha61

## バグの詳細

アリーナから出てくると乗っていないペットが消える

## 再現手順

ペットを連れた状態でアリーナに入り、勝利し、出る

## 期待される正常な動作

クエスト受注などによるMAP再生成と同様にペットはそのまま残る

**Comment by dis-** [comment]
調査したところ、名前を付けていないペットは@に隣接しているもののみ、名前を付けているペットは半径3マスルールで付いてくるようです。
これは通常の帰還/マップ切替と同様であり仕様の範囲で正常動作であると判断します。
