### ISSUE TITLE
新規モンスター群の階層調整

### ISSUE THREAD

**Issue by Thujopsis** [hengband/hengband#255]
現Verの新規モンスター群はSUPERHURTや上級魔法の安売り状態で、
早い段階でスターバーストや暗黒の嵐、時間逆転のブレスを吐くモンスターが散在している。
これを一度精査し、能力にふさわしい適切な階層に配分しなおす必要があるものと思われる。

**Comment by Hourier** [comment]
開発者権限で却下します

1. SUPERHURT：SUPERHURTそれ自体の調整は現時点で予定しておりません。朦朧に関しては別方面で調整中です、詳細は#249 及び#553 を参照して下さい

1. スターバーストは『ボルドール』から確定で耐光が手に入ります。物資破壊もなく、POWERFULフラグがない限りはお手頃な中層レベルの魔法です。ここでいうスターバーストの使い手は30Fユニークである撲殺の天使を指していると思われますが、他の中～深層ユニークに比べれば一発芸です。POWERFULフラグもなく、魔法自体の確率も低く、無駄魔法も多いためです。また高級品ドロップ＋★ドロップでリスクに見合うリターンも用意しました。毒耐性・カオス耐性どちらが抜けても深刻な被害のある29F『ガチャピン』を上回る驚異にはなりません。なお『ガチャピン』は調整対象外です

1. 暗黒の嵐は何体か候補がいますが、『影のジャック』より低階層で、かつ彼よりも強烈な頻度で叩き込んでくるモンスターはいません。『クラウス』に至ってはFRIENDLY持ちなのでRQに出現せず、反攻や城で『ジャック』の前哨戦・試金石としてのみ機能するユニークです

1. 時間逆転のブレスは上位毒コボルドが該当すると思いますが、HP全開でも平均ダメージは42、きれものメイジマインドフレアでも耐えきれます。また確率も単純計算でターン当たり7.5% (＠が等速の場合)です。テストプレイで潜りましたが、1回も時間逆転ブレスは受けていません。フレーバー以上の役割はないということです。更に言えば『クァチル・ウタウス』は38F組から44F組に格上げしました。まさに能力にふさわしい適切な階層への再配分であると自負しております

以上により、頂いたご意見に基づく階層再配分の必要はないものと認めます
更なる調整の必要性があれば別途チケットを作成の上、開発チームまでご相談下さい
