### ISSUE TITLE
【バグ】 "The & Phial~ wells with clear light."

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#2555]
## 環境

- OS: macOS 12.4
- バージョン: 3.0.0Alpha62 compiled for English (up to date with develop branch changes as of 2022/6/30 and with macOS-specific changes from https://github.com/backwardsEric/hengband )

## バグの詳細

In the English version, activating the Phial of Galadriel gives this message "The & Phial~ wells with clear light.".  The message would be clearer and more immersive if it used the artifact name rather than the kind name.

## 再現手順

1. Uncompress the attached save file.
2. Load it into hengband.
3. Activate the equipped Phial of Galadriel.

## 期待される正常な動作

The message uses the artifact name rather than the kind name.  Perhaps use describe_flavor() to get the name for the activation message?

## 補足事項

The attached file is a save file compressed with zip where the character has the Phial of Galadriel equipped.

[Hadin.zip](https://github.com/hengband/hengband/files/9020159/Hadin.zip)

**Comment by habu1010** [comment]
アイテム発動時は「玻璃瓶から澄んだ光があふれ出た」のようにベースアイテム名のみを表示しようとするために k_info.txt のN:フィールド（英語版ではE:フィールド）の文字列をそのまま使用しており、英語版では接頭語や接尾語のプレースホルダである & や ~ が残ってしまっているようです。
一旦 `describe_flavor` を通したほうがよさそうですが、 `describe_flavor` 関数の `mode` 引数を見たところ、ベースアイテム名のみを得るように強制するオプションは現状なさそうなので、そのようなオプションを新設してベースアイテム名のみを引けるようにするか、特にベースアイテム名のみを表示することにこだわらないのであれば `mode` に `(OD_OMIT_PREFIX | OD_NAME_ONLY)` を指定して名称全体を表示（「★ガラドリエルの玻璃瓶から澄んだ光があふれでた」のようになる）するようにするのが良さそうです。
