### ISSUE TITLE
確認-赤魔の古い城報酬について

### ISSUE THREAD

**Issue by Thujopsis** [hengband/hengband#256]
★サンブレードを報酬とする会話が昔あったものと思われるが、
今はどのようになっているか一度確認をお願いしたい。

調整の結果不要と判断するならば閉じていただいて構いません。

**Comment by sikabane-works** [comment]
単純に忘れ切っとるだけのようです、今のうちにやっておきます。

**Comment by sikabane-works** [comment]
まだ古い城の報酬としては力不足ではないかという意見が。さらに強化の上設定するか。

> [81] ★カタナ『アグララング』 (8d4) (+0,+0) / The Katana 'Aglarang'
> +2の修正: 攻撃回数, 器用, スピード
> 武器属性: 切れ味
> 維持: 器用
> 階層: 50, 希少度: 25, 2.5 kg, $150000

> [252] ★グレート・ソード『サンブレード』 (3d6) (+16,+20) [+10] / The Two-Handed Sword 'Sun Blade'
> +3の修正: 知能
> 対: 邪悪, アンデッド
> 武器属性: 理力
> 麻痺知らず, 永久光源(半径1)
> 階層: 30, 希少度: 150, 9.0 kg, $65000

**Comment by iks3** [comment]
★サンブーレドを調整して古い城に入れたいと思います。

**Comment by sikabane-works** [comment]
課題終了したのでチケット完了します。
