### ISSUE TITLE
新規効果音の要望

### ISSUE THREAD

**Issue by multilockon123** [hengband/hengband#2567]
お疲れ様です。以下の効果音の実装を提案いたします。

・主人公の打撃音と、敵の打撃音を完全に分ける
・ミス以外の理由（恐怖、斬鉄剣が対応してない等）で打撃に失敗した音

**Comment by RL-Nadir** [comment]
便乗いたします
・壁を掘る(dig)に加えて、壁を彫り抜いた時の音
彫り抜くまで dig に定義した音が鳴り続けてうるさくなるため、分けたほうが良いのではないかと思いました。
