### ISSUE TITLE
【バグ】 松明の燃料残量が異様に大きな数値になる

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#2577]
## 環境

- OS: [Windows 版]
- バージョン: [3.0.0Alpha64]

## バグの詳細

特定の状況で、松明の燃料残量が異様に大きな数値になる

## 再現手順
・キャラクターを作成する
・証人クエに入り即階段を登り放棄
・松明を装備してターン送りし松明の燃料残量を90程度にする
・その松明を街のtに投げる
・死亡したtの足元に落ちた松明の燃料残量が、異様に大きな数値になる
（例:松明(4294967174ターンの寿命)(e)を拾った。）

ここで一度セーブして変愚を立ち上げ直すと、松明の燃料残量は正常な数値（0）に戻っているように見える

## 期待される正常な動作

松明の燃料残量は投げたときより増えることはないし、元々の上限値は超えないはず？

**Comment by habu1010** [comment]
PR #2197 の下記変更により、燃料が負の場合にゼロにする処理が消されたのが原因のようです。

- https://github.com/hengband/hengband/pull/2197/files#diff-ad5f895006ac15ea3a88e3e6bb2b593a91f10070fffc7f8472856f6b64bba5dcL74-L78

そもそも最初は fuel の型を ushort として定義していたため警告が出るようになったので消したようですが、後に光源のターン数がおかしくなる不具合が発生して fuel の型を short に戻したという経緯があるのでこの処理も復活させる必要があります。

**Comment by chikatei** [comment]
再度確認してみると、再現手順の
・証人クエに入り即階段を登り放棄
は不要な手順のようでした。クエストを経ずにtに松明をぶつけても再現します。もう解決しそうなので不要な情報かもしれませんが、一応訂正しておきます。
