### ISSUE TITLE
【バグ】 Visual Studio 2022 v17.3 でコンパイルエラーが発生する

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2581]
エラーメッセージ (一部省略)：
> .Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\memory(3386): message : クラス テンプレート メンバー関数 'std::unique_ptr<ObjectType [],std::default_delete<ObjectType []>>::~unique_ptr(void) noexcept' のコンパイル中 (ソース ファイルをコンパイルしています ..\..\src\world\world-turn-processor.cpp)
> .\src\store\store-util.h(49): message : コンパイル対象の クラス テンプレート インスタンス化 'std::unique_ptr<ObjectType [],std::default_delete<ObjectType []>>' のリファレンスを確認してください (ソース ファイルをコンパイルしています ..\..\src\world\world-turn-processor.cpp)
> .\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\memory(3154,25): error C2338: static_assert failed: 'can't delete an incomplete type' (ソース ファイルをコンパイルしています ..\..\src\world\world-turn-processor.cpp)
> .\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\memory(3155,9): warning C4150: 'ObjectType' 型を削除するため delete 演算子が呼び出されましたが、定義がありません。 (ソース ファイルをコンパイルしています ..\..\src\world\world-turn-processor.cpp)
> .\src\system\player-type-definition.h(25): message : 'ObjectType' の宣言を確認してください (ソース ファイルをコンパイルしています ..\..\src\world\world-turn-processor.cpp)

VSのバージョンは17.3 のまま、cba2763ac まで巻き戻してコンパイルしてもエラーが出るので、VS側のチェックが厳しくなったものと思われる

以下のフィールド変数定義が原因らしい：
> src/store/store-util.h:49:    std::unique_ptr\<ObjectType[]\> stock{};

明示的にstore\_type やObjectType のデストラクタを宣言してみたが、同様の結果だった

更に、以下のように変更し、見た目のコンパイルエラーが出なくなるように調整したが、同様の結果だった：
> std::vector\<std::unique_ptr\<ObjectType\>\> stock{};

参考資料 (noexcept云々と直接の関係はないはずだが、一応)：
https://docs.microsoft.com/ja-jp/cpp/error-messages/compiler-errors-1/compiler-error-c2338?view=msvc-170

> 標準 C++11 以降では、constexpr 関数が定数式で使用される場合、既定では noexcept と見なされなくなりました。
> この動作変更は、Core Working Group (CWG) [CWG 1351](https://wg21.link/cwg1351) の解決によるものであり、[/permissive-](https://docs.microsoft.com/ja-jp/cpp/build/reference/permissive-standards-conformance?view=msvc-170) モードで有効になります。

**Comment by habu1010** [comment]
いろいろ試して見ましたが、どうやら stock メンバを宣言の中で初期化すると `std::unique_ptr<ObjectType[]>` をインライン展開するため、その時点でObjectType型が不完全型なのでコンパイルエラーになるようです。（これまで大丈夫だった理由についての詳細は不明）
とりあえず解決策として、stock{} の {} を削除すればインライン展開されなくなるのでコンパイルエラーにはならなくなるようです。

**Comment by Hourier** [comment]
確認ありがとうございました
それでは上記内容にて修正してPR出します
