### ISSUE TITLE
Supporting English version

### ISSUE THREAD

**Issue by EvidentlyCube** [hengband/hengband#2591]
I love the effort of continued Hengband development and I'd like to help with keeping the site, repo and game accessible to English speakers. I don't know Japanese so my translations would require excessive use of Google Translate, but it should be more than enough for most cases.

So if you're interested I'll start by translating the current version of readme to English as a starting point and then if you're happy with that I'll pick up the next thing.

The reason I am asking before doing anything is I'd rather avoid making a PR with translations if you already have someone working on it internally.

(And I just wanted to notice that the discord invite on the website is no longer working)

**Comment by sikabane-works** [comment]
Hello. It is a very welcome offer.
I feel that English support for the site and manuals was lacking, including internationalization support in more popular libraries, for example vue.js.
If you send translations by any methods, I merge and try to use it effectively. Thank you in advance.

**Comment by Hourier** [comment]
@EvidentlyCube Here is the new link to join us.
We welcome you!
https://discord.gg/fGNt7WeDFQ

**Comment by Hourier** [comment]
Already he came to the Discord channel, I close this case.
