### ISSUE TITLE
【バグ】 公式ページのdiscordサーバーへの招待リンクが無効になっている

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#2592]
## バグの詳細

変愚蛮怒の公式webページのコミュニティのページに貼られているdiscordサーバーへの招待のリンクが無効になっている。spoiler wikiに貼られているdiscordへの招待は有効

## 期待される正常な動作

本来期待される正常な動作を記載

## 補足事項

https://github.com/hengband/hengband/issues/2591

こちらで報告されているとおり

**Comment by sikabane-works** [comment]
すみません、はよやっておきます。

**Comment by sikabane-works** [comment]
こちらで済ませました。クローズします。
