### ISSUE TITLE
座標を表すクラスを作る

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2621]
「POSITION y, POSITION x」が多すぎる
引数の値を変えている箇所もあるのでリファクタリングが困難
ほぼ確実にセットで使うのでクラス化するだけで全然違うと思われる
……が少なくとも600組検索に引っかかるのでいつやるかは別途検討

**Comment by habu1010** [comment]
あまり使われていませんが、2次元座標をまとめるだけのクラスであれば `util/point-2d.h` に

```c++
template <typename T>
struct Point2D;

using Pos2D = Point2D<POSITION>;
```

があります。

**Comment by Hourier** [comment]
本件ですが、Point2DをBaseitemKeyのようにイミュータブルクラスとして発展的に再定義したいと考えています
少し別件で、座標は常にPOSITION (int)で定義されているので、敢えて他の型も使えるようにテンプレート化せずに使いたいです
問題ないでしょうか？
(前者はともかく後者はusing宣言されてるので使い勝手がそこまで悪いとも言いにくいですが……)

**Comment by Hourier** [comment]
どちらかというとPOSITION 型エイリアスに問題があるという方針にまとまったので本チケットはクローズ
状況に応じて再開する (POSITION の使用箇所は1000を超えるので何年後になるかは不明)
