### ISSUE TITLE
ArtifactTypeをラップしたクラスに、再老番のアーティファクトIDを返すメソッドを作る

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2625]
固定アーティファクトIDリストには歯抜けがあるので、mapの個数と最老番IDが一致しない
以下のコードで実現可能なのでオブジェクトメソッドとして再定義する
a\_info.txt においてIDが昇順で並んでいなくても対応できる
(今は仕方なくコピペ中)

```cpp
    std::vector<short> a_nums;
    for (const auto &[a_idx, a_ref] : a_info) {
        a_nums.push_back(enum2i(a_idx));
    }

    auto max_a_idx = *max_element(a_nums.begin(), a_nums.end());
    return i2enum<FixedArtifactId>(max_a_idx);
```

**Comment by habu1010** [comment]
mapのキーは昇順で並んでいるので最後尾が最大値です。

```c++
return a_info.rbegin()->first;
```

で定数時間で処理できます。(前提条件: `!a_info.empty()`)

**Comment by Hourier** [comment]
昇順で並ぶことが保証できるのは大きいですね
使用箇所は全てa\_info.txt を読み込んだ後なので遠慮なく使えそうです
まずは今ある構文を書き換えておきます (まだラップしたクラスがないので呼び出し側で直接呼んでます)

**Comment by Hourier** [comment]
a_info.txt の中身において番号が入れ違いになる事態は基本的にない(あってもレビューで弾ける)ので、現状はrbgin() を呼ぶ方針でラッピング設計を考えます
