### ISSUE TITLE
Windows版リリースビルドスクリプトにエラーが起きてBGMが追加されない。

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#2663]
以下のエラーで、途中で中断されるためと思われる。サブモジュール化が原因か。要修正。

> Remove-Item : 項目 C:\Users\deskull\AppData\Local\Temp\tmp2050.tmp\Hengband-3.0.0Alpha67-en\lib\xtra\.git を削除できま
> せん: この操作を実行するために十分なアクセス権がありません。
> 発生場所 C:\Users\deskull\Documents\hengband\Build-Windows-Release-Package.ps1:40 文字:119
> + ... hildItem $_ -File -Recurse | Remove-Item; $_ } | Remove-Item -Recurse
> +                                                      ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (.git:FileInfo) [Remove-Item], IOException
>     + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
> Remove-Item : ディレクトリ C:\Users\deskull\AppData\Local\Temp\tmp2050.tmp\Hengband-3.0.0Alpha67-en\lib\xtra は空ではな
> いため、削除できません。
> 発生場所 C:\Users\deskull\Documents\hengband\Build-Windows-Release-Package.ps1:40 文字:119
> + ... hildItem $_ -File -Recurse | Remove-Item; $_ } | Remove-Item -Recurse
> +                                                      ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (xtra:DirectoryInfo) [Remove-Item], IOException
>     + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand
> 
> Remove-Item : ディレクトリ C:\Users\deskull\AppData\Local\Temp\tmp2050.tmp\Hengband-3.0.0Alpha67-en\lib は空ではないた
> め、削除できません。
> 発生場所 C:\Users\deskull\Documents\hengband\Build-Windows-Release-Package.ps1:40 文字:119
> + ... hildItem $_ -File -Recurse | Remove-Item; $_ } | Remove-Item -Recurse
> +                                                      ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (lib:DirectoryInfo) [Remove-Item], IOException
>     + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand
> 
> Remove-Item : ディレクトリ C:\Users\deskull\AppData\Local\Temp\tmp2050.tmp\Hengband-3.0.0Alpha67-en は空ではないため、
> 削除できません。
> 発生場所 C:\Users\deskull\Documents\hengband\Build-Windows-Release-Package.ps1:40 文字:119
> + ... hildItem $_ -File -Recurse | Remove-Item; $_ } | Remove-Item -Recurse
> +                                                      ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (Hengband-3.0.0Alpha67-en:DirectoryInfo) [Remove-Item], IOException
>     + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand
> 
> Remove-Item : ディレクトリ C:\Users\deskull\AppData\Local\Temp\tmp2050.tmp は空ではないため、削除できません。
> 発生場所 C:\Users\deskull\Documents\hengband\Build-Windows-Release-Package.ps1:40 文字:119
> + ... hildItem $_ -File -Recurse | Remove-Item; $_ } | Remove-Item -Recurse
> +                                                      ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (C:\Users\deskul...emp\tmp2050.tmp:DirectoryInfo) [Remove-Item], IOException
>     + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by Hourier** [comment]
バグ？ の割には約2ヶ月放置されてしまっています (しかもNext Sprintのままなので「α67～68？ に入れるはずだった修正が入っていない」というあまり良くないステータス)
優先度は高くすべきか低くすべきかの2択と思いますが、どちらでしょうか？

**Comment by sikabane-works** [comment]
毎回手動で突っ込みなおしてすませてしまっていたので、なんか忘れてました。今回も手動でやって、次回に回します。
