### ISSUE TITLE
【バグ】 暗黒耐性及び盲目耐性抜けで暗黒属性攻撃を受けても盲目にならない

### ISSUE THREAD

**Issue by PoisonCorgi** [hengband/hengband#2668]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha67

## バグの詳細

表題の通り
閃光属性については耐性抜けで攻撃を受けると盲目になる

## 再現手順
暗黒・盲目耐性抜けで暗黒属性攻撃を受ける

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
[test.zip](https://github.com/hengband/hengband/files/9645849/test.zip)

## 期待される正常な動作

耐性抜けで暗黒攻撃を受けた場合盲目になる

**Comment by Hourier** [comment]
ご報告ありがとうございます
昔「耐性があっても盲目になる」という不具合がありましたが、多分条件を緩めすぎて今回の事象が起きたものと思われます
修正しますのでしばらくお待ち下さい
