### ISSUE TITLE
PlayerType::dungeon_idx とfloor_type::dungeon_idx の多重実装

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2713]
なぜなのか
設計レベルの潜在バグと思われる
(PlayerTypeがでかすぎるのと、「プレイヤーがどのダンジョンにいるか」より「ここはどこか」の方がそれっぽいのでfloor\_type にいて欲しい)

多重実装された経緯が不明瞭なので、その時期の作業内容をご存じの方、対応頂けるとありがたいです

**Comment by sikabane-works** [comment]
1.7.0くらいの頃のソース見直すとdungeon_typeとかいうグローバル変数（怨）で一律管理していたのを、私がリファクタリングしてた頃に何か処理の流れ上止むからずか、あるいは全く思考停止して切り分けてしまった可能性ですかね。せっかくですし触ってみます。

**Comment by sikabane-works** [comment]
do_cmd_go_down()あたりがどうもフロア生成前にplayer_ptrでdungeon_idx持たせておかないと次のダンジョンのID受け渡せないって事情があったようですが、それこそフロア生成のprepare_change_floor_mode()あたりで引き渡せばいいんでねえの？と思えてきた。

**Comment by Hourier** [comment]
FloorTypeに「dungeon\_idとfoor\_idの組み合わせを表す構造体を作る」
そして「それを引数に取り次のフロアを表すdungeon\_typeかwild\_typeのvariantを返す関数を作る」でいい感じに解決しそう？　な気がします
コードを見てないのでテキトーこいてるかもしれませんがご検討下さい

**Comment by sikabane-works** [comment]
もっとシンプルに関数の受け渡しで何とかならないかとか、馬鹿馬鹿で既に適用済（かつ比較的安定した）フロア更新処理の改変もあるので、そちらの意見も含めつつなんか考えてみます。とりあえずDraftでは手を付けやすい所から順に整理する所存。

**Comment by Hourier** [comment]
本件引き取ります
