### ISSUE TITLE
【バグ】 A setgid installation doesn't put the files in lib/edit/towns in the right place

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#2731]
## 環境

- OS: Linux X11 (Debian 11)
- バージョン: 3.0.0Alpha69 with the changes up to https://github.com/hengband/hengband/pull/2730

## バグの詳細

Configuring, building, and installing a version with setgid does not create lib/edit/towns within the installation directories and puts the files from lib/edit/towns directly in the installed version of lib/edit rather than in subdirectory, towns, of that directory.

## 再現手順

1. clone git repository
2. Change directory to the top-level directory of the repository.
3. Run ```./bootstrap```
4. Run ```./configure --prefix=/var/tmp/hengband-alpha --with-setgid=games --disable-worldscore```
5. Run ```make```
6. Use the preferred method to become a super-user (su, sudo, ...) and run ```make install```
7. Run ```diff -r lib/edit /var/tmp/hengband-alpha/share/games/hengband/lib/edit``` to compare the installed contents of lib/edit to what's in the source directories.

On my system, step 7 reports

Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/01_Outpost_Full.txt
Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/01_Outpost_Lite.txt
Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/02_Telmora.txt
Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/03_Morivant.txt
Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/04_Angwil.txt
Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/05_Zul.txt
Only in /var/tmp/hengband-alpha/share/games/hengband/lib/edit/06_Rlyeh_Obsoleted.txt
Only in lib/edit/Makefile
Only in lib/edit/Makefile.am
Only in lib/edit/Makefile.in
Only in lib/edit/towns

## 期待される正常な動作

The installed version of lib/edit keeps the same structure, excepting the Makefiles, as in the source files.

## 補足事項

There's at least one other issue with a setgid installation (when I try to run the installed executable it reports ```./hengband: Cannot create '~/.angband/Hengband/'```; I do happen to already have a directory, .angband/Hengband in my home directory), but I'm interested in the installed layout because the macOS version uses the same logic to install the files into the macOS application.

**Comment by habu1010** [comment]
I tried on Ubuntu 20.04 on WSL2 with the configure options specified above, but it went to read '${prefix}/share/games/hengband/lib/file/news_j.txt' at startup and could not start.
Looking at src/autoconf.h

```
#define DEFAULT_LIB_PATH "${prefix}/share/games/hengband/lib/"
```

and it seems to be because ${prefix} is not correctly expanded.
Is there any particular problem in Debian 11 environment?

At any rate, I was able to confirm that by changing `$datadir` to `$datarootdir` in configure.ac, the files under towns/ are correctly extracted and installed in the correct location.

**Comment by backwardsEric** [comment]
I saw the same error you saw (the error I mentioned about cannot create ~/.angband/Hengband was when configured with --disable-japanese).  With your change to use $datarootdir in configure.ac, the game reaches the splash screen and can proceed through character generation, but bails out when leaving character generation with the message shown in the attached screenshot.  The contents of /var/tmp/hengband-alpha/share/games/hengband/lib/edit are

01_Outpost_Full.txt 01_Outpost_Lite.txt 01_Outpost_OnlyAngband.txt 02_Telmora.txt
03_Morivant.txt 04_Angwil.txt 05_Zul.txt 06_Rlyeh_Obsoleted.txt
ArtifactDefinitions.txt BaseItemDefinitions.txt ClassMagicDefinitions.txt ClassSkillDefinitions.txt
DungeonDefinitions.txt EgoDefinitions.txt misc.txt MonsterRaceDefinitions.txt
q0000001.txt q0000002.txt q0000003.txt q0000004.txt q0000005.txt
q0000006.txt q0000007.txt q0000019.txt q0000020.txt q0000021.txt
q0000022.txt q0000023.txt q0000027.txt q0000028.txt q00000ms.txt
q000chao.txt q000dekn.txt q000eric.txt q000natu.txt q000sorc.txt
q00water.txt q0clone0.txt q0dumpwitness.txt q0fields.txt q0thief1.txt
q0thief2.txt q0willow.txt qdarkelf.txt qhaunted.txt q_oberon.txt q_pref.txt
q_random.txt q_serpen.txt QuestDefinitionList.txt q_warg.txt
TerrainDefinitions.txt TownDefinitionList.txt TownPreferences.txt
VaultDefinitions.txt WildernessDefinition.txt

Note that there is no towns subdirectory there, and the town files are directly in /var/tmp/hengband-alpha/share/games/hengband/lib/edit .

The versions of automake, autoconf, and install are the versions packaged with Debian and are automake 1.16.3, autoconf 2.69, and install (GNU coreutils) 8.32.  The part of lib/edit/Makefile (generated by automake and the configure script from lib/edit/Makefile.am) that installs the files for the setgid build looks like

```
install-angbandDATA: $(angband_DATA)
        @$(NORMAL_INSTALL)
        @list='$(angband_DATA)'; test -n "$(angbanddir)" || list=; \
        if test -n "$$list"; then \
          echo " $(MKDIR_P) '$(DESTDIR)$(angbanddir)'"; \
          $(MKDIR_P) "$(DESTDIR)$(angbanddir)" || exit 1; \
        fi; \
        for p in $$list; do \
          if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
          echo "$$d$$p"; \
        done | $(am__base_list) | \
        while read files; do \
          echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(angbanddir)'"; \
          $(INSTALL_DATA) $$files "$(DESTDIR)$(angbanddir)" || exit $$?; \
        done
```

![Hengband-towns-problem](https://user-images.githubusercontent.com/55062581/198507205-8dcfa065-9c79-4907-8c21-a022f099be3c.png)

**Comment by habu1010** [comment]
> 
> At any rate, I was able to confirm that by changing `$datadir` to `$datarootdir` in configure.ac, DEFAULT_LIB_PATH is correctly extracted and the files under towns/ are installed in the correct location.

This is what I meant when I applied PR #2733.
My point was that even if we apply PR #2733, we may not be able to successfully launch the game when we use the `--with-setgid=games` option in configure.
I think this should also be fixed, but do you have any better suggestions besides changing $datadir to $datarootdir in configure.ac?

**Comment by backwardsEric** [comment]
With your $datadir to $datarootdir change in configure.ac and https://github.com/hengband/hengband/pull/2733 , a build with "--disable-japanese --with-setgid=games --disable-worldscore" (the last is just there because I haven't installed libcurl in the Debian environment) installs and runs well as far as a quick test could exercise (could get through character generation, enter Outpost, visit all the stores, enter and fail a quest, enter and leave Yeek's den, use all the knowledge menu items, save and then reload the save, die and quickstart to see that high score file updates).  So I don't have any other suggestions about the setgid build.

**Comment by habu1010** [comment]
Understood.
I will merge #2733 once and create another PR to modify configure.ac.
