### ISSUE TITLE
デバッグモードにおけるアイテム任意取得ルーチンの改善

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2779]
#2745 の作業過程で、「tvalごとのsvalリスト」を作ったが、svalリストが一番多かったのが薬だった
ちょうど62個 (AlphaNumericの数：10 + 26 + 26 = 62)であり、これ以上薬を増やすと増分についてデバッグ生成できなくなる
次にアイテム実装依頼が来たら、番号指定する方式に変える必要がある
(担当者は別途調整)

**Comment by habu1010** [comment]
述べられているような処理として、固定アーティファクトを生成するデバッグコマンド（`^a C`）で必要ならページネーションを挟みつつ候補から選択する関数 wiz_select_named_artifact があります。
必要になるたびに一つ一つ再実装するのも面倒ですし、この関数をベースにもうすこし汎用的な関数を実装して、色々な候補のリストから選べるようにするのがベターかと思います。

インターフェース案：
```c++
// [first, last) で与えられたイテレータ範囲の指す要素から選択する
// msg: 最上行に表示するプロンプトメッセージ
// candidate_name: 要素から候補の名称を生成するコールバック関数
// start_x: それぞれの候補名の表示を開始するx座標
// max_per_page: 1ページあたりに表示する最大候補数
// 
// 選択した要素を指すイテレータを返す、キャンセルした場合 std::nullopt を返す
template <typename InIter>
std::optional<InIter> select_from_candidates(InIter first, InIter last, std::string_view msg, std::function<std::string(InIter::value_type)> candidate_name, int start_x, size_t max_per_page)
```
