### ISSUE TITLE
【QoL向上】魔法書のアイテム名先頭にLv値を表示する

### ISSUE THREAD

**Issue by arumons** [hengband/hengband#2785]
# やりたいこと
ダンジョンで魔法書がドロップした際、金策のために拾うべきか（高レベルの魔法書かどうか）、
スルーで良いかをwikiを見てチェックしているのですが、魔法書名の先頭にLvを表示することで
判断がスムーズになるのではと思いました。

# 実装イメージ
下のような表示になるイメージです
![スクリーンショット](https://user-images.githubusercontent.com/555232/201485279-42db31c1-04cc-457f-8748-4dfc46cf73b5.png)

**Comment by Hourier** [comment]
確かにどれが何冊目かは分かりづらい部分もあり、ましてやプレイヤーに暗記させるほどの価値はないので、リポジトリレベルでの修正は歓迎です
(自動拾いでも何とかなりますが、システム側で対応すべき)

**Comment by arumons** [comment]
確認ありがとうございます
ではpull reqだしますー
