### ISSUE TITLE
VS 2022 v17.4 で追加された警告への対策

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#2786]
C5262、C5263、C5264 がVS 2022 v17.4 で警告に追加されました
主にgamevalue.h 等の、広範に呼び出されうる定数類がcpp側で呼びされないと警告になるようです
変愚蛮怒の設計的に、特にC5264は抑制したいです
(というか、「a.h で定義された定数を、a.h をインクルードする全cppで使う」と、一般的に言ってアボカドバナナとな要求を満たす必要があるので、なんでこんな警告が定義されているのかは不明)

C5262は、switch/case文のfallthroughに関する警告なので、これは対応すべきと思われます
(clangとフラグの付け方が違うのでちょっと気持ち悪いですが、関数分割でそもそもfallthroughしなくて良いように書き換えたい)

C5263は、std::move に関するもので、α70時点のソースコードでは出ていません

[既定で無効になっているコンパイラ警告](https://learn.microsoft.com/ja-jp/cpp/preprocessor/compiler-warnings-that-are-off-by-default?view=msvc-170)

**Comment by habu1010** [comment]
C5262について、現在のソースコードにある `/* Fall through */` コメントは gcc/clangのswitch caseの暗黙のfallthroughの警告を抑止するものですが、C++17 から追加された [[fallthrough]] 属性があるので、fallthroughコメントをこれで置き換えれば対応できそうです。
https://cpprefjp.github.io/lang/cpp17/fallthrough.html

**Comment by habu1010** [comment]
上記2つの PR で C5262、C5264 に対応。
STLへの修正が入り次第クローズしてよいかと思います。

**Comment by Hourier** [comment]
STL への修正がもうVS に入っているのでクローズします
