### ISSUE TITLE
【QoL向上】視界内のモンスター一覧表示に起きているモンスターの数を追加する

### ISSUE THREAD

**Issue by arumons** [hengband/hengband#2796]
# やりたいこと
視界内のモンスター一覧で起きているモンスターの数を確認できるようにしたい

# 実装案
# 表示
↓のようにモンスターの数に続いて `(覚 起きている数)` を表示するイメージです　
![スクリーンショット](https://user-images.githubusercontent.com/555232/201535845-b290ef63-95d6-4f16-b1d5-2b5bd0ad2080.png)

# 実装詳細
モンスター一覧を表示する `print_monster_list` 関数で、それぞれのモンスターに対して `is_asleep()` を呼び出し、起きている数を集計する。
その数を `print_monster_line` に渡して画面に出力する

**Comment by Hourier** [comment]
仕様確認しました
これを追加してもスポイラー的に情報が増えることはなさそうです
(今でも眠っているモンスターはlで調べた時にHPバーが青く表示されるので)

作業開始お願いします
(といっても見た目は実装済だしPR出すだけ？)

**Comment by arumons** [comment]
確認ありがとうございます
ではpull req出しますね

**Comment by arumons** [comment]
pull reqがマージされたのでcloseします
