### ISSUE TITLE
サブモジュールを交えたhengbandの開発導入方法をマークダウンやWebサイトにまとめる

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#2799]
分かりづらいという話を受けたので。

**Comment by Hourier** [comment]
こちらで実験済につき、私の方でまずはWikiの開発指針に書いておきます (PR不要なので作業フロー的には楽ちん)
その上でreadme等にWikiへのリンクが必要であれば追加してもらえると助かります

**Comment by sikabane-works** [comment]
了解。

**Comment by sikabane-works** [comment]
ありがとうございます。そもそもこのWikiのページを公式Webにリンク張ることを持って本件完了とします。

**Comment by sikabane-works** [comment]
https://github.com/hengband/hengband.github.io/pull/70
Webに更新かけました。
https://hengband.github.io/development.html
時間差あると思いますがすぐ反映されます。完了とします。
