### ISSUE TITLE
自動生成スポイラーを出力するコマンドラインオプション

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#28]
現在、ゲーム中にデバッグ/詐欺オプションを有効にして、デバッグコマンド`^a`→`"`キーで出力できるスポイラーファイルを、`hengband --output-spoiler` のような感じでコマンドラインオプションを与えることで出力できるようにしたい。

この機能があれば、どこかに最新のスポイラーファイルを自動的にアップロードするなどの機能も実現できそう。

とりあえず指定したファイル名で指定したスポイラーファイルを出力する関数を作って、後はプラットフォーム毎にコマンドラインオプションを解析してそれを呼ぶようにする感じか。

**Comment by taotao54321** [comment]
Windows には疎いのですが、`main()` から `WinMain()` を呼ぶ方式は今は使えないのでしょうか?
エントリポイントを統一しておけば重複コードを書かずに済むのかなと思いました。

**Comment by habu1010** [comment]
Windows版では #152 で実装された。
Windows版以外は基本的に main.c がエントリポイントだと思うので、そこを対応させればよさそう。
（Mac App版とかは分からない）

**Comment by habu1010** [comment]
Windows/UNIX系環境で実装されたので、ひとまず完了とする。
