### ISSUE TITLE
[Fix] FLAG_CAUSE_* がビット位置でなく即値として扱われている

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#280]
#273 のレビューから分離。

>FLAG_CAUSE_* がビット位置でなく即値として扱われているコードが他にもあるようです。例えば:
>
>https://github.com/hengband/hengband/blob/be9e5d6a03b8bd90b4af8cc192ffb8ac587029f3/src/player/player-status-flags.c#L691-L692
>
>そこそこ量が多いので別件として扱ってもよいかと思いますが、一応ご報告まで。

**Comment by sikabane-works** [comment]
これは私が戦犯ですねえ、申し訳ない。まず即値になっているものを論理和に直してから、所定のリファクタリングしてもらう方がいいかもしれませんね。
