### ISSUE TITLE
【QoL向上】現在のフロアで発見済みの床落ちアイテム一覧サブウィンドウを実装

### ISSUE THREAD

**Issue by arumons** [hengband/hengband#2802]
# やりたいこと
今いるフロアで視界に入れたアイテムの一覧を表示できるサブウィンドウを追加したい

# 実装概要
# 表示項目
- アイテムシンボル
- アイテム名
- アイテム座標
- Inventoryと同じ順でソートして表示する

表示例
![スクリーンショット_20221115_035634](https://user-images.githubusercontent.com/555232/201743076-7bfb49d3-61f3-4012-9150-5fd12aecde64.png)

# 実装案
`床上のアイテム一覧` サブウィンドウの実装をベースにして
リストアップの対象を ` floor_ptr->o_list` の中から o_ptr->marked & OM_FOUND` のフラグが立っているアイテムを対象にすればできそう

**Comment by Hourier** [comment]
これは是非やって頂きたいです！
ただ気になるのがObjectTypeの取り扱いで、昔ながらのビットフラグ様になっていることです
もしかすると先にEnumFlagsへの改定を行った方がスムーズかもしれません
EnumFlagsの話は長いので、詳細はDiscordでお話します

(o\_list もめんどくさい仕様を抱えているので、「先にどれをやるか」は別途相談で)

**Comment by Hourier** [comment]
調査結果：
- ObjectType::marked は、先にEnumFlags へ改定した方がベター (誰がやるかはDiscordで要相談)
- o\_list は、ひとまず触らなくてOK

**Comment by arumons** [comment]
> ただ気になるのがObjectTypeの取り扱いで、昔ながらのビットフラグ様になっていることです
もしかすると先にEnumFlagsへの改定を行った方がスムーズかもしれません
EnumFlagsの話は長いので、詳細はDiscordでお話します

了解です〜

**Comment by arumons** [comment]
EnumFlagsについてdiscordで話している箇所
https://discord.com/channels/724811119545417790/804318964121468958/1042038147346878484

**Comment by arumons** [comment]
pull reqがマージされたのでclose
