### ISSUE TITLE
【QoL向上】ターゲットしているモンスターの画面に出す情報を追加

### ISSUE THREAD

**Issue by arumons** [hengband/hengband#2825]
# やりたいこと
画面左に表示している選択しているモンスターの情報部に↓の情報を追加したい

## 今出している情報
- 残りHP（割合）
- バーの色で瀕死度（緑、黄色、オレンジ、赤）、無敵（白）、起きているかどうか（青）、恐怖状態（紫）かを表示

## 追加したい項目
- モンスター名（幅に収まらないときは途中で切る）
- 下記状態の時にテキスト|色で表示（騎乗しているモンスターに対しては表示しない）
  - 無敵|TERM_WHITE
  - 加速|TERM_L_GREEN or 減速|TERM_UMBER
  - 恐怖|TERM_SLATE
  - 混乱|TERM_L_UMBER
  - 睡眠
  - 朦朧|TERM_ORANGE

## 項目を追加したい理由
- ゲームに慣れていない状態だとモンスター名が出ていないのでHPの割合を示していることがわかりづらい
- バフ、状態異常のときにゲージの色しか変わらないので、どの色がどういう状態を表しているのかわかりづらい
- 無敵や恐怖の時は色を変えているが、混乱やスタンでは色をかえていないので一貫性が無い
 
## 実装イメージ
![スクリーンショット](https://user-images.githubusercontent.com/555232/204131578-9b4cc90a-9356-44b6-b9bc-8565810dc200.png)

**Comment by Hourier** [comment]
是非実施頂きたいです
一方で、MonsterEntityの該当設計を生配列からmapに変える計画があります
本件実施の目処としては次々回のαになりそうですが問題ないでしょうか？

**Comment by arumons** [comment]
> 本件実施の目処としては次々回のαになりそうですが問題ないでしょうか？

了解です
現時点の実装で進めれそうなところは今から進めようと思います～

**Comment by Hourier** [comment]
よろしくお願いします
それとは別に仕様面でコメントです
(思い出表記に揃える旨)
- スタンは「朦朧」の方がベター
- 鈍足は「減速」の方がベター
- 色分け

**Comment by arumons** [comment]
> 
    スタンは「朦朧」の方がベター
    鈍足は「減速」の方がベター
    色分け

了解ですー

ちなみに↓状態異常時の挙動ってどこかにドキュメントがあったりしますでしょうか？（ヘルプを見ても見つからなかったので）
無さそうならソース見て挙動をヘルプかスポイラーにまとめようと思います（というか自分が知りたい）
- 無敵
- 恐怖
- 混乱
- 朦朧

**Comment by Hourier** [comment]
モンスターの状態異常についてはハッキリとしたドキュメントが整備されているか不明瞭です
但し、昔deskullさんがブログに何かスポイラー記事を残していた可能性はあります
後ほど聞いてみて下さい

**Comment by sikabane-works** [comment]
ちょっと自分の記事検索かけてみましたがすぐには見つかりませんでしたね。
http://sikabane-works.net/monzetsu_diary/?category=%E5%A4%89%E6%84%9A%E8%9B%AE%E6%80%92%2F%E3%82%B9%E3%83%9D%E3%82%A4%E3%83%A9%E3%83%BC
遠いこととはいえ書いた記憶はない気がします。

**Comment by Hourier** [comment]
残念、確認ありがとうございました
朦朧は確率1/2で色々キャンセルされるとか読んだ記憶があるのですが、どこかのスポイラーですかね
これを機に仕様化する方針で進めましょう

**Comment by arumons** [comment]
このissue、実装を始めているのですが、騎乗中のモンスターの表示をどうするか相談したいです（自分、アーチャーしかやったことが無いのでどの仕様だと騎兵/魔獣使いにとって助かるかを知りたい）

・従来と変えずにHP割合だけ出す
・追加で名前も出すようにする
・ターゲットしているモンスターと同様に状態異常も表示するようにすうる

**Comment by daradarach** [comment]
騎兵だと騎乗伸びてくれば馬の状態異常治しちゃうからあんまり気にならないしHPだけあればいい気がしますが騎兵魔獣使いは3勝しかしてないので詳しい方のご意見待ち

**Comment by arumons** [comment]
今のところこんな感じ
![Uploading スクリーンショット.png…]()

**Comment by iyukyo** [comment]
・騎乗職は熟練度が上がると乗騎の悪い状態異常を勝手に治してくれる
・良い状態異常は残るが、無敵はHPバーが白くなり、加速は乗っている＠本人の加速が上がることでわかる（他に良い状態異常があるだろうか）
仕様を知らない初心者が乗騎が無敵であるかないかを知りたいと思うことがあるなら文字で表示する意味があるかもしれない

**Comment by arumons** [comment]
情報ありがとうございます
一旦騎乗中のモンスターの情報は
`名前表示 + 従来のHPバー` （↑に張った画像の内容）

で実装しようと思いますー
