### ISSUE TITLE
【バグ】 Apple's clang 14.0.0:  deprecation warnings for sprintf()

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#2858]
## 環境

- OS: MacOS
- バージョン: 3.0.0Alpha71

## バグの詳細

The most recent release  of Apple's version of clang (14.0.0) issues deprecation warnings for sprintf().  A build with that compiler using "./bootstrap; ./configure --disable-worldscore --disable-pch; make" will display those warnings.

## 再現手順

These steps run with the Alpha71 source code on MacOS 12.6.1 with Apple's clang 14.0.0 (from Xcode 14.1) show the deprecation warnings.

1. Change directories to the top level of Hengband's files.
2. Run ./boostrap.
3. Run ./configure --disable-worldscore --disable-pch
4. Run make.

## 期待される正常な動作

The build is clean without warnings.

## 補足事項

There's some overlap between this and https://github.com/hengband/hengband/issues/2854 (warnings from GCC 12 for too short buffers passed to sprintf()).

**Comment by habu1010** [comment]
@backwardsEric 
Does applying this branch in your environment fix the problem?
https://github.com/habu1010/hengband/tree/feature/fix-for-gcc-12-error-warn

**Comment by backwardsEric** [comment]
That fixes the deprecation warnings for core/scores.cpp, but,  as you note in https://github.com/hengband/hengband/issues/2859 , there are many affected files.  https://github.com/hengband/hengband/pull/2861 tries to get all the ones that don't affect globally visible prototypes.  It does prefer the hengband-specific routines (strnfmt(), angband_strcpy(), angband_strcat()) rather than more standard ones (snprintf(), strncpy() and strncat()).
