### ISSUE TITLE
【リファクタリング】angband_term配列に対してループ処理を記述する際、'8'というマジックナンバーを使っているのをやめる

### ISSUE THREAD

**Issue by arumons** [hengband/hengband#2860]
# やりたいこと

タイトルの通り。↓のような処理が散見されますが、ウィンドウの数はどこか一か所で定数定義して
それを使うようにしたいです

```
  for (int j = 0; j < 8; j++) {
    /// angband_term[j]にアクセスする処理
```

main-win.cppに↓の定数が定義されているので、これを
gameterm.hに移動させて使うのがよさそう？

```
#define MAX_TERM_DATA 8 //!< Maximum number of windows
```

**Comment by habu1010** [comment]
実は angband_term と main-win.cpp の MAX_TERM_DATA の数は直接関係ありません。
angband_term[] は各インターフェースが持つ term_data 構造体へのポインタになっており、main-win.cpp の場合はそれが8個であるため MAX_TERM_DATA が 8 になっています。
例えば main-gcu.cpp (Linux/macOS の GCU版インターフェース) ではつい最近まで MAX_TERM_DATA は 4 でした（先日 8 に増やした）。つまり MAX_TERM_DATA を gameterm.h に移して使うのは適切ではありません。

やるのであれば、 angband_term の定義を
```c++
std::array<term_type *, 8> angband_term;
```
とし、ループは
```c++
for (auto i = 0U; i < angband_term.size(); ++i) {
    auto term = angband_term[i];
}
// もしくはインデクス番号が不要な場合
for (auto term: angband_term) {
}
```
のようにするのがいいのではないかと思います。

**Comment by arumons** [comment]
マージされたのでclose
