### ISSUE TITLE
言語標準バージョンを C++20 にする

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#2894]
# 概要

現在マルチプラットフォームでの開発において使用されているコンパイラの MSVC/GCC/(Apple)Clang である程度 C++20 を使える状況が整ったので言語標準バージョンを C++17 から C++20 にアップデートしたい。

# 個人的に嬉しそうな機能

## 言語機能
- [スコープ付き列挙型のusing宣言](https://cpprefjp.github.io/lang/cpp20/using_enum.html)
- [初期化式をともなう範囲for文](https://cpprefjp.github.io/lang/cpp20/range-based_for_statements_with_initializer.html)
- [コンセプト](https://cpprefjp.github.io/lang/cpp20/concepts.html)
- [可変サイズをもつコンテナのconstexpr化](https://cpprefjp.github.io/lang/cpp20/more_constexpr_containers.html)

## ライブラリ
- [std::span](https://cpprefjp.github.io/reference/span/span.html)
- [std::ranges](https://cpprefjp.github.io/reference/ranges.html)
- [std::format](https://cpprefjp.github.io/reference/format.html) (但しGCC/Clangではまだサポートされていないため現状使用不可)

**Comment by Hourier** [comment]
z-form::format() との区別を明確化するために、この関数だけでもangband 名前空間に定義した方が良さそうですね
(来るべきタイミングでstd::format に変えやすくすることも見込みつつ)
