### ISSUE TITLE
【バグ】 弓を装備せずにキャラクタ情報を表示するとクラッシュする

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#2898]
## 環境

- OS: Any
- バージョン: 現時点での develop ブランチ最新コミット 4228a51cb4fd8aeaf2cffc38939fc0af4a2a1839

## バグの詳細

弓を装備せずにキャラクタ情報を表示（'C'コマンド）するとクラッシュする。

## 再現手順

上記の通り。

## 期待される正常な動作

クラッシュしない。

## 補足事項

https://github.com/hengband/hengband/blob/4228a51cb4fd8aeaf2cffc38939fc0af4a2a1839/src/view/display-player-middle.cpp#L110-L116

`display_hit_damage()` の上記部分で std::nullopt の状態の optional に対し value() を取っているためクラッシュする。sval が optional でなかった時はおそらく 0 になっていたと思われるが、そもそも弓を装備していない時のスキルの sval は 0 を参照するのが正しいのかという疑問もある。

**Comment by Hourier** [comment]
調査しました
その前段で弓装備へのポインタを取得しますが、何も装備していない場合のtval はNONE でした
そうだと分かった瞬間にsvalをチェックせず処理を分岐すべきでした
(ランダム生成以外でもnulloptになる可能性がある場所は今後いくつか見つかっていくかもしれない)

スキル参照値も調査しましたが、無装備状態のweapon\_exp はClassSkillDefinitions.txt 側に定義があります
ここも含めて本不具合の修正範囲とするには重すぎると判断し、暫定で0のままとしておきます
