### ISSUE TITLE
アリーナ外周の上辺と左辺が永久壁でなく花崗岩になる

### ISSUE THREAD

**Issue by taotao54321** [hengband/hengband#294]
以下の画像のようになる。(0,0) の地形IDは 56(花崗岩) であることを確認済み。
![スクリーンショット_2021-02-25_01-21-08](https://user-images.githubusercontent.com/21364118/109041167-175cb380-7712-11eb-98dd-ce8cdf6f71c5.png)

フロア全体を初期化する際の地形が花崗岩になっているのが原因。該当コードは以下:
https://github.com/hengband/hengband/blob/78654668dcac9ba90b15dc4e5a8d68a1b7eb54a2/src/floor/floor-generator.c#L189-L194

v2.2.1 の該当箇所を見ると、地形を配置する際に `place_solid_perm_bold(y, x);` としているが、この内容が現行コードの `place_bold(challanger_ptr, y, x, GB_SOLID_PERM);` と異なる。
現行コードでも `place_grid()` の方だと `GB_SOLID_PERM` が渡されたときは永久壁(`feat_permanent`)を配置するようなので、`place_bold()` 内に問題がある可能性がある。

@Hourier
`place_bold()` と `place_grid()` で処理内容が異なるのは意図的なものなのでしょうか?
v2.2.1 のコードを見ると、`place_hoge_bold(Y,X)` と `place_hoge_grid(C)` は引数の形式が違うだけで同じことをするものに見えたので、現在の `place_bold()` と `place_grid()` についても同様かと思ったのですが、実際はそうではないようなので確認したいです。
また、v2.2.1 と比較すると `delete_monster()` の呼び出し条件も変化しているようなので、この辺りの理由も確認したいです。
お手数ですが、よろしくお願いします。

**Comment by Hourier** [comment]
お手数おかけしました
非意図的なものでバグです
元々はその辺りの関数が全てplace_*_bold()とplace_*_grid() という関数マクロの集合体で非常に気持ち悪かったので、引数に壁種別を取る形にして統合したものです
place_bold() の中身が変わってしまっているならば、続けてお手数ですが修正頂けますでしょうか？
delete_monster() の条件変化も恐らく想定通りになっていないものと思われます。あり得るとしたら量子ドットの消滅条件だけです：ユニーク追加に伴ってコードも追加したことによります。

**Comment by taotao54321** [comment]
ありがとうございます。影響範囲が大きそうなので推測のみで進めるのはためらわれたところなので、確認できてよかったです。
v2.2.1 のコードも参照しつつ修正したいと思います。
