### ISSUE TITLE
キーを押しっぱなしにした時の動作が遅い

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#3]
alpha4とalpha5で比較したとき、キー押しっぱなしで移動した時の動きが異なる

- alpha4では2歩目までの待機が短く、3歩目以降速い
- alpha5では2歩目までの待機が長く、3歩目以降も1歩ずつ動くような遅さになる

**Comment by dis-** [comment]
auto_debug_saveをONにすると動作がもたつく。
遅延を回避できないか検討する。

**Comment by dis-** [comment]
再描写の整理により、auto_debug_saveによる過剰な再描写を回避した。(つもり)
α6リリース後のユーザの反応を見て改善したか判断する。

**Comment by tanguband** [comment]
Mac X11 developerブランチのビルドで以前と同様のスピードに戻っていることを確認しました。
