### ISSUE TITLE
親ペットが召喚した子ペットが、親ペット消失時に消失しないことがある

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#302]
例えば、複数召喚持ちのペット(親)に、敵モンスターに対して複数召喚させたあと、ペット(親)をモンスターボールで捕まえて消去させたときに、ペット(子)全てが消え去るはずなのに1体ないしは複数残ることがある。

**Comment by taotao54321** [comment]
v2.2.1 から存在する問題です。

例えば `m_list[1]` に親ペット P, `m_list[2]` に子ペット C が存在するとします。
このとき `C->parent_m_idx == 1` となっています。

P が消滅すると、C に対する `process_monster()` が呼ばれたとき `vanish_summoned_children()` で C が連鎖的に消えます。
このとき親が生きているかの判定は `m_list[C->parent_m_idx].r_idx > 0` となっています。つまり、親ペットのエントリ `m_list[1]` が空かどうかを見ています。

ここで、P の消滅と C に対する `process_monster()` 呼び出しにはタイムラグがあり、間にプレイヤーターンが挟まることもあります。
この間に `compact_monsters()` によってモンスター配列の詰め直しが行われると、C は `m_list[1]` に移動します。すると `C->parent_m_idx` が自分自身を指してしまい、C が消えなくなります。
(`compact_monsters()` は詰め直すモンスターの子たちの `parent_m_idx` 更新は行いますが、これだけでは不十分です)

`compact_monsters()` はセーブ時に呼ばれるので、v2.2.1 でも親ペットが消えてから子ペットが消えるまでの間にセーブすれば子ペットが消えなくなります。
現在はデバッグセーブが導入されたために問題が顕在化した形です。

詰め直し処理で親子関係が壊れないようにするか、もしくは親ペットを消す際に子孫も一挙に消すようにするなどの対処が必要かと思います。
