### ISSUE TITLE
キャラクタ情報を画面中央に表示する

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#3026]
# 概要

キャラクタ情報は最小サイズの画面に合わせた大きさで表示されるため、ウィンドウサイズを広げていると以下のように左上に寄ってしまう。
![image](https://user-images.githubusercontent.com/1501750/209824271-e3d7a82b-7abf-4d34-a977-495cbf908b60.png)

これを画面中央に表示するようにしたい。
他にも左上に寄ってしまう画面はあるが、一番よく見る画面なのでまず優先的に対応したい。

# 考慮しなければならない事

キャラクタ情報の画面表示は、ダンプファイルの生成にも使われている。（内部的に画面を表示する→表示した画面データを読み込んでダンプを作成）
したがって、ダンプ作成時に画面中央に表示が有効だとダンプファイル内の表示までずれるので、実際の画面に表示する時とダンプ用の表示の時でオフセットを切り替える必要がある。

**Comment by Hourier** [comment]
これを機会に、純粋仮想関数で画面表示用とダンプ用の処理を分けたいところですね

**Comment by habu1010** [comment]
各表示処理毎にオフセットを持たせて、`term_*` 系の画面表示関数を呼ぶのは変更量が多くなる、オフセット引数を延々とひきまわす必要がある、そもそも表示処理の呼び出し側で制御するものでもない、という事で次のような方法を考えています。

TermOffsetSetterクラスというクラスを新設する。
TermOffsetSetterはオブジェクトが生成された時のオフセット設定をバックアップし、新たにオフセットを設定する。オブジェクトが破棄される時にバックアップされていたオフセット設定に戻す。（入れ子でのオフセット設定に対応）

```c++
{
    // オフセットを 右に10、下に5に設定
    TermOffsetSetter tos(10, 5);

    // term_putstr などの呼び出し。右に10下に5ずらした位置に表示される。

    // tos が破棄される。tos生成前のオフセット位置に戻る。
}
```
