### ISSUE TITLE
C++のコードの使用を許可する

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#306]
もう2021年です。
C++コンパイラが無い環境で変愚を遊んでる人世界中さがしても一人も居ないと思います。（そもそもそんな環境で現状のコードのコンパイルは通るのか？）
もう自分で文字列や配列のバッファ用意してごちゃごちゃ操作してとかやりたくないのです。

**Comment by sikabane-works** [comment]
もう、やっちゃいましょう。

**Comment by sikabane-works** [comment]
やるとしたら大分大きな作業を小分けする必要があるので新しくプロジェクトとして登録しましょう。

**Comment by taotao54321** [comment]
賛成です。
エラー処理の方法だけは決めておいた方が良いかもですね(事前条件が満たされていなかったり、iconv などの外部ライブラリがエラーを返してきたときなど)。
個人的には例外を使うとまたカオスになりそうなので、変なことが起きたら素直にクラッシュさせたいです。

**Comment by habu1010** [comment]
現状のソースをC++に移行するにあたり、一番の障壁はenum型と整数型の相互変換が行われている事。
C++はCより型に関して厳密なので、変換でエラーが出てしまう箇所がある。
典型的なのは、 type というenum型があったとして、
```c++
void func(type t)
{
}

int main() {
  type val;

  for (val = TYPE_A; val < TYPE_MAX; val++) {
      func(val);
  }
}
```
のように整数として扱っていること。
enum型は算術演算ができないので、こういう使い方をする時は以下のように整数型の変数にする必要がある。
また、整数型をenum型に暗黙に変換しようとするとエラーになるので、以下のようにキャストが必要となる。
```c++
void func(type t)
{
}

int main() {
  int val;

  for (val = TYPE_A; val < TYPE_MAX; val++) {
      func(static_cast<type>(val));
  }
}
```

**Comment by habu1010** [comment]
その他のenumに関するC++移行メモ：
```c
typedef enum enum_type {
//...
} enum_type;
```
は、
```c++
enum enum_type {
//...
}:
```
とする。前方宣言も同様に
```
typedef enum enum_type enum_type;
```
を
```
enum enum_type;
```
とする。
場合によっては enum 型に割り当てる整数型を明示する必要があるかもしれない。

**Comment by habu1010** [comment]
#410 にて、ひとまずLinuxでg++-10によるコンパイルとゲーム起動ができるところまで進めた。

変更量が多く、レビューが難しいと思う。
ロジックを変えるような変更はしていないので、とりあえずマージして様子を見ていく他はなさそう。
またファイルの拡張子の変更という他の作業とコンフリクト必須のコミットが必要なので、準備ができたら他の作業の切りが良いところで一気にマージしたい。
