### ISSUE TITLE
【バグ】 画面左側の敵HPの下の状態異常表示が残存する

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#3092]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha75

## バグの詳細
敵HPゲージの下に敵が陥っている状態異常が表示されるようになったが
寝ている敵を攻撃する、恐怖した敵を殺すなどして状態異常がなくなった後でも状態異常表示だけ残り続ける

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 寝ている敵を攻撃する
2. 目覚めているのに睡眠表示が残り続ける等

恐怖などでも同様に表示残存を確認
恐怖させた後に倒してもHPゲージだけが消えて恐怖表示が残る

## 期待される正常な動作

敵の状態異常が解除されたら、解除されたターンor次のターンには状態異常表示が消えること

## スクリーンショット

![起きてるが睡眠状態](https://user-images.githubusercontent.com/79730818/215267086-3cd5e515-c842-471b-8066-a2d913387584.jpg)

![死亡しても睡眠残存](https://user-images.githubusercontent.com/79730818/215267331-e1200142-fa7e-4f98-b39d-f10f17ce57b1.jpg)

![死んでも恐怖残存　次のターンも表示消えず](https://user-images.githubusercontent.com/79730818/215267370-de5a8d14-d62c-420d-93e6-cd31b97836b6.jpg)

**Comment by habu1010** [comment]
#3088 で修正済みのため duplicate で閉じます。
