### ISSUE TITLE
新しい属性ブレスをパワーDや巨大サイバー以下略などに適用する

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#3105]
daradarach氏提案。欲張り全属性攻撃持っているモンスターを選別、適用する。

**Comment by sikabane-works** [comment]
ひとまず案。

* 虚無/深淵ブレスを追加予定
  * エーテル・ハウンド
  * パワー・ワイアーム
* 虚無/深淵ブレスとボール双方追加予定
 * 巨大サイバー以下略

**Comment by sikabane-works** [comment]
エーテル・ボルテックスも追加。

**Comment by sikabane-works** [comment]
巨大サイバー以下略にはボルトも追加。

**Comment by dis-** [comment]
実装済のためCloseします
