### ISSUE TITLE
【バグ】 histedit.prfから読み込む際、特定の文字数だと読み込みがおかしくなる

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#3110]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha75以降

## バグの詳細

hdns氏より報告。おかしくなった文字の次が半角英数で特定の文字数だと？おかしな空白が発生します

## スクリーンショット

![image](https://user-images.githubusercontent.com/61610939/218486991-cf3299df-8a7e-4337-a10f-85d8288e02dc.png)
![image](https://user-images.githubusercontent.com/61610939/218487070-79a3e949-1bce-499f-915c-ba3d39768229.png)

**Comment by habu1010** [comment]
空白が発生すること自体は仕様です。
histedit.prfから読み込んだ文章には、連続するASCII文字（すなわち英単語を想定）の途中でなるべく改行されないようにする処理が施されるため、空白が発生すること自体は仕様です。
ただし、区切る位置がおかしい（スクリーンショットの例だとhhhhhhhh…の先頭で改行されるべきところ、「あ」も含まれてしまっている）ので、その部分については修正を予定しています。
