### ISSUE TITLE
【バグ】 床置きしたアーティファクトが階移動で消滅する

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3111]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha76

## 詳細

アーティファクトを床に置いたあと、階移動して戻ってくると消滅している

## 再現手順

1. デバッグデータで開始
2. 適当な階層にジャンプして階段の隣に移動する
3. 適当なアーティファクトを生成して床に置く
4. 階段で別の階に移動する
5. 前の階に戻るとアーティファクトが消滅している

## 補足事項

溜まり場の加速スレからの報告です
http://jbbs.shitaraba.net/bbs/read.cgi/game/9358/1618842554/722

Mac 版の Ver 2.2.1.7 でも同様でした

**Comment by habu1010** [comment]
ソースコードを調べた所、次のような仕様のようです。

- 固定アーティファクトは生成されたフロアのフロアIDを持っていて、階に戻ってきた時にそのフロアIDと一致していなければ消える
- 固定アーティファクトを拾って、階を移動するとそのアーティファクトに記録されたフロアIDはリセットされる

その結果、以下のような挙動になります。
固定アーティファクトを生成された階から移動させず（一旦拾ってからまた床に置いてもよい）床に置いたまま階を移動して戻ってくる→消えずに残っている
固定アーティファクトを生成された階から拾って別の階に移動し（ここでアーティファクトに記録されたフロアIDがリセットされる）、その後床において他の階に行き、戻ってくる→フロアIDがリセットされているため、階のフロアIDと一致せず消える
おそらく溜まり場のスレで報告した方は、報告の内容からはそこまでは読み取れませんが、アーティファクトを拾った階と床に置いて移動した階が別の階になっているのだと思います。

ちなみに、デバッグコマンドで生成した固定アーティファクトは生成されたフロアのIDを記録する処理が行われないため、アーティファクトを持って階の移動を挟まなくても、別の階にいって戻ってくるとアーティファクトが消えます。

このフロアIDの記録まわりの処理が現状どういう意味があるのかわからず、正直おかしな挙動だとは思いますが、どうするのがよいのか考えどころです。

**Comment by habu1010** [comment]
この仕様についてですが、別の階層で同じアーティファクトが生成された場合に重複してしまわないようにするための措置ののようです。
具体的には以下のようなシチュエーションが考えられます。

1. 階層Aで★リンギルがドロップする（★リンギルのフロアIDに階層Aが記録される）
2. 鑑定せずに階層Bへ移動
3. 階層Bで★リンギルがドロップする（鑑定していないので、保存モードの場合階層を移動した時点で生成されたフラグは一旦削除される。したがって階層Bでは★リンギルは生成可能であり、生成されるとフロアIDに階層Bが記録される）
4. 階層Aに戻った時、★リンギルのフロアIDは階層Bになっているので階層Aにおかれていた★リンギルが削除される

固定アーティファクトが重複して生成されてしまうとまずいのでこの処理は残しておく必要があります。一案として、アイテムを床に置いた時に固定アーティファクトならフロアIDを現在のフロアに更新するという処理を追加すれば自然になるかもしれません。

**Comment by habu1010** [comment]
致命的なバグがあったので #3127 にて対処。
