### ISSUE TITLE
【バグ】 未鑑定のフェアノールのランプがザックで重なる

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3133]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha73以降で確認

## 詳細

未鑑定のフェアノールのランプを2個拾うとザックで重なってしまう

## 再現手順

1. デバッグデータで開始
2. フェアノールのランプを2個生成する
3. 両方とも拾う

## 補足事項

溜まり場の加速スレからの報告です
http://jbbs.shitaraba.net/bbs/read.cgi/game/9358/1618842554/726

Ver 2.2.1.7 と Alpha52 では重ならないのを確認

**Comment by sikabane-works** [comment]
報告ありがとうございます。

**Comment by sikabane-works** [comment]
出来れば今回中に直す。

**Comment by Hourier** [comment]
原因判明
object\_similar\_part() のLITE caseにおいて、is\_known() の判定がなされていない
但しこの辺りのコードはα52の頃ぐっちゃぐちゃで今も立て直し中につき、コピペではなく少し設計を考えてから修正する

```cpp
if (!o_ptr->is_known() || !j_ptr->is_known()) {
    return 0;
}
```

**Comment by Hourier** [comment]
周辺コードを調べた結果、該当case文に上記の処理を追加すればいいだけだと確信できた
直す
