### ISSUE TITLE
【バグ】 キャラメイク時職業を選択して確認する時に能力修正の表示が更新されない

### ISSUE THREAD

**Issue by oguchi2918** [hengband/hengband#3137]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha78-jp

## バグの詳細

タイトルの通り

## 再現手順

1. キャラメイク開始
2. 職業の選択でaの戦士以外を選択
3. よろしいですか？の確認画面右上の能力修正値が更新されていない(戦士のまま)

## 期待される正常な動作

種族、性格の選択確認時には選択したモノの能力修正値が表示されている為
職業も直前に選択したモノの能力修正値が表示されるべき

## 補足事項

職業選択と以降のキャラメイク自体は正常に行われている模様なので実害はほぼ無いと思われます
Issueに無かったので一応報告

**Comment by sikabane-works** [comment]
報告ありがとうございます。
