### ISSUE TITLE
【バグ】 魔道具術師で足元の杖/魔法棒の充填を吸うとゲームが落ちる

### ISSUE THREAD

**Issue by HiddenNameZ** [hengband/hengband#3144]
## 環境

- OS: Windows
- バージョン: 3.0.0Alpha78

## バグの詳細

タイトル通り。ロッドでは問題が発生しない。

**Comment by Hourier** [comment]
本件、杖と魔法棒各1本ずつ実施しましたが特にクラッシュは発生しませんでした
セーブデータの提供をお願いします

**Comment by Hourier** [comment]
提供ありがとうございます！
これを解析してみます、しばらくお待ち下さい

**Comment by Hourier** [comment]
@HiddenNameZ 
原因判明しました
「発見済のアイテム一覧」サブウィンドウがONの時だけクラッシュすることが分かりました
回避策としてはこれをOFFにして頂くことです

修正については、設計方針も含めて開発メンバーで協議します
しばらくお待ち下さい

**Comment by Hourier** [comment]
メモ
足元のアイテムだとItemEntity::numberが0になるが、それで0除算例外
「アイテムが足元にあるか？」という旨のメソッドを作りたいが、それは明らかにプレイヤーの座標に依存するのでプレイヤー側に「足元のアイテムか？」を作りたい
もっといえばインベントリを表すクラスを作って、「インベントリ外のアイテムか？」とすると根本的解決になりそう
但しそこまでリファクタリングする暇があったら暫定措置した方がベター

```cpp
PRICE object_value_real(const ItemEntity *o_ptr)
{
(中略)
    value += (value * o_ptr->pval / o_ptr->number / (baseitem.pval * 2));
```

**Comment by Hourier** [comment]
更にメモ
本数は関係なく、インベントリか足元かでクラッシュするかどうかが決まる
