### ISSUE TITLE
職業選択のみ十字キーでの項目移動ができなくなっている。

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#3186]
## 環境

- OS: Windows
- バージョン: 例: 3.0.0Alpha78開発中

## バグの詳細

職業選択のみ十字キーでの項目移動ができなくなっている。

## 再現手順

同バージョン通常起動時

## 期待される正常な動作

元通り職業選択を方向キーで選択可能にする。

## スクリーンショット

![image](https://user-images.githubusercontent.com/61610939/234753290-a15cddbc-c07d-48b8-b166-f044753d0bc8.png)

**Comment by Hourier** [comment]
@habu1010 原因判明しました
select\_class() でint\_cs 変数をwhile の内側に置いたコミットで引き起こされたようです
あっちを立てればこっちが立たず状態ですが、何か上手い修正案ありますでしょうか？
