### ISSUE TITLE
【バグ】 カオスパトロンの能力値上昇時の処理がおかしい

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3200]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha78

## 詳細

カオスパトロンの能力値上昇後のメッセージが文字化けして
呪文の学習数が100くらい増える

## 再現手順

1. 混沌の戦士で開始
2. 能力値上昇の報酬を持つ守護悪魔を選択（例：バロ）
3. デバッグモードで能力値上昇が出るまで報酬を受ける

## 補足事項

twitterからの報告です
https://twitter.com/yonezzawwa/status/1651060887342714881

src/player/patron.cpp:324 の (void) 抜けが原因？

<img width="490" alt="0429" src="https://user-images.githubusercontent.com/17109188/235284108-3d5219e8-d2f0-4692-abaa-c20141d026f4.png">

**Comment by Hourier** [comment]
セーブデータの提供をお願いします
恐らくL320の引数boost\_stat に異常な値が保存されています

**Comment by tanguband** [comment]
デバッグセーブです
[ chaos-w.zip](https://github.com/hengband/hengband/files/11358454/chaos-w.zip)
