### ISSUE TITLE
【バグ】 picktypeで兜を拾う設定にしても硬革帽子と鉄冠を拾わない

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3265]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha81

## 詳細

Alpha78では拾われるアイテムがAlpha81では拾われない

## 再現手順

1. 適当なキャラで開始
2. Picktypeに 兜 を追記
3. デバッグモードで硬革帽子と鉄冠を生成
4. 上に移動しても拾われない

## 補足事項

溜まり場の変愚スレからの報告です
Alpha78では拾われます

**Comment by Hourier** [comment]
ifの判定が反転していることが分かりました
修正します
