### ISSUE TITLE
【バグ】(wikiの)自動生成スポイラーのオブジェクト一覧が正しく出力されていない

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#3273]
## 環境

変愚蛮怒スポイラーwikiの自動生成スポイラーのオブジェクト一覧
- バージョン: 3.0.0Alpha82

## バグの詳細

wikiの自動生成スポイラーのオブジェクト一覧において、アイテムの名前が表示されるべき場所にアイテム名の代わりに、

~/.angband/Hengband/obj-desc.txt 

のように表示されている。

## 再現手順

wikiを見る

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

アイテム名が正しく表示される。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
報告ありがとうございました。対応いたしました。
