### ISSUE TITLE
【バグ】ペットへのプレイヤーを巻き込む範囲魔法を使う命令の不具合？

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#3291]
## 環境
- OS: [Windows 版]
- バージョン: [3.0.0Alpha82]

## バグの詳細
クローン地獄を攻略中、ペットにシャンブラーを連れて歩いていたら
ペットの命令の「プレイヤーを巻き込む範囲魔法を使う」がいいえにも拘らず
ペットの攻撃に巻き込まれた。(そして死亡した)
http://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=86574

スコアのペットへの命令一覧でもいいえですし、クイックスタートで確認してもいいえのままでした。
ペットの攻撃対象は巨大赤アリ、スクショの@の右下にある赤い~の位置にいた巨大火アリ。それに対して電撃ブレスで攻撃。
攻撃前は森地形あり。確か一歩右に動いた後にに攻撃されました。

## 再現手順
不明
## 期待される正常な動作
「プレイヤーを巻き込む範囲魔法を使う」がOFFの時はプレイヤーを巻き込む行動を選択しない。

## スクリーンショット
http://mars.kmc.gr.jp/~dis/heng_score/show_screen.php?score_id=86574
## 補足事項
補足事項があれば記載

**Comment by Hourier** [comment]
報告ありがとうございます
不具合の可能性は高いですが調査します
しばらくお待ち下さい
