### ISSUE TITLE
エルドリッジホラー発生時のモンスターの見える位置と実際にいる位置のずれ

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#330]
![狂気を誘う効果が発生した時モンスターの位置が１マスずれて見える](https://user-images.githubusercontent.com/79730818/109370538-18453f00-78e4-11eb-8d89-aebd018922a9.png)
上記の画像は忍者の位置交換で石壁1マスにアブドゥルを閉じ込めた状態です。
本来なら画像より1マス左の位置にアブドゥルがいるはずなのですが、エルドリッジホラー発生時のみ、アブドゥルの位置が＠がいる方向の1マス近い位置に見えます。
見える位置がずれるだけで石壁が消失している等は起きていませんでした。

**Comment by meetname** [comment]
追記：関係ないとは思いますが、こちらが一時加速込み加速+20,アブドゥルの加速+10で超隠密状態で隣接していた割にはやけに先制攻撃されました。

**Comment by dis-** [comment]
少し検証しましたが再現が難しいようです。
もし再現可能なセーブデータが残っていれば添付していただけると助かります。

**Comment by meetname** [comment]
もう残ってないです。こちらでも他のモンスターで再現しようとしましたが再現できませんでした。
アブドゥルじゃないといけないのか…？

**Comment by iks3** [comment]
center_playerがYESの時に起きやすいですね。
移動後の処理が以下のようになっています。
1) 座標を移動する
2) モンスターの表示情報を更新
3) マップ等の情報を再計算して描画を更新

エルドリッチホラーの判定は、2)の中で行われてしまっていますので、先にモンスターの描画がずれて狂気のメッセージが出てから、マップが再表示される感じになります。
移動だけでなく感知魔法やテレポートその他でも 2)の処理が出てきますので修正は大変かもしれません。
