### ISSUE TITLE
【バグ】 "make distcheck" fails after changes for lib/file/books

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#3319]
## 環境

- OS: macOS 12.6.5
- バージョン: 3.0.0Alpha83 plus the changes up to bde4e7146159a22eaec8d4665dd4b073de4f12e8

## バグの詳細

Running ```./bootstrap ; ./configure --disable-japanese --disable-worldscore ; make DISTCHECK_CONFIGURE_FLAGS="--disable-japanese --disable-worldscore" distcheck``` fails with the message ```make[6]: *** No rule to make target `book-0_jp.txt', needed by `distdir-am'.  Stop.``` after the recent changes for lib/file/books.  The cause is a reference to book-0_jp.txt in lib/file/Makefile.am: that file is no longer present in that directory.

Related to that, should the files in lib/file/books be copied to a generated source archive or into the lib directory hierarchy if the game is being installed into another directory?  If so, then a Makefile.am will have to be set up in lib/file/books (with a reference to that Makefile.am in the AC_CONFIG_FILES() macro invocation in configure.ac).

## 再現手順

1. Clone the git repository and setup the submodule handling lib/xtra.
2. Run ```./bootstrap``` in the top level directory of the cloned repository.
3. Run ```./configure --disable-japanese --disable-worldscore``` in the top level directory of the cloned repository.
4. Run ```make DISTCHECK_CONFIGURE_FLAGS="--disable-japanese --disable-worldscore"``` in the top level directory of the cloned repository.

## 期待される正常な動作

```make distcheck``` runs to completion without an error.

**Comment by Hourier** [comment]
Sorry for inconvinience.
I'll fix it this night.
