### ISSUE TITLE
ビルド方法をwikiに記述する

### ISSUE THREAD

**Issue by argrath** [hengband/hengband#3353]
[ブログ記事](https://hourier.livedoor.blog/archives/12542881.html)はあるので当面リンクだけでも。

**Comment by Hourier** [comment]
雑ですが作成しました
https://github.com/hengband/hengband/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86
