### ISSUE TITLE
【バグ？】ゲームが時々フリーズする

### ISSUE THREAD

**Issue by TX105** [hengband/hengband#3354]
[ライルnn.zip](https://github.com/hengband/hengband/files/11599268/nn.zip)

## 環境
ウインドウズ版　ウインドウズ10　3.00Alpha84

## バグの詳細
ゲームがフリーズしたのちゲームが強制終了、その後添付した異常なセーブデータが発生
ゲームフリーズする頻度も高い

## 再現手順

バグを発生させる手順が分かっていれば記載

1. ○○ する
2. ✕✕ する
3. バグが発生

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

本来期待される正常な動作を記載

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by Hourier** [comment]
報告ありがとうございます
しかしながら、**配布されているα84ビルド**で頂いたセーブデータを読み込み、以下の操作を行いましたが特にフリーズやクラッシュなどの重篤な症状は発生しませんでした：
- 帰還する (巻物)
- ダンジョン内を移動する (歩き、走り)
- アイテムを使う (杖、薬、装備切り替え)
- モンスターを殴る (倒す、アイテムを拾う)
- 階段を降りる
- 魔法を使う

なお、開発環境も今のところフリーズ症状は未遭遇です
フリーズが起きる直前の操作など、再現できるだけの情報をできるだけ詳しく提供頂けますでしょうか
フリーズ頻度が高いのであれば、直前に何かしら兆候があるのではないかと推測しています

**Comment by TX105** [comment]
このキャラ、盗賊なのになぜかウィザードになっています
これこそがバグの所以なのです

**Comment by Hourier** [comment]
これはウィザードモードといって正常な手順でこの表示になります
つまり、忍者だろうが狂戦士だろうが、ウィザードモード (Ctrl+W)に入ると[ウィザード] と表示されます
(歴史的経緯により、デバッグモードでは一部のデバッグコマンドのみが実行可能であり、更にウィザードモードに入ることで全てのデバッグコマンドが実行可能になる仕組み)

もし「ウィザードモードに入ったはずがない、入力ミスは一切なかった」または「デバッグモードにすら入っていない、入り方すら知らない」であれば別種の不具合と思われますので、その旨ご報告下さい
意図的なウィザードモードであれば、当初の依頼通りフリーズに至るまでの詳細をご連絡下さい

**Comment by Hourier** [comment]
セーブデータを再確認したところ、実際にはウィザードモードでなさそうなことが分かってきました
これは別種の問題と思われるので確認・修正します
(補足・追加情報はどんな些細なことでも大歓迎です)

**Comment by TX105** [comment]
ありがとうございます
デバッグモード的な表示だったんですね
知識がたりず申し訳ありません。
しかしデバッグモードの操作は行っていないわけでなんらかのエラーはありそうですね

**Comment by TX105** [comment]
念のためデバッグモードの使用法はさっき別データで確認しました

**Comment by Hourier** [comment]
承知しました＞デバッグモードの操作は行っていない
開発者2名がかりで現在調査中ですが、全くフリーズ事象が発生しません
念のため、PCの詳細情報をご提供下さい：
- Windows 10 の詳細バージョン ex. 22H2 (スタートメニュー → winver とタイプ → 出てきたツールを起動)
- CPU型番 (タスクマネージャ → パフォーマンス → CPU で確認可能)
- GPU型番 (同 GPU 0 で確認可能)
- メモリ容量 (同 メモリ で確認可能)

**Comment by TX105** [comment]
22h2 os build 19045. 2965
AMD　A8-7410 APU with AMD Radeon R5 Graphics
AMD Radeon(TM) R5 Graphics
メモリ　7.0GB

**Comment by TX105** [comment]
ゲームPCの地力の問題はあるとおもいますが、一応クラッシュ直後のセーブデータをフォルダごとゲットしているので参考に提出いたします
[save.zip](https://github.com/hengband/hengband/files/11642723/save.zip)

**Comment by Hourier** [comment]
データのご提供ありがとうございます
近々β版を出す計画があるので、そこで(他の、開発メンバーでは見つけられなかったような不具合も含めて)広くユーザに動作確認して頂ければと考えております
引き続き調査は進めるつもりですのでよろしくお願いします

**Comment by tkkarube** [comment]
同様の事象が私のところでも発生します。3.0.0.79以降発生するようになりました。ただ移動しているだけでもフリーズ、クラッシュします。なのでずっとα78で遊んでます。調査よろしくお願いします。

**Comment by habu1010** [comment]
調査のため、情報の提供にご協力ください。

1. まず、最新版 3.0.0.86(Alpha) でも現象が変わらず発生するかどうかを確認してください。元の報告はAlpha84ですが、85と86でいくつかクラッシュの原因となり得るバグが修正されているので、もしそれで改善していれば調査は徒労に終わります。
2. 変わらず発生するのであれば、ゲームにおける特定の環境・状況に依存する可能性があります。同じ状況を再現するため、現象が発生する状態の変愚蛮怒のゲームフォルダの中身をまるごとzipにしてどこかにアップロードしてください。特にセーブファイルとHengband.INIが重要です。（容量が大きいので lib/xtra/music、および lib/xtra/sound の中身は削除しても構いません）

**Comment by tkkarube** [comment]
3.0.0.86で再現しました。モノ言えぬ証人でクロスボウの矢を打ちまくっていた状況でクラッシュです。
[Hengband-3.0.0.86-Alpha-jp.zip](https://github.com/hengband/hengband/files/11928685/Hengband-3.0.0.86-Alpha-jp.zip)

**Comment by habu1010** [comment]
報告ありがとうございます。
アップロードしていただいたファイルをチェックしていたのですが、lib/save のフォルダに 「.new」のついたファイルができているのが気になっています。このファイルは、セーブの処理中に一時的にしか作成されないファイルなので、これが残っているという事はセーブの処理の途中でクラッシュしていることになります。
オプションを確かめたところ、自動セーブ系のオプションはオンにされていないようなので、おそらくデバッグセーブの途中でクラッシュしているのではないかと思われます。

そこで、次の設定変更をためしていただきたいです。

- オプションコマンド（'='）→ (4) ゲームプレイオプション → 「デバッグ用セーブデータを自動生成する（auto_debug_save）」を「いいえ」に設定

これにより状況が改善されれば、デバッグ用セーブデータの作成が引き金になっているということまで絞り込めそうです。（元の報告主の方もデバッグセーブを提供してくださったので、やはりデバッグセーブはONになっているという状況は同じ）

**Comment by tkkarube** [comment]
ご指定のオプションをオフにし、別キャラで３０分ほどプレイしましたが、問題は出ておりません。おそらく改善されたのかと思われますのでご一報です。
もし、また出るようでしたらご連絡いたします。
変愚の改善、いつもありがたく感じております。

**Comment by habu1010** [comment]
報告ありがとうございます。
今回の調査によりセーブ時に潜在的な問題があり、デバッグ用セーブの作成をONにしているとそのセーブ処理の頻度から発現する可能性が高いという事がわかりましたので、対策を行いたいと思います。
ご協力ありがとうございました。

**Comment by TX105** [comment]
お疲れ様です
お忙しい中
検証ありがとうございます。
とりあえずバグ発生時のデータをお送りします。
オプションの改善はこれから試します。
[Hengband-3.0.0.86-Alpha-jp - コピー.zip](https://github.com/hengband/hengband/files/11928900/Hengband-3.0.0.86-Alpha-jp.-.zip)

**Comment by habu1010** [comment]
> お疲れ様です お忙しい中 検証ありがとうございます。 とりあえずバグ発生時のデータをお送りします。 オプションの改善はこれから試します。 [Hengband-3.0.0.86-Alpha-jp - コピー.zip](https://github.com/hengband/hengband/files/11928900/Hengband-3.0.0.86-Alpha-jp.-.zip)

やはりこちらのファイルにも .new がついたセーブファイルが含まれているので、同じ原因のように思われます。デバッグ用セブデータの生成をオフにして改善するかどうか、検証結果をお待ちしています。

**Comment by habu1010** [comment]
もう1点、本件の原因と思われる箇所に対策を施したソフトを以下にアップロードしますので、余裕がありましたらこれを現在のAlpha86の Hengband.exe と差し替えて、「デバッグ用セーブデータを自動生成する」オプションを **「はい」にした状態** で、現象が改善されているかどうか確認していただければ幸いです。

[Hengband.zip](https://github.com/hengband/hengband/files/11929115/Hengband.zip)

**Comment by TX105** [comment]
お疲れ様です
デバッグ用セーブをオフにしたところ強制終了はおきなくなりました。
修正ファイルを試します

**Comment by tkkarube** [comment]
ご指定の状態で３０分テストプレイ、問題はありませんでした。改善されたと思われます。

**Comment by habu1010** [comment]
お二方共、情報の提供および動作検証ありがとうございました。
解決したようですので、本Issueはクローズします。次のリリースで本修正は反映されますが、それまで上記にアップロードしたものを引き続き使用していただいて差し支えありません。
