### ISSUE TITLE
MSVCでリリースビルドのコンパイルが通らなくなった

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#3356]
# 注意喚起

**この件はVisual Studio自体の不具合に起因しています**
**Visual Studio環境の方はデバッグビルドをご利用下さい**

## 環境

- OS: Windows 10 Pro 22H2
- バージョン: 3.0.0 α84
- IDE: Visual Studio 2022 v17.6.2

## バグの詳細

コンパイルすると以下のエラーが出る：
```
ビルドを開始しました...
1>------ ビルド開始: プロジェクト: Hengband, 構成: Release Win32 ------
1>モジュール依存関係のソースをスキャンしています...
1>コンパイルしています...
1>std.ixx
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\modules\std.ixx(147,1): fatal  error C1001: 内部コンパイラ エラーが発生しました。
1>(コンパイラ ファイル 'msc1.cpp'、行 1589)
1> この問題を回避するには、上記の場所付近のプログラムを単純化するか変更してください。
```

## 再現手順

開発環境でリリースビルドを実行する

## 期待される正常な動作

コンパイルできる

## 補足事項

変愚蛮怒のソースコードよりVS2022の方に問題が隠れている可能性アリ → 確定
このチケットに対して特別な作業をするつもりは現時点でなく、注意喚起が主目的
(α70までロールバックしても全く同じエラーが出る。コンパイラ最適化による高速化チェックのため、たまにリリースビルドを作るので、こんなに長期間リリースビルドを実行しなかったとは考えにくい)

msc1.cpp L1589 に起因する問題は他でも報告されている模様
https://developercommunity.visualstudio.com/t/ICE-in-VC-1760-LTSC---msc1cpp-line/10367337

**Comment by habu1010** [comment]
上記のForumではduplicateとして下記のスレッドが挙げられています。
このスレッドの最後で、問題は修正済みで 'Pending Release' の状態であることが書かれています。（問題はいつ修正版がリリースされるかですが…）
https://developercommunity.visualstudio.com/t/176-ICE-for-using-CObject::operator-del/10367118

**Comment by Hourier** [comment]
VS2022 v17.7 で解消予定とのこと
備考：現在、デバッグビルドであっても英語版はビルドできない。注意！

**Comment by habu1010** [comment]
なぜ日本語版デバッグビルドだけコンパイル可能なのかと考えてふと気づいたのですが、日本語版デバッグビルドだけ言語標準バージョンがC++20になっていて、他はC++latestになっています。そこでリリースビルドで言語標準バージョンをC++20にしてビルドしたところあっさりコンパイルできました…
latestゆえの不安定さというところでしょうか。この際全部C++20に統一しておいたほうがいいかもしれません。

**Comment by Hourier** [comment]
むしろ単なる作業漏れのままズルズル来てしまった感があるので、今日中に対応しておきます
