### ISSUE TITLE
【バグ】 シンボルエディタの地形を変更するときに明度を暗色にすると機能しない場合がある

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3395]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha84

## 詳細

シンボルエディタの地形を変更するときに明度を暗色にすると機能しない場合がある

## 再現手順

1. 適当なキャラで開始
2. '%' コマンドで (9) の地形の色/文字を変更する（シンボルエディタ）を選ぶ
3. 'v' コマンドで 床 のシンボルを選んで変更する
4. 'a' コマンドで 対象明度を変更して (暗色)を選ぶ

## 補足事項

v2.2.1.7 では機能します
<img width="1291" alt="2 2 1 7" src="https://github.com/hengband/hengband/assets/17109188/82c4d698-d775-4ccb-adbe-348b25e72cf2">
<img width="1291" alt="3 0 0Alpha84" src="https://github.com/hengband/hengband/assets/17109188/1560788d-4669-4ab3-ac1d-c062b1d6812b">

**Comment by Hourier** [comment]
再現しました
また不具合箇所も特定できましたので次αでは修正されている見込みです
