### ISSUE TITLE
【バグ】 初期オプション 体格/地位にオートローラーを使用 をオンにするとオートローラーが止まらない

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3429]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha84以降

## 詳細

初期オプション 体格/地位にオートローラーを使用 をオンにするとオートローラーが止まらない

## 再現手順

1. 新規キャラで開始
2. キャラ作成時に初期オプション 体格/地位にオートローラーを使用 をオンにする
3. 最低値と最高値は初期設定のままでオートローラーを回す

## 補足事項

溜まり場の変愚スレの報告です
Alpha83 では止まります

**Comment by sikabane-works** [comment]
Alpha85からの開発途中、デバッグビルド時、能力オートローラー要求ステ3、体格/地位ローラーONで初期値要求したところ再現できました。
