### ISSUE TITLE
バグ報告用のテンプレート作成

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#349]
バグ報告で欲しい情報が記載されていない事が多いので、GitHub の Issue Template 機能を利用してバグ報告用のテンプレートを作成する。

**Comment by habu1010** [comment]
とりあえず導入しました。
まだこのIssueは閉じず、しばらく運用してテンプレートの過不足等ないかどうかを確認していきます。

**Comment by sikabane-works** [comment]
今のところ十分に機能している気がします。問題なければこのまま閉じたいと思いますがいかがでしょう。

**Comment by iks3** [comment]
テンプレートの存在は新Issueを立てるときにも認識できますし、運用もできていると思います。
ですので、一旦クローズで大丈夫かと思います。

**Comment by sikabane-works** [comment]
例によって、他の意見や改良があればまたReopenできますし一度閉じます。お疲れさまでした。
