### ISSUE TITLE
【バグ】店で射撃武器を変更した時に矢玉のダメージ量表示が更新されない

### ISSUE THREAD

**Issue by k245ta** [hengband/hengband#3500]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha85 

## バグの詳細
従来は店頭の矢玉のうち射撃武器にマッチした物（ショートボウ→矢、スリング→鉄弾等、クロスボウ→クロスボウ矢）だけダメージ量が表示されており、店内で射撃武器を変更した時は表示が更新されていたと思います。
しかし現在は店内で射撃武器を切り替えた時に切替前の武器にマッチする矢玉のダメージ量が表示されたままとなります。

## 再現手順
１：武器屋でショートボウ・スリング・クロスボウなど矢玉の種類が異なる武器を購入
２：ショートボウを装備→矢にダメージ表示が出ない。スリング、クロスボウなど装備変更しても同様（NG１）
３：店を出る
４：ショートボウを装備して武器屋・道具屋に入ると矢のダメージ量が表示されている
５：装備をスリング、クロスボウなどに変更→矢のダメージ量が表示されたままで鉄弾やボルトのダメージ量が表示されない（NG２）

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
省略。
当方環境では@の新規作成直後から上記手順で再現するため。
もし開発で再現できないようであればあらためて添付いたします。

## 期待される正常な動作
装備している射撃武器にマッチした矢玉のみに店頭商品にダメージ量が表示されること。

## スクリーンショット
店内でクロスボウからロングボウに切り替えた時のSS。
クロスボウの矢のダメージ量が表示されたままで、矢のダメージ量が表示されていません。
![image](https://github.com/hengband/hengband/assets/128159186/5f6c638c-86ab-42a8-8785-0dbab8e6c5ce)

## 補足事項
なし

**Comment by habu1010** [comment]
報告ありがとうございます。現象確認しましたので、調査・修正します。
ちなみに、現状では表示ページの切り替え、Ctrl+rコマンドによる強制再描画でも更新されるようなので、修正まではそちらでご対応ください。
