### ISSUE TITLE
静的解析パッケージの更新

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#3518]
現在使っているパッケージは開発終了警告が出ている
推奨されるアップデートがあるのでそちらに差し替える

**Comment by Hourier** [comment]
@habu1010 json.hpp の中で静的解析警告が出てしまっています
これ自体は通常のビルド時に出る警告と性質が異なるのでコード内で直接抑制する他ないように思いますが、何か良いアイディアありますでしょうか？

**Comment by habu1010** [comment]
静的解析警告が出る箇所を確認したのですが、一度std::forwardしたオブジェクトをまた使用しているので、本当にバグっていますね。
それで本家を確認したのですが、変愚で使用することにした現時点での最終リリースバージョン（3.11.2）後に修正されているようです。

- https://github.com/nlohmann/json/commit/80dfb049b32e275586bd785944e3eb18f422ecef 

この修正のみ取り込むことにします。

**Comment by Hourier** [comment]
確認ありがとうございます！
それではそこは無視して進めます
