### ISSUE TITLE
【バグ】 未鑑定の「丸い小石」がザック内で重なる

### ISSUE THREAD

**Issue by k245ta** [hengband/hengband#3534]
## 環境

- OS:Windows 版
- バージョン: 変愚蛮怒 3.0.0Alpha85

## バグの詳細
自動拾いで未鑑定の「丸い小石」が重なる
うろ覚えですが従来は未鑑定や、簡易鑑定状態が同一でも殺戮修正値が不明な状態では重ならない挙動だったと記憶しています。
この挙動の方が便利なのは確かなので、意図的な挙動変更の場合はクローズ願います。

## 再現手順
1. 丸い小石を拾う
2. 別の丸い小石の上に@を移動する
3. 自動拾いで「1」で拾った丸い小石に「2」で拾った物が重なる

>22個の 丸い小石 (1d2)(d)を拾った。                
>フルーツ・コウモリが目を覚ました。                
> 中略
>のろまの薬がある。                                
>18個拾って、40個の 丸い小石 (1d2)(d)を持っている。

## 期待される正常な動作
未鑑定（殺戮修正が未知）のアイテムはザック内で重ならないこと

## スクリーンショット
なし

## 補足事項
なし

**Comment by Hourier** [comment]
ご報告ありがとうございます
事象の再現・特定はできました
そこでv2.2.1 と動作を見比べてみましたが、「未鑑定かつ殺戮修正値も不明」であったとしても、内部的に殺戮修正値が同一であれば重なります
未鑑定の矢弾を敵に放った後回収しようとした時に重ならなかったら不便極まりないのでこういう仕様になっています
ですので問題はないと思われます
なお、v2.2.1 もv3.0.0.87 も、内部的に殺戮修正が異なっていれば重なりません

**Comment by k245ta** [comment]
ご確認ありがとうございました。ご面倒をおかけしました。クローズさせていただきます。

その後、こちらでもプレーしてみましたが
・未鑑定矢玉を拾って打ち出す
・使ってるうちにザック内で簡易鑑定が出る
・元が同じでも簡易鑑定が出たものと、打ち出して床に落ちて簡易鑑定が出てない物が重ならない
と言う挙動あたりから、重ならない物と勘違いしていたようです。
