### ISSUE TITLE
【バグ】 買い物や自宅のアイテム選択中にESCキーが反応しない

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#3537]
## 環境
- OS: Windows 版
- バージョン:  3.0.0Alpha87
## バグの詳細
店でのpコマンドでの買うを選んだあと、どの商品を選ぶかa~の入力を求められる場面で
Escキーが反応せず、キャンセルができない。
何か商品を選んでからEscキーを押さないといけなくなっている。
自宅でのアイテム出し入れも同様にEscキーが反応しない。
## 再現手順
1.alpha87で新規セーブを作成
2.キャラメイク
3.店で買い物をし、pを押した後Escキーを押す
## 期待される正常な動作
Escキーを押せば商品を選ぶ段階の入力をキャンセルできる。
## 補足事項
alpha86でも新規データでテストしてみましたが、再現性はありませんでした。
87からの発生と思われます。

**Comment by Hourier** [comment]
ご報告ありがとうございます
原因特定しました
次バージョンで修正予定です
それまではお手数ですが、キャンセルが必要な場面では適当な商品/アイテムを選んでからのキャンセルをお願いします
