### ISSUE TITLE
【バグ】 博物館の20ページ目以降でスペースキーを押すと1ページ目に戻ってしまう

### ISSUE THREAD

**Issue by nilpon** [hengband/hengband#3542]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha86

## バグの詳細

博物館にアイテムが241項目以上収蔵され21ページ以上存在する状態で、
20ページ目以降でスペースキーを押すと、次のページではなく1ページ目に遷移してしまいます。

## 再現手順

1. 博物館に241種以上アイテムを寄贈する。
2. 博物館の画面でスペースキーを繰り返し押すことで20ページ目を表示する。
3. 20ページ目でスペースキーを押すと1ページ目に戻ってしまい、21ページ目以降を表示できない。

## 期待される正常な動作

博物館において、最後のページを除く任意のページでスペースキーを押すと次のページに遷移し、
また最後のページでのみスペースキーを押すと1ページ目に遷移すること。

## スクリーンショット

なし

## 補足事項

一つ前のページに戻るマイナスキーは正常に機能しており、
マイナスキーを繰り返し押せば21ページ目以降も表示できますが、
20ページ目以降の任意のページでスペースキーを押すと次のページではなく1ページ目に遷移してしまいます。

**Comment by habu1010** [comment]
報告ありがとうございます。
本件について調査したところ、だいぶ昔から存在するバグのようで、正確には我が家に保管できる個数までしか表示できないという動作になっています。したがって初期オプションの「我が家を拡張する」がいいえの場合、2ページまでしか表示されません。
我が家を拡張するをいいえでプレイしている人がおらず、博物館に240個以上のアイテムを預ける人も稀であるためこれまで報告されていなかったようです。

次回のリリースで修正予定です。
