### ISSUE TITLE
【バグ】 店舗でアイテム購入キャンセル時にクラッシュする

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#3546]
## 環境

- OS: Windows版
- バージョン: 3.0.0.87-Alpha

## バグの詳細

店舗でアイテム購入を行おうとし、特定の手順でキャンセルした時にクラッシュする事がある。

## 再現手順

1. 店舗で'p(purchase)'コマンドによりアイテムの購入を行おうとする。
2. 店舗で表示されているアイテムの選択肢として存在しない記号を入力する（例えば 'z' など）。見た目には変化なし。
3. Escapeキーでキャンセルする。
4. クラッシュする。

## 期待される正常な動作

存在しない記号を入力したとしてもEscapeキーで正常にキャンセルできる。

## 補足事項

一連の入力処理のリファクタリングが原因と思われますので、 @Hourier 氏を割り当てさせていただきます。

**Comment by Hourier** [comment]
割当確認しました
対応します
