### ISSUE TITLE
【バグ】 *勝利*メッセージ確認のyes/noが逆転している？

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#3547]
## 環境

- OS: Windows 版
- バージョン:3.0.0Alpha87

## バグの詳細
引退して*勝利*メッセージ入力後、これでいいか確認を求められるが
yes/noの選択肢がどうやら逆転している。
yesを選ぶとメッセージ再入力になり、noを選ぶと勝利メッセージが確定するようになっている。
## 再現手順
1. *勝利*する
2,引退する
3. 勝利メッセージを入力し、yes/noの確認でyesを選択する

## 期待される正常な動作
yesを選ぶと勝利メッセージが確定するようにする。

## 補足事項

**Comment by Hourier** [comment]
ご報告ありがとうございます
作業した記憶のある箇所なので私が担当します
