### ISSUE TITLE
【バグ】 アリーナのメッセージの位置がずれる

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3563]
## 詳細
アリーナのメッセージの位置がずれる
## 再現手順
1. 新規キャラで開始
2. メイン画面のサイズを80x24以上の大きさに変更する（例 120x48 など）
3. テルモラに移動してアリーナに入る
4. 戦わずに外に出ようとする
5. ゲートは閉まっている。モンスターがあなたを待っている！　のメッセージがズレた場所に表示される
## 補足事項
Discord の報告です
Alpha74 では正常に表示されました
Alpha78 では位置がズレます

**Comment by Hourier** [comment]
過去に類似の不具合があったかと思いますので @habu1010  氏に割り当てます
お手数ですがご確認下さい

**Comment by tanguband** [comment]
#3758 の修正により正常に表示されるようになりました
クローズします
