### ISSUE TITLE
【バグ】 タイルが表示されない

### ISSUE THREAD

**Issue by multilockon123** [hengband/hengband#3571]
お疲れ様です。

## 環境

- OS:  Windows 版
- バージョン: [例: 3.0.0Alpha88]

## バグの詳細

タイル（8x8.bmp）が表示されない

## 再現手順

1. オプション→グラフィクス→旧タイルを選択する。
2. 「ビットマップ''を読み込めません」「グラフィクスを初期化できません」というダイアログが出てタイルが表示されない。

## 期待される正常な動作

lib/xtra/graf/8x8.bmpの画像が表示される。

**Comment by Hourier** [comment]
ご報告ありがとうございます
調査の後修正します
少々お待ち下さい

**Comment by multilockon123** [comment]
追記：
おそらくalpha79からと思われます。

**Comment by Hourier** [comment]
不具合箇所特定しました
次回αにて修正予定です

**Comment by Hourier** [comment]
修正しました
次回α (stable？)にて反映予定です
