### ISSUE TITLE
隕石属性のボール・ボルトを追加

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#3574]
隕石属性のボールがありそうでないので実装する
威力は魔力の嵐に近いものになる予定
詳細は PR にて

**Comment by Hourier** [comment]
ボルトもそれっぽいので実装お願いします
あとしばらく前に弱点・耐性も追加したはずなのでその辺りの整合性も追加頂けると助かります

**Comment by Slimebreath6078** [comment]
承知いたしました。
ボールの方は「メテオ・スウォーム」、矢の方は「メテオストライク」の名前で実装しようと思います。
