### ISSUE TITLE
MonsterRaceDefinitions.txtの表記が未修正

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#3578]
Line: 142
# === Understanding r_info.txt ===
→MonsterRaceDefinitions.txt

Line: 147
# W: depth : rarity : 0 : exp : next_exp : next_mon
→実際は
# W: depth : rarity : exp : 0 : next_exp : next_mon
が正しい。
この説明文の通りに実装したがために、現状Expが0になってしまっているが、本来はExpを設定しようとしたであろうモンスターが若干ながら存在する。

Line 190-192
# Version stamp (required)

V:2.8.1
→本当に必要なら3.0.0になるべき？

**Comment by sikabane-works** [comment]
https://github.com/Hourier/hengband/commit/d995dd64ab596350021763cd908f82db56bcc887
このコミットで使わなくなった0定数を削除したため、
> W: depth : rarity : exp : next_exp : next_mon
が正しくなったようです。現在の汚いイタズラ小僧の設定も下記のとおりです。

> #J0#
> N:1:汚いイタズラ小僧
> E:Filthy street urchin
> G:t:D
> I:110:1d4:4:1:40
> W:0:2:0:10:14
> B:BEG:FLAVOR
> ...

**Comment by daradarach** [comment]
失礼しました。無駄な0はもうなくなってるんですね。
そうすると元のissueのLine147に対しての修正すべき点は下記となります。

Line: 147
# W: depth : rarity : 0 : exp : next_exp : next_mon
→実際は
# W: depth : rarity : exp : next_exp : next_mon
が正しい。
