### ISSUE TITLE
【バグ】 射撃の威力表示がおかしい

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#3592]
## 環境

- OS: Windows版で確認したが全てで発生し得る。
- バージョン: 3.0.0Alpha89

## バグの詳細

馬鹿馬鹿で確認。下記のように打撃枠４つ全て埋めてないモンスターの射撃威力が24d4でなく先頭HITの4d4表記になる。
> N:1973:GX-87 ダーベック
> E:GX-87 Kilroy
> G:p:B
> I:108:13d30:40:120:60
> W:36:2:0:1200:0:0
> B:HIT:HURT:4d4
> B:HIT:HURT:4d4
> B:HIT:HURT:4d4
> B:SHOOT:HURT:24d4
> F:MALE | PREVENT_SUDDEN_MAGIC | FORCE_MAXHP | DROP_1D2 | SMART
> F:DROP_CORPSE | DROP_SKELETON | CAN_SWIM | FRIENDS
> S:1_IN_3 |
> S:SHOOT | ROCKET
> D:月面の過酷な環境で争うために作られたパワードスーツをまとう兵士だ。

## 再現手順

上記のようなモンスターの場合常に発生。

## 期待される正常な動作

正しく射撃威力が反映されるようにする。

馬鹿馬鹿の下記で修正できたはず、だが微妙なのでもう少し修正しつつこちらに反映する。
https://github.com/sikabane-works/bakabakaband/pull/3620/commits/55e0850212bdb0c1c9f6101198ef8ab81667c9d7

**Comment by dis-** [comment]
#4052 により問題が消滅したためCloseします
