### ISSUE TITLE
【バグ】 ケット・シーを殺したらハングアップ

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#3595]
## 環境
Windows Alpha89

## バグの詳細

ケットシーを殺したらハングアップ

**Comment by daradarach** [comment]
[2023-08-16-20-54-43.zip](https://github.com/hengband/hengband/files/12359627/2023-08-16-20-54-43.zip)

たぶんこれがハングアップ時のデバッグセーブなんですが普通に起動しちゃったしよくわかりませんでした

**Comment by Slimebreath6078** [comment]
質問ですが、そのケット・シーはどこで倒したか覚えていらっしゃいますか？

**Comment by Slimebreath6078** [comment]
ありがとうございます。ではもう一つ質問をいたします。
どのようにしてケット・シーが地上に出現していましたか？

**Comment by daradarach** [comment]
トランプ領域の召喚魔法を使ったところ敵対召喚されました

**Comment by Slimebreath6078** [comment]
ありがとうございます。
バグの原因と対処法が掴めたので自分の方から修正をしてみます。
