### ISSUE TITLE
アイテムフラグ「SUPPORTIVEの新設」

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#360]
現在マンゴーシュと脇差の非利き手への装備のボーナスの判定は武器種を見て行っている。
そこで、新しいアイテムフラグの「SUPPORTIVE」を新設してフラグがあればボーナスを得られるようにする。

二刀流ボーナスについてはすでにEASY2_WEAPONフラグがあるため、将来的には、利き手にEASY2_WEAPON、反対の手にSUPPORTIVEを装備していたらボーナスが得られるといった拡張を行いやすいと思われる。

**Comment by sikabane-works** [comment]
別件もあったのでSUPPORTIVEだけ先行に実装させてもらいました。クロスチェックにお手数おかけしました。

**Comment by iks3** [comment]
すでにマン・ゴーシュ、脇差及びそれらの★にフラグ追加済みで、あとは追々新アイテム等に追加すればよいのでクローズします。
