### ISSUE TITLE
【バグ?】 荒野でレベルテレポを読んだときの移動先が以前と変わっている

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3611]
## 環境

- OS: Mac App 版　
- バージョン: 3.0.0Alpha88

## 詳細

街または荒野でレベルテレポを読むと最後に帰還したダンジョンの入口がある荒野に移動する
v2.2.1 及び Alpha78 の時点ではダンジョン内に移動する

## 再現手順

1. 新規キャラで開始
2. イークの洞窟に入る
3. 辺境の街に戻る
4. レベルテレポを読む
5. イークの洞窟の1階ではなくイークの洞窟の入口の上に移動している

**Comment by Hourier** [comment]
少なくとも意図しない仕様変更です
まずは調査します
