### ISSUE TITLE
【バグ】[3.0.0 alpha79以降~alpha89(現時点最新版)]でタイル適応時警告が表示されてタイルを使用することができない。

### ISSUE THREAD

**Issue by pacchinot** [hengband/hengband#3620]
## 環境

- OS: [Windows 版]
- バージョン: [3.0.0Alpha79以降~alpha89(現時点最新版)]

## バグの詳細

alpha79以降~alpha89{現時点最新版}のWindows版でタイルを使用しようとすると「ビットマップ''を読み込めません。」「グラフィクスを初期化できません!」という警告が出てタイルを適応することができない

## 再現手順

1. オプションを選択する
2. 旧タイルを選択
4. バグが発生。警告「ビットマップ''を読み込めません。」「グラフィクスを初期化できません!」が表示、タイルを適応することができない

どのセーブで行っても再現できるはず

## 期待される正常な動作

手順2の後タイルが適応される
alpha78以前のwindows版では機能している

## スクリーンショット

![名称未設定](https://github.com/hengband/hengband/assets/144972292/8c25fb70-2555-4483-8767-f37b407e17fe)

## 補足事項

試しにタイルをmultilockon123様の更新したものに入れ替えてみましたが、同じくalpha79以降では適応できませんでした。

**Comment by Hourier** [comment]
#3571 で修正済です
リリースまでしばらくお待ち下さい
