### ISSUE TITLE
【バグ】タイルの情報を読み込むとキャラクターが正常に表示されない

### ISSUE THREAD

**Issue by multilockon123** [hengband/hengband#3675]
## 環境

- OS:Windows
- バージョン: 3.0.0Alpha90以降

## バグの詳細

タイルの情報を読み込むとキャラクターが正常に表示されない

## 再現手順

1. タイル表示にする
2. 画面表示の設定から「ユーザー設定ファイルのロード」を実行
3. キャラクターが正常に表示されなくなる（アイテムと地形は影響なし）

正常に動作していたこともあるが条件不明。

## 期待される正常な動作

prfファイルに記録したタイルが表示される

**Comment by Hourier** [comment]
ご報告ありがとうございます
事象再現できました
詳細調査を行いますのでしばらくお待ち下さい

**Comment by Hourier** [comment]
v2.2.1 の時点で、プレイヤー(＠)は上記手順でASCIIに戻ってしまう事象も確認しました
これは別件として対応します

**Comment by Slimebreath6078** [comment]
適当にそれぞれの 色/文字 情報書き出してそれをロードしたところモンスターシンボルに関するものが含まれてる場合はバグり、それ以外ではバグらなかったので恐らくユーザー設定ファイルのロードでモンスターの表示情報を更新する際にバグが発生していると考えられます
まだ特定には至っておりませんが、途中経過として報告しておきます

**Comment by Slimebreath6078** [comment]
@multilockon123 
お手数ですが、ユーザー設定ファイルをテキストエディタで開いてみて、`R:`で始まる行の最後が`0xFFFFFF80`になっているかご確認いただけますでしょうか
そこがわかればこのバグの発生源特定できそうです

**Comment by multilockon123** [comment]
0xFFFFFF80となっている行は３０個確認できます。

また、正常なバージョンと比較するとFFFFFFがつくオブジェクトが正常に表示されていないようです。テキストエディタでFFFFFFを消したものをロードすると正常に表示されました。
現バージョンでprfファイルの書き出しを行った時にモンスターの１～１３５２の行にFFFFFFが書き込まれるようです。

**Comment by Slimebreath6078** [comment]
ご確認ありがとうございます
先ほどFFFFFFが書き込まれないように修正したPRを出しましたので、それでこのバグは解消されると思われます
