### ISSUE TITLE
【バグ】 古いバージョンのデータを読み込むと新規追加ユニークが討伐済みになる

### ISSUE THREAD

**Issue by rurero2** [hengband/hengband#3682]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha90

## バグの詳細
古いバージョンのデータを読み込むと、それまでのバージョンで追加されたユニークが討伐済みになる。
ほぼプレイに影響はないが、レベルの高いユニークモンスターは、ダンプで上位に表示されてしまうので不自然なダンプが出力されてしまう。
https://mars.kmc.gr.jp/~dis/heng_score/show_dump.php?score_id=87255# などのダンプで見られる。

## 再現手順

古いバージョンでデータを作成し、新しいバージョンでダンプを出力または新規追加ユニークを召喚

## 期待される正常な動作

新規追加ユニークがまだ生きている状態になる

## 補足事項

セーブファイル読み込み時の[rd_lore()関数](https://github.com/hengband/hengband/blob/7cb70499b28bc726f8847d3c0f31100d7ccd8765/src/load/lore-loader.cpp#L294C13-L294C20)でモンスターの生存数を含む全ての値を0にしているのが原因のようなので、セーブファイルに無いモンスターは初期状態での生存数に設定し直す。

**Comment by Hourier** [comment]
報告ありがとうございます
内容確認しました
「0にしている」というのは厳密には違っていて、「セーブデータに存在しないモンスターの最大存在数はそもそも何も設定されない (初期値0のまま動かず)」です
これを踏まえて、セーブデータを読み込む前にmonraces\_info が初期化されていることを利用し、セーブデータに存在しないユニークのフラグを初期化するよう修正します

※ 本来MonsterRaceInfo は定義だけ読み込むべきなのに、定義でないフィールドも大量に定義されているのが根本原因です……が、これは今のところv3.0 のリファクタリング対象に含まれておりません。v3.1 以降で根本修正します

**Comment by rurero2** [comment]
修正ありがとうございますm(_ _)m　そういうことだったんですねー
