### ISSUE TITLE
【仕様拡張】他領域の特異点も作る

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#3720]
取り敢えず秘術から

**Comment by Hourier** [comment]
詳細：
現在、特異点クエストは仙術・カオス・自然しかない
生命などの領域についても確定で4冊目が手に入る仕組みがあると嬉しいというDiscord のコメントと、その場のノリと勢いで本チケットの作成に至る
取り敢えず秘術にしてもらったのは、4冊目が店売りでクエスト自体の存在価値が低く、どんなクエスト内容になっていても誰からも文句が出なさそうという実験も含んでいるため

備考1：PRを見る限りノーコードで追加できた模様
備考2：秘術以外の領域についてはマイルストーンは未定
