### ISSUE TITLE
ウィザードモードの任意魔法効果("@"コマンド)の拡張

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#374]
OSDNの https://osdn.net/projects/hengband/ticket/39832 でひとまず機能を加えたものをさらに拡張していく。

* 単純に使える効果を増やす。
* 効果の一覧を?キーなどで出力できるようにする。

**Comment by iks3** [comment]
思い立ったときに徐々に追加するという感じで行けばよいかと思いますので、一旦クローズさせていただきます。

**Comment by sikabane-works** [comment]
了解です。ありがとうございます。
