### ISSUE TITLE
【バグ】 トラップが仕掛けられた箱を開けるとクラッシュ

### ISSUE THREAD

**Issue by rurero2** [hengband/hengband#3747]
## 環境

- OS: Windows10
- バージョン:  3.0.0Beta など

## バグの詳細

トラップが仕掛けられた箱を開けるとクラッシュ

## 再現手順

１．マルチ・トラップの仕掛けられた大きな鋼鉄の箱を用意
２．悪魔召喚トラップが作動するまでデバッグモードで生成して開ける
３．画像のようなメッセージが表示される

再現確率は大きな鋼鉄の箱100個生成して1個程度。5回再現に成功しメッセージは全て下記のものだった。
悪魔ではなくドラゴンが生成されればクラッシュしない。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付
▼足元の箱(トラップ厳選済み)を開けると比較的高い確率で発生する
[箱バグ.zip](https://github.com/hengband/hengband/files/13418081/-.-.6.zip)

## 期待される正常な動作

クラッシュしない

## スクリーンショット
![箱バグ](https://github.com/hengband/hengband/assets/108442898/4d57c152-d042-4916-8242-88403ee8f972)
![vs箱バグ](https://github.com/hengband/hengband/assets/108442898/8bce92ab-960f-4a38-8833-2eb4399a88b6)

## 補足事項
原因は、おそらくトラップの処理にある。トラップで火炎の爆発が発生→召喚→箱の中身を生成という順の処理になっているので、火炎の爆発で箱が燃えてしまい、箱の中のアイテム生成時に無を参照してしまう。
https://github.com/hengband/hengband/blob/fcd5c6f3af256c644b660c2b0c8d6982b2e76663/src/specific-object/chest.cpp#L239

**Comment by Hourier** [comment]
報告ありがとうございます
状況から修正方針がハッキリしましたので対応します
なお、以下のデバッグコマンドで任意のトラップを設定可能です
(注：この機能、諸事情によりその内色々手を入れます)

^A → o → 箱を選択 (足元でも可) → t(weak) → trap.cpp のchest\_traps にある箱トラップ種別番号を指定 → a(ccept)
