### ISSUE TITLE
【バグ】 乗馬した騎兵でアリーナで勝利すると外に出られない

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3791]
## 環境

- OS: Mac App & X11
- バージョン: 3.0.1Beta3

## 詳細

乗馬した騎兵でアリーナで勝利すると外に出られない

## 再現手順

1. 騎兵で始める
2. テルモラのアリーナに乗馬したまま入場する
3. 敵を倒す
4. 出口に移動する

## 補足事項

溜まり場の報告です

**Comment by Slimebreath6078** [comment]
#3796 で解決済みのためClose
