### ISSUE TITLE
【バグ】 ペットを殴ろうとしたときにカーソルが変なところに出る

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#3793]
## 環境

- バージョン3.0.1.3beta

## バグの詳細

ペットを殴ろうとしたときにカーソルが変なところに出る
![image](https://github.com/hengband/hengband/assets/78687408/01edd873-112e-4b59-ad2f-ea5ce1f7432a)

## 再現手順

ペットを殴ろうとするとモンスターの体力ゲージ周りのあたりにカーソルが出現する

**Comment by rurero2** [comment]
少なくともAlpha78からあるバグで、オプションの「キー待ちしないで連続でメッセージを表示する(auto_more)」をいいえにしていると発生するようです。オプション変更で発生しなくなるのはhttps://github.com/hengband/hengband/blob/6f427c9cd7afb2aae8927f4fb01127746a842004/src/core/asking-player.cpp#L294 のhandle_stuff()処理が入るため？
