### ISSUE TITLE
【バグ？】 経験値吸収のエゴで最大経験値が現在経験値と同量減少する

### ISSUE THREAD

**Issue by jiro-r** [hengband/hengband#3820]
## 環境

- OS: 例: Windows 版
- バージョン: 3.0.0Alpha15

## バグの詳細

経験値吸収のついた悪魔の鎧を装備して経験値吸収が発生すると、最大経験値が現在経験値と同量減少する。
（経験値が最大値より下がっている表示にならない）

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 経験値吸収のついた悪魔の鎧を装備する
2. 経験値吸収の効果が出るまで時間を経過させる
3. バグが発生

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

経験値欄は現在経験値が最大経験値より低くなっていることを示す表示になる。
（最大経験値の減少は現在経験値の減少より少ないと思っていましたが、誤りでしたら誤報です）

**Comment by jiro-r** [comment]
バージョンは 3.0.1.5-betaの誤りです。申し訳ありません

**Comment by dis-** [comment]
装備の呪いによる経験値の減少は経験値の現在値と最大値を同時に同量減らします。
正常動作です。
