### ISSUE TITLE
【バグ】 「directory_iterator::directory_iterator: パラメータが間違っています」エラーで起動できない

### ISSUE THREAD

**Issue by ArrR-9** [hengband/hengband#3858]
## 環境

- OS: Windows vista 32bit
- バージョン: hengband-3.0.1.7-Beta-jp

## バグの詳細

hengband.exeをダブルクリックすると「[配列を初期化しています... (街)]」の段階で以下のエラーで起動しない

---------------------------
予期しないエラー！
---------------------------
directory_iterator::directory_iterator: パラメータが間違っています。: "C:\Utility\game\ローグライク\Hengband-3.0.1.7-Beta-jp\lib\edit\towns"

開発チームにエラー情報を送信してよろしいですか？
※送信されるのはゲーム内の情報のみであり、個人情報が送信されることはありません。

## 再現手順

1.https://hengband.github.io/index.html から
　[Windows(日本語版)](https://github.com/hengband/hengband/releases/download/3.0.1.7-Beta/Hengband-3.0.1.7-Beta-jp.zip)を
　ダウンロードする
2.適当なフォルダに解凍する
3.hengband.exeをダブルクリックする

## 補足事項

hengband-2.2.1rは起動できます。
angband-initializer.cppにエラーの記述を見つけられたんですが、素人には理解できませんでした。
XPとかVistaだと最新版はもう動かないんでしょうか。

**Comment by Hourier** [comment]
返答遅くなりました
1点確認頂きたいポイントがあります

hengband.exe が含まれるパスを「ASCIIのみ」にして起動を確認してみて下さい
日本語などのマルチバイト文字が悪さをしている可能性があります
例：
C:\Games\Hengband\Hengband.exe

※1
Windows 8.1 以前は、少なくとも今いる開発メンバーで動作確認は行っておりません
上記手順で起動しなかった場合、Vista では起動しない可能性があります

※2
Vista は2012年にMSのサポートが終了しています

**Comment by ArrR-9** [comment]
返信ありがとうございます。

例として教えていただいたパスに変更しての起動や、Cドライブ直下に「hengband」フォルダを作成後に「hengband.exe」含む全ファイルを移動しての起動と試してみましたが、同じエラー「[配列を初期化しています... (街)]でエラー」が出てしまいました。
変愚3.0～はVistaでは動かないっぽいですね。

これは覚悟していたので、最近も更新があるLinux（Debian系）でやろうとしたんですがBGMとか効果音の鳴らしかたがわからず
「[開発への質問はこちらまで](https://github.com/hengband/hengband/discussions/356)」に質問させてもらっていました。

この質問にどなたか答えてもらえるとありがたいです。
こっちの問題も解決できそうになければ、Vistaで変愚2のクリアを目指そうと思います。

**Comment by ArrR-9** [comment]
過去バージョンの変愚蛮怒があるみたいなので、いくつかダウンロードしてみたら
「Hengband-3.0.0Alpha6-jp」～「Hengband-3.0.0Alpha78-jp」まではVistaでも動くっぽいです。
「Hengband-3.0.0Alpha79-jp」～はエラーです。

Alpha78～79までの間に更新がいっぱいあって素人にはよくわかりませんが、このタイミングでVistaは切られちゃったみたいです。

**Comment by Hourier** [comment]
調査の結果、α79でdirectory\_iterator を利用する形にソースコードの変更を行っていました
このソースコードにVistaが対応していないというのが現状のようです

念のためもう1件、XP互換モードで動くか確認頂けますか？
下記ページの下部、「互換性を手動で設定する方法」をご参照下さい
これでも動かない場合、サポートも切れて久しいOSですので動作不能ということでご了承下さい
https://www.fmworld.net/cs/azbyclub/qanavi/jsp/qacontents.jsp?PID=0207-2872

(Linuxの方は別剣対応する予定です)

**Comment by ArrR-9** [comment]
下記バージョンの「hengband.exe」プロパティより「互換モード」を試してみましたが、
「[配列を初期化しています... (街)]」でエラーとなり起動できませんでした。
詳しく調べたわけではありませんが、おそらく起動できないものと思います。
本件、お付き合いいただきありがとうございました。

■試したバージョン
Hengband-3.0.0Alpha79-jp
Hengband-3.0.1.7-Beta-jp
Hengband-3.0.1.9-Beta-jp

■試した互換モード
Windows Server 2003 Service Pack 1
Windows XP Service Pack 2
Windows 2000
Windows NT 4.0 Service Pack 5
Windows 98 / Windows Me
Windows 95

■実際のエラーメッセージ
---------------------------
予期しないエラー！
---------------------------
directory_iterator::directory_iterator: パラメータが間違っています。: "C:\Hengband\lib\edit\towns"

開発チームにエラー情報を送信してよろしいですか？
※送信されるのはゲーム内の情報のみであり、個人情報が送信されることはありません。

---------------------------
はい(Y)   いいえ(N)   
---------------------------

**Comment by Hourier** [comment]
確認ありがとうございました
解決に至らず残念です
それでは本件クローズ致します
