### ISSUE TITLE
【バグ】 水棲生物がおかしい？

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#3873]
## 環境

- OS: Windows 版、
- バージョン: 3.0.1.8-Beta-jp

## バグの詳細
水棲生物が水辺のない陸上に生成され、なおかつ陸上を移動できる。
また下水道クエストにいるはずの何体かのモンスターが不在。

## 再現手順
1. 下水道クエストに挑む

## 期待される正常な動作
水棲生物が水中に生成され陸上を移動しない。

## スクリーンショット
![水棲生物が水辺でないところに生成され陸上でも移動する](https://github.com/hengband/hengband/assets/79730818/48fcc7c6-8726-40f3-8eab-cf9ae21ba3f5)
## 補足事項
プレイ途中のため詳しく検証できていませんが、
ダンジョン内にて陸上でジャイアント・ピラニアに遭遇。
下水道クエストには白ワニ、深い水たまりがいませんでした。浅い水たまりはいました。
リリースノートにクエスト内容変更等はないので不具合を疑い報告します。

**Comment by meetname** [comment]
新規セーブを作りデバックモードで確認したところ
下水道にはちゃんと深い水たまりと白ワニが存在するのを確認したので下水道クエストの件は取り下げます。
さすがに白ワニのいるいないを勘違いはしないと思うのですが。

**Comment by iyukyo** [comment]
3.0.1.7-Betaで新規作成したセーブファイルを3.0.1.8-Betaで読み込むことで、ピラニアが陸上を移動することと、下水道に白ワニが配置されていないことを確認しました。

**Comment by Slimebreath6078** [comment]
ご報告ありがとうございます
原因を突き止めましたので私が対応いたします
