### ISSUE TITLE
Point2D  (Pos2D) クラスの算術演算子オーバーロードの実装

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#3913]
Point2Dクラスの使用が進んできているので、自然な形で2次元座標の演算ができるような算術演算子のオーバーロードを実装する。

イメージとしては、二次元座標の2点間の差を表す Point2DDelta クラスを実装し、

Point2D + Point2DDelta → Point2D
Point2DDelta + Point2D → Point2D
Point2D - Point2D → Point2Ddelta

となる演算子を定義する。Point2D 同士の足し算というのは概念としておかしいので実装しない。
ちなみにこれは STL の `<chrono>` ヘッダにおける、 `std::time_point` クラスと `std::duration` クラスの関係から着想を得ている。

**Comment by Hourier** [comment]
DeltaよりDistanceの方が好ましく思います
ちなみに普段遣いする方のエイリアスはどうしましょうか (Dist2D ？)

**Comment by habu1010** [comment]
いいえ、Distanceはスカラ量なのであまり良くないかと

**Comment by Hourier** [comment]
Discord での議論により「Vector2D (エイリアスはPos2DVec)」が良さそうだという意見が出ました
これならば異論ありません
