### ISSUE TITLE
【バグ】 サーペントのダンジョンの主召喚で敵が出現しない

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#3970]
##### バグレポート #####

サーペントのダンジョンの主召喚で敵が出現しない

## 環境

- OS: Mac App & X11
- バージョン: 3.0.1Beta11

## 詳細

サーペントがダンジョンの主召喚を唱えても敵が出現しない

## 再現手順

1. 適当なキャラで始める
2. サーペントにダンジョンの主召喚を唱えさせる
3. 何も出現しない

## 補足事項

溜まり場の報告です

**Comment by rurero2** [comment]
summon_specific_typeがグローバル変数ではなくなったことで[monster-util.cppの270行目](https://github.com/hengband/hengband/blob/84131a65b9edb89540307813daadea07a46c4950/src/monster/monster-util.cpp#L270)が機能しなくなった？

**Comment by sikabane-works** [comment]
こちらでもダンジョンの主召喚処理ですっからかんなのを確認。

**Comment by sikabane-works** [comment]
![image](https://github.com/hengband/hengband/assets/61610939/b2061790-091d-433b-b8a2-f92dfd5c7a9c)
水地形がドバーっと噴き出ることはあるんすがやはり空。

**Comment by sikabane-works** [comment]
`summon_specific()` 内 `get_mon_num_prep()` から得られるモンスター候補が0になっているところまで確認。

**Comment by sikabane-works** [comment]
`get_mon_num_prep()` 中の参照しているグローバル変数 `summon_specific_type` がヘッダ上の宣言もなくアクセスできず常に0になっているために、クエストやガーディアンの主が常に候補から除外される状態になっているのが原因でした。
多分これまでの方針の限りでは、このグローバル変数をブチ転がす能動的修正で何とかする必要がありそうです。
