### ISSUE TITLE
【バグ】 キャラメイク画面で負の経験値修正が正しく表示されない

### ISSUE THREAD

**Issue by rurero2** [hengband/hengband#3972]
## 環境

- OS: Windows10
- バージョン:3.0.1.11-Beta-jp

## バグの詳細

経験値修正が負の値になるとキャラメイク画面での経験値修正が正しく表示されない。
ドワーフ観光客(-5%)で+65531%、人間観光客(-30%)で+65506% となる。観光客の職業説明画面は-30%と正しく表示される。

## 再現手順

1. 新規キャラ作成を始める
2. 人間観光客を選ぶ
3. 経験値修正が+65506%となる

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

負の経験値修正が表示される

## スクリーンショット

![heng_wrong_exp_penalty](https://github.com/hengband/hengband/assets/108442898/d37cfd31-99ab-44c6-9f49-692b3e0ed099)

## 補足事項

経験値修正の計算は[birth-stat.cpp 94行目](https://github.com/hengband/hengband/blob/84131a65b9edb89540307813daadea07a46c4950/src/birth/birth-stat.cpp#L94 )で行われておりuint16_t型を返している
画面表示は[birth-wizard.cpp 285行目](https://github.com/hengband/hengband/blob/84131a65b9edb89540307813daadea07a46c4950/src/birth/birth-wizard.cpp#L285)で行われている

**Comment by Hourier** [comment]
ご報告＆調査ありがとうございます
これを元にこちらでも確認＆修正してみます

**Comment by rurero2** [comment]
修正ありがとうございます🙇‍♂️
