### ISSUE TITLE
MonsterRaceDefinitionを可読性のある形式に変換する

### ISSUE THREAD

**Issue by dis-** [hengband/hengband#3991]
ヒューマンエラー多発地帯なので多少コストをかけても改善する価値はありそう。
jsonとかにしておくと扱いが楽だろうか？

**Comment by Hourier** [comment]
ついでにベースアイテムやアーティファクト、エゴに地形に荒野＆街と、類似のファイルは全部いい感じのフォーマットにまとめてしまいたいですね？
(なお工数は後で考えるものとする)
