### ISSUE TITLE
設定ファイルのJSON形式化に伴うチェックサムの問題

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#4021]
現在、ダンプの最後に `lib/edit/` 以下にある各種設定情報を記載した txt ファイルの内容を SHA-256 でハッシュダイジェスト化した値がチェックサムとして記載されており、これをもって公式が配布しているデータでプレイしていることの（一応の）証明となっている。
現在 #4018 でモンスター設定情報を json 形式化する作業が進められているが、従来の txt 形式のファイルをパースする枠組みから外れるため、モンスター設定情報がチェックサムに反映されなくなる。
この問題をどう取り扱うか、方針を決める必要がある。

- jsonファイルを別口でハッシュに加える
- もうチェックサムとか気にしない

など。

**Comment by Hourier** [comment]
配布するファイルそのもののハッシュを取っても良いようには思います
根拠が雑すぎますがご参考下さい
- エンコード変換はテキストとして読み込む時に行うのでバイナリとして読み込んでしまえば常にUTF-8扱いになる……はず？
- 過去のバージョンでは上記エンコーディングの問題とも絡みフレーバーテキストはハッシュ計算の対象外だったが、おそらくフレーバーだけ変えて遊ぶ人はかなりレアと思われる (多分)

**Comment by dis-** [comment]
読み込んだJSON Object全体をdumpしてハッシュを取る形で実装しました。
