### ISSUE TITLE
【バグ】 schema directory is not included in the output of 'make dist'

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#4047]
## 環境

- OS: macOS 12.7.4
- バージョン: 3.0.1Beta12 plus changes up to 4d919d06df05a9a743aead5944a4df224fdb34d2

## バグの詳細

The .tar.gz file generated by running 'make dist' (after having set up a configure-based build) does not include the schema directory and its contents.

## 再現手順

1. Run ./bootstrap in the top-level directory.
2. Run './configure --disable-net --disable-worldscore' in the top-level directory.
3. Run 'make dist' in the top-level directory.
4. Run 'gunzip -c hengband-3.0-.1.12-Beta.tar.gz | tar -tBf - | grep schema' in the top-level directory to see if any paths in the archive include 'schema'.

## 期待される正常な動作

The .tar.gz file generated by 'make dist' includes the schema directory and its contents.

**Comment by Hourier** [comment]
Thank you for the report.

Please note that current schema denies empty flavor text.
Some monsters don't define flavor text, so English version will not run correctly.
Now our team is fixing it.
