### ISSUE TITLE
【バグ】 English version halts reading ArtifactDefinitions.jsonc

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#4106]
## 環境

- OS: macOS 12.7.4 with Apple's clang 14.0.0
- バージョン: 3.0.1Beta12 + changes up to 8fa0147414a271b3c5155b96e6c4be4d101f6e85

## バグの詳細

At startup with the English version using the curses frontend, the game exits with the message "Error in 'ArtifactDefinitions.jsonc' file." Running the game under a debugger with a breakpoint set at info-reader/artifact-read.cpp:495 indicates that the error is with the flavor text of artifact 149.  That artifact is the Yasaka-no-Magatama, the first artifact which lacks flavor text in English.

## 再現手順

From the top-level directory of the distribution run

1. ./bootstrap
2. ./configure --disable-japanese --disable-worldscore --disable-net CXXFLAGS="-g -O0"
3. make
4. src/hengband -mgcu

## 期待される正常な動作

The English version starts successfully and an artifact which does not have flavor text in English does not cause an error when parsing ArtifactDefinitions.jsonc.

**Comment by dis-** [comment]
Thanks for Reporting.
Fixed at #4108
