### ISSUE TITLE
【Documentation】shield activations in jdefend.txt 

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#411]
## 環境

- OS: Any
- バージョン: 3.0.0Alpha8

## バグの詳細

Google Translate gives translations that say that the shields of acid, electric, and fire resistance activate for temporary cold resistance rather than temporary acid, electric, or fire resistance, respectively.  Is that a mistake in the translation or a problem with the Japanese text in lib/help/jdefend.txt, lines 146 - 161?

**Comment by iks3** [comment]
Thank you for your report,

These are problems in lib/help/jdefend.txt.
Each of shields of acid, electric or fire resistance can activate for temporary acid, electric or fire resistance.
