### ISSUE TITLE
【バグ】 object's damage sides is zero triggering infinite loop in MeleeWeaponEnchanter::strengthen()

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#4130]
## 環境

- OS: macOS 12.7.4
- バージョン: 3.0.1Beta12 + changes up to bd421768ae67928eefee61b966fee28a9d9a794c

## バグの詳細

With the English version, recalled to a dungeon, Castle, from Morivant and the game hung.  Examining the state of the game in lldb gave this as the top of the call stack:

1. 0x00000001002a7156 hengband`rand_range(a=0, b=-1) at z-rand.cpp:71 [opt]
2. 0x00000001001b7319 hengband`MeleeWeaponEnchanter::strengthen() [inlined] int randnum0<int, int>(initial_max=<unavailable>) at z-rand.h:46:79 [opt]
3. 0x00000001001b72f9 hengband`MeleeWeaponEnchanter::strengthen() [inlined] int randint0<int>(max=<unavailable>) at z-rand.h:53:12 [opt]
4. 0x00000001001b72f9 hengband`MeleeWeaponEnchanter::strengthen(this=0x0000600000d24f00) at melee-weapon-enchanter.cpp:53:12 [opt]
5. 0x00000001001b037c hengband`ItemMagicApplier::execute(this=0x00007ff7bfef9b98) at item-magic-applier.cpp:61:16 [opt]
6. 0x000000010009545c hengband`make_object(player_ptr=0x0000000100424890, j_ptr=0x00007ff7bfef9bf0, mode=0, rq_mon_level=<unavailable>) at floor-object.cpp:145:72 [opt]
7. 0x00000001000a407a hengband`place_object(player_ptr=0x0000000100424890, y=27, x=190, mode=0) at object-placer.cpp:86:10 [opt]
8. 0x000000010009a4ef hengband`alloc_object(player_ptr=0x0000000100424890, set=ALLOC_SET_ROOM, typ=<unavailable>, num=11) at object-allocator.cpp:231:13 [opt]
9. 0x000000010008d31d hengband`cave_gen(PlayerType*, char const**) [inlined] allocate_dungeon_data(player_ptr=0x0000000100424890, dd_ptr=0x00007ff7bfef9dc0, d_ptr=0x0000000102067f00) at cave-generator.cpp:380:5 [opt]
10. 0x000000010008d20c hengband`cave_gen(player_ptr=0x0000000100424890, why=0x00007ff7bfefd448) at cave-generator.cpp:456:10 [opt]
11. 0x0000000100092cb0 hengband`generate_floor(PlayerType*) [inlined] level_gen(player_ptr=0x0000000100424890, why=0x00007ff7bfefd448) at floor-generator.cpp:335:12 [opt]
12. 0x0000000100092c72 hengband`generate_floor(player_ptr=<unavailable>) at floor-generator.cpp:516:20 [opt]
13. 0x000000010008efe8 hengband`change_floor(PlayerType*) [inlined] generate_new_floor(player_ptr=0x0000000100424890, sf_ptr=0x00000001003cf2b0) at floor-changer.cpp:352:9 [opt]
14. 0x000000010008eefb hengband`change_floor(PlayerType*) [inlined] update_floor(player_ptr=0x0000000100424890) at floor-changer.cpp:406:9 [opt]
15. 0x000000010008e98b hengband`change_floor(player_ptr=0x0000000100424890) at floor-changer.cpp:430:5 [opt]
16. 0x0000000100065fed hengband`play_game(PlayerType*, bool, bool) [inlined] process_game_turn(player_ptr=0x0000000100424890) at game-play.cpp:397:9 [opt]
17. 0x0000000100065f60 hengband`play_game(player_ptr=0x0000000100424890, new_game=<unavailable>, browsing_movie=<unavailable>) at game-play.cpp:455:5 [opt]

According to the debugger, this->o_ptr->dd is -382597524 (likely wrapped around by the time I interrupted) and this->o_ptr->ds is 0 at melee-weapon-enchanter.cpp:53.  At the same point, this->o_ptr->bi_id is 48, this->o_ptr->bi_key has HAFTED for type_value and 6 for the subtype_value, and this->o_ptr->ego_idx is KILL_UNDEAD.

## 再現手順

When I forced the process to exit, reloaded the save, and then entered 'R' and '50' to wait for the recall to trigger, the game did not hang during dungeon generation so I don't know a method to reproduce the infinite loop.  The save file attached below is at the point where the character is in Morivant waiting for the recall to trigger.

[Hilda.zip](https://github.com/hengband/hengband/files/15395474/Hilda.zip)

## 期待される正常な動作

The game does not hang when recalling to a dungeon.

**Comment by backwardsEric** [comment]
Saw a similar hang when continuing the game that successfully recalled to the dungeon:  in this case MeleeWeaponEnchanter::strengthen() is called when an object is created upon a monster's death.  this->o_ptr->dd was -1955042159, this->o_ptr->ds was 0, this->o_ptr->bi_id was 43, this->o_ptr->bi_key had SWORD for type_value and 4 for the subtype_value, and this->o_ptr->ego_idx was WEST at melee-weapon-enchanter.cpp:53 when I interrupted the game in the infinite loop and examined its state in the debugger.

**Comment by backwardsEric** [comment]
Perhaps this happens because lib/edit/BaseItemDefinitions.jsonc uses "base_damage" as the name of the field with the base damage string but schema/BaseItemDefinitions.schema.json and info-reader/baseitem-reader.cpp:586 use "base_dice" as the name of that field.

**Comment by dis-** [comment]
Thanks for reporting. Issue is fixed.
