### ISSUE TITLE
モンスターの思い出表示でクラッシュ(英語版)

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#415]
## 環境

- OS: Windows または Any
- バージョン: 3.0.0Alpha9

## バグの詳細

モンスターの思い出の説明文を出すとクラッシュする。

## 再現手順

英語版でゲームを開始して、White Ratの思い出を表示する。
経験値が表示される状態だとクラッシュする。

## 原因

思い出の経験値を表示するためのformat()関数が、int64_tにちゃんと対応できないため。(32bit版でリリースしているため？)
日本語版では大丈夫なようだが、潜在的には同じバグがあると思われる。(たまたま先にレベルをパラメータに入れているから落ちないだけ？)

**Comment by shimitei** [comment]
format()関数の処理を追いかけていくと、%ldの場合は可変長引数からlong型を取って使うようになっていて、引数の型のサイズが合っていないため不整合が出るようです。
8バイト整数用の書式を設けて対応するか、問題が出ないようにformat()の引数に8バイト整数を使わないようにするかですね。

**Comment by iks3** [comment]
なるほど。
いただいている修正はおそらくそのまま採用させていただくかと思います。
