### ISSUE TITLE
【バグ】 反射が的確に魔法を使うの対象外になっている？

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#4174]
## 環境

- OS: Windows 版
- バージョン:3.0.1.12-Beta

## バグの詳細
初期オプションで
モンスターが失敗を学習する　と　モンスターはプレイヤーの弱みを突くが両方ともはいの状態で
@が反射能力を持っている状態にて
的確に魔法を使うことができ、スターライト・アローを使うモンスター（ウサウサストライカーやラファエルなど）が
複数回スターライト・アローを反射されても使用を継続するように思える。

## 再現手順
1. キャラメイクしデバッグモードで反射を持つ装備を生成し装備
2. 任意のモンスター召喚でスターライト・アローを持つモンスター（ウサウサストライカー等）を召喚
3. 死なないよう足踏みする

## 期待される正常な動作
@が反射を持っていることを学習もしくは認識したモンスターは
矢・ボルト系魔法を使わないようにする？

## 補足事項
仮に全く使用しなくなるではなく使用率が下がるだけとしても、
ウサウサストライカーのスターライト・アロー使用率は妙に高いように思える。
ヴォアで実験したところ、複数回反射されても魔力の矢を使用を継続したのでただの仕様かもしれません。
もしバグでなかったら削除してください。

**Comment by habu1010** [comment]
報告ありがとうございます。
最初に予想されていた #4173 の通り、スターライトアロー（とメテオストライク）が反射を学習した時に除外する魔法として扱われていないのが原因でした。
ちなみに、ヴォアについては的確に魔法を使うフラグが無いため25%の確率で除外されないので、学習しても依然として魔力の矢を使用することがあります。
