### ISSUE TITLE
我が家から出るとBasicに指定したBGMが鳴る

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#42]
OSDNより移行。[41477](https://osdn.net/projects/hengband/ticket/41477)

店 (1～7＆9)、及び宿屋等の各種施設では掲題の事象が起きない
テルモラで再現したが他の街はBasicを指定してるので、他でも再現するかは要検証

**Comment by taotao54321** [comment]
`play_music()` 呼び出し引数のログをとってみたところ、我が家および博物館から出た場合のみ `(TERM_XTRA_MUSIC_TOWN, 1)` で呼ばれているように見えました。

`do_cmd_store()` 内の以下のコードが怪しい感じがします。もう少し調べてみます。
https://github.com/hengband/hengband/blob/a3cbda8b7d2ba3e7c643f8e3155da717fe87829b/src/cmd-building/cmd-store.c#L70-L71
