### ISSUE TITLE
`ItemKindType::SKELETON` `ItemKindType::CORPSE` の改名

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#4228]
# 概要

列挙値 `ItemKindType::SKELETON` `ItemKindType::CORPSE` を、適切な名称にする

# 理由

モンスターを倒した時、モンスターは死体か骨を残すことがあるが、これらはそれぞれ `ItemKindType::CORPSE` カテゴリーの `SV_CORPSE` と `SV_SKELETON` である。
一方、 `ItemKindType::SKELETON` は 頭蓋骨の破片・骨の破片・犬の骨・ネズミの骨… といった具合にモンスターとは関係ない固有のアイテムである。
これらが紛らわしいので、検討のうえ `ItemKindType::SKELETON` `ItemKindType::CORPSE` 適切な名称に変更する。

**Comment by habu1010** [comment]
英語版の表現を見たところ、`ItemKindType::CORPSE` の `SV_SKELETON` も、 `ItemKindType::SKELETON` も骨としての表現は 'skeleton' である模様。またモンスターの（骨ではない）死体は 'corpse' とされている。
とりあえず、`ItemKindType::COPRSE` はゲームに出てくるモンスターの「死体」か「骨」であるため、「遺体」や「遺骨」といった意味を持つらしい 'remains' を使用して `ItemKindType::MONSTER_REMAINS` とすることを提案。少なくともサブカテゴリの `SV_CORPSE`、 `SV_SKELETON` との紛らわしさは解消される。

**Comment by Hourier** [comment]
調査お疲れ様です
そうすると、種別としての骨は「FLAVOR\_SKELETON」にしておくと更に取り違えが少なくなると思います
