### ISSUE TITLE
【バグ】 Balrog weaponsmith triggers unhandled exception when eating

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#4237]
## 環境

- OS: macOS 12.7.5
- バージョン: 3.0.1Beta14 English version + changes up to fb4ede76b69b8f5d602c3f96b96aa91209613ea3 + changes from https://github.com/backwardsEric/hengband compiled with clang 14 

## バグの詳細

~~A balrog weaponsmith has an item with added essence (a guisarme of extra attacks with an added cold brand) in the pack.~~
(edit item with added essence is not necessary) When the player tries to eat, the game crashes on an unhandled exception.  Running under the lldb, the message printed immediately before the game quits because of the unhandled exception is "libc++abi: terminating with uncaught exception of type std::logic_error: item-entity.cpp:906: This item is not related to monrace!".

## 再現手順

1. Load the attached save file.
2. Press 'E' to eat.

[Hilda.zip](https://github.com/user-attachments/files/15750349/Hilda.zip)

## 期待される正常な動作

A balrog player does not trigger an unhandled exception by eating.

## 補足事項

If configured with CXXFLAGS as "-g -O0" and run under lldb with a breakpoint at item-entity.cpp:906, the top of the call stack when the unhandled exception is raised is:

1. ItemEntity::get_monrace(this=0x000000010498ba08) const at item-entity.cpp:906
2. item_tester_hook_eatable(player_ptr=0x0000000100be2b00, o_ptr=0x000000010498ba08) at hook-expendable.cpp:38
3. decltype(__f=0x00007ff7bfefcdf8, __args=0x00007ff7bfefc210, __args=0x00007ff7bfefc208)(static_cast<PlayerType*>(fp0), static_cast<ItemEntity const*>(fp0))) std::__1::__invoke<bool (*&)(PlayerType*, ItemEntity const*), PlayerType*, ItemEntity const*>(bool (*&)(PlayerType*, ItemEntity const*), PlayerType*&&, ItemEntity const*&&) at type_traits:3918
4. bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<bool (__args=0x00007ff7bfefcdf8, __args=0x00007ff7bfefc210, __args=0x00007ff7bfefc208)(PlayerType*, ItemEntity const*), PlayerType*, ItemEntity const*>(bool (*&)(PlayerType*, ItemEntity const*), PlayerType*&&, ItemEntity const*&&) at invoke.h:30
5. std::__1::__function::__alloc_func<bool (*)(PlayerType*, ItemEntity const*), std::__1::allocator<bool (*)(PlayerType*, ItemEntity const*)>, bool (PlayerType*, ItemEntity const*)>::operator(this=0x00007ff7bfefcdf8, __arg=0x00007ff7bfefc210, __arg=0x00007ff7bfefc208)(PlayerType*&&, ItemEntity const*&&) at function.h:178
6. std::__1::__function::__func<bool (*)(PlayerType*, ItemEntity const*), std::__1::allocator<bool (*)(PlayerType*, ItemEntity const*)>, bool (PlayerType*, ItemEntity const*)>::operator(this=0x00007ff7bfefcdf0, __arg=0x00007ff7bfefc210, __arg=0x00007ff7bfefc208)(PlayerType*&&, ItemEntity const*&&) at function.h:352
7. std::__1::__function::__value_func<bool (PlayerType*, ItemEntity const*)>::operator(this=0x00007ff7bfefcdf0, __args=0x00007ff7bfefc210, __args=0x00007ff7bfefc208)(PlayerType*&&, ItemEntity const*&&) const at function.h:505
8. std::__1::function<bool (PlayerType*, ItemEntity const*)>::operator(this= Function = item_tester_hook_eatable(PlayerType*, ItemEntity const*) , __arg=0x0000000100be2b00, __arg=0x000000010498ba08)(PlayerType*, ItemEntity const*) const at function.h:1182
9. FuncItemTester::okay_impl(this=0x00007ff7bfefcde0, o_ptr=0x000000010498ba08) const at item-tester-hooker.cpp:95
10. ItemTester::okay(this=0x00007ff7bfefcde0, o_ptr=0x000000010498ba08) const at item-tester-hooker.cpp:85
11. get_item_okay(player_ptr=0x0000000100be2b00, i=0, item_tester=0x00007ff7bfefcde0) at inventory-util.cpp:191
12. get_item_floor(player_ptr=0x0000000100be2b00, cp=0x00007ff7bfefccde, pmt="Eat which item? ", str="You have nothing to eat.", mode=6, item_tester=0x00007ff7bfefcde0) at floor-item-getter.cpp:227
13. get_item(player_ptr=0x0000000100be2b00, cp=0x00007ff7bfefccde, pmt="Eat which item? ", str="You have nothing to eat.", mode=6, item_tester=0x00007ff7bfefcde0) at item-getter.cpp:213
14. choose_object(player_ptr=0x0000000100be2b00, initial_i_idx=0x00007ff7bfefcd5e, q="Eat which item? ", s="You have nothing to eat.", option=6, item_tester=0x00007ff7bfefcde0) at floor-object.cpp:645
15. do_cmd_eat_food(player_ptr=0x0000000100be2b00) at cmd-eat.cpp:345
16. process_command(player_ptr=0x0000000100be2b00) at input-key-processor.cpp:493
17. process_player(player_ptr=0x0000000100be2b00) at player-processor.cpp:317
18. process_dungeon(player_ptr=0x0000000100be2b00, load_game=true) at dungeon-processor.cpp:229
19. process_game_turn(player_ptr=0x0000000100be2b00) at game-play.cpp:371
20. play_game(player_ptr=0x0000000100be2b00, new_game=false, browsing_movie=false) at game-play.cpp:454

According to the debugger, the item passed to get_monrace() is the level 2 demon spell book (this->bi_id is 647; this->bi_key  has a type_value of DEMON_BOOK and a Value of 1) that is the first entry in the weaponsmith's pack.

**Comment by Hourier** [comment]
Thank you for the report.
I'll check and fix it.
