### ISSUE TITLE
【バグ】 ★ものまねの始祖ゴゴのペンダントがものまねののロケットにだけ失率低下効果がない？

### ISSUE THREAD

**Issue by meetname** [hengband/hengband#4260]
## 環境

- OS: Windows版
- バージョン: 例: 3.0.1.14-Beta

## バグの詳細
ものまね師が★ものまねの始祖ゴゴのペンダントを装備しても
暗黒の嵐その他魔法や倍返しの失率低下の効果はあるのに
ロケットのものまねには失率低下効果がないように思える。
ペンダントを装備していようがいまいが、変動しなかった。

## 再現手順
1. ものまね師でキャラメイク
2. デバックモードでLv50にして、サイバーデーモンあたりからロケットをラーニング
3. ★ものまねの始祖ゴゴのペンダントの装備の有無で失率を比較

## 期待される正常な動作
ロケットの失率も低下する。

## 補足事項
ロケットの参照ステータスの腕力が増加すると失率は低下した。
ロケットよりLv,難度が高い暗黒の嵐を習得してペンダントの有無で失率の変化を確認すると、こちらはきちんと効果がある。
気づいた範囲ではロケットだけが例外的に扱われている？

**Comment by dis-** [comment]
ロケットだけが例外的に扱われているということはありません。
使用ステータスが違うため、ステータスによる失率限界が異なるためそのように見えたのだと思われます。
(★ゴゴのボーナスはステータスによる失率限界を超えることはできません)
レベルを下げるなどして限界値より失率が高い状態にすれば正常に動作していることを確認できます。
