### ISSUE TITLE
get_mspeed() をMonsterEntity に組み込む

### ISSUE THREAD

**Issue by Slimebreath6078** [hengband/hengband#4264]
#4240 でMonsterRaceInfo の参照を受け取る引数がconst になっていないためconst 参照を代入する際にエラーが発生した。
このエラーを解決するついでにMonsterEntity のメソッドとして繰り込んでしまう

**Comment by Hourier** [comment]
Discord ではget\_mspeed() と記載しましたが、よく考えるとMonsterRace のspeed であることは自明なので「m」は不要です
更に、モンスターのスピードは非ユニークについては乱数依存なので、getよりmakeの方がベターです (もっと良い単語があればそちらを使ってもOKです)

**Comment by Slimebreath6078** [comment]
Discord 内でこの関数をMonsterRaceInfo のメソッドにするべきなのかどうか議論があり、その結果MonsterEntity に移植することになったため題名・本文を少し書き替え
