### ISSUE TITLE
【バグ】 視界内モンスターリストが更新されない

### ISSUE THREAD

**Issue by knpn329** [hengband/hengband#4277]
## 環境

- OS: Windows
- バージョン: [例: 3.0.1.15(Beta)

## バグの詳細

視界内にモンスターを収めても視界内モンスターリストの更新がされない

## 再現手順
視界にモンスターを入れる
[knpn.zip](https://github.com/user-attachments/files/15857511/knpn.zip)

## 期待される正常な動作
モンスターリストが更新される

## スクリーンショット
![Beta15バグ報告](https://github.com/hengband/hengband/assets/91238926/47a4de87-0085-46a8-96bc-73b34076fb52)

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

Lキーを押してもモンスターリストの更新がされませんでした。
モンスター感知の魔法を唱えた際は更新されるのですが、ターンを経過させてモンスターが見えなくなってもリストに感知で見えたモンスターが残り続けました。

**Comment by knpn329** [comment]
スクリーンショットの補足説明です。
Term-7がモンスターリストに割り当てられているものとなります。

**Comment by Hourier** [comment]
ご報告ありがとうございます
不具合箇所を特定しました
β16で修正予定です
