### ISSUE TITLE
毒の沼で毒状態になる場合の回復処理

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#428]
現状、毒の沼で毒状態になる場合、直後に回復して毒ダメージを食らうタイミングがありません。

> 深い毒の沼に毒された！毒に侵されてしまった！やっと毒の痛みがなくなった。

src/world/world-turn-processor.c 行225-226
```
      process_player_hp_mp(player_ptr);
      reduce_magic_effects_timeout(player_ptr);
```

地形等のダメージ処理(毒沼毒もここ)をしてから即座に回復処理が行われるので、以下のどちらかの対応が必要でしょう。
1) 上記の処理順を前後逆にする
2) 毒沼で毒状態にするときにターン数に回復量分も足す

**Comment by sikabane-works** [comment]
#427 で解決なすったようなので閉じます。お疲れさまでした。

**Comment by sikabane-works** [comment]
こいつはまだ未解決ということでAlpha11にて改めて。
