### ISSUE TITLE
悪魔領域の魔法強化案

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#4331]
### Discussed in https://github.com/hengband/hengband/discussions/4325

<div type='discussions-op-text'>

<sup>Originally posted by **tanguband** June 22, 2024</sup>
### 目的
攻撃魔法4領域のなかで最弱の悪魔を選ばれる魅力のある攻撃領域に強化する

### 現状分析と改善案
カオスは魔力炸裂、カオスボルト、破壊、魔力の嵐
破邪は聖なる光球、ハルマゲドン、神威
暗黒は吸血の連矢、地獄の劫火、幽体化
どの領域も特徴となる魔法がありそれが魅力につながっている
悪魔といえばコレと言われるような特徴的な魔法を導入したい

攻撃のメイン属性は火、地獄、プラズマなので、現在のフレーバーを壊さないように属性は引き継ぎたい

補助魔法は充実している、デュアルを対象に不利にならないような調整を行いたい

自分が実際に触った感触と溜まり場、wikiなどの意見では攻撃魔法のコスパが悪いので改善したい

### 魔法変更案

地獄の矢　->　ファイア・ボルト
ダメージ(6+(レベル-5)/4)d8　消費MPはカオスのファイアボルトより1減らす

地獄の焔　->　地獄球
ダメージ 6d6+レベル2 半径2(レベル30以上で3) の地獄の球
メイジ、ハイメイジ、スペルマスターはダメージ 6d6+レベル3

デーモン支配はリストラ

ファイア・ボールは変更しない

地獄球　->　悪魔火
ダメージ(レベル*5)の火炎の矢
裁きの雷より習得LVは1LV、消費MPは2点、それぞれ減らす

悪魔の目は変更しない

地獄の波動は2冊目の一番最後に移動　習得LV、難度はそのまま、消費MPは半減　

火炎破
ダメージ 200+レベル*2 , 半径4 の火炎の球
習得LVと消費MPを暗黒魔法の吸血の連矢と同じ

サキュバスの接吻は難度を暗黒の嵐やスターバーストと同様に合わせる

士気高揚　->　炎の嵐
ダメージ レベル*15 , 半径 レベル/5 の火炎の球
地獄嵐を基準として習得LVは1LV早めに消費MP、難度は同じにする

**Comment by meetname** [comment]
地獄の焔は序盤の主力魔法かつ越前や死神ももえなど低～中HP善良に対する削りとして深層でも使えますし士気高揚は悪魔の数少ない取り柄なのに消してしまうんですか？

**Comment by dis-** [comment]
discussionにも議論がありますが、調整後の地獄球は十分な威力となるよう調整がされています。
地獄の焔は優秀な序盤の魔法でしたが大きく見劣りするものではないと判断しています。

士気高揚は攻撃魔法の増量のため、削減枠として悪魔領域のフレーバー的に重要でないものを選択しました。
店売りのヒーローの薬で代用できるためゲームへの影響は少ないと考えています。
低コスト微量の回復が重要であると判断した場合、なんらかフレーバー的にふさわしい魔法を別途採用するかもしれません。

**Comment by tanguband** [comment]
士気高揚は #4337 で対応することになりました

**Comment by tanguband** [comment]
士気高揚は [Feature] 悪魔領域魔法 士気高揚を1冊目に追加する #4338 で追加されました
他の部分の調整の意見は ディスカッションの 悪魔領域の魔法強化案 #4325 にお願いします
こちらのissueは一旦クローズいたします
