### ISSUE TITLE
【バグ】 新しい階層生成時(ランダムアーティファクトに発動を付与するとき?)に時々クラッシュする

### ISSUE THREAD

**Issue by qilin-h16** [hengband/hengband#4341]
## 環境

- OS:  Windows 版
- バージョン: 3.0.1.14(Beta)

## バグの詳細

(普段と違う設定としては)初期オプションの常に普通でない部屋ONで、
新しい階層に入るとき、たまにクラッシュする。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 常に普通でない部屋を「はい」にしてキャラクター生成
2. 任意のダンジョンの入り口を何度も出入りする
3. そのうちバグが発生

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

クラッシュしない

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付
![2024-06-25_bugreport](https://github.com/hengband/hengband/assets/144030385/7bea4ed2-2cdb-4d82-ae6e-d38fc527dce9)

## 補足事項

補足事項があれば記載
スクリーンショットを見るとランダムアーティファクト生成の話のようなので、オプションのせいというよりかは試行回数の問題なのかもしれないですね。

**Comment by qilin-h16** [comment]
クラッシュではなく例外発生ですね、すみません

**Comment by dis-** [comment]
#4217 にて修正済と思われます。最新版でもバグが出る場合報告してください。

**Comment by qilin-h16** [comment]
きちんと過去の修正を確認できていませんでした、すみません。
15(beta)では問題なく動作しているように思われます(14が最新だと勘違いしてました)。お騒がせしました。
