### ISSUE TITLE
キャラ作成時の能力値表示にHD、隠密、赤外線視力を表示

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#436]
HDや隠密、赤外線視力の能力値はゲームで重要な項目なのに表示されていないので、キャラクタ作成時に表示している腕力等6能力と経験値修正のほかに、追加で表示してはどうか。
また、オートローラー画面で選択種族、職業、性格の合計の修正値を表示してはどうか。

**Comment by sikabane-works** [comment]
追加終わっているので閉じます。お疲れました。
