### ISSUE TITLE
モンスター遭遇時BGM変更の追加

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#44]
OSDNより移行。[41474](https://osdn.net/projects/hengband/ticket/41474)

せっかく視界内モンスターリストの正常化も果たされたのでそれに伴いBGMを変える機能を検討してみる。

**Comment by shimitei** [comment]
とりあえずドラフト版仕様
モンスターBGM再生のトリガーにしやすいところから対応する。

サブウインドウの視界内モンスターリスト更新時に、
リスト先頭モンスターのBGMを再生する。

（[Monster]にモンスターID毎の設定追加）
モンスターIDに対応するBGMの設定が無い場合は、
次の順に設定を探して再生する。

- ユニーク（[BASIC]に設定追加）
- あやしい影（[BASIC]に設定追加）
- 未知のモンスター（[BASIC]に設定追加）
- 既知の高レベルモンスター（[BASIC]に設定追加）

これらはモンスターリストのソート条件になっているもの。
