### ISSUE TITLE
【バグ】 剣術家の技「幻惑」の説明と実際の効果が異なる

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#440]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha9

## バグの詳細

剣術家の技「幻惑」は、bコマンドでの説明は「視界内の起きている全モンスターに朦朧、混乱、眠りを与えようとする。」となっています。
実際の効果は減速、朦朧、眠りのいずれかで、混乱の効果は発生しません。

## 補足事項

バージョン2.2.1も同じ説明文と効果でした。

**Comment by iks3** [comment]
ご報告ありがとうございます。
混乱を与える処理がすっぽりと抜けているようです。
