### ISSUE TITLE
【バグ】 新規キャラを作成し、名前を入れたところでエラーが出現する

### ISSUE THREAD

**Issue by mfujita47** [hengband/hengband#4418]
## 環境

- OS: Windows 11 Pro x64
- バージョン: Hengband-3.0.1.17-Beta-jp.zip および Hengband-3.0.1.16-Beta-jp.zip

## バグの詳細

新規キャラを作成し、名前を入れたところでエラーが出現

## 再現手順 (必ず出現)

1. 起動する
2. 「新規」を選ぶ
3. キャラメイクする
4. 最後に名前を入れる
5. エラー出現

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付 → ありません

## 期待される正常な動作

ゲームが開始される

## スクリーンショット

![image](https://github.com/user-attachments/assets/e77358c7-0a2e-402a-9338-f0032bd965c5)

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
報告ありがとうございます。
マクロなどが記録されたユーザ個人のprefファイルに依存したエラーである可能性が高いように思えます。
このエラーが発生する状態の lib 以下のファイルを丸ごとzipファイルなどに固めてアップロードしてもらえますでしょうか。
大きすぎる場合は、 lib\xtra\music 以下にある mp3 ファイルは削除して構いません。

**Comment by mfujita47** [comment]
ウェブサイトからダウンロードした zip ファイルを解凍して直後に出るエラーなのですが、アップします。mp3 は削除済みです。
[Hengband.zip](https://github.com/user-attachments/files/16249747/Hengband.zip)

**Comment by habu1010** [comment]
Windowsのシステム設定で、下記の「ベータ：ワールドワイドサポートで Unicode UTF-8 を使用」にチェックが入っていないでしょうか？現在の変愚蛮怒は通常のShift-JISをシステムロケールとしていることを前提としていますので、下記のチェックが入っていると文字コードの変換がうまくいかず、本エラーが発生するようです。
![image](https://github.com/user-attachments/assets/0d52d430-ab6e-4c96-985e-18347850020d)

**Comment by mfujita47** [comment]
承知しました。こちらまたいずれ対応できそうであればお願いします (東方環境はこの設定が必要なので、現時点ではゲームの方をあきらめます)

**Comment by mfujita47** [comment]
ご対応ありがとうございました。起動するようになりました。

**Comment by mfujita47** [comment]
ご対応ありがとうございました。起動するようになりました。

**Comment by habu1010** [comment]
起動するようになったようでなによりです。
解決ということでこのIssueはクローズします。
