### ISSUE TITLE
矢を作成すると骨を全て消費してしまう

### ISSUE THREAD

**Issue by TX105** [hengband/hengband#4441]
## 環境

- OS: windows10
- バージョン: [例: 3.0.0Alpha17]

## バグの詳細

アーチャー職を選択、モンスターの骨を複数スタックして矢を作成すると、一回の矢作成で全ての骨を消費、
骨のスタックが０になってしまう。

**Comment by sikabane-works** [comment]
![image](https://github.com/user-attachments/assets/41490da0-7598-4c63-a1e3-e93f94f51152)
どうも製造したアイテムをそのまま原材料のスロットに上書きするエンバグが起きているようです。

**Comment by sikabane-works** [comment]
修正かけました。報告ありがとうございます。
