### ISSUE TITLE
【バグ】 呪術の「呪力吸収」の説明が不正確？

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#453]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha10

## バグの詳細

bコマンドで呪術の「呪力吸収」の説明を見ると、
「呪われた武器の呪いを吸収して魔力を回復する。」と出ます。

実際には選択肢のメッセージ「どの装備品から吸収しますか？」の通りに
呪われていれば武器以外の装備品も選択できます。

これは説明文の方が間違っているのでしょうか？

## 補足事項

以前のバージョンも武器だけでなく装備品を選択できました。

**Comment by iks3** [comment]
ご報告ありがとうございます。
確認しましたが呪文コマンドでは装備品が選択できて、説明文では武器となっているのはXAngbandからでした。
実装からだいぶ経ちましたので、挙動の方(装備品)を正式として説明文の方は直したいと思います。
