### ISSUE TITLE
【バグ】 ./configure できない【Ubuntu 24.04.1 LTS】

### ISSUE THREAD

**Issue by KawaneRio** [hengband/hengband#4556]
### OS
Ubuntu 24.04.1 LTS

### Version
3.0.1.20-Beta

## 詳細 Description

Readmeには複数の問題があるが、最大の問題はやはり `./confgure` が実行不可能であることと、 Readme に Dependencies の記述が一切無いことだろう。我は最新版の Ubuntu 24.04.1 LTS を使用しているが、やはり初心者ユーザーにソースコードからコンパイルさせるのは難易度が高すぎると感じた。完璧な世界であれば、Windows同様に落して即実行可能なAppImageが望ましいのだが、これはきびしいことを我は知っている。しかしあらゆる手を尽くしてみたが、どうやってでも我にはこのゲームを起動することすら叶わなかった。誰か何か知ってるものがあれば、ぜひ我に知恵を分け与えてほしい。

running ./confgure outputs `bash: ./configure: No such file or directory` out of the box. Says nowhere in the Readme that this game has a *ton* of dependencies, and that `./bootstrap` need to be ran first prior to ` ./configure`. Even after all that, the game still won't compile! If you know a solution to this, please reply in the thread I beg of you.

## 再現手順 Steps to Reproduce

1. 
https://github.com/hengband/hengband/releases/tag/3.0.1.20-Beta を落とし、`~/hengband/hengband-3.0.1.20-Beta` にて展開する。

2. `~/hengband/hengband-3.0.1.20-Beta` Directory 内にて以下の<ruby>駒手<rp>《</rp><rt>コマンド</rt><rp>》</rp></ruby> を実行する：

```
./configure
```

3. `./configure` が失敗したので`./bootstrap`を試みる
```
./bootstrap
```

4. `./bootstrap` が失敗したので https://sweatshop2.hatenablog.com/entry/2020/12/13/164558 の手順に従い、`automake`, `libcurl4-openssl-dev` 及び `autoconf-archive` をインストールしてみる
```
sudo apt-get install automake
```

5. 
```
sudo apt-get install make
```

6. 
```
sudo apt-get install libcurl4-openssl-dev
```

7. 
```
sudo apt-get install autoconf-archive
```

8. 再
```
./bootstrap
```

9. 
```
./configure
```
...失敗。しかしこんどは別のエラーだ。`nkf` が無いらしいのでそれを入れてみる。

10. `nkf`を入れる。
```
sudo apt install nkf
```

11. アプデ
```
sudo apt update
```

12. 再
```
./bootstrap
```

13. 再
```
./configure
```
...失敗。エラーは以下の通り：

```
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
```

`Makefile.in' が無いらしい。調べてみたが、我の技術レベルを遥かに超越している。全くわからなかった。

14. 再
```
./bootstrap
```

15. ダメ元で
```
make install
```

エラー：`ake: *** No rule to make target 'install'.  Stop.` 

## 期待動作 Expected Behavior

1. 変愚蛮怒.AppImageを落し、即実行。~~そもそもなぜLinux民だけソースコードからコンパイルしなきゃいけないのが不便（特に自分のような初心者ユーザーにとって！）~~

## ログ Logs

https://gist.github.com/KawaneRio/a8cc3fcbf4194afe9a2ea663d662b054 

## スクリーンショット Screenshot

![image](https://github.com/user-attachments/assets/a13c0b54-e79a-49c5-b824-2e00c7c923aa)

## 補足事項 Additional Information

同じ問題を体験しているユーザーはリプライなどで知らせてください。
Users with similar issues may chime in via reply.

**Comment by tanguband** [comment]
Makefile.in がないのは lib/xtra の導入ができていないようです

https://github.com/hengband/hengband/wiki/Git%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E9%81%8B%E7%94%A8%E8%A6%8F%E7%B4%84
このページのサブモジュール導入を参考に lib/xtra を入れてみてください

lib/xtra 以下に　sonud　music　Makefile.am などがあればOK
うまく行かない場合は上のページの 新規導入 を参考に git で入れ直してみてください

うまく行った場合は

make clean
./bootstrap
./confifure
make install

でビルドできると思います

もしビルドできない場合はエラーメッセージをあげていただければ再度アドバイスできるかもしれません

**Comment by KawaneRio** [comment]
@tanguband おかげさまでできました！以下、我が環境での導入手順を記載します！

## Hengband を Ubuntu で動かすための手順

1. 以下のコマンドで変愚蛮怒に必要な依存をインストールする

```
sudo apt install git
```

```
sudo apt install gcc
```

```
sudo apt install nkf
```

```
sudo apt install automake
```

```
sudo apt install autoconf-archive
```

```
sudo apt install libcurl4-openssl-dev
```

2. apt を updateする。
```
sudo apt update
```

3. 次に、先程インストールしたGitを使用し、変愚蛮怒のGitリポジトリをローカル環境へと<ruby>写す<rp>《</rp><rt>cloneする</rt><rp>》</rp></ruby>。以下のコマンドは`hengband`という名前のディレクトリーを作成し、その中にGithubからの変愚蛮怒のファイルをすべて入れる。
```
git clone --recursive https://github.com/hengband/hengband.git hengband
```

4. 新しく`hengband`という名前のディレクトリができているはずなので、ディレクトリを開く。
```
cd hengband
```

5. `hengband`ディレクトリ内で、Bootstrapを実行する：
```
./bootstrap
```

6. 次に、Configureを実行する：
```
./configure
```

※ここでエラーが発生することもある。その場合は GitHub にて [Issueを立てる](https://github.com/hengband/hengband/issues/new?assignees=&labels=bug&template=bug_report.md&title=%E3%80%90%E3%83%90%E3%82%B0%E3%80%91+%E3%83%90%E3%82%B0%E5%A0%B1%E5%91%8A%E3%81%AE%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB%E3%82%92%E7%B7%A8%E9%9B%86) ことができます。

7. 無事 Configure ができれば、`make install` を実行する。これにはかなり時間がかかるのでコーヒーでも飲んでゆっくり待とう。
```
make install
```

8. `make install` が終われば、`hengband` ディレクトリ内に `hengband` と言う名前の実行可能なExecutableファイルが生成されるので、それを実行する。
```
./hengband
```

## ログ Log

https://gist.github.com/KawaneRio/37de38d60561f4245c97df7028d648dd

## スクリーンショット Screenshots

![image](https://github.com/user-attachments/assets/8a04cc53-2c09-4928-b61d-0929122962a7)

---

ありがとうございました！
