### ISSUE TITLE
特定財宝ドロップフラグをコード内に組み込む

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#4610]
現在、baseitem-info.cpp/h (近い内にbaseitem-list.cpp/h へ移設予定)にはCREEPING\_COIN\_DROPS テーブルが存在する
しかしこれはMonraceId がキーであり、「モンスターXとYとZは金貨だけをドロップする」という追加・変更に弱い
#4608 でモンスター定義に汎用的なドロップフラグが定義されたので、キーをこのフラグに差し替える
(担当者未定)

**Comment by dis-** [comment]
#4651 にて解決済
