### ISSUE TITLE
ペット騎乗時の加速が乗らない

### ISSUE THREAD

**Issue by gkuraki** [hengband/hengband#466]
## 環境

- Windows10
- 3.0.0Alpha10

## バグの詳細

ペット騎乗時にペット分の加速がプレイヤーに反映されていないように見える

## 再現手順

チャージマンクター騎兵(技能：達人)で九首ヒドラ(+10)に騎乗したが加速が乗らない、スピードモンスターの杖を振っても変化なし。
いかさま人間騎兵でやせこけた馬に騎乗し、スピードの薬をぶつけたが変化なし。

## 補足
developは修正済みらしいですが、ご報告を

**Comment by dis-** [comment]
#465にて例外処理を統一したときに該当のバグがついでに修正されているようです

**Comment by iks3** [comment]
> #465にて例外処理を統一したときに該当のバグがついでに修正されているようです

以下の表示を確認できました。問題ないと思います。
・馬に乗ったときの熟練度による加速(デバグで熟練変更した場合含む)
・馬に乗って足元にスピードモンスターの魔法棒を振ったときの一時加速
・スピードモンスターの魔法棒を振って加速したペットに乗馬したときの一時加速
・スロウモンスターの魔法棒を振って加速したペットに乗馬したときの一時減速
・一時加速/減速の効果時間が切れたときの速度の変更

追伸
乗馬した状態で足元をターゲットにスロウモンスターを振った場合になんの効果も発生しないという別な不具合がありました(回数は減る)。
こちらについては修正するなら別Issueということで。

**Comment by dis-** [comment]
本件は修正が確認できましたのでクローズします。
発覚した別件は#467で対応します。
