### ISSUE TITLE
【バグ】 影分身時にGF_WATERの攻撃が水耐性で軽減されない

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#474]
## 環境

- バージョン: 3.0.0Alpha10

## バグの詳細

GF_WATERの攻撃に対して水耐性があるとダメージが軽減されるようになっているが、
朦朧や混乱などの効果を影分身で回避した場合のダメージに水耐性が考慮されていない。

## 対象ソース

https://github.com/hengband/hengband/blob/d44bedf8685e3f763ac75c444ee65573b68dbefe/src/effect/effect-player-resist-hurt.cpp#L165-L189

**Comment by habu1010** [comment]
それ以前に、`ep_ptr->get_damage` を 1/4 しても意味が無さそうなので、水耐性によるダメージ軽減自体が機能していない気がします。

https://github.com/hengband/hengband/blob/d44bedf8685e3f763ac75c444ee65573b68dbefe/src/effect/effect-player-resist-hurt.cpp#L185-L188
