### ISSUE TITLE
【バグ？】光明エゴのランタンが燃料0でも光っている

### ISSUE THREAD

**Issue by k245ta** [hengband/hengband#4771]
## 環境

- OS: Windows 版
- バージョン: Hengband-3.0.1.23-Beta-jp

## バグの詳細

光明の真鍮のランタンを装備し燃料が0になったが半径1の光源として機能している。

## 再現手順
1. 光明の真鍮のランタンを装備し燃料0まで使い切る
2. バグ(？)が発生。

## 期待される正常な動作

燃料0の時は通常のランタン同様、光源としての機能が失われる（？）

>光明の真鍮のランタン(0ターンの寿命) {明}
>アイテムの能力:
>それは**燃料補給によって明かり(半径 3)を授ける**。
>それは火炎では傷つかない。

## スクリーンショット
・燃料0で光明の真鍮のランタンを装備した状態
　残燃料ありの「半径3」でもなく、素のランタンのように光源機能が完全失われる事もなく、
「半径1」の光源として機能しており巻物も読めます。
![image](https://github.com/user-attachments/assets/500525e8-a338-4c8b-995e-86e41143b7c5)

・燃料0で素の真鍮のランタンを装備した状態
　光源機能は失われ、巻物は読めない。
![image](https://github.com/user-attachments/assets/6f3eb902-f2e3-4020-8563-1cd0343ee298)

## 補足事項

不具合というか気になった程度です。
プレイヤーにとってはメリットであるので強いて修正する必要もないとは思います。
光明エゴの動きがどのように実装されているか分かりませんが、
エゴ効果の半径+1はアイテムの説明と異なり光エゴ防具のように燃料不要の扱いなのかもしれません。
ただうろ覚えですが不朽か灼熱あたりは燃料0だとエゴ効果が無効になってたか(？)
もしそのようなバラつきがあるなら、燃料0の時にエゴ光源の機能を無効化するか、しないかの統一感は欲しい気もします。

**Comment by dis-** [comment]
報告ありがとうございます。
一貫性を重視して燃料切れの場合は光明エゴ由来の永久光源を消す方向で調整します。
