### ISSUE TITLE
性格がコンバットorチャージマンでメッセージの差し替え追加(英語版)

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#48]
OSDNより移行。[41414](https://osdn.net/projects/hengband/ticket/41414)

[#41399](https://osdn.net/projects/hengband/ticket/41399) の関連

元々仕様で、英語版は「性格がコンバットorチャージマンの時でも各種メッセージは差し替えない」としていた
[#41399](https://osdn.net/projects/hengband/ticket/41399)ではクエスト突入時のみ言及されており、例えばテレポアウェイを受けた際やインベントリにダメージを受けた際のメッセージは全て空欄になっている
先のチケットのみ対応すると確実に漏れを起こすのでこのチケットで備忘しておく
(それはそれとしてセリフがリテラルのコピペになっているのは何とかしたい)

**Comment by sikabane-works** [comment]
プルリクを→に指定できませんが、https://github.com/hengband/hengband/commit/678ca4cf383e7d9735e47bc7928b0e50cbdc6e3b
で解決したので閉じます。
