### ISSUE TITLE
【バグ】 勇者の殿堂で性格と種族が違うものになります

### ISSUE THREAD

**Issue by February20** [hengband/hengband#484]
## 環境

- OS: [Windows 版.]
- バージョン: [Alpha10]

## バグの詳細

ゲーム終了（死亡）後、勇者の殿堂で表示される性格と種族が違うものになります

１件目
（送信したスコアの表示・正しい）きれもののmat　ホビット　盗賊 (仙術)
が
（勇者の殿堂・誤り）ふつうのmat　-　エルフ盗賊
と表示されてます。

２件目
（送信したスコアの表示・正しい）ラッキーマンのmat　ホビット　観光客 (秘術）
が
（勇者の殿堂・誤り）ふつうのmat　-　ハイエルフ観光客
と表示されてます。

## スクリーンショット
![無題](https://user-images.githubusercontent.com/80531998/110961884-9ea55a80-8393-11eb-8bff-5729fa591f66.gif)
![無題1](https://user-images.githubusercontent.com/80531998/110962560-75d19500-8394-11eb-99ff-2cd61c6ade6a.gif)

**Comment by iks3** [comment]
ご報告ありがとうございます。

本件は#454にて対応済みですので、クローズさせていただきます。

**Comment by February20** [comment]
失礼しました。オープンだけ見て未報告だと勘違いしました。恥ずかしい(;^ω^)

**Comment by iks3** [comment]
プルリクのCloseを掘り返さないと見れないんでしょうがないです。
