### ISSUE TITLE
fix_monster_listの副作用を分離する

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#50]
OSDNより移行。[41427](https://osdn.net/projects/hengband/ticket/41427)

display-sub-window.c の fix_monster_list() はサブウィンドウの描写のみをするべきである。 現状、なんらかの副作用がターゲッティングの挙動に影響を与えている。 調査・整理するべき。

**Comment by dis-** [comment]
ターゲット処理の初期化問題が改善したため、fix_monster_list()から分離するべき副作用はなくなったと判断する。
