### ISSUE TITLE
【バグ】 モンスターの自爆でスタックオーバーフロー発生

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#505]
## 環境

- OS: Windows 版

## バグの詳細

afa500adde13c84adb697756a953a60480677c07 
のコミット以降に、モンスターが自爆すると処理中に再び自爆が発生しスタックオーバーフローで強制終了する。

## 再現手順

セーブファイル
[saveffile.zip](https://github.com/hengband/hengband/files/6136338/saveffile.zip)

セーブファイルを開いて、爆弾をとりつけられた蚊を攻撃する。

**Comment by iks3** [comment]
ご報告ありがとうございます。
修正できたと思います。α11に取りこめました。
