### ISSUE TITLE
AQUATICつきモンスターの陸上生成の可能性

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#51]
OSDNより移行。[41437](https://osdn.net/projects/hengband/ticket/41437)

![lup13088](https://user-images.githubusercontent.com/78687408/107513457-94a10800-6beb-11eb-88cc-379a011599c7.png)
山の特殊地形にて遭遇。空を飛べはしますが水棲生物であるセイレーンが陸上に生成されています。

**Comment by daradarach** [comment]
deskull:

CAN_FLY持ちだと普通に陸上でも存在していられる上に、生成もされることを確認。それでいいかどうかは検討。

**Comment by daradarach** [comment]
hourier:

[#41006](https://osdn.net/projects/hengband/ticket/41006) もちょっと絡んできそうです

**Comment by sikabane-works** [comment]
Hourierさんより↑OSDNチケットより指摘もらいつつ、話回されたので引き続き対処します。

> 調査した結果、mon_hook_deep_water() --> mon_hook_dungeon() において、WILD_ONLYフラグを持ち、かつダンジョンとモンスター種族のいずれか一方にWILD_MOUNTAINフラグを持たない場合、弾いている
> 
> すなわちそのようなモンスターの存在を前提にしていない設計なので、根っこから変えないといけないかもしれない
> 
> 怪しい挙動だが今すぐ直せそうにもないので一旦保留とする
> 
> 備考：
> 
> 巨大ピンク・ガエルはWILD_ONLY | WILD_SHORE | WILD_SWAMP だが、↑とは異なるコールチェーンを通るのでたまたまOKだった模様
> 
> 具体的には、山や浅瀬ではそもそもmon_hook_dungeon() にブレークポイントを置いても引っかからない
> 
> 浅瀬と海で異なるコールチェーンを通ること自体がどうなのか疑問ではある (現段階では、これ以上深く追いかけないことにする)

**Comment by iks3** [comment]
山及び火山のダンジョン内の話なので、mon_hook_dungeon()関数でしかチェックしていないようですね。
なので、WILD_ONLYフラグを持たない場合、常にTRUEですので深い水にAQUATICなモンスターが生成されていました。

とりえず以下のような感じでいかがでしょうか。WILD_ONLY出ない場合、
・ダンジョンが山と火山以外ならTRUE
・山の場合、AQUATICじゃないか、WILD_ALLまたはWILD_MOUNTAIN持ちならTRUE
・火山の場合、AQUATICじゃないか、WILD_ALLまたはWILD_VOLCANO持ちならTRUE
・それ以外はFALSE

WILD_ALL許容ですと、ピラニアやイクシツザチトルなどは出ます。

```
bool mon_hook_dungeon(player_type *player_ptr, MONRACE_IDX r_idx)
{
    monster_race *r_ptr = &r_info[r_idx];
    dungeon_type *d_ptr = &d_info[player_ptr->dungeon_idx];

    if ((r_ptr->flags8 & RF8_WILD_ONLY) == 0)
        return !test_bit(d_ptr->mflags8, RF8_WILD_MOUNTAIN | RF8_WILD_VOLCANO)
            || (test_bit(d_ptr->mflags8, RF8_WILD_MOUNTAIN)
                && (!test_bit(r_ptr->flags7, RF7_AQUATIC) || test_bit(r_ptr->flags8, RF8_WILD_ALL | RF8_WILD_MOUNTAIN)))
            || (test_bit(d_ptr->mflags8, RF8_WILD_VOLCANO)
                && (!test_bit(r_ptr->flags7, RF7_AQUATIC) || test_bit(r_ptr->flags8, RF8_WILD_ALL | RF8_WILD_VOLCANO)));

    return (test_bit(d_ptr->mflags8, RF8_WILD_MOUNTAIN) && test_bit(r_ptr->flags8, RF8_WILD_MOUNTAIN));
}
```

**Comment by iks3** [comment]
Discordで話をした結果、ダンジョンにマッチした荒野フラグがない水棲動物は出ない方向になりました。
ダンジョン山なら、荒野の山に出られる水棲動物はOK。
ダンジョン火山なら、荒野の火山に出られる水棲動物はOK。
現状いませんが、ダンジョン山には水場ができるので、淡水生物っぽいやつは出てもよさそうなので。

**Comment by Hourier** [comment]
https://github.com/hengband/hengband/issues/51#issuecomment-778155955
の件は完全に別件だということが判明したのでチケットを分割します
