### ISSUE TITLE
通路生成のエンバグ

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#52]
OSDNより移行。[41438](https://osdn.net/projects/hengband/ticket/41438)

![lup13089](https://user-images.githubusercontent.com/78687408/107513641-da5dd080-6beb-11eb-8023-309754c5f721.png)
山にて遭遇。山地形に囲まれ入れない部屋がありました。

**Comment by daradarach** [comment]
taotao:


v2.2.1 でも山で孤立部屋ができる現象を確認しました。スクリーンショットとセーブデータを上げておきます:

    https://osdn.net/ticket/download.php?group_id=541&tid=41438&file_id=5958
    https://osdn.net/ticket/download.php?group_id=541&tid=41438&file_id=5959 

d_info.txt を見ると山だけ外壁 (outer_wall) が永久壁 (MOUNTAIN_WALL) なのが怪しい気もしますが、あまりコードが理解できてないのでまだよくわかりません。

**Comment by daradarach** [comment]
taotao:

テスト用として、永久壁で仕切られた孤立部屋ができるまでフロア再生成(上限1000回)を試みるパッチを書いてみました:
https://osdn.net/users/taotao/pf/hengband/scm/commits/3df441b0db3b021e66a416300b56c616d165410b
プレイヤーの位置から到達不能な領域はトラップ感知済みとして表示するので、view_unsafe_grids を有効にするとわかりやすいと思います。

本件についてはまず要求仕様を明確にする必要があると思います。
自分は今のところ「永久壁のみを壁とみなしたとき、フロア全体は連結でなければならない」という仕様なのかなと推測しています(例えば狂戦士などで到達困難な領域ができると困るため)が、そこまで深く考えたわけではないので他の意見もあるかもしれません。

実装については、上記パッチのコードを流用してフロア全体が連結になるまで再生成を試みる、という方法でも確率的には問題なさそうに思えます。
山でちょくちょく孤立部屋ができるのは build_tunnel2() の失敗が無視されているあたりが原因かと思いますが、ログをとってみるとこの関数は結構な頻度で失敗しているので、根本的な修正は今のところ思いつきません。
いずれにせよ自分は地形フラグなどの細かい部分について把握しきれていないので、実際の修正はより詳しい方にお任せしたいと思います。

**Comment by taotao54321** [comment]
フロアが非連結なら再生成を試みるPRを書いてみました。
が、永久壁と判定するためにどの地形フラグを見ればよいかなどよくわかっていない部分もあるのでとりあえず Draft とし、詳しい方のご指摘などを待ちたいと思います。

**Comment by sikabane-works** [comment]
リリース側としてもひとまず解決できたものとしてノートに記述しておきます。お疲れ様でした。
