### ISSUE TITLE
【バグ】 賢者の塔で魔道具を全てのアイテムを再充填しようとすると 50 feet[y/n] と表示される

### ISSUE THREAD

**Issue by onget** [hengband/hengband#523]
## 環境

- OS: [Windows 版]
- バージョン: [ 3.0.0Alpha12]

## バグの詳細

賢者の塔で魔道具を全てのアイテムを再充填しようとすると
50 feet[y/n]
と表示される(キャンセルしてもう一度全てのアイテムを再充填しようとすると正常なメッセージ(すべてのアイテムを ＄840 で再充填しますか？[y/n])が表示される

## 再現手順

1.賢者の塔に入る
2.全てのアイテムを再充填しようとする

## 期待される正常な動作

正常なメッセージ(すべてのアイテムを ＄840 で再充填しますか？[y/n])が表示される

## セーブデータ、スクリーンショット
[saveSS.zip](https://github.com/hengband/hengband/files/6145666/saveSS.zip)

## 補足事項

なんか前からあった気もする

**Comment by iks3** [comment]
セーブデータありがとうございます。
おかげで調査がすぐでした。
