### ISSUE TITLE
【バグ】 マンションVault探索中にフリーズ

### ISSUE THREAD

**Issue by gkuraki** [hengband/hengband#525]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha12（直前のセーブを添付）,
  及び2.2.1r（以前にも確認）

## バグの詳細

vault[N:20:Greater vault (huge)]を探索中、雰囲気最悪時のBGMが終わると共に変愚がフリーズする

## 再現手順

1. ダンジョンにN:20:Greater vault (huge)が生成
2. ダンジョンの雰囲気が表示され、雰囲気最悪時のBGM(MIDI)が再生される
3. BGMが最後まで再生される
4.変愚が応答しなくなる

## 期待される正常な動作

もう一度雰囲気最悪時のBGMが鳴り始め、普通にプレイが出来るはず

##追記
1, BGMが何週かした後、フリーズするようです
2. 他のmidファイル名やwavファイルを設定した所、再現性を確認できませんでした

[bugrep.zip](https://github.com/hengband/hengband/files/6147488/bugrep.zip)

**Comment by iks3** [comment]
音楽の切り替わり時に前曲の解放を待たずに次曲の再生を始めようとしてそうなので、それが原因のような気がします。
