### ISSUE TITLE
【バグ】 マーフォークの種族による徳が設定されていない

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#532]
## 環境

- OS: すべて
- バージョン: 3.0.0Alpha12

## バグの詳細

通常、選択した種族によって1つ固定で徳が決定されるが、マーフォークにはそれが設定されていない。

## 再現手順

種族マーフォークでキャラを作成し、徳を確認する。
他の種族であれば、必ず種族ごとに定められた1種の徳が固定で設定されるが、マーフォークだとそれが存在しない。

## 期待される正常な動作

マーフォーク以外のすべての種族で種族ごとに定められた徳が設定されるようになっているので、マーフォークもそうなってしかるべきだと思われる。

**Comment by sikabane-works** [comment]
無難に然にしてみました。
