### ISSUE TITLE
リファクタリングに伴うmasterとのマージ漏れ調査

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#55]
OSDNより移行。[41447](https://osdn.net/projects/hengband/ticket/41447)

現状以下の2点が修正済or修正中なので、他にもないか調査したい

    モンスターリスト自動更新機能
    光の剣ダメージが0になる不具合 

＞deskullさん
と言いつつ備忘レベルなのと、当時の細かいコミット状況が不明ですので、お手数ですが調査願います
調査完了＆チケット化次第、このチケットはクローズお願いします (あくまで調査用であって修正用チケットではないので)

**Comment by shimitei** [comment]
参考までに手元のメモでは
masterとFor2.2.2-Refactoringブランチが分離して以降、
masterに取り込まれたプルリクエストは次の３つです。
他にマージ前にmasterにコミットされたものは無いと思います。

1. [「行動前に視界内モンスターリストを更新」オプションを追加](https://osdn.net/projects/hengband/ticket/39637)
2. [Fix Fix a build failure that occurs when --disable-japanese is in effect](https://osdn.net/projects/hengband/ticket/40005)
3. [Feature Add ./configure option "--with-varpath=PATH"](https://osdn.net/projects/hengband/ticket/40011)

**Comment by habu1010** [comment]
確認ありがとうございます。

> 1. [「行動前に視界内モンスターリストを更新」オプションを追加](https://osdn.net/projects/hengband/ticket/39637)

オプションではなくデフォルトで視界内モンスターリストを自動更新する機能として取り込み直されました。

> 2. [Fix Fix a build failure that occurs when --disable-japanese is in effect](https://osdn.net/projects/hengband/ticket/40005)

現在、 --disable-japanese により英語版をビルドする機能は正常に使えているので問題なさそうです。

> 3. [Feature Add ./configure option "--with-varpath=PATH"](https://osdn.net/projects/hengband/ticket/40011)

configure.ac のログを確認しましたが、上記のコミットはマージで上書きされているようなことはなく、残っていました。

**Comment by sikabane-works** [comment]
自分の不始末であったものを確認いただきありがとうございます。問題なさそうならば閉じましょうか。

**Comment by sikabane-works** [comment]
問題なさそうなので閉じさせてもらいます。自分のミスでお手数かけさせてしまいました。
