### ISSUE TITLE
朦朧効果の調整

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#553]
#249 にも関連するが、そもそもダイスの指定次第で朦朧の蓄積量が爆発的に跳ね上がる現在の朦朧蓄積ルール自体にも問題があると判断。

今後追加されるモンスターでも網の目を抜けてしまうケースが多そうなので、ルールの方を間抜けに何ターンも殴り合わない限りは不明瞭まではそうそうないくらいまで調整することを考える。

**Comment by Hourier** [comment]
雑調整の素案ですが、現在0～7の朦朧判定値であるところ、0～14と全部倍にすればある程度問題なくなると思います
AC緩衝手段も豊富になったので、そう簡単には意識不明瞭にはならないかと
ご検討下さい

**Comment by Hourier** [comment]
これ、そろそろ解凍しようかと思います
いかがでしょうか？

**Comment by sikabane-works** [comment]
OKです。どっち主体で行きましょうか。一応こっちで次バージョン中にやってみたいとは思っています。

**Comment by Hourier** [comment]
私の方で↑の件も含めたクラス化の設計アイディアはあるので、一旦引き取ります
PRの結果がダメダメだったら引き継ぎお願いします

**Comment by sikabane-works** [comment]
りょうかいです。とりあえずAssignessにどうぞということで。

**Comment by Hourier** [comment]
このチケット単品でやるには作業量が多いので、後で小チケットを作って分割する
- 朦朧に関する処理を一箇所 (player-status/player-stun.cpp/h)にまとめる
  具体的には以下の3つ
  1. attack-criticality::calc_monster_critical()
  2. bad-status-setter::set_stun()
  3. monster-attack-player::calc_player_stun()

- クラス化する (これだけである程度労力がかかることが分かっているので、これだけで1ブランチとする)
- 適宜メソッド分割を行い、クラスに状態を持たせてエンティティ化する
- 概ね、一撃で意識不明瞭になる閾値を2～3倍に引き上げる
- そもそもの蓄積が始まる閾値自体を上げる
- その他、全体のバランスを見ながら調整

なお、コード上はダメージが21以上の時に朦朧値の蓄積が発生する
一方で、何故か12～20の時も蓄積するかのように見えるデッドコードが存在する
これはVからZがフォークした瞬間には既にあった
最低27年間ほったらかしにされていたクサレ仕様である
「一撃で意識不明瞭になる可能性があるモンスターがいる」は、ゲームがアンバランスなのではなかった
明確かつ致命的なバグである

**Comment by Hourier** [comment]
備考
- 更に↑の前段として、player_raceやらplayer_classやらにも思うところが出てきたので何とかする
  (クラス化できるところは順繰りにやっていかないと永遠に追いつかない)
- バランス調整案：肉体的な要素 (腕力、器用、耐久、AC辺り)で朦朧値を減少させる

**Comment by sikabane-works** [comment]
#1682 とすっかり重複していたようですので閉じます。お疲れさまでした。
