### ISSUE TITLE
【バグ】 自殺時にgameoverのBGMが反映されない

### ISSUE THREAD

**Issue by gkuraki** [hengband/hengband#558]
## 環境

- Windows10
- 3.0.0Alpha12

## バグの詳細

Qy@(自殺)時にgameoverで指定されているBGMが再生されず、直前のBGMが流れたままゲームが終了する。

## 再現手順

1. 勝利せず、Qy@する

## 期待される正常な動作

Qy@時にgameoverで指定されたBGMが再生される

## 補足事項

普通にモンスターに殴られてHPがマイナスになった時は再生される
引退時はちゃんとwinnerのBGMが再生される模様

**Comment by sikabane-works** [comment]
報告ありがとうございます。追加しておきます。
