### ISSUE TITLE
可読性のないファイル名を冗長化する

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#56]
OSDNより移行。[41450](https://osdn.net/projects/hengband/ticket/41450)

lib/ 以下の大半のファイル名が、高々数文字をケチっているせいでファイル名から中身が分からなくなっている。
人類に理解できる名称に変更するべき。
ただし、ファイル名の差し替えは影響が大きいのでどこかキリの良いタイミングでやるべきと思われる。
Beta公開のタイミング等がふさわしいだろうか？

**Comment by Hourier** [comment]
いい加減我慢できなくなった (リファクタリングの足かせになるほど乖離があちこちで出てきた)ので、αの内に直します
むしろこれを契機にβ版と呼んでもいいくらいには大改造しました
実際どうするかはDiscord で相談お願いします
