### ISSUE TITLE
【コンパイルエラー】AndroidのUserLAndのUbuntuでビルドできない

### ISSUE THREAD

**Issue by pachenya** [hengband/hengband#560]
バージョン : 3.0.0Alpha12
【コンパイルエラー】AndroidのUserLAndのUbuntuでビルドできない

tar.gz　のファイルを解凍後、
./bootstrap
./configure -without-x
と打ち、configureの最中

./configure: line 3707: AX_CXX_COMPILE_STDCXX_17: command not found
というメッセージが含まれる。

In file included from ./object-enchant/object-ego.h:5:0,
                 from action/activation-execution.cpp:19:
./util/flag-group.h:426:78: error: 'std::string_view' has not been declared
 lagType> &fg, const Map &dict, std::string_vie what)
                                     ^~~~~~~~~~
mv: cannot stat 'action/.deps/activation-execution.Tpo': No such file or directory
Makefile:4647: recipe for target 'action/activation-execution.o' failed

というエラーが出てコンパイルが停止します。

'std::string_view'　で検索した結果
-std=c++17
というC++のオプションを付ければどうにかなりそうなのですが、どこに付ければよいのかわか、もしくはそれで解決するかもわかりませんでした。

## 補足事項
こちらが何か必要なパッケージをインストールしていないのかもしれません。
hengbandOSX(?)のリポジトリにも似たような記事があり、そちらでは当該オプションで解決していたようでした。

**Comment by iks3** [comment]
ご報告ありがとうございます。

> configure: error: AX_CXX_COMPILE_STDCXX_17 macro is not defined. You need to install autoconf-archive.

と出ているかと思います。メッセージの通りに、autoconf-archiveをインストールしていただけると解決します。
インストール後、bootstrapでconfigureを作成しなおしていただければ大丈夫です。

例:
$ sudo apt -y install autoconf-archive
$ ./bootstrap
$ ./configure

**Comment by habu1010** [comment]
> configure: error: AX_CXX_COMPILE_STDCXX_17 macro is not defined. You need to install autoconf-archive.

このエラーメッセージが出るように修正したのは、前回のリリース以降なので、現在リリースしているtar.gzに含まれるconfigureでは表示されないと思います。次のリリース以降では表示されるようになります。
必要なパッケージは上での指摘の通りautoconf-archiveですので、それをインストールすれば -std=gnu++17 が付加され、コンパイルできるようになります。

**Comment by pachenya** [comment]
素早い対応ありがとうございます。
ご指摘どおりのソフトの導入で解決しました。
コンパイルエラーも無くなり、問題なく遊べています。

**Comment by iks3** [comment]
ご報告ありがとうございました。
本Issueはこれにてクローズとします。
