### ISSUE TITLE
【バグ】 3.0.0Alpha12 Windows(English Version)のメニューが日本語

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#573]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha12 Windows(English Version)

## バグの詳細

タイトルの通り、メニューが英語ではなく日本語のものになっている。
Windowsの表示言語を英語にしても変わらなかった。

## 再現手順

English Versionを起動する。

## 期待される正常な動作

メニューも英語が期待される。

## スクリーンショット

![title_en](https://user-images.githubusercontent.com/3318603/111868484-72a25e80-89bd-11eb-9535-565a089d8c66.png)

## 補足事項

ang_eng.rcのファイルを見ると英語版にはメニューにBGM設定が無いようだ。

**Comment by sikabane-works** [comment]
ang_eng.rcに切り替えし損ねている上に更新してないんですな。対応します。
