### ISSUE TITLE
Win版壁紙の対応形式を増やす

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#596]
Win版の壁紙機能はBMP形式のみの対応となっている。
「Win版背景をBGMと同じようにシチュエーションに応じて切り替える機能を実装する #396」に向けて対応形式を増やす。

Win版の機能のため、特にlibpng等は導入せずにWindowsのAPIで対応する。
現在の描画方法と互換性を持てるGDI+で対応する。
Windows XP以降は標準でGDI+に対応している。
GDI+でサポートされている画像形式はBMP, GIF, JPEG, PNG, TIFF, Exif, WMF, EMF。

**Comment by sikabane-works** [comment]
マージ確認しました。お疲れさまでした。
