### ISSUE TITLE
mom_type、monap_typeのメンバ変数ap_cntが不要

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#63]
打撃回避バグの周辺を呼んでて気づいたが、mon_type、monap_typeのap_cntというメンバはモンスターの打撃処理で何回目の打撃かを保持しているだけであり他のどこからも参照されていない。
構造体に持たせる必要がなくローカル変数で十分と思われる。

**Comment by Hourier** [comment]
process_monster_blows() とincrease_blow_type_seen() で参照されているので、エイヤで構造体に押し込んだものですね
increase_blow_type_seen() にintの引数を足せば解決しますが、それで大丈夫でしょうか？
(気にしていること：引数が少ないことによる分かりやすさを優先するか、変数スコープを構造体からローカル変数へ狭めることによる分かりやすさを優先するか)

**Comment by habu1010** [comment]
引数が少なくなってもわかりやすくなっているとは思えません。ap_cntが何なのか、元のところでループ変数になっているのを確認する必要があります。
この関数にはdoxygenでのコメントはありませんが、あるのを前提とすると引数を渡してコメントを入れるほうがわかりやすいです。

なにより、単なるループ変数がローカル変数でないというのは、非常に違和感を覚えます。

**Comment by Hourier** [comment]
承知しました
ではローカル変数として扱います
#36 と同じブランチで(taotaoさんとは別方向の)修正をしていますので、併せてご確認下さい
