### ISSUE TITLE
ハイメイジで魔法学習のストックがなくなる

### ISSUE THREAD

**Issue by bbbband** [hengband/hengband#64]
レベル40までは魔法の学習ストックが11つほど残っていたのですがレベル42辺りから魔法の学習ストックがいきなり0になりました。　それ以降レベルを上げても全くストックが増えなかったです。　装備を付け替えて知能のステータスを上下させても変わらず。　呪文の巻物を使用した時はしっかりストックが1つ増えました。

**Comment by habu1010** [comment]
ここまでに確認できている状況を整理。

- 貰ったセーブファイルを確認したところ、player_type構造体に保持されている学習数(learend_spells)は38。これはハイメイジで学習可能な最大数36と呪文の巻物で増やした2回を足したものに一致していた。
- @dis- 氏が検証中に一度だけ再現した（セーブ&ロード時に学習可能数が0になっていたとのこと）が、それ以降再現せず。

**Comment by argrath** [comment]
最後に再現してからコードも大きく変わっているので、一旦クローズして良さそうな気がします。

**Comment by Hourier** [comment]
上記の通りコードの変更量が大きく再現性も乏しいため、一旦クローズします
v3.0β以降に再発したら再調査する方針とします
