### ISSUE TITLE
【バグ】 rod of light + invisible monster = information leak with "is unaffected" message

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#640]
## 環境

- OS: [macOS]
- バージョン: [例: 3.0.0Alpha13]

## バグの詳細

Zapped a rod of light to light up a line.  Got two "It was unaffected." messages from invisible creatures that were on the line at the time.  Since the character did not have a source of see invisible, those messages seem like a leak of information that the character shouldn't have access to.  I don't know if this is a broader problem and affects other situations where a "is unaffected" or "is unharmed" message reveals more information than the character should be privy to.

## 再現手順

1) Have a character with one or more rods of light and no source of see invisible.
2) Use the rod of light to light a corridor which has one or more creatures which are invisible and not sensitive to light.

The situation mentioned in the bug report happened in "Doom Quest 1" with two imps as the invisible creatures.

## 期待される正常な動

The "is unaffected" or "is unharmed" message should not be generated if the monster was not visible to the character.

**Comment by sikabane-works** [comment]
Sorry I late. I think too, Non-damage effect should be invoked reaction of Invisible monsters. I'll try fix.
