### ISSUE TITLE
【バグ】 元素使いで知識の石発動時にMPが消費されない(混乱はする)(地領域でのみ確認)

### ISSUE THREAD

**Issue by HiddenNameZ** [hengband/hengband#685]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha15

## バグの詳細

元素使いで知識の石発動時にMPが消費されない(混乱はする)
(地領域でのみ確認)

## 再現手順

元素使いで知識の石を発動する

## 期待される正常な動作

MP消費+足りないと耐性無視で麻痺

## スクリーンショット

省略

## 補足事項

(バグではないですが、現状元素使いだと矢の呪文がビーム化する可能性がメイジ/スペマより低くなっています。このバグも含めこの辺は特定の職業にあてはまるフラグ(MPの有無/恐怖の仮面のデメリット付与など)を実装するなどすれば新しい職業を導入するときに役立つかもしれないです)

**Comment by iks3** [comment]
魔法書の仕様が設定されていない職業はMPがあっても関係なくHPを消費するようです(例: 超能力者、鏡使い)。
MPを消費するのが正しい仕様だと思われますのでそのように修正したいと思います。
