### ISSUE TITLE
[enhancement] make 't' command in window flags menu work as a toggle

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#686]
The 't' command in the window flags menu appears to have remained unchanged since Angband 2.8:  for the selected flag and window, turn that flag off in all windows, turn all flags in the selected window off, then turn on the selected flag in the selected window.  At some point between Angband 2.8 and Angband 2.9, vanilla Angband changed the meaning of 't' to toggle the selected flag (turn off if on; turn on if off) without side effects on the other flags or windows.

One disadvantage of the current behavior for 't' is, that when the flag is on for the selected window and flag and that flag is off in all other windows while the selected window has no other flags set, the 't' command has no effect.  That does not match up with the brief description it's given in the Japanese header for the menu, "でチェンジ" or the player's expectations, if that player thinks 't' stands for "toggle".

To avoid that, the command could be changed to work as a simple toggle without side effects as it does in Angband 2.9 and later.  Another option would be to use a hybrid approach, if the flag is off for the currently selected window and flag, use the current behavior of 't'.  If the flag is on for the selected window, turn it off without changing any of the other flags for the window or other windows' flags.

If changing 't' seems useful and the hybrid option is chosen, I can post a pull request with an implementation for that.

**Comment by iks3** [comment]
Thank you for your suggestion.
