### ISSUE TITLE
【軽微なバグ】ダンジョンの主召喚に伴う地形変化がちょっとヘン

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#697]
## 環境

- OS: [例: Windows
- バージョン: [例: 3.0.0Alpha15

## バグの詳細

混沌のサーペントによるダンジョンの主召喚がペットに対して行われた時にも、
@の居る場所を中心とした9マスに深い水が生成される

## 再現手順

＠のペットに対してJにヨルムンガンドを召喚させる

## 期待される正常な動作

@の回りの地形は変化しない

**Comment by iks3** [comment]
おそらく、ターゲットになったペットと水場の中心を作るproject()関数の指定座標に齟齬が発生すると思われるが、再現手法がないので確認できるようになってから修正したい。

**Comment by sikabane-works** [comment]
どうも重複な様子ならDuplicateつけてこちらは閉じようと思いますがOKでしょうか。

**Comment by daradarach** [comment]
はい、より詳しく調査したissueがありますのでそちらに移行でいいと思います

**Comment by sikabane-works** [comment]
結果として報告長らく放置した形ですみません。では閉じます。
