### ISSUE TITLE
【バグ】 DUMP出力時に日本語が使えない？

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#708]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha15

## バグの詳細

tekitou.txtは吐ける
てきとう.txtは吐けない

## 再現手順

DUMP出力する

## 期待される正常な動作

出る

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付
![image](https://user-images.githubusercontent.com/78687408/113500726-465d1500-955b-11eb-8542-6dd0aea344a9.png)

**Comment by daradarach** [comment]
すみませんalpha15版じゃなかったです。
alpha15には敵がアイテム持ってるとフリーズするバグがあったので、
回避するためにローグライク実験室から下記を取得し使っていました。

hengband-20210401042722-develop-c5f792f-win

**Comment by shimitei** [comment]
hengband-20210401042722-develop-c5f792f-winでも3.0.0Alpha15でもこちらでは再現しないですね。
Windows 10 バージョン20H2です。

**Comment by daradarach** [comment]
こちらWindows8.1、WindowsUpdateは最新まで当てています

**Comment by shimitei** [comment]
VirtualBox上のWindows8.1で確認すると再現しました。
公式の3.0.0Alpha15、3.0.0Alpha16は問題なし。
hengband-20210401042722-develop-c5f792f-winは日本語を含むファイル名出力に失敗しました。
プレイヤー名に日本語を使った場合にはセーブも失敗します。

ローグライク実験室の最近のビルドは何もビルドオプション等を変更していないのですが、何か違いがあるようです。
試した範囲では開発に使っている（GitHub Desktop管理の）プロジェクトフォルダ上でビルドしたバイナリはOKで、ソース取ってきてビルドするとNGでした。(IDE上でもBuild-Windows-Release-Package.ps1でもコマンドラインでmsbuildでも同じ結果になる。)
公式ソース(zip)では改行がLFになっている違いはありましたが、ローグライク実験室のビルド用は改行CRLFでGitHub Desktop管理のものとソースコードの差異なしです。

今のところ原因不明で、引き続き調べてみます。

**Comment by shimitei** [comment]
古いバージョンのWindows SDK（今回の場合10.0.177630）を使うとWindows8.1で同様の問題が発生し、
新しいバージョンのWindows SDK（10.0.19041.0）を使うと問題が発生しないことを確認できました。
