### ISSUE TITLE
【バグ】 探索モードに入ると減速する

### ISSUE THREAD

**Issue by gkuraki** [hengband/hengband#709]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha15

## バグの詳細

Sキーで探索モードに入ると減速(-10)になる

## 再現手順

1. 注意深く歩き始める

## 期待される正常な動作
本来なら減速しないはず

**Comment by gkuraki** [comment]
探索モードに入ると減速になるのは以前からの仕様で、可視化されただけとのことです。
ご迷惑をおかけしました。

**Comment by iks3** [comment]
クローズします。
