### ISSUE TITLE
【要望】死亡/引退DUMPのプレイ時間を死亡/引退が確定した時間までにして欲しい

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#710]
現状、死亡/引退した後もプレイ時間は増え続け、DUMPを吐くたびにプレイ時間は更新される。
死亡/引退した時点でプレイ時間は止まって欲しい。

**Comment by iks3** [comment]
Qy@して放置してると増えてるという感じで、これは確かにおかしいので対応したいと思います。

**Comment by iks3** [comment]
#830 で実装済みなのでクローズします。
