### ISSUE TITLE
【バグ】 通常の雰囲気なのにFEEL1に設定したBGMが演奏される

### ISSUE THREAD

**Issue by Kcalsh** [hengband/hengband#714]
## 環境

- OS: Windows版
- バージョン: 3.0.0Alpha15

## バグの詳細

Alpha15で新規で作成したキャラクターで、
イークの洞窟および鉄獄に潜った際、雰囲気不明の間はdun_lowに設定したBGMがなるが、
雰囲気が判明した際に通常の雰囲気（退屈～何か緊張するまで確認）なのにFEEL1に設定した（緊張感のある）BGMに変わる。
緊張以下の範囲で雰囲気が変動しても、BGMは変わらない。
フロアを移動して雰囲気不明になると、dun_lowから再度選ばれる。

## 再現手順

１．鉄獄又はイーク洞に入り口から入る（他のダンジョンでは未確認、帰還時は未確認）
２．雰囲気が判明するまで時間を経過させる

[セーブファイル.zip](https://github.com/hengband/hengband/files/6254195/default.zip)
[music.cfg.zip](https://github.com/hengband/hengband/files/6254198/music.cfg.zip)

## 期待される正常な動作

雰囲気が悪い予感未満の場合はdun_lowに設定したBGMが再生される

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
#689 で報告のあったものと同じバグだと思われます。
すでに修正済みで、Alpha16リリースに反映される予定ですのでお待ち下さい。

このIssueは修正済みとしてクローズします。
