### ISSUE TITLE
【バグ】広域マップでの光源の減りがおかしい

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#743]
## 環境
- OS: Any
- バージョン: 3.0.0α16

## バグの詳細
広域マップでランタン等の残ターン数の減り方がおかしい。
キャラ作成直後のキャラにランタンを持たせて広域マップで移動すると100減るように見えるが、コマンドを実行しようとすると100未満のターン数が減り、その後歩くと末尾2桁が00になるように端数が減る。

## 再現手順
キャラクタを作成して開始。雑貨屋でランタンと油つぼを買い、ランタンを装備。
サブウィンドウを表示して、装備/持ち物一覧にする。
広域マップに出て歩く(100減る、たまに200減る、ように見える)。
油つぼの補充や食料を食べようとしてみると微妙に減る。
歩くと下2桁が00になるように端数だけ減る。

## 期待される正常な動作
端数に関係なく100なら100減るべき？(ランタン等が切れそうなときどうするか)
コマンドを選ぶだけで実行していないのに減っているのもおかしい。

**Comment by shimitei** [comment]
再描画で末尾が00から減るため、実際の値を表示できていないようです。

**Comment by sikabane-works** [comment]
オプションの問題でしょうか。こちらが試した分には下二桁が00になるような減り方は確認できていません。チート以外初期オプションのつもりです。

**Comment by habu1010** [comment]
燃料の残ターン数が100の倍数（および100未満）の時にサブウィンドウの再描画フラグを立てるようになっているためのようです。オプション設定によるかもしれませんが、手元での確認では広域マップに限らずサブウィンドウの燃料は100の倍数のターンでしか更新されませんでした。（再描画が発生するような別の行動があった場合は、端数含めて更新されます。）
おそらくは頻繁にサブウィンドウの再描画が発生するのを防ぐための措置だと考えられます。

https://github.com/hengband/hengband/blob/773787c8729e302b866653d8bc27481dc3c3a0f5/src/object/lite-processor.cpp#L42-L47

**Comment by dis-** [comment]
キー待ちになるときにサブウィンドウの強制描写を入れる修正を入れました。
これにより、広域でも1入力毎に1度だけ描写更新が発生します。

**Comment by shimitei** [comment]
#754 でサブウインドウでの光源の寿命表示についても、下2桁00ではなく実際の値が表示されるようになりました。
クローズします。
