### ISSUE TITLE
【バグ】 方向を指示する魔法を使用するとカーソルが出現する

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#760]
## 環境

- OS: Mac X11
- バージョン: Alpha16 4/11最新Develop

## バグの詳細

方向を指示する魔法を使用するとMP表示欄の右側にカーソルが出現する

## 再現手順

1. カオスハイメイジで開始する
2. maaコマンドでマジックミサイルを使用する
3. カーソルが出現する

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

カーソルが出現しない

## スクリーンショット

<img width="560" alt="魔法方向指示" src="https://user-images.githubusercontent.com/17109188/114288613-903e8180-9aac-11eb-8fca-3c2ecef2357a.png">

## 補足事項

他の方向を指示する魔法でも同様の現象が発生

**Comment by shimitei** [comment]
バージョン2.2.1および3.0.0alpha16でもカーソルは最後にテキスト出力した所に出ています。
#754 のマージにより最後に出力した位置が変わったためと思われます。

![2 2 1](https://user-images.githubusercontent.com/3318603/114292246-00a6cc00-9ac8-11eb-8a94-2e6c9711edb2.png)
