### ISSUE TITLE
【バグ】 '+' コマンドの入力で謎の数字が表示される

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#772]
## 環境

- OS: Mac X11
- バージョン: 3.0.0Alpha17

## バグの詳細

'+' コマンドの入力で謎の数字が表示される

## 再現手順

1. '+' コマンドを入力する
2. メイン画面の時刻の上に謎の数字が表示される

## 期待される正常な動作

何も表示されない

## スクリーンショット
<img width="561" alt="'+' コマンドで 98 が表示される" src="https://user-images.githubusercontent.com/17109188/114335772-6d819b00-9b88-11eb-949f-58cd79db7092.png">

**Comment by sikabane-works** [comment]
ん、例の休憩コマンド中に表示される待機ターン量でしょうか。調べてみます。

**Comment by habu1010** [comment]
#754 でキー入力待ちの時にすべての情報を再描画するようになった影響で、今まで表示されていなかった物が表示されています。

コマンド自動繰り返し回数を格納→方向を入力という流れなので、方向入力時の強制再描画により残りの自動繰り返し回数が表示されてしまっています。
他に自動繰り返しできる以下のコマンドも同様の問題が発生しています。

- 壁掘り
- ドアの開閉
- ドアのバッシュ
- 罠の解除
