### ISSUE TITLE
【バグ？】 BGMの優先度が「未知の敵遭遇時」＞「ゲーム中断時」になっている

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#776]
## 環境

- OS: Windows 版
- バージョン: 例: 3.0.0Alpha17

## バグの詳細

題名通り。緊迫感ありままで中断もいいかもしれないが意図してない可能性は高そうなので念のため報告。

## 再現手順

やはり題名通り。未知の敵遭遇時に終了しても同じBGMが鳴り直るのみ。

## 期待される正常な動作

「ゲーム中断時」を優先。

**Comment by shimitei** [comment]
割り込み系BGM＞通常BGMの優先は最後に対応を入れたものの、
割り込み系BGM＞モンスターBGMの対応が漏れていました。
修正します。
