### ISSUE TITLE
【バグ】 プリーストの第1領域が「暗黒」、「悪魔」、「ランダム」からしか選べない

### ISSUE THREAD

**Issue by 7exp** [hengband/hengband#781]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha17

## バグの詳細
プリーストの第1領域が「暗黒」、「悪魔」、「ランダム」からしか選べない

## 再現手順
1. 起動
2. キャラメイクを「男性」＞「ハーフトロル」＞「プリースト」で進行
3. 第1領域の選択に移ると暗黒・悪魔・ランダムしか選択肢がでてこない

## 期待される正常な動作
選択肢に「生命」、「破邪」も表示されること

## スクリーンショット
<img width="501" alt="category1" src="https://user-images.githubusercontent.com/79756503/114472946-3c5ba600-9c2e-11eb-9643-04abd0764089.png">

## 補足事項
再現手順は一例です。他の性別、種族の組合せでも発生しました。

**Comment by sikabane-works** [comment]
すみません。 #779 で修正済です。Hotfixは検討中です。
