### ISSUE TITLE
【要望】キャラメイク時に勝利済み職業をなんかマークして欲しい

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#784]
1. `*勝利*`済み職業の文字色を変更する
2. 未`*勝利*`職業からランダムセレクト
3. 未`*勝利*`職を潰していく遊びをする人向けに、選択順を職業→種族→性格に(オプション？)

**Comment by iks3** [comment]
ランダムセレクトは今回は見送りです(領域など変えて遊んでほしい職業もあるので)
