### ISSUE TITLE
【バグ】 未鑑定のアイテムを売るとアイテムが残る

### ISSUE THREAD

**Issue by gold-onion** [hengband/hengband#790]
## 環境

- OS:Windows10
- バージョン:3.0.0Alpha17

## バグの詳細

未鑑定のアイテムを売るとアイテムが残る

## 再現手順

1. 未鑑定のアイテムを売却する
2. そのアイテムは店に陳列され、鑑定される
3. アイテムが鑑定されたことによりインベントリの並びが変更される
4. そのアイテムが消滅しないで残る
5. 代わりに変更前にあった位置のアイテムが消滅する場合がある（指輪は消えるが薬は消えない模様）

[Europa_crash.zip](https://github.com/hengband/hengband/files/6304963/Europa_crash.zip)

## 期待される正常な動作

インベントリの並び変えを追跡して元のアイテムが消滅する

## スクリーンショット

なし

## 補足事項

添付したセーブファイルで魔法棒を売るとクラッシュする

**Comment by habu1010** [comment]
#789 の修正と同根のバグです。
次のリリースをお待ち下さい。クラッシュの可能性を含むかなりまずいバグですので、定期リリース前に修正リリースを行うかもしれません。
