### ISSUE TITLE
【バグ】ウィンドウの位置が復元されないことがある

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#791]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha17

## バグの詳細

1月にDiscordで会話してて、当時taotaoさんが原因箇所までは見つけていた件です。

main-win.c
    posx = GetPrivateProfileInt(sec_name, "PositionX", posx, ini_file);
    posy = GetPrivateProfileInt(sec_name, "PositionY", posy, ini_file);
    td->pos_x = MIN(MAX(0, posx), dispx - 128);
    td->pos_y = MIN(MAX(0, posy), dispy - 128);

となっており、マイナス座標が考慮されていないようです

## 再現手順

マルチモニタ環境で、メインモニタより左にサブモニタを配置し、サブモニタ側で変愚を遊ぶ
終了する
再度起動する

## 期待される正常な動作

サブモニタに変愚が表示される

**Comment by shimitei** [comment]
再現することを確認しました。

原因箇所の処理で行いたいのは、ウインドウが画面外に配置されないようにすることなので
チェックの仕方を変えて対応したいと思います。

**Comment by shimitei** [comment]
タイトルを変更しました。
ウインドウ位置の保存は正常で、保存した値の読み込み時の問題のため。
