### ISSUE TITLE
【バグ】 ナズグルの生存数が減っている

### ISSUE THREAD

**Issue by Nupepo** [hengband/hengband#809]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha18
- マインドフレア元素使い（瘴気）

## バグの詳細

本プレイ中にてまだ一体も倒していないナズグルの生存数が減っていた。
このとき、前のセーブにて何体かナズグルを倒していた。

## 再現手順

1. 先祖が生成制限のあるモンスター（=ナズグル）を倒しておく。
2. 同じセーブデータで新しく始める。
3. ナズグルの思い出を見る。

## 期待される正常な動作

新しく始めた際にナズグルの思い出を見ると”彼らはまだ9体生きている。”と表示される。

## スクリーンショット
![2無題](https://user-images.githubusercontent.com/81358368/115019867-b91fa600-9ef4-11eb-9f23-00dcec2ce32a.png)

## 補足事項

思い出の表記だけがおかしくなっていて、
実際には9体生存しているかどうかは不明です。

先祖が累計9体以上倒している際にどう表示されるかは不明です。

**Comment by iks3** [comment]
アングマールの魔王、東夷カムル、犬王ドワール、ディアのホアルムラスの4体もナズグルですので、9 - 4 = 5 で 5体が最大になっています。(備忘録も兼ねて)
というわけで本件クローズです。
