### ISSUE TITLE
【バグ】 種族ゾンビが持つ毒耐性が機能していない

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#815]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha18

## バグの詳細

種族ゾンビのキャラクターで毒攻撃を受けた際、耐性によるダメージの軽減が発生しない

## 再現手順

1. 種族ゾンビのキャラクターを作成し、ウィザードモードで生成したドローレムのブレスを受ける
2. ブレス一発で800ダメージを受けることが確認できる

セーブファイル
[2021-04-17-13-30-16.zip](https://github.com/hengband/hengband/files/6328634/2021-04-17-13-30-16.zip)

## 期待される正常な動作

ゾンビは毒耐性を持っているので、装備などによる毒耐性が無くても毒ブレスのダメージが軽減される

## 補足事項

ドローレムの毒属性の打撃により毒の継続ダメージ（毒状態の間ターン経過に伴いHP減少）も発生しましたが、本来はこれも毒耐性があれば発生しなかったと思います。上記と同様、ゾンビの毒耐性が機能していないことによるバグかと思われます。
なお、ステータス画面ではゾンビの毒耐性は表示されています。

**Comment by shimitei** [comment]
再現することを確認しました。
毒ブレスのMAX800ダメージ受けます。
