### ISSUE TITLE
耐性の有無判定処理は現状バグを検出し難く、新種族等を追加し難い

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#817]
攻撃に対して毒耐性があるかないかはplayer/player-status-flags.cppのhas_resist_pois関数で処理されている。
ここに種族がゾンビの場合の判定が抜けていると耐性が無いことになる。

新しく種族を追加するときはそれぞれの耐性判定処理に新種族の判定を追加することになるが、そんなことしたくないよね。
どこか１か所にこの種族はこの耐性を持っていると定義したらよきにはからって欲しい。

**Comment by habu1010** [comment]
全くです。
リファクタリング案：
耐性情報(耐性い限らず免疫/弱点/能力も含む)を持つenum class を新設し、(仮にRES_INFOとする)
```c++
std::array<std::unordered_map<RES_INFO, PLAYER_LEVEL>, MAX_RACES> race_res_info = 
{
    {{}}, // 0: 人間
    …
    {{RES_INFO::RES_BLIND, 1}}, // 5:ドワーフ
    ...
    {{RES_INFO::LVEITATION, 1}, {RES_INFO::RES_FIRE, 5}, {RES_INFO::RES_COLD, 10}, {RES_INFO::RES_ACID, 15}, {RES_INFO::RES_ELEC, 20}, {RES_INFO::RES_POIS, 35}}, // 20: ドラコニアン
    ....
};
```
のようなテーブルを作成し、これを参照して耐性があるかどうかを調べるようにする。
種族だけでなく職業、性格にも応用できそう。
（耐性に限らないのでRES_INFOはもっと適切な名前がよさそうですが）

**Comment by sikabane-works** [comment]
下手なのはもっともなんですが、まだCの頃にcalc_bonuses()ってクソデカ変数整理するのに手一杯だったので、ご容赦願いたい。修正の案には賛成しますのでよろしくお願いします。

**Comment by iks3** [comment]
ハーフトロルだけレベル15で戦士と狂戦士が遅消化を得るという条件のためunordered_mapはあきらめて、vectorで能力条件を実装しました。
種族のフラグ判定については共通化がほぼできたかと。
影フェアリーの怒られないやつとか、幽霊とか、種族の食糧とか、その辺はまだ未対応ですが。
