### ISSUE TITLE
相応しい/相応しくない武器 の判定反転

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#82]
OSDNより移行。[41319](https://osdn.net/projects/hengband/ticket/41319)

現在はicky (相応しくない)という変数が使われているが、相応しい時は!icky である
これは負論理でよろしくないので、suitable (相応しい)に変更し、相応しくない時は!suitable とする
なお負論理のコードは他にもあるが、まとめて実施するとブランチが膨れ上がるので都度対応とする

**Comment by iks3** [comment]
ペナルティの条件が、装備している武器が ickyである(不愉快である) 時なので、条件自体は正論理ですから、suitable にすることで条件が負論理( !suitable のときにペナルティ)になってしまうので、変えない方がよろしい気がします。
日本語で「不」愉快ですので反対に思えますが、不愉快の反対は愉快ではありませんので、言葉の上でも同じかと。
ただ、ickyではわかりにくいので、badとかhateとかに変えるのはアリかと思います。
