### ISSUE TITLE
オプションの設定　基本ウエイト量　調整の提案

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#83]
OSDNより移行。[41318](https://osdn.net/projects/hengband/ticket/41318)

現状では ウエイト量 1 に対して 1 の 3乗ミリ秒 になっていて細かい調整が難しい。 そこで ウエイト量 1 に対して 1 ミリ秒 に変更を提案します。 
( ソースの対応箇所は delay_factor と 多分 delay_factor_val )

**Comment by sikabane-works** [comment]
要望あったので調整してみます。
