### ISSUE TITLE
【バグ】サブウィンドウの持ち物一覧でウィンドウの高さ不足で落ちる

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#840]
## 環境
- OS: Windows版
- バージョン: 3.0.0Alpha19

## バグの詳細
起動後、サブウィンドウで持ち物一覧が表示される際、ウィンドウ内に収まりきらない場合に落ちる。

## 再現手順
ゲームを開始して、サブウィンドウに持ち物一覧を出し、ウィンドウサイズを足りなくなるまで縮める。
→落ちる

## 期待される正常な動作
落ちない

## 補足事項
ウィンドウの高さが十分なら落ちないので、十分な高さを確保しておけばよい。

**Comment by shimitei** [comment]
この問題は3.0.0Alpha19では発生しませんでした。
#832 の対応以降で発生します。

**Comment by shimitei** [comment]
3.0.0Alpha19では装備一覧のサブウインドウ高さを縮め、高さ不足にすると表示外になった部分のアイテム重量が変な位置に表示される程度です。

![sub](https://user-images.githubusercontent.com/3318603/115159983-ce512c00-a0d0-11eb-89a1-b9b2d74850a3.png)
