### ISSUE TITLE
【バグ】 ★武器の善良スレイが表示されない

### ISSUE THREAD

**Issue by chikatei** [hengband/hengband#846]
## 環境

- OS: Windows 版
- バージョン: 3.0.0Alpha19

## バグの詳細

武器を*鑑定*すると「善良なる存在に対して邪悪なる力で攻撃する」という説明文を確認できるが、スレイ一覧（/邪などが表示される欄）には/善が表示されていない

## 再現手順

1. ウィザードモードで★ドワーフのロッホアーバー・アックスを願う
2. ウィザードモードの機能で*鑑定*する
3. ★ドワーフのロッホアーバー・アックスに/善が表示されていないことが確認できる

## 期待される正常な動作

善良スレイを持つ武器ならば/善が表示される

## スクリーンショット

![WS20210419_014105](https://user-images.githubusercontent.com/79318041/115228547-e1094680-a14c-11eb-9e11-4ed6d07f7029.png)

## 補足事項

実際に善良スレイ効果が発揮されているか、★ドワーフのロッホアーバー・アックス以外でも発生する現象かどうかについては未確認です。

**Comment by iks3** [comment]
*鑑定*の表示の方が不具合で、善良スレイはついていません。
コピペ元のSLAY_EVILのときに間違って表示してしまっています。
銘刻みの方を信用しておいてください。
