### ISSUE TITLE
【バグ】 BGM周りの挙動がおかしい

### ISSUE THREAD

**Issue by gkuraki** [hengband/hengband#854]
## 環境

- OS: Windows10
- バージョン: 3.0.0Alpha19

## バグの詳細

BGMの挙動が以前のバージョンまでと異なる。
どうやら[Basic]のBGMが優先されすぎて、以降の記述が反映されない模様。

## 再現手順

・[Basic]のTownの記述が無いと辺境の町やモリバント固有の町の指定BGMが再生されず、無音になる。
・イークの洞窟に入ると鉄獄浅層のBGMが再生される。
・固定クエストで鉄獄ランダムクエストのBGMが再生される。

## 期待される正常な動作
[Town]や[Dungeon], [Quest]の記述があればそっちが優先されるはず。

**Comment by shimitei** [comment]
確認しました。
BGM設定を読み込むタイミングが早くなったためか、町の数等が0扱いで[Town]、[Dungeon]、[Quest]の設定が読み込まれなくなっていました。
