### ISSUE TITLE
メンテナンスされていないメイクファイルの削除

### ISSUE THREAD

**Issue by shimitei** [hengband/hengband#860]
メンテナンスしたい人が現れるまでmakefile.bccとmakefile.stdを削除する。

Borland C++後継のC++Builderも今やClangベースらしいのでそのまま使える気がしない。

**Comment by Hourier** [comment]
去年の今頃にDOSやらIBM-PCのサポートを完全終了させた時に議論になりましたが、一旦残すという方針になりました
しかしながらC++化した時にBCBとの互換性が切れたので、もはやこのファイルでコンパイルすることが不可能になったことが結論付けられました
よって削除します
