### ISSUE TITLE
[Refactor] アイテムのパイルのデータ情報をstd::vector配列にする

### ISSUE THREAD

**Issue by iks3** [hengband/hengband#878]
現在、床上のアイテムや敵が拾ったアイテムがリンクリストになっている。
そのため、次のオブジェクトへのポインタの管理などに失敗すると無限ループなどの不具合を発生させていた。
C++でサイズ可変配列が使用できるので、std::vector<object *>型の配列にして、リンクを廃止したい。

オブジェクトはそれぞれ座標値や所持している敵のIDを保有しており、パイル情報はセーブ時に破棄されロード時に復元されている。
なので、この復元の部分をリンクリストではなくstd::vector<object *>に復元し管理することで現在と同等の機能をより安全に実現できる。

**Comment by habu1010** [comment]
#972 にドラフトPRを提出しました。
リストの管理には std::vector ではなく、std::list を使用しています。
これは、リストを走査しながらその中の要素を削除する事がある(例えばモンスターが床上のアイテムを拾う等の処理)ので、要素の削除をした時にイテレータが無効になってしまう std::vector をそのまま使用するのは難しいためです。
（std::vector を使う場合は、例えばループ中は削除マークを付けておいて後で詰めるといったことをしないといけないので、コードをかなり修正しないといけなくなる。）

既知の不具合として、auto_debug_saveがONだと、モンスターがばらまいたアイテムがスタックした時に床上から消えてしまう（セーブ & ロードで復活する）という現象があります。
例によってデバッグセーブがらみなので原因が謎です。（既存のコードでは再現せず）

**Comment by habu1010** [comment]
追記：リストの要素はポインタではなくOBJECT_IDXを保持しています。
元のコードがOBJECT_IDXを使う形になっているので、とりあえず元のコードからの修正量を最少にするためです。
