### ISSUE TITLE
v3.0.0 Alpha20 モンスター調整

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#886]
レアリティ・打撃値・魔法使用率など
余力があれば一部モンスターの追加も検討する

**Comment by RRyukkuriRyu** [comment]
以前クローズした件で「撲殺の天使のスターバーストはPOWERFULフラグがないので一発芸レベル」と書いてありましたが、スターバーストは暗黒の嵐や魔力の嵐と同様POWERFULフラグの影響を受けない魔法のはずですがそこのところ大丈夫でしょうか？

**Comment by Hourier** [comment]
確認しました
確かにPOWERFULフラグの有無はスターバーストに対しては無関係ですね、これは失礼しました
但しいずれにせよ問題はない認識です
重要なポイントはシステム上確定で耐光が手に入ることです
遠距離を徹底すれば大した脅威ではないです
