### ISSUE TITLE
mondeath.txt / mondeath_j.txt の拡張

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#890]
CAN_SPEAKフラグのないモンスターは、掲題のファイルに何かを指定しても「～～は死んだ/～～を倒した」としか表示されない
必要があればハードコードしているが、死亡時のメッセージをCAN_SPEAKフラグに囚われず自由に編集できるような拡張があると嬉しい

**Comment by sikabane-works** [comment]
個人的にはメッセージの類の各ファイル個別にではなく、r_info.txt中にまとめることもできないかな、と考えましたがセリフについて1対1対応とは限らないし難しいでしょうね。

**Comment by Hourier** [comment]
飛竜氏の尽力によりフラグ拡張が完了したので、呼び出し側のコードを合わせ込んでいく
