### ISSUE TITLE
【バグ】 隊士が生き残っていても全滅したことになる

### ISSUE THREAD

**Issue by daradarach** [hengband/hengband#895]
## 環境

- OS: [例: Windows 版
- バージョン: [例: 3.0.0Alpha19

## バグの詳細

鬼殺隊の『先輩』が魔法で手下を召喚した。                                        
しかし、隊士は全滅していた…。                                                  
鬼殺隊の『先輩』は戦いを決意した！                                              
まだ 69本の クロスボウの矢 (1d5) (+0,+0) (23/shot 19/turn) {@f1=g}を持っている。
クロスボウの矢 (1d5) (+0,+0) (23/shot 19/turn) {@f1=g}が鬼殺隊の『先輩』に命中し
た。                                                                            
鬼殺隊の『先輩』は死んだ。                                                      
何かが足下に転がってきた。                                                      
鬼殺隊の隊士に斬られた。                                                        
*** 警告:低ヒット・ポイント！ ***                                               
殴られた。                                                                      
*** 警告:低ヒット・ポイント！ ***                                               
まだ 68本の クロスボウの矢 (1d5) (+0,+0) (23/shot 19/turn) {@f1=g}を持っている。
クロスボウの矢 (1d5) (+0,+0) (23/shot 19/turn) {@f1=g}が鬼殺隊の隊士に命中した。
鬼殺隊の隊士は痛みでうなった。                                                  
鬼殺隊の隊士に斬られた。                                                        

## 再現手順

鬼殺隊の『先輩』に隊士を召喚させる
鬼殺隊の『先輩』に隊士を召喚させる
鬼殺隊の『先輩』に隊士を召喚させる

## 期待される正常な動作

隊士は出払っている、くらいでしょうか。

**Comment by Hourier** [comment]
モンスター調整の作業として引き取ります
