### ISSUE TITLE
武器匠での会心ダメージやステータス画面上の平均ダメージに強撃の効果が反映されない

### ISSUE THREAD

**Issue by iyukyo** [hengband/hengband#897]
## 環境

- OS: Windows
- バージョン: 3.0.0Alpha19

## バグの詳細
[ウィザード.zip](https://github.com/hengband/hengband/files/6369011/default.zip)

タイトルの通り。
添付のセーブファイルだと、強撃籠手を装備しない場合7回攻撃の平均ダメージ482で一回あたりのダメージはおよそ68であるのに対し、殺戮修正(-3,+15)の強撃籠手を装備した場合6回攻撃の503ダメージで一回あたり83ダメージとなり、強撃によるクリティカル率の増加やクリティカルダメージの増加の影響が確認できない。

## 再現手順

修行僧で強撃エゴの籠手を装備した場合と装備しない場合のCから表示されるステータス画面を比較する。

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作

強撃エゴの効果で一回あたりのダメージが高く表示される。

## スクリーンショット

可能であれば、バグ発生時のスクリーンショットを添付

## 補足事項

補足事項があれば記載

**Comment by habu1010** [comment]
修行僧に限らず、強撃エゴの効果によるクリティカル率/ダメージアップによるダメージ期待値上昇はステータス画面上の平均ダメージには反映されないのが現状のようです。（実態に合わせて Issue のタイトルを修正しました）
クリティカル率上昇の反映はともかく、クリティカルダメージの上昇は、ダメージ上昇の区画の計算が

- 強撃なし： weight + d650
- 強撃あり： weight + d650 + d650

と強撃無しと違い一様分布でなくなっているので、正確に期待値を計算するのは難しいかもしれません。

**Comment by habu1010** [comment]
武器匠の会心ダメージ計算もステータス画面の平均ダメージと同様に `calc_expect_crit()` を使用しているため、強撃エゴの効果は反映されていない。
