### ISSUE TITLE
grid.c/h の分割 Alpha33

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#919]
OSDN より移行。 [#40654](https://osdn.net/projects/hengband/ticket/40654)

> grid_type 構造体をsystem/ 以下に逃がす作業と、ファイル分割の作業をこのチケットで実施する

**Comment by sikabane-works** [comment]
この件着手がまだ付きそうにないので、後のマイルストーンへ飛ばします。

**Comment by Hourier** [comment]
grid_type をgrid.h からgrid-type-definition.h へ逃がすだけで大量の差分が発生している
継続的に修正予定としたいのでバージョン番号を付記
