### ISSUE TITLE
床置きアイテム自動破壊時にメッセージウインドウが遅れる

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#92]
Mac X11 developerブランチビルド
カオス仙術メイジで"¥e¥e¥emfb-"マクロを使用
床置きのアイテムを拾わずにマクロで鑑定して自動破壊対象になった場合に
メインウインドウでは"〜を自動破壊します。"のメッセージがすぐに出るが
メッセージウインドウではさらに何かキーを押した後にしか表示されません。
マクロを使用しない場合は通常表示します。
セーブデータはマクロをshift+Xに割り当ててアイテムの上にいる状態です。
[mage.zip](https://github.com/hengband/hengband/files/5972167/mage.zip)

**Comment by dis-** [comment]
再現を確認しました。調査に入ります。
