### ISSUE TITLE
アーチャーレイシャル「弾/矢の製造」によるエラー落ち

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#926]
OSDN より移行。[#40343](https://osdn.net/projects/hengband/ticket/40343)

> フォーラム 変愚蛮怒フォーラム [#84796] からの引用
> [forum: 84796]
> 公式サイトの2.2.1r-win.zipから、Windows8.1でプレイしています。
> レンジャーのレイシャルである弾/矢の製造についてですが、 発動して選択肢を開き、aを押して骨を消費して矢の作成を行い、
> その後nでレイシャルを繰り返し発動して選択肢を開いたとき、
> sを押すとエラーが出てクラッシュする現象を確認しました。
> 骨の所持数に関係はなさそうです。 他の弾の順(矢→クロスボウの順など)は試していません。 

> バグ再確認とおおよそ見当ついている修正手段と踏まえて3h～程

**Comment by habu1010** [comment]
現状、矢弾の生成レイシャルコマンドにおいて、弾/矢/クロスボウの矢のどれを生成するかを選択する部分が、繰り返しコマンドに対応していない。

コマンドの流れとして、弾を作るときは、

- レイシャル発動 (繰り返し対応)
- S(弾生成)を選択 (繰り返し非対応)
- 岩石のある方向を選択 (繰り返し対応)

矢を作る時は、

- レイシャル発動 (繰り返し対応)
- A(矢生成)を選択 (繰り返し非対応)
- 材料にする骨を選択 (繰り返し対応)

となる。

例えば矢を作った場合は繰り返しコマンドとして、レイシャル発動と材料にする骨のインベントリ番号が記録される。
この記録された繰り返しコマンドを実行する途中で矢生成でなく弾生成を選択してしまった場合、インベントリ番号が岩石のある方向の選択に使用されてしまう。
方向番号は1～9として想定されており、配列も要素番号9までしか無いため、例えば骨のインベントリ番号が10以上だった場合に配列外アクセスを起こしてしまい、運が悪ければクラッシュする。

#965 で矢弾の種類選択部分も繰り返しコマンドに対応させたので、とりあえずインベントリ番号が方向に適用されてしまう事はなくなったが、安全対策として方向を得る関数 `get_rep_dir` では繰り返しコマンドのバッファから得られた方向が範囲内かどうかチェックを入れたほうがいいかもしれない。
