### ISSUE TITLE
危ない水着のレアリティを下げる

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#927]
OSDN より移行。[#41109](https://osdn.net/projects/hengband/ticket/41109)

> [forum: 85702]
> 危ない水着
> 常時反感で決して楽とはいえない性格セクシーギャルの数少ない特典ですがレアリティが高すぎて
> なまけもの神器以上に入手機会、使用機会に乏しいです
> レアリティの割には危ない水着の固定★はそれほど高性能とは言い切れませんし
> セクシーギャルの難易度がなまけものより上に位置付けされているとは思えませんし、もっと入手しやすくしていいのではないでしょうか

**Comment by Hourier** [comment]
ちょうどa_info、k_infoなど弄り倒せるタイミングなので、どこかのタイミングで併せて実施したい

**Comment by sikabane-works** [comment]
微細な修正が個別Issue化していることだしこちらでAlpha30対応で着手してみる。
