### ISSUE TITLE
v3.0.0 Alpha21 モンスター調整

### ISSUE THREAD

**Issue by Hourier** [hengband/hengband#933]
新規モンスターの強さチェックは満足に行えていないので、それらが中心
レアリティ・打撃値・魔法使用率など
多分余力がないので新規実装はない見込み

**Comment by RRyukkuriRyu** [comment]
『ヴィネガー・ドッピオ』の感知範囲が0になっているようです。
本来は200フィートなので修正をお願いします。

**Comment by Hourier** [comment]
承知しました、Alpha21にて対応します
それとは別の問題も確認しました
ドッピオ自体は56F RQ組ですが、ここで『ディアボロ』は倒さずにテレポアウェイで高級品だけ掻っ攫うと勝ち得になってしまいます
どうしたものかは別途検討します

**Comment by RRyukkuriRyu** [comment]
おや、ドッピオはRQに出ないよう原案にFRIENDRYフラグを書いておいたのですが、FRIENDRYフラグだけではRQに出現してしまうのですか？

**Comment by Hourier** [comment]
失礼しました
FRIENDLYフラグがあれば問題なしですね
では感知範囲だけ修正します
(OSDN のチケットを調べ直しましたが、やはりr_infoベースの記述では0になっていました。その下の思い出文章では200になっていますね)

**Comment by RRyukkuriRyu** [comment]
自分も今OSDNの方で確認しました。そのミスに気付いたのが#41042のモンスター案募集ページができた後だったので、訂正案をそちらに送っていました。https://osdn.net/projects/hengband/ticket/41042#comment:541:41042:1612187985
#37285の方に貼るべきでしたね、失礼しました。

**Comment by RL-Nadir** [comment]
鬼殺隊の隊士ですが、射撃ダメージが設定されている一方で、射撃能力を設定されていないので、設定が死んでいるようです。

**Comment by Hourier** [comment]
失礼しました、Alpha21までに修正しておきます
確率を定義するか射撃を外すかはリリースまでに検討します

**Comment by RRyukkuriRyu** [comment]
『チョコラータ』に人間フラグが付いていないというツッコミをスポイラーwikiでいただきました。
デスモルドをベースに書いていたのでつけ忘れてしまっていたようです。
あくまでスタンドではなく本体の方なので人間フラグがあった方が自然ですし、スレイが効いて倒しやすくなるので付与をお願いします。

**Comment by RL-Nadir** [comment]
あつくもえるてき　の海外版の名称は、Soul Consuming Flame　との指摘をいただきました。
お手数ですが修正をお願いいたします。

**Comment by RL-Nadir** [comment]
『マニマニのあくま』のシンボルについて、gではなく、( ` ) シンボルじゃないか、とのツッコミをいただきました。
像のシンボルなので妥当ですし、唯一の( ` )シンボルユニークという個性も付いて良いと思うので、変更いただけますと幸いです。
