### ISSUE TITLE
【バグ】 宿屋の噂を聞くとメッセージが重なって表示される

### ISSUE THREAD

**Issue by tanguband** [hengband/hengband#950]
## 環境

- OS: Mac X11
- バージョン: 3.0.0Alpha20 developブランチ　4/28版

## バグの詳細

宿屋の噂を聞くとメッセージが重なって表示される

## 再現手順

1. 適当なキャラクターで始める
2. 辺境の地の宿屋に入り噂を聞く

## 期待される正常な動作

メッセージが重ならない

## スクリーンショット

<img width="982" alt="噂" src="https://user-images.githubusercontent.com/17109188/116335133-4c1fe080-a811-11eb-8382-ec862e01f1e8.png">

**Comment by habu1010** [comment]
#948 でエンバグした件で、 #959 で修正されました。
この件はクローズします。
