### ISSUE TITLE
敵に殴られた時に "unexpected: monap_ptr->effect == RBE_NONE" というエラー

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#98]
汚いいたずら小僧に殴られたときに、タイトルの通りのエラーがポップアップで表示された（Windows版）。

先に実装しなおしたモンスターの打撃判定で、RBE_NONEはありえないという話だったが実際はあるらしい？

セーブファイルを添付する。このセーブファイルをロードして、1ターン待機すると再現する。
[セーブファイル.zip](https://github.com/hengband/hengband/files/5973914/default.zip)

**Comment by backwardsEric** [comment]
I don't have a save file, but I saw the warning message from process_monster_blows() triggered several times in a fight with Orfax (there were also brown and kamikaze yeeks nearby so they could also have been the cause).  This was on macOS with the current development version, modified to use the macOS-specific front-end.

**Comment by Hourier** [comment]
Eric氏の報告と合わせると、ダメージのない打撃属性の場合にRBE_NONEになるようです

**Comment by backwardsEric** [comment]
I've also seen the warning triggered by a blubbering icky thing and the greater hell-beast.  For the latter, the call stack at the point of the warning looked like:

- process_monster_blows() at monster-attack-player.c:403
- make_attack_normal() at monster-attack-player.c:524
- exe_monster_attack_to_player() at monster-attack-processor.c:57
- process_monster_movement() at monster-move.c:364
...

The contents of *monap_ptr leaving off the name and pointer fields were:

m_idx = 7
do_cut = 2036636
do_stun = 1
touched = '\0'
method = RBM_GAZE
explode = '\0'
rlev = 1
do_silly_attack = '\0'
d_dice = 0
d_side = 0
obvious = '\0'
damage = 0
effect = RBE_NONE
blinked = '\0'
get_damage = 0
ac = 1
alive = '\x01'
fear = '\0'
ap_cnt = 0

**Comment by taotao54321** [comment]
r_info.txt の `B:` の行で method だけ定義されてて effect がないものがあり、その場合 effect が `RBE_NONE` になるようです。
汚いイタズラ小僧の `B:BEG` などが該当します。

v2.2.1 では `effect == RBE_NONE` の打撃は必中となっていました。この辺の仕様も検討した上で修正したいと思います。

**Comment by taotao54321** [comment]
フレーバー的な打撃については `RBE_FLAVOR` を追加してはどうかという議論になり、その方向で修正中です。
内容が #95 とコンフリクトしそうなので、あちらのマージ後にプルリクしようかと思います。
