### ISSUE TITLE
【Doxygen】main-win.cpp ファイル の関数/変数詳解が正しく出力されない

### ISSUE THREAD

**Issue by sikabane-works** [hengband/hengband#987]
> warning: Reached end of file while still inside a (nested) comment.
暫定的に上記警告を潰すように修正したがいまだ直らず。引き続き対応する。

**Comment by shimitei** [comment]
main-win.cppは#ifdef WINDOWSでくくっているため、WINDOWSが定義されていないと最初のコメントしか出力されません。

Hengband.doxyfileにWINDOWSとJPの定義を追加するとよさそうです。

`PREDEFINED             = WINDOWS JP
`

とすると出力されるようです。

**Comment by sikabane-works** [comment]
ありがとうございます。マージしてみました。
